Repository jenkins-x/jx, pull requests merged in 2018-10, with the labels that each got.

#1830 `jx upgrade platform` should not perform upgrade if given version is installed
  pkg/jx/cmd/upgrade_platform.go
Labels: size/M

#1828 When headless mode is set, don't exec into devpod shell after creation.
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/S

#1831 Heptio AWS authenticator version should be managed by jx
  pkg/binaries/binaries.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/upgrade_binaries.go
Labels: needs-ok-to-test, size/L

#1834 chore: better error handling on startup
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/M

#1836 fix: team controller so it can run in a pod
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/controller_team.go
  pkg/kube/constants.go
Labels: size/L

#1797 refactor: use the Jenkins cookie after login to generate the Jenkins API token
  myvalues.yaml.template
  pkg/jenkins/utils.go
  pkg/jx/cmd/create_jenkins_token.go
Labels: size/L

#1840 fix(git) reverted git error checking when not running in a repo
  pkg/gits/git_cli.go
Labels: approved, size/XS

#1842 fix: add retries around registering CRDs
  pkg/kube/crds.go
Labels: approved, size/S

#1855 feat: Add StaticProgramAnalysis summary to PipelineActivity
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
Labels: approved, size/M

#1852 fix: avoid issue creating environments in team controller
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/install.go
Labels: approved, size/L

#1861 Added YAML support to `jx get eks`
  pkg/jx/cmd/get_eks.go
Labels: approved, needs-ok-to-test, size/M

#1860 fix: Add a name field and fix ids
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
Labels: approved, size/M

#1847 Added logrus based logging to `upgrade cli` command
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/upgrade_cli.go
  pkg/log/log.go
Labels: approved, size/M

#1853 chore: fmt
  pkg/jx/cmd/mocks/matchers/auth_authconfigservice.go
  pkg/jx/cmd/mocks/matchers/clientset_interface.go
  pkg/jx/cmd/mocks/matchers/cmd_factory.go
  pkg/jx/cmd/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/mocks/matchers/io_writer.go
  pkg/jx/cmd/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset0_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/mocks/matchers/table_table.go
  pkg/jx/cmd/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
Labels: size/M

#1863 feat(serverless jenkins)
  Jenkinsfile
  pkg/jx/cmd/import_test.go
  pkg/kube/activity.go
  pkg/prow/prow.go
Labels: approved, size/L

#1867 fix: try moving the close
  pkg/apis/jenkins.io/v1/types_extensions.go
Labels: approved, size/XS

#1845 fix:(anchore) use the current namespace to retrieve the dev namespace for basic auth
  pkg/jx/cmd/create_addon.go
Labels: approved, size/XS

#1858 Upgrade to Anchore chart 0.2.3 by default
  pkg/jx/cmd/create_addon_anchore.go
Labels: approved, size/XS

#1844 Added --always-upgrade flag to `jx upgrade platform`
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, size/S

#1871 fix: properly use the prow branch in team controller
  pkg/jx/cmd/install.go
Labels: approved, size/XS

#1829 standardize casing
  pkg/config/project_config.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/create_addon_knative_build.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/logs.go
  pkg/jx/cmd/step_create_build.go
  pkg/jx/cmd/test_data/step_create_build/README.md
Labels: approved, size/M

#1874 Open docs
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/docs.go
Labels: approved, size/S

#1875 feat: summary info for code coverage
  pkg/apis/jenkins.io/v1/types_pipeline.go
Labels: approved, size/M

#1879 Fetchbranch
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/auth_authconfigservice.go
  pkg/jx/cmd/mocks/matchers/clientset0_interface.go
  pkg/jx/cmd/mocks/matchers/cmd_factory.go
  pkg/jx/cmd/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/mocks/matchers/io_writer.go
  pkg/jx/cmd/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/mocks/matchers/table_table.go
  pkg/jx/cmd/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_collect.go
Labels: approved, size/L

#1883 could of bug fixes
  pkg/jx/cmd/import.go
  pkg/kube/env.go
  pkg/kube/ingress.go
Labels: approved, size/M

#1877 fix: actually display the name
  pkg/jx/cmd/step_pre_extend.go
Labels: approved, size/XS

#1872 Allow for verbose logging on `jx create cluster minikube`
  pkg/jx/cmd/create_cluster_minikube.go
Labels: approved, size/XS

#1887 feat(github limits) added a command to display current github limits
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_limits.go
Labels: approved, size/L

#1889 fix: wrong type in map
  pkg/apis/jenkins.io/v1/types_pipeline.go
Labels: approved, size/XS

#1891 chore: fmt
  pkg/jx/cmd/common.go
  pkg/jx/cmd/get_eks.go
  pkg/jx/cmd/get_limits.go
  pkg/jx/cmd/mocks/matchers/auth_authconfigservice.go
  pkg/jx/cmd/mocks/matchers/clientset0_interface.go
  pkg/jx/cmd/mocks/matchers/cmd_factory.go
  pkg/jx/cmd/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/mocks/matchers/io_writer.go
  pkg/jx/cmd/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/mocks/matchers/table_table.go
  pkg/jx/cmd/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/upgrade_cli.go
  pkg/log/log.go
Labels: approved, size/M

#1888 feat: namespace extensions
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/step_pre_extend.go
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/M

#1892 fix: try another way to get the gh-pages branch checked out
  pkg/jx/cmd/step_collect.go
Labels: approved, size/XS

#1832 fix: jx edit gitprivate
  pkg/jx/cmd/common_team_settings.go
Labels: approved, size/S

#1837 fix: ask for git user credentials in more cases
  pkg/gits/provider.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/gc_previews.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/step_split_monorepo.go
Labels: approved, size/M

#1838 fix: ask for organisation before replacing placeholders
  pkg/jx/cmd/import.go
Labels: approved, size/S

#1894 fix: Add .lock to extensions repo filename
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/XS

#1896 fix: ensure extensions CRD is created
  pkg/jx/cmd/step_pre_extend.go
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/S

#1899 feat: Add Extensions repo .lock file tooling
  pkg/jx/cmd/update.go
  pkg/jx/cmd/update_extensions.go
  pkg/jx/cmd/update_extensions_repository.go
Labels: approved, size/L

#1900 feat(builders) Added jenkins-x-builders as a downstream of jx
  .updatebot.yml
Labels: size/XS

#1904 Revert "fix: ask for organisation before replacing placeholders"
  pkg/jx/cmd/import.go
Labels: approved, size/S

#1902 fix: unbreak jx import --list-packs
  pkg/jx/cmd/import.go
Labels: approved, size/XS

#1907 feat: add `jx cloudbees pipeline` command
  pkg/jx/cmd/cloudbees.go
  pkg/jx/cmd/cloudbees_pipeline.go
Labels: approved, size/L

#1906 feat(updatebot) added jenkins-x-serverless as downstream job
  .updatebot.yml
Labels: approved, size/XS

#1908 feat: recursively resolve composite extensions
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/jx/cmd/update_extensions_repository.go
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/L

#1911 Chore: rename update extensions repository to upgrade extensions repo…
  pkg/jx/cmd/update.go
  pkg/jx/cmd/update_extensions.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_extensions_repository.go
Labels: approved, size/L

#1913 feat:(addon vault opeator) add an addon for vault-operator
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_addon_vault.go
  pkg/kube/constants.go
Labels: approved, size/L

#1914 Improved debug log logic for EKS
  pkg/jx/cmd/create_cluster_eks.go
Labels: approved, size/M

#1912 fix: trim the v prefix to create a version from a tag
  pkg/jx/cmd/upgrade_extensions_repository.go
Labels: approved, size/XS

#1915 `jx install --provider=eks` should check for binaries dependencies
  pkg/jx/cmd/install.go
Labels: approved, size/S

#1884 feat:(addon) add a command which deletes the sso addon
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/delete_addon.go
  pkg/jx/cmd/delete_addon_cloudbees.go
  pkg/jx/cmd/delete_addon_sso.go
  pkg/jx/cmd/step_validate.go
  pkg/kube/constants.go
Labels: approved, size/L

#1917 chore: big refactor of extensions data model
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/jx/cmd/step_pre_extend.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_extensions_repository.go
  pkg/kube/extensions.go
Labels: approved, size/XL

#1886 feat:(addon) define a global option for version which is used by all create addon commands
  pkg/binaries/binaries.go
  pkg/binaries/binaries_test.go
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_ambassador.go
  pkg/jx/cmd/create_addon_anchore.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/create_addon_gitea.go
  pkg/jx/cmd/create_addon_istio.go
  pkg/jx/cmd/create_addon_kubeless.go
  pkg/jx/cmd/create_addon_pipeline_events.go
  pkg/jx/cmd/create_addon_prow.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_addon_vault.go
Labels: approved, size/L

#1919 feat: actually execute children
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/step_pre_extend.go
Labels: approved, size/M

#1833 fix:(install) set GitHub as default git provider URL
  pkg/jx/cmd/common_git.go
Labels: approved, size/XS

#1921 fix: better colouration :-)
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/S

#1922 fix: nicer layout on screen
  pkg/jx/cmd/step_pre_extend.go
Labels: approved, size/XS

#1924 feat: actually we need to carry the tree to pre extend
  pkg/jx/cmd/step_pre_extend.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_extensions_repository.go
Labels: approved, size/M

#1927 feat: use configmap to control installed extensions
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/step_post_run.go
  pkg/jx/cmd/step_pre_extend.go
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/L

#1928 fix: attempt to fix indents in tree
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/S

#1926 fix: removed builder-base as a downstream job
  .updatebot.yml
Labels: approved, size/XS

#1835 Expose tiller namespace to extraValues
  pkg/jx/cmd/install.go
Labels: approved, size/XS

#1932 fix setting chartmuseum admin password
  pkg/config/admin_secrets.go
  pkg/config/admin_secrets_test.yaml
Labels: approved, size/S

#1933 feat: allow definitions to specify remotes and tags
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/upgrade_extensions_repository.go
Labels: approved, size/L

#1936 Don't try and re-add an alias
  pkg/jx/cmd/common_helm.go
Labels: approved, size/XS

#1930 Upgraded eksctl version
  pkg/binaries/binaries.go
Labels: approved, size/XS

#1931 Added `jx delete eks` command
  pkg/jx/cmd/delete.go
  pkg/jx/cmd/delete_eks.go
Labels: approved, size/M

#1895 Created Prometheus addon
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_prometheus.go
Labels: approved, size/L

#1935 Upgraded AWS SDK
  Gopkg.lock
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/reporter.go
  vendor/github.com/aws/aws-sdk-go/aws/defaults/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/request/validation.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/internal/s3err/error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/host.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ecr/api.go
  vendor/github.com/aws/aws-sdk-go/service/elbv2/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/s3/service.go
  vendor/github.com/aws/aws-sdk-go/service/s3/statusok_error.go
  vendor/github.com/aws/aws-sdk-go/service/s3/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: approved, size/XXL

#1941 BitBucketCloudProvider should be automatically detected from server URL
  pkg/gits/provider.go
Labels: approved, size/S

#1925 fix(cli upgrade): Extract JX tarball to temp folder during cli upgrade.
  pkg/jx/cmd/common_install.go
Labels: approved, size/S

#1939 'delete aws' command should respect profile option
  pkg/jx/cmd/delete_aws.go
Labels: approved, size/S

#1944 feat: pass team namespace to extension
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/step_pre_extend.go
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/M

#1945 feat: switch to fact model
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
Labels: approved, size/L

#1951 feat: add ComplianceCheck CRD
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types_governance.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/compliancecheck.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_compliancecheck.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/v1/compliancecheck.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/listers/jenkins.io/v1/compliancecheck.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
Labels: approved, size/XL

#1949 Deleted duplicate option given at gc example
  pkg/jx/cmd/gc.go
Labels: approved, size/XS

#1961 feat(codeship) passing on prow & tiller flags to codeship build
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/jx/cmd/create_codeship.go
Labels: approved, size/M

#1962 feat: add some facts constants
  pkg/apis/jenkins.io/v1/types_pipeline.go
Labels: approved, lgtm, size/S

#1964 fix: add pipelineuser back into auth pending schema.
  pkg/auth/config_service.go
  pkg/auth/types.go
Labels: approved, size/S

#1966 feat: add `jx start compliance`
  pkg/jx/cmd/start.go
  pkg/jx/cmd/start_compliance.go
  pkg/prow/prow.go
Labels: approved, size/L

#1967 fix(upgrade) lets backup prow config and allow individual plugins to be upgraded
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/kube/constants.go
Labels: approved, size/M

#1970 Fix: minor changes to compliance check
  pkg/prow/prow.go
Labels: approved, size/XS

#1972 fix: switch to using the commit sha for the compliance check
  pkg/jx/cmd/step_pre_check_compliance.go
Labels: approved, size/M

#1974 fix: pass should not be empty
  pkg/apis/jenkins.io/v1/types_governance.go
Labels: approved, size/XS

#1969 Add Dropwizard draft pack detection
  pkg/jx/cmd/common_import.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/import.go
  pkg/util/pom_flavour.go
Labels: approved, size/S

#1971 feat: extract lastCommitSha from prow
  pkg/jx/cmd/controller_build.go
Labels: approved, size/S

#1979 Compliancecontroller1
  charts/controller-compliance/Chart.yaml
  charts/controller-compliance/Makefile
  charts/controller-compliance/requirements.yaml
  charts/controller-compliance/values.yaml
  pkg/gits/github.go
  pkg/governance/compliance.go
  pkg/jx/cmd/controller_compliance.go
  pkg/jx/cmd/step_pre.go
  pkg/jx/cmd/step_pre_check.go
  pkg/jx/cmd/step_pre_check_compliance.go
  pkg/prow/prow.go
Labels: approved, size/XL

#1976 fix: missing new line in log
  pkg/jx/cmd/init.go
Labels: approved, size/XS

#1980 fix: specify service account
  pkg/prow/prow.go
Labels: approved, size/XS

#1981 feat: use tagged extension repos
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_extensions_repository.go
  pkg/util/downloads.go
Labels: approved, size/M

#1982 warn if we cannot upgrade an addon
  pkg/jx/cmd/upgrade_addons.go
Labels: approved, size/XS

#1983 docs: correct misleading comments in create cluster and formatting
  pkg/jx/cmd/create_cluster.go
Labels: approved, size/S

#1984 feat: allow status to be overridden
  pkg/governance/compliance.go
Labels: approved, size/S

#1987 standardize “macOS”
  docs/dev/changelog-header.md
  pkg/jx/cmd/common.go
Labels: approved, size/XS

#1986 fix: allow install of new extensions
  pkg/jx/cmd/upgrade_extensions_repository.go
Labels: approved, size/XS

#1988 fix: remove nil pointer dereference
  pkg/governance/compliance.go
Labels: approved, size/XS

#1990 fix: get the sha for a post submit build
  pkg/jx/cmd/controller_compliance.go
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/XS

#1991 fix: branch for PRs
  pkg/jx/cmd/controller_compliance.go
Labels: approved, size/XS

#1995 Fix: swallow error if no gh-pages branch, as we’ll create it later
  pkg/jx/cmd/step_collect.go
Labels: approved, lgtm, size/S

#1996 fix: must use branch name in attachment url
  pkg/jx/cmd/step_collect.go
Labels: approved, lgtm, size/XS

#1959 feat:(vault) add a command which creates a vault backed by GCP
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/cloud/gke/gcloud.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_gke.go
  pkg/jx/cmd/create.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_gke_terraform.go
  pkg/jx/cmd/create_gke_service_account.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/kube/service_accounts.go
  pkg/kube/vault.go
  vendor/github.com/banzaicloud/bank-vaults/LICENSE
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1/doc.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1/register.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1/types.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/doc.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/doc.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/generated_expansion.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vault.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vault_client.go
  vendor/github.com/banzaicloud/bank-vaults/operator/pkg/client/clientset/versioned/typed/vault/v1alpha1/vaultlist.go
  vendor/github.com/operator-framework/operator-sdk/LICENSE
  vendor/github.com/operator-framework/operator-sdk/pkg/util/k8sutil/constants.go
  vendor/github.com/operator-framework/operator-sdk/pkg/util/k8sutil/k8sutil.go
Labels: approved, size/XXL

#1956 feat: add --values flag to jx create addon, closes #1954
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_ambassador.go
  pkg/jx/cmd/create_addon_anchore.go
  pkg/jx/cmd/create_addon_gitea.go
  pkg/jx/cmd/create_addon_istio.go
  pkg/jx/cmd/create_addon_kubeless.go
  pkg/jx/cmd/create_addon_pipeline_events.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_addon_vault.go
Labels: approved, lgtm, size/M

#2004 rename cdx -> core
  pkg/jx/cmd/cloudbees.go
  pkg/jx/cmd/cloudbees_pipeline.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/delete_addon_cloudbees.go
  pkg/jx/cmd/login.go
  pkg/jx/cmd/login_test.go
  pkg/kube/constants.go
Labels: approved, size/M

#2014 fix: corrected name of gcloud binaries on windows
  pkg/binaries/binaries.go
Labels: approved, size/XS

#2023 fix: it’s github.io
  pkg/jx/cmd/step_collect.go
Labels: approved, size/XS

#2024 fix: too many build numbers
  pkg/jx/cmd/step_collect.go
Labels: approved, size/XS

#2026 Fix: Remove PR- prefix from branch before getting PullRequest
  pkg/governance/compliance.go
Labels: approved, size/XS

#2027 chore: update name for now, until we can rename CRDs
  pkg/governance/compliance.go
  pkg/jx/cmd/controller_compliance.go
Labels: approved, size/M

#2030 fix: only update GitHub if there is a change
  pkg/governance/compliance.go
Labels: approved, size/M

#2031 added fix for no tiller
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/install.go
Labels: approved, size/M

#2034 fix: check whether we are duplicating status updates
  pkg/governance/compliance.go
  pkg/jx/cmd/controller_compliance.go
Labels: approved, size/M

#2035 chore: expose the CreateDymamicClient interface on Factory
  go.mod
  go.sum
  pkg/cloud/iks/datacenters.go
  pkg/cloud/iks/helper.go
  pkg/cloud/iks/regions.go
  pkg/cloud/iks/registry.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/create_addon_prometheus.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/create_codeship.go
  pkg/jx/cmd/delete_aws.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/clientset_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset0_clientset.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/kube/vault.go
Labels: approved, size/L

#2036 feat: upgrade platform now pulls in the correct env config
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/L

#1968 Fix run kops
  pkg/jx/cmd/create_cluster_aws.go
Labels: approved, size/S

#2032 fix: `jx shell` to make it work in bash/zsh
  pkg/jx/cmd/shell.go
Labels: approved, size/M

#1947 Git credentials passed via `jx install` cmd options should be saved
  pkg/jx/cmd/install.go
Labels: approved, size/S

#1952 Avoid prompting when creating from quickstart in batch mode
  pkg/jx/cmd/create_quickstart.go
  pkg/quickstarts/model.go
Labels: approved, size/XS

#2028 Some cleanup for create cluster iks command
  pkg/cloud/iks/datacenters.go
  pkg/cloud/iks/helper.go
  pkg/cloud/iks/iam.go
  pkg/jx/cmd/create_cluster.go
  pkg/jx/cmd/create_cluster_iks.go
Labels: approved, size/M

#1957 Make jx compliance results available on failures
  pkg/jx/cmd/compliance_results.go
Labels: approved, size/XS

#1999 Default region for registry repository
  pkg/cloud/amazon/ecr.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/step_pre_build.go
Labels: approved, size/S

#2040 fix:(jenkins api token) fall back to old method of acquiring Jenkins API token if Jenkins version cannot be detected
  go.sum
  pkg/jx/cmd/create_jenkins_token.go
Labels: approved, size/S

#2001 Fault tolerant gc previews
  pkg/jx/cmd/gc_previews.go
Labels: approved, size/S

#1885 Add ability to patch service accounts upfront through create env
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_env.go
  pkg/kube/namespaces.go
  pkg/kube/service_accounts.go
Labels: approved, size/M

#1946 Support placeholders in paths for quickstarts
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_placehoders_test.go
  pkg/jx/cmd/test_data/replace_placeholders/REPLACE_ME_APP_NAME/REPLACE_ME_APP_NAME.txt
Labels: approved, lgtm, size/L

#2045 feat:(vault) expose the vault after being created
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/create_vault.go
  pkg/kube/containers.go
  pkg/kube/env.go
  pkg/kube/services.go
  pkg/kube/vault.go
Labels: approved, size/M

#2048 fixes for build controller
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/create_env.go
Labels: approved, size/M

#2051 fix:(upgrade platform) when exposecontroller config is nil
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, size/S

#2057 Fix: add git submodule init
  hack/update-codegen.sh
Labels: approved, lgtm, size/XS

#2058 refactor:(helm test) refactor helm tests to use the commander interface and a mocked helm command
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_fake.go
  pkg/helm/helm_template.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/clientset_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset0_clientset.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/util/commands.go
  pkg/util/interface.go
  pkg/util/mocks/commander.go
Labels: approved, size/XL

#2061 feat(devpods): Allow users to patch Image Pull Secrets when creating DevPods
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/S

#2053 fix:(install) add promt for Jenkins installation type if prow or batch mode is not selected
  pkg/jx/cmd/install.go
Labels: approved, size/S

#2067 fix: prompting for login when creating terraform scripts
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_codeship.go
  pkg/jx/cmd/create_gke_service_account.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/mocks/matchers/auth_authconfigservice.go
  pkg/jx/cmd/mocks/matchers/clientset0_interface.go
  pkg/jx/cmd/mocks/matchers/clientset_interface.go
  pkg/jx/cmd/mocks/matchers/cmd_factory.go
  pkg/jx/cmd/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/mocks/matchers/io_writer.go
  pkg/jx/cmd/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset0_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_dynamic_apihelper.go
  pkg/jx/cmd/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/mocks/matchers/table_table.go
  pkg/jx/cmd/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/shell.go
Labels: approved, size/L

#2071 Update minimum Go version mentioned in Contributing.MD
  CONTRIBUTING.MD
Labels: approved, size/XS

#1975 docs: point hacking.md to content on jenkins-x.io website
  docs/contributing/hacking.md
Labels: approved, size/L

#2066 chore: rename compliance -> commitstatus
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/types_governance.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/commitstatus.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/compliancecheck.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_commitstatus.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_compliancecheck.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/v1/commitstatus.go
  pkg/client/informers/externalversions/jenkins.io/v1/compliancecheck.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/listers/jenkins.io/v1/commitstatus.go
  pkg/client/listers/jenkins.io/v1/compliancecheck.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/extensions/commitstatuses.go
  pkg/jx/cmd/controller.go
  pkg/jx/cmd/controller_commitstatus.go
  pkg/kube/crds.go
Labels: approved, size/XXL

#2070 fix(devpods): Allow for TILLER_NAMESPACE to be passed in to DevPods
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/M

#2074 standardize to uppercase Prow
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/start_compliance.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/kube/constants.go
  pkg/kube/namespaces.go
  pkg/prow/prow.go
Labels: approved, lgtm, size/M

#2078 standarize ChartMuseum casing
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#2065 fix:(cloudbees addon) remove the hack which grants admin permissions to all service accounts
  pkg/jx/cmd/create_addon_cloudbees.go
Labels: approved, size/M

#2075 typos
  CONTRIBUTING.MD
Labels: approved, size/XS

#2076 Bitbucket Server integration: Wrong states are used, promote fails
  go.mod
  go.sum
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
Labels: approved, lgtm, size/S

#2073 Add IBM Cloud Private as a provider
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/common_kube_rbac.go
  pkg/jx/cmd/create_cluster.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
Labels: approved, size/L

#2079 fix(vault): expose properly the vault service
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_vault.go
  pkg/kube/constants.go
  pkg/kube/vault.go
Labels: approved, size/L

#2084 Feat: Switch commit status to depend on branch protection
  pkg/jx/cmd/controller_commitstatus.go
  pkg/jx/cmd/start.go
  pkg/jx/cmd/start_compliance.go
  pkg/jx/cmd/start_protection.go
  pkg/prow/prow.go
Labels: approved, size/L

#2082 fix: minor tweak to skip-login logic when using jx create codeship
  pkg/jx/cmd/create_codeship.go
Labels: approved, size/XS

#2086 feat(vault): add a command which list all vaults available in a namespace
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_vault.go
  pkg/kube/vault.go
Labels: approved, size/L

#2091 feat(vault): add a command which deletes a vault and the cloud resources allocated for it
  pkg/cloud/gke/gcloud.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete.go
  pkg/jx/cmd/delete_vault.go
  pkg/kube/ingress.go
  pkg/kube/vault.go
Labels: approved, lgtm, size/L

#2080 bitbucket server build status fixes #2072
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
Labels: approved, size/XS

#2088 fix(prow): skip the Jenkins API token in a prow installation
  pkg/jx/cmd/install.go
Labels: approved, size/M

#2097 fix(install): Helm install reported as failed but actually succeeded
  pkg/jx/cmd/common_install.go
Labels: approved, size/XS

#2115 feat: updating webhooks based on id if possible
  pkg/gits/bitbucket_server.go
  pkg/gits/github.go
  pkg/gits/provider.go
  pkg/jx/cmd/mocks/matchers/auth_authconfigservice.go
  pkg/jx/cmd/mocks/matchers/clientset0_interface.go
  pkg/jx/cmd/mocks/matchers/cmd_factory.go
  pkg/jx/cmd/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/mocks/matchers/io_writer.go
  pkg/jx/cmd/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_dynamic_apihelper.go
  pkg/jx/cmd/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/mocks/matchers/table_table.go
  pkg/jx/cmd/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/update_webhooks.go
Labels: approved, size/L
