Repository jenkins-x/jx, pull requests merged in 2018-12, with the labels that each got.

#2390 get more test info
  pkg/jx/cmd/compliance_results.go
Labels: approved, lgtm, size/XS

#2375 feat(vault): Store a flag in the jx-install-config to denote if secrets are to be stored in vault
  pkg/io/secrets/secret_locations.go
  pkg/io/secrets/secret_locations_test.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/extraValues.yaml
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/interface.go
  pkg/kube/configmap.go
Labels: approved, lgtm, size/L

#2393 improve CLI for no-tiller
  pkg/builds/build_logs.go
  pkg/helm/helm_template.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/step_collect.go
  pkg/jx/cmd/step_helm.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_helm_delete.go
  pkg/kube/activity.go
  pkg/kube/patch.go
  pkg/util/retry.go
  pkg/util/suggestions.go
Labels: approved, lgtm, size/L

#2408 fix: pass the repo to fetch
  pkg/helm/helm_cli.go
Labels: approved, lgtm, size/XS

#2412 fix: add a team setting for storage locations
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/edit.go
  pkg/jx/cmd/edit_storage.go
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_storage.go
  pkg/jx/cmd/step_collect.go
  pkg/kube/env_cache.go
  pkg/kube/storage.go
Labels: approved, lgtm, size/L

#2418 workaround for promote getting stuck on prow installs see #2410
  pkg/jx/cmd/promote.go
Labels: approved, lgtm, size/S

#2421 Fix: don’t swallow errors on gitops
  pkg/jx/cmd/common_environments.go
Labels: approved, lgtm, size/XS

#2422 fixes for build controller and prow
  pkg/config/helm_values.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/M

#2425 fix: if no options specified lets reuse the arguments
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/step_helm_apply.go
Labels: approved, lgtm, size/M

#2428 Fix: register the plugin CRD
  pkg/kube/crds.go
Labels: approved, lgtm, size/XS

#2426 feat: added the addon version to 'jx get addons'
  pkg/helm/helm_cli.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/helm/mocks/helmer_fake.go
  pkg/jx/cmd/extraValues.yaml
  pkg/jx/cmd/get_addon.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_validate.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_apps.go
Labels: approved, lgtm, size/L

#2434 fix: using correct env.Name when creating environments in prow
  pkg/jx/cmd/create_env.go
Labels: approved, lgtm, size/XS

#2435 fix: removed <>& from the list of allowed symbols in password generation
  pkg/config/admin_secrets.go
Labels: approved, lgtm, size/S

#2439 fix initial build of maven projects and fixed build numbers from `jx start pipeline`
  Dockerfile.jenkins-maven
  Makefile
  go.mod
  go.sum
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/step_changelog.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, lgtm, size/L

#2444 fix: ensure git user + email is setup
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/gits/helpers.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/edit_storage.go
Labels: approved, lgtm, size/M

#2417 refactor(install): break the install command in smaller methods and make the cloud providers configuration more self contained
  pkg/cloud/gke/gcloud.go
  pkg/io/secrets/secret_locations.go
  pkg/io/secrets/secret_locations_test.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/extraValues.yaml
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/uninstall.go
  pkg/util/files.go
  pkg/vault/constants.go
  pkg/vault/vault_client.go
Labels: approved, lgtm, size/XXL

#2446 Disabled prow configuration for jx delete app
  go.mod
  go.sum
  pkg/jx/cmd/controller_commitstatus.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/get_applications.go
  pkg/jx/cmd/import.go
  pkg/prow/config/branch_protection.go
  pkg/prow/config/tide.go
  pkg/prow/config/types.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
  pkg/util/git.go
  pkg/util/git_test.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: approved, lgtm, size/XL

#2450 fix(git): Handier error message if you get errors pushing to https
  pkg/gits/git_cli.go
Labels: approved, lgtm, size/S

#2454 2446-followup
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/controller_commitstatus.go
  pkg/jx/cmd/delete.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/get_applications.go
  pkg/prow/config/branch_protection.go
  pkg/prow/config/branch_protection_test.go
  pkg/prow/config/tide.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, lgtm, size/L

#2456 test(uninstall): make uninstall command test state independent
  pkg/jx/cmd/uninstall.go
  pkg/jx/cmd/uninstall_test.go
Labels: approved, lgtm, size/S

#2453 add a new option to avoid waiting for merge build success as tide isn't updating status #2410
  pkg/jx/cmd/login.go
  pkg/jx/cmd/promote.go
Labels: approved, lgtm, size/M

#2460 fix(jenkins): use only the new API to generate tokens
  pkg/jx/cmd/create_jenkins_token.go
Labels: approved, lgtm, size/L

#2458 fix: lets use the teams StorageLocation settings in `jx step collect`
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/edit_storage.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_collect.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/util/files.go
Labels: approved, lgtm, size/L

#2462 Why would the help for `jx update webhooks` claim it is not implemented?
  pkg/jx/cmd/update_webhooks.go
Labels: approved, lgtm, size/XS

#2466 fix: lets ensure we detect termination of knative builds
  pkg/jx/cmd/controller_build.go
Labels: approved, lgtm, size/XS

#2469 bug(create team): Update status on the Team CRD in the admin namespace
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/delete_team.go
Labels: approved, lgtm, size/M

#2471 feat: use brew if available to install helm
  pkg/jx/cmd/common_install.go
Labels: approved, lgtm, size/S

#2472 fix: removed additional 'Needs more' in jx status output
  pkg/jx/cmd/status.go
Labels: approved, lgtm, size/XS

#2476 Fix jx upgrade extensions repository
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/step_split_monorepo.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_extensions_repository.go
Labels: approved, lgtm, size/M

#2475 fix(github archive api): prevent github archive url from redirecting
  pkg/gits/github.go
Labels: approved, lgtm, ok-to-test, size/XS

#2474 refactor(install): revamp the git auth configuration and make the organization selectable for environment repositories
  pkg/auth/auth_config.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/L

#2479 fix: `jx add app` error if no repo defined
  pkg/jx/cmd/add_app.go
  pkg/kube/namespaces.go
  pkg/kube/namespaces_test.go
Labels: approved, lgtm, size/S

#2478 feat(gke) can now provide oauth scopes when creating gke cluster
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, lgtm, size/XS

#2484 feat: initial support for chart repo username/password
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/helm/mocks/helmer_fake.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_helm_install.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_apps.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/L

#2486 fix(istio-addon): changed directory that istio is unziped in from outputDir to binDir.
  pkg/jx/cmd/create_addon_istio.go
Labels: approved, lgtm, ok-to-test, size/XS

#2481 fix(compliance): print a more user friendly message in the status command when no compliance is found
  pkg/jx/cmd/compliance_status.go
Labels: approved, lgtm, size/XS

#2487 Some git provider refactoring
  go.mod
  go.sum
  pkg/builds/build_info.go
  pkg/extensions/commitstatuses.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_cloud_test.go
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
  pkg/gits/commits.go
  pkg/gits/commits_integration_test.go
  pkg/gits/gerrit.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_provider_fake.go
  pkg/gits/git_url.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitrepositoryinfo.go
  pkg/gits/provider.go
  pkg/gits/provider_fake.go
  pkg/issues/jira.go
  pkg/jenkins/jobs.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/common_environments.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/common_import.go
  pkg/jx/cmd/controller_commitstatus.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/create_pullrequest.go
  pkg/jx/cmd/extraValues.yaml
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_blog.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/test_helpers.go
  pkg/jx/cmd/update_webhooks.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/kube/activity.go
Labels: approved, lgtm, size/XL

#2495 fix: more aggressively push stuff to PipelineActivity
  pkg/jx/cmd/controller_commitstatus.go
Labels: approved, lgtm, size/M

#2499 fix: if there is no team setting for classifier, don't use default, b…
  pkg/jx/cmd/step_collect.go
Labels: approved, lgtm, size/XS

#2497 fixes(#2496) add support for bash completion on debian devpod images
  pkg/jx/cmd/create_devpod.go
Labels: approved, lgtm, ok-to-test, size/XS

#2501 fix: handle BUILD_ID and BUILD_NUMBER
  pkg/jx/cmd/controller_commitstatus.go
Labels: approved, lgtm, size/S

#2502 fix(secrets): clean up the old jenkins-git-credentials secret
  pkg/jx/cmd/create_git_api_token.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/L

#2508 fix: hide the error about missing apt-get/yum
  pkg/jx/cmd/create_devpod.go
Labels: approved, lgtm, size/XS

#2523 fix(Jenkinsfile): cleanup the old github credential from Jenkinsfile
  Jenkinsfile
  pkg/jx/cmd/step_git.go
  pkg/jx/cmd/step_git_envs.go
Labels: approved, lgtm, size/L

#2525 bug(install): use client-only mode to install the Helm secrets plugin.
  pkg/jx/cmd/common_install.go
Labels: approved, lgtm, size/XS

#2503 bug(delete team): Clear cached clients & namespaces when switching namespaces
  pkg/jx/cmd/common.go
  pkg/jx/cmd/delete_team.go
Labels: approved, lgtm, size/M

#2531 fix: only load managed plugins if CRD available
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/common_plugins.go
  pkg/jx/cmd/get_plugins.go
Labels: approved, lgtm, size/L

#2505 Added verbose flag to `eks get` command
  pkg/jx/cmd/get_eks.go
Labels: approved, lgtm, ok-to-test, size/XS

#2513 feat(install): store the amdin secrets in vault and to not print the admin password in logs if vault is enabled
  pkg/config/admin_secrets.go
  pkg/config/types.go
  pkg/expose/exposecontroller.go
  pkg/jx/cmd/create_addon_prometheus.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/util/auth.go
  pkg/vault/constants.go
  pkg/vault/helpers.go
  pkg/vault/vault_client.go
  pkg/vault/vault_path.go
Labels: approved, lgtm, size/L

#2537 fix: jenkins client creation inside pods
  pkg/jenkins/utils.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/gc_activities.go
Labels: approved, lgtm, size/M

#2533 Added --git-owner flag to `create env` command
  pkg/jx/cmd/create_env.go
Labels: approved, lgtm, ok-to-test, size/XS

#2538 Upgraded eksctl version
  pkg/binaries/binaries.go
Labels: approved, lgtm, ok-to-test, size/XS

#2511 EKS cluster creation should deal with rolled back stacks
  pkg/cloud/amazon/eks.go
  pkg/jx/cmd/create_cluster_eks.go
Labels: approved, lgtm, ok-to-test, size/M

#2536 Changed "Delete" -> "Deletes" in help for `jx delete eks`
  pkg/jx/cmd/delete_eks.go
Labels: approved, lgtm, ok-to-test, size/XS

#2541 fix: ensure the namespace exists when creating the vault SA
  pkg/kube/serviceaccount/serviceaccounts.go
Labels: approved, lgtm, size/XS

#2540 Remove extravalues files
  .gitignore
  pkg/jx/cmd/extraValues.yaml
Labels: approved, lgtm, size/S

#2547 fixes for aks and git service
  pkg/jx/cmd/create_cluster_aks.go
  pkg/jx/cmd/create_git_server.go
  pkg/kube/crds.go
Labels: approved, lgtm, size/S

#2552 feat: support for external prow plugins
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, lgtm, size/L

#2555 fixes for prow build pods
  Jenkinsfile
  pkg/builds/build_info.go
Labels: approved, lgtm, size/S

#2556 fixes for DevPods
  pkg/jx/cmd/create_devpod.go
Labels: approved, lgtm, size/M

#2557 fix YAML marshalling for gitops
  pkg/config/admin_secrets.go
  pkg/config/admin_secrets_test.go
  pkg/config/helm_values.go
  pkg/config/helm_values_test.go
  pkg/config/preview_values.go
  pkg/io/config_store.go
  pkg/jx/cmd/preview_test.go
Labels: approved, lgtm, size/L

#2554 feat: add labels to PRs
  pkg/gits/github.go
  pkg/gits/provider.go
Labels: approved, lgtm, size/S

#2553 Added Git provider kind option to `jx install`
  pkg/gits/git_repo.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, ok-to-test, size/S

#2559 feat: ignore merge commits when creating changlogs
  pkg/jx/cmd/step_changelog.go
Labels: approved, lgtm, size/XS

#2562 fix(cmd): make the suggestFor consisten with the command action and update the init command description
  pkg/jx/cmd/edit.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/start.go
  pkg/jx/cmd/stop.go
  pkg/jx/cmd/upgrade.go
Labels: approved, lgtm, size/S

#2565 feat: add updatedAt to pull request
  pkg/gits/github.go
  pkg/gits/provider.go
Labels: approved, lgtm, size/XS

#2569 chore: update `go.sum`/`go.mod` for go 1.11.4
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#2567 fix: for long term build logs lets use raw git URLs
  pkg/jx/cmd/controller_build.go
Labels: approved, lgtm, size/XS

#2574 #2573 GKE does not expect a param for this option
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, lgtm, ok-to-test, size/XS

#2558 bug(controller buildnumbers): Remove encoding of PipelineActivity.Name
  go.sum
  pkg/kube/activity.go
  pkg/kube/activity_test.go
Labels: approved, lgtm, size/M
