Repository jenkins-x/jx, pull requests merged in 2018-08, with the labels that each got.

#1416 add OWNERS file for prow approver and reviewer plugin
  OWNERS
  pkg/jx/cmd/common.go
  pkg/jx/cmd/factory.go
Labels: size/S

#1418 fix: fixing prow installation when installing from codeship
  pkg/gits/git_repo.go
  pkg/jx/cmd/common_install.go
Labels: approved, size/XS

#1421 add a CLI for adding/removing Teams/Users
  Gopkg.toml
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types_release.go
  pkg/apis/jenkins.io/v1/types_teams.go
  pkg/apis/jenkins.io/v1/types_users.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_team.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/team.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/team.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/client/listers/jenkins.io/v1/team.go
  pkg/config/project_config.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/create.go
  pkg/jx/cmd/create_team.go
  pkg/jx/cmd/create_user.go
  pkg/jx/cmd/delete.go
  pkg/jx/cmd/delete_team.go
  pkg/jx/cmd/delete_user.go
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_team.go
  pkg/jx/cmd/get_user.go
  pkg/kube/crds.go
  pkg/kube/teams.go
  pkg/kube/users.go
Labels: approved, size/XXL

#1422 feat(builds) install knative build when using prow
  pkg/jx/cmd/common_install.go
  pkg/prow/prow.go
Labels: size/S

#1426 initial support for generating knative builds
  Makefile
  pkg/builds/jenkinsfiles.go
  pkg/builds/jenkinsfiles_test.go
  pkg/config/project_config.go
  pkg/config/project_config_test.go
  pkg/helm/helm_cli.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_create_build.go
  pkg/jx/cmd/step_create_build_test.go
  pkg/jx/cmd/test_data/step_create_build/README.md
  pkg/jx/cmd/test_data/step_create_build/add_common_envvars/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/add_common_envvars/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_pod_templates/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_pod_templates/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_previous_step/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_previous_step/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_build/inherit_pod_template_env_volumes/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/inherit_pod_template_env_volumes/jenkins-x.yml
  pkg/kube/containers.go
  pkg/tests/files.go
Labels: approved, size/XXL

#1429 remove reliance on GOPATH for util command tests ready for switch to …
  pkg/util/commands_test.go
  pkg/util/test_data/scripts/fail_iterator.sh
  pkg/util/test_data/scripts/sleep.sh
Labels: size/M

#1435 fix CRD columns for 1.11
  pkg/kube/crds.go
Labels: size/S

#1436 fix: use correct integer CRD column type
  pkg/kube/crds.go
Labels: size/XS

#1440 feat(gke) only attempting to enable apis if they are not enabled
  pkg/cloud/gke/gcloud.go
Labels: size/M

#1442 fix: Added extra debug information for google cloud shell
  pkg/cloud/gke/gcloud.go
  pkg/terraform/terraform.go
Labels: size/XS

#1445 chore: add extra verbose logging to diagnose cloudshell issue
  pkg/jx/cmd/create_terraform.go
Labels: size/S

#1449 feat(updatebot) updating the jx-tutorial repo after each release
  .updatebot.yml
  Makefile
Labels: approved, size/XS

#1446 add docker-test to Makefile for running unit tests in isolated enviro…
  Makefile
Labels: size/XS

#1454 fix: always add the actuator when creating new projects
  pkg/jx/cmd/create_spring.go
Labels: approved, size/XS

#1455 add tests for versioning. Update Makefile for semver dev builds based…
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/upgrade_cli.go
  pkg/jx/cmd/version.go
  pkg/jx/cmd/version_test.go
  pkg/version/VERSION
  pkg/version/info.go
  pkg/version/info_test.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: size/XXL

#1456 fix: prow installation should support gcp configurations
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/install_test.go
Labels: size/S

#1457 fix: overlayfs2 issue on gke
  Makefile
Labels: size/XS

#1458 fix: lets ensure the web dependency is added to spring boot apps
  pkg/jx/cmd/create_addon_owasp.go
  pkg/jx/cmd/create_spring.go
  pkg/kube/configmap.go
  pkg/kube/constants.go
  pkg/kube/namespaces.go
Labels: approved, lgtm, size/M

#1460 try prune all using docker system prune
  .gitignore
  Makefile
Labels: size/XS

#1459 Fix AWS hosted zone search in Route53
  pkg/cloud/amazon/routes.go
Labels: needs-ok-to-test, size/XS

#1433 Gc preview app
  charts/gc-previews/Chart.yaml
  charts/gc-previews/Makefile
  charts/gc-previews/requirements.yaml
  charts/gc-previews/values.yaml
  charts/step-link-services/Chart.yaml
  charts/step-link-services/Makefile
  charts/step-link-services/requirements.yaml
  charts/step-link-services/values.yaml
Labels: size/L

#1493 allow Releases to be created in the dev namespace
  pkg/jx/cmd/common_jenkins.go
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/gc.go
  pkg/jx/cmd/gc_activities.go
  pkg/jx/cmd/gc_releases.go
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_release.go
  pkg/jx/cmd/step_changelog.go
  pkg/kube/git_services.go
  pkg/kube/releases.go
Labels: size/L

#1499 Add --git-private flag to make private repositories
  pkg/gits/git_repo.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/install.go
Labels: approved, needs-ok-to-test, size/XS

#1509 fix: minor fix to ensure JX_HOME is used when locating .jx dir
  pkg/jx/cmd/create_cluster_gke_terraform.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/update_cluster_gke_terraform.go
Labels: size/S

#1504 feat: add a command which scans a cluster for potential security vulnerabilities
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/scan.go
  pkg/jx/cmd/scan_cluster.go
Labels: approved, lgtm, size/L

#1508 Upgraded aws-sdk version
  Gopkg.lock
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/decode.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/build.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/doc.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
  vendor/github.com/wbrefvem/go-gitlab/commits.go
  vendor/github.com/wbrefvem/go-gitlab/deployments.go
  vendor/github.com/wbrefvem/go-gitlab/events.go
  vendor/github.com/wbrefvem/go-gitlab/gitlab.go
  vendor/github.com/wbrefvem/go-gitlab/group_boards.go
  vendor/github.com/wbrefvem/go-gitlab/group_variables.go
  vendor/github.com/wbrefvem/go-gitlab/keys.go
  vendor/github.com/wbrefvem/go-gitlab/merge_requests.go
  vendor/github.com/wbrefvem/go-gitlab/pipelines.go
  vendor/github.com/wbrefvem/go-gitlab/project_variables.go
  vendor/github.com/wbrefvem/go-gitlab/repositories.go
  vendor/github.com/wbrefvem/go-gitlab/tags.go
Labels: approved, lgtm, needs-ok-to-test, size/XXL

#1502 Crd rolebindings
  pkg/jx/cmd/create_user.go
  pkg/jx/cmd/delete_user.go
Labels: approved, size/M

#1506 Update gc.go
  pkg/jx/cmd/gc.go
Labels: approved, needs-ok-to-test, size/XS

#1513 fix: install command with gitlab provider
  pkg/gits/git_url.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#1517 fix:(gitlab) fix 'delete repo' command for Gitlab
  pkg/gits/gitlab.go
Labels: approved, lgtm, size/M

#1518 fix:(gitlab) get the environment pipelines working with Gitlab v4 API
  pkg/gits/gitlab.go
  pkg/gits/gitlab_test.go
  pkg/gits/test_data/gitlab/group-projects.json
  pkg/gits/test_data/gitlab/user-projects.json
Labels: approved, lgtm, size/L

#1524 Fix: jx update and add structure and docs for mocking/stubbing best practices
  Gopkg.lock
  Makefile
  docs/contributing/hacking.md
  pkg/jx/cmd/common_install.go
  pkg/util/commands.go
  pkg/util/commands_test.go
  pkg/util/dirs.go
  pkg/util/dirs_test.go
  pkg/util/interface.go
  pkg/util/mocks/command_interface.go
  vendor/github.com/onsi/gomega/LICENSE
  vendor/github.com/onsi/gomega/format/format.go
  vendor/github.com/petergtz/pegomock/LICENSE
  vendor/github.com/petergtz/pegomock/dsl.go
  vendor/github.com/petergtz/pegomock/internal/verify/verify.go
  vendor/github.com/petergtz/pegomock/invocation_count_matchers.go
  vendor/github.com/petergtz/pegomock/matcher.go
  vendor/github.com/petergtz/pegomock/matcher_factories.go
  vendor/github.com/petergtz/pegomock/testing_t_support.go
  vendor/github.com/petergtz/pegomock/types.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: approved, lgtm, size/XXL

#1525 chore: remove -a from prune as it is breaking releases.
  Makefile
Labels: size/XS

#1527 fix for error during cluster creation on AWS:
  pkg/jx/cmd/create_cluster_aws.go
Labels: approved, lgtm, size/XS

#1539 fix(CI) test running CI on new cluster
  Jenkinsfile
  pkg/auth/config.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_auth.go
Labels: approved

#1533 refactor: extract into a helper function the code which sets the myvalues.yaml file
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, size/L

#1538 CLI upgrade should show final binary path
  pkg/jx/cmd/common_install.go
Labels: approved, size/XS

#1540 All Git options should be copied for 'jx install'
  pkg/jx/cmd/install.go
Labels: approved, size/XS

#1534 fix:(gitlab) fix the path of the webhook URL
  pkg/gits/gitlab.go
Labels: size/XS

#1552 fix(release) use git creds step so we can make PRs on downstream repos with updatebot
  Jenkinsfile
Labels: approved, lgtm, size/XS

#1542 Correct kind for jira secret
  pkg/jx/cmd/create_tracker_token.go
Labels: approved, size/XS

#1546 chore: upgrade docker commands to use go 1.11
  Makefile
Labels: size/XS

#1560 Openshift registry support
  pkg/config/helm_values.go
  pkg/jx/cmd/install.go
Labels: approved, size/M

#1569 added no wait option to promote, which desables waiting for promotion…
  pkg/jx/cmd/promote.go
Labels: approved, size/XS

#1567 fix:(compliance) update the sonobuoy client library
  Gopkg.lock
  pkg/jx/cmd/compliance_results.go
  pkg/jx/cmd/compliance_status.go
  vendor/github.com/heptio/sonobuoy/pkg/buildinfo/version.go
  vendor/github.com/heptio/sonobuoy/pkg/discovery/queries.go
  vendor/github.com/heptio/sonobuoy/pkg/plugin/driver/daemonset/daemonset.go
  vendor/github.com/heptio/sonobuoy/pkg/plugin/driver/daemonset/template.go
  vendor/github.com/heptio/sonobuoy/pkg/templates/manifest.go
Labels: approved, size/L
