Repository jenkins-x/jx, pull requests merged in 2018-09, with the labels that each got.

#1553 Create docker auth
  pkg/jx/cmd/create.go
  pkg/jx/cmd/create_docker_auth.go
Labels: approved, lgtm, size/L

#1565 fix: allow for downloading quickstarts from other git providers
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/provider.go
  pkg/gits/provider_fake.go
  pkg/quickstarts/model.go
Labels: approved, lgtm, size/M

#1564 feat:(sso addon) create an addon which installs and configures dex identity provider and sso-operator
  pkg/jx/cmd/common_cert_manageer.go
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/upgrade_ingress.go
Labels: size/L

#1576 fix: make jx promote update the PipelineActivity resource
  pkg/jx/cmd/create_cluster.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_changelog.go
Labels: approved, size/M

#1577 feat:(devpod) add an option which defines which container ports will be exposed by the DevPod
  pkg/jx/cmd/create_devpod.go
Labels: size/S

#1582 Added --skip-installation option to 'create cluster' command
  pkg/jx/cmd/create_cluster.go
Labels: approved, size/S

#1587 a few fixes around promote and workflow controller
  Makefile
  charts/controller-build/Chart.yaml
  charts/controller-build/Makefile
  charts/controller-build/requirements.yaml
  charts/controller-build/templates/.gitignore
  charts/controller-build/values.yaml
  pkg/jx/cmd/common_environments.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/promote.go
Labels: size/L

#1586 feat(teams): initial version of a team controller
  pkg/helm/helm_cli.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/controller.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/install.go
  pkg/kube/pod.go
  pkg/prow/prow.go
Labels: approved, size/L

#1578 EKS should use ecr-login
  pkg/jx/cmd/install.go
Labels: approved, size/S

#1588 Added ECR tests
  pkg/cloud/amazon/ecr_test.go
Labels: approved, needs-ok-to-test, size/S

#1580 ECR should take AWS_DEFAULT_REGION into account
  pkg/cloud/amazon/ecr.go
Labels: approved, needs-ok-to-test, size/XS

#1579 Upgraded AWS SDK
  Gopkg.lock
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: size/XXL

#1589 fix: disable the new workflow engine unless specified
  Makefile
  charts/jx/templates/deployment.yaml
  pkg/jx/cmd/common.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/promote.go
Labels: approved, size/S

#1590 fix release pipeline d808702
  Jenkinsfile
  Makefile
Labels: size/XS

#1593 fix: make probes optional in the jx chart
  charts/jx/templates/deployment.yaml
Labels: size/XS

#1591 feat(teams) team controller updates team status when provisioning
  pkg/cloud/amazon/ecr_test.go
  pkg/helm/helm_cli.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/controller_backup.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/update_cluster_gke_terraform.go
  pkg/kube/crds.go
  pkg/kube/pod.go
Labels: approved, size/L

#1592 chore: vendoring
  Gopkg.lock
  vendor/github.com/wbrefvem/go-bitbucket/api_client.go
  vendor/github.com/wbrefvem/go-bitbucket/repositories_api.go
  vendor/github.com/wbrefvem/go-bitbucket/repository.go
Labels: approved, needs-ok-to-test, size/L

#1602 fix: DevPods
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/create_user.go
  pkg/jx/cmd/rsh.go
Labels: size/M

#1603 fix: quickstart filter matches only one quickstart if name is an exac…
  pkg/jx/cmd/import.go
  pkg/quickstarts/model.go
  pkg/quickstarts/model_test.go
Labels: approved, size/L

#1599 Upgraded AWS SDK version
  Gopkg.lock
  vendor/github.com/aws/aws-sdk-go/aws/signer/v4/v4.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
Labels: approved, size/L

#1606 fix: avoid unnecessarily updating PipelineActivity resources
  pkg/jx/cmd/controller_workflow.go
Labels: size/XS

#1607 fix: team-controller now works with helm3
  pkg/helm/helm_cli.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/init.go
  pkg/kube/crds.go
  pkg/prow/prow.go
Labels: approved, size/M

#1609 Add cloud provider config files
  pkg/jx/cmd/install.go
Labels: approved, size/XS

#1613 fix: minor spelling fix in Makefiles
  charts/controller-backup/Makefile
  charts/controller-role/Makefile
  charts/controller-workflow/Makefile
  charts/gc-activities/Makefile
  charts/gc-previews/Makefile
  charts/gc-releases/Makefile
  charts/service-linker/Makefile
Labels: approved, size/S

#1614 feat(team) added basic controller config for team controller
  charts/controller-team/Chart.yaml
  charts/controller-team/Makefile
  charts/controller-team/requirements.yaml
  charts/controller-team/values.yaml
Labels: approved, size/M

#1611 Minor changes/typos in pkg/jx/cmd/install.go
  pkg/jx/cmd/install.go
Labels: approved, needs-ok-to-test, size/S

#1612 Add docker registry organisation through command line argument
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_placehoders_test.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_tag.go
  pkg/jx/cmd/test_data/replace_placeholders/dir1/file.txt
  pkg/jx/cmd/test_data/replace_placeholders/dir2/file.txt
  pkg/jx/cmd/test_data/replace_placeholders/file.txt
Labels: approved, needs-ok-to-test, size/M

#1618 chore: add a helper method so that we can expose services for devpods
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/S

#1625 fix: command line shorthand conflict
  pkg/jx/cmd/create_docker_auth.go
Labels: approved, size/XS

#1624 JXBinaryLocation() function should attempt to lookup for result in env variable
  pkg/util/dirs.go
  pkg/util/dirs_test.go
Labels: approved, lgtm, size/S

#1622 Version should be respected by CommonOptions.installJx()
  pkg/jx/cmd/common_install.go
Labels: approved, size/S

#1627 fix: allowing controller to install any missing dependencies
  charts/controller-team/values.yaml
Labels: approved, size/XS

#1626 feat: create jx-install-config configmap during jx install. For use with
  pkg/cloud/amazon/ecr_test.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_ingress.go
  pkg/kube/config.go
  pkg/kube/configmap.go
  pkg/kube/constants.go
  pkg/kube/ingress.go
  pkg/kube/jx_install_config.go
  pkg/kube/jx_install_config_test.go
  pkg/util/structs.go
  pkg/util/structs_test.go
Labels: size/L

#1630 fix: correctly opens cdx url when sso addon is installed
  pkg/jx/cmd/cloudbees.go
Labels: approved, size/XS

#1632 Environment role bingding for role
  pkg/jx/cmd/controller_role.go
  pkg/jx/cmd/controller_role_test.go
Labels: approved, size/M

#1628 Removed ECR workaround
  pkg/jx/cmd/install.go
Labels: approved, needs-ok-to-test, size/S

#1631 feat:(login) add a login command for CloudBees app
  Gopkg.lock
  Gopkg.toml
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/login.go
  pkg/jx/cmd/login_test.go
  pkg/kube/config.go
  vendor/github.com/hpcloud/tail/LICENSE.txt
  vendor/github.com/hpcloud/tail/ratelimiter/Licence
  vendor/github.com/hpcloud/tail/ratelimiter/leakybucket.go
  vendor/github.com/hpcloud/tail/ratelimiter/memory.go
  vendor/github.com/hpcloud/tail/ratelimiter/storage.go
  vendor/github.com/hpcloud/tail/tail.go
  vendor/github.com/hpcloud/tail/tail_posix.go
  vendor/github.com/hpcloud/tail/tail_windows.go
  vendor/github.com/hpcloud/tail/util/util.go
  vendor/github.com/hpcloud/tail/watch/filechanges.go
  vendor/github.com/hpcloud/tail/watch/inotify.go
  vendor/github.com/hpcloud/tail/watch/inotify_tracker.go
  vendor/github.com/hpcloud/tail/watch/polling.go
  vendor/github.com/hpcloud/tail/watch/watch.go
  vendor/github.com/hpcloud/tail/winfile/winfile.go
  vendor/gopkg.in/tomb.v1/LICENSE
  vendor/gopkg.in/tomb.v1/tomb.go
Labels: approved, size/XXL

#1637 Initial work to add theia
  pkg/jx/cmd/create_devpod.go
  pkg/kube/services.go
Labels: size/M

#1641 fix(pipeline secrets) lets make sure the pipeline user is used in the git secrets
  pkg/jx/cmd/create_env.go
Labels: approved, size/S

#1648 fix: add a simple step to generate a new build number
  pkg/jx/cmd/get_teamrole.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_next_buildnumber.go
  pkg/kube/constants.go
  pkg/kube/crds.go
Labels: approved, size/L

#1650 fix:(login) keep the session open until the user is onboarded an decode the server CA
  pkg/jx/cmd/login.go
Labels: approved, size/M

#1651 fix:(login) remove the decoding of server CA data
  pkg/jx/cmd/login.go
Labels: approved, size/S

#1654 fix:(devpod) fix the pod reuse option
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/M

#1649 Add git cloning
  pkg/jx/cmd/create_devpod.go
Labels: size/L

#1656 Oops, got limit and request inverted
  pkg/jx/cmd/create_devpod.go
Labels: size/XS

#1657 add filtering of `jx ctx` and fixes for `jx edit userrole`
  pkg/jx/cmd/context.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/get_user.go
  pkg/jx/cmd/promote.go
  pkg/kube/roles.go
Labels: approved, size/M

#1658 Bug fix - issue#1635
  pkg/jx/cmd/create_docker_auth.go
  pkg/jx/cmd/step_link_services_test.go
Labels: approved, size/S

#1665 fix devpod reuse and a couple of other fixes
  pkg/helm/helm_cli.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/M

#1660 feat(prow) fix up pre and post triggers
  pkg/prow/prow.go
Labels: approved, size/S

#1662 Add jx to bash completion
  pkg/jx/cmd/create_devpod.go
Labels: approved, lgtm, size/XS

#1646 #1640 - Align Azure datacenters where AKS is available
  pkg/cloud/aks/helper.go
Labels: approved, needs-ok-to-test, size/S

#1669 fix: lets allow filtering with `jx shell`
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/shell.go
Labels: size/S

#1672 fix: reuse the username CLI argument
  pkg/jx/cmd/create_devpod.go
Labels: size/M

#1675 feat: first working version of prow OWNERS file creation on import
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_test.go
  pkg/jx/cmd/test_data/prow/OWNERS
  pkg/jx/cmd/test_data/prow/no_owners_file/.gitignore
Labels: approved, size/XL

#1680 fix: create devpods
  pkg/jx/cmd/create_devpod.go
Labels: size/S

#1681 feat(prow) use language detection to select builder image
  pkg/gits/git_cli.go
  pkg/jx/cmd/import.go
  pkg/prow/prow.go
Labels: approved, size/M

#1682 fix: make username configurable on `jx rsh`
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/rsh.go
Labels: size/M

#1687 feat:(login) add support for bearer token in the factory
  Makefile
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/kube/config.go
Labels: approved, size/L

#1686 fix: tide config now separated into two blocks
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: size/M

#1684 fix:(login) configure the default namespace when storing the kube config
  pkg/jx/cmd/login.go
  pkg/kube/config.go
Labels: size/S

#1677 fix: run jx team after jx login to switch the team
  pkg/jx/cmd/login.go
Labels: size/XS

#1685 fix: delete app should only delete from permanent environments
  pkg/jx/cmd/delete_app.go
Labels: size/XS

#1674 Add client secret and service principal to aks create cluster - fix #1643
  pkg/jx/cmd/create_cluster_aks.go
Labels: approved, size/S

#1690 add 'jx upgrade addons' and fix for 'jx upgrade plattform`
  pkg/jx/cmd/gc_activities.go
  pkg/jx/cmd/upgrade.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/kube/namespaces.go
Labels: approved, size/L

#1688 fix(prow) use correct deploy namepace and run jx commands in corrent workdir
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_env.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, size/M

#1692 fix: better fix for finding kops state from env var
  pkg/jx/cmd/create_cluster_aws.go
Labels: size/S

#1697 fixes for prow
  pkg/jx/cmd/common_import.go
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/create_spring.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/install.go
Labels: size/M

#1691 feat:(addon) expose the addon if it has a service defined
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_anchore.go
  pkg/kube/constants.go
Labels: size/M

#1698 fix: do not search theia service when the sync option is toggled
  pkg/jx/cmd/create_devpod.go
Labels: size/S

#1700 Fixed typo in cert manager file name
  pkg/jx/cmd/common_cert_manager.go
Labels: approved, needs-ok-to-test, size/XS

#1704 Add "disk-size" option to "jx create cluster minikube"
  pkg/jx/cmd/constants.go
  pkg/jx/cmd/create_cluster_minikube.go
Labels: approved, lgtm, size/S

#1706 fix: added helm debugging, checking for noTiller on 'jx step helm build'
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_auth_test.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/controller_role_test.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/create_quickstart_integration_test.go
  pkg/jx/cmd/get_workflow_integration_test.go
  pkg/jx/cmd/import_integration_test.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/jx_namespace_test.go
  pkg/jx/cmd/step_create_build_test.go
  pkg/jx/cmd/step_link_services_test.go
Labels: approved, size/M

#1708 feat(tiller) added common flags to 'jx step helm build'
  pkg/jx/cmd/common.go
  pkg/jx/cmd/step_helm_build.go
Labels: approved, size/XS

#1710 fix: fix log message for noTiller
  pkg/jx/cmd/common.go
Labels: approved, size/XS

#1711 Allow user to select a subscription when creating aks cluster
  pkg/jx/cmd/create_cluster_aks.go
Labels: approved, lgtm, size/S

#1707 fix:(tilerless) some fixes to get the tillerless installtion going when there is already a tiller/helm installed
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/install.go
Labels: approved, size/M

#1713 Allow users to override the Docker registry used in DevPods.
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/M

#1712 Fix bitbucket cloud paging
  Gopkg.lock
  pkg/gits/bitbucket_cloud.go
  pkg/jx/cmd/create_quickstart.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: approved, lgtm, size/XXL

#1719 chore: update image version in knative containers
  pkg/prow/prow.go
Labels: approved, lgtm, size/XS

#1723 fix: ignore error when detecting if prow is enabled
  pkg/jx/cmd/gc_activities.go
Labels: approved, needs-ok-to-test, size/XS

#1726 Add an environment flag to "jx rsh"
  pkg/jx/cmd/rsh.go
Labels: approved, size/S

#1730 feat(prow): only returning an error if not 'deployment not found'
  pkg/jx/cmd/gc_activities.go
  pkg/kube/namespaces.go
Labels: size/S

#1729 fix: minor spelling mistake in upgrade ingress command
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, size/XS

#1733 Update OWNERS
  OWNERS
Labels: size/XS

#1732 Ports2
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/M

#1734 Theia version
  pkg/jx/cmd/create_devpod.go
Labels: approved, size/S

#1725 feat: add flags to delete cluster and user to jx delete context
  pkg/jx/cmd/delete_context.go
Labels: approved, size/S

#1716 fix:(prow) crate the prow OWNERS_ALIASES file when importing a project
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_test.go
  pkg/jx/cmd/test_data/prow/OWNERS_ALIASES
Labels: approved, size/M

#1739 Added AWS region resolving logic
  pkg/jx/cmd/delete_aws.go
Labels: approved, lgtm, size/S

#1745 feat: Default DEX URL
  pkg/jx/cmd/create_addon_cloudbees.go
Labels: approved, lgtm

#1747 Cloudbees prompts
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, size/S

#1748 fix: remove trailing slash
  pkg/jx/cmd/create_addon_cloudbees.go
Labels: approved, size/XS

#1749 Correct email value in create docker auth command
  pkg/jx/cmd/create_docker_auth.go
Labels: approved, size/XS

#1742 standardize casing for Environment
  pkg/jx/cmd/delete_env.go
  pkg/jx/cmd/promote.go
Labels: approved, size/XS

#1735 fix: gc-activities needs permission to get deployments to detect prow
  charts/jx/values.yaml
Labels: approved, size/XS

#1752 #1737 - Move ip.go to cmd location
  cmd/ip/ip.go
Labels: approved, size/XS

#1754 fix spelling issues with comments
  pkg/addon/config.go
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/chats/provider.go
Labels: size/XS

#1736 `create eks cluster` command should support --node-type flag
  pkg/jx/cmd/create_cluster_eks.go
Labels: approved, needs-ok-to-test, size/XS

#1760 fix: auto-strip trailing slash
  pkg/jx/cmd/create_addon_cloudbees.go
Labels: size/XS

#1756 Added `keep-environments` options to `uninstall` command
  pkg/jx/cmd/uninstall.go
Labels: approved, needs-ok-to-test, size/M

#1764 eksctl binary version should be extracted into const
  pkg/jx/cmd/common_install.go
Labels: needs-ok-to-test, size/XS

#1767 feat(diagnose): Add a `jx diagnose` command to help with debugging.
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/diagnose.go
Labels: needs-ok-to-test, size/M

#1763 standardize casing for Availability Zones
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/init.go
Labels: needs-ok-to-test, size/S

#1757 Extracted AWS region resolving logic
  pkg/cloud/amazon/common.go
  pkg/cloud/amazon/common_test.go
  pkg/cloud/amazon/ecr.go
  pkg/jx/cmd/delete_aws.go
Labels: needs-ok-to-test, size/M

#1741 installChart function should accept struct parameter
  pkg/jx/cmd/common_helm.go
Labels: approved, needs-ok-to-test, size/S

#1555 fix:(jenkins api token) fix the api token for new Jenkins version
  Gopkg.toml
  pkg/jenkins/utils.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/install.go
Labels: approved, size/L

#1779 fixes for install using helm template mode
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_template.go
  pkg/helm/helm_template_test.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/get_addon.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_helm.go
  pkg/jx/cmd/step_helm_install.go
  pkg/jx/cmd/step_helm_version.go
  pkg/jx/cmd/step_validate.go
  pkg/jx/cmd/step_validate_test.go
  pkg/jx/cmd/uninstall.go
  pkg/jx/cmd/upgrade_addons.go
Labels: approved, size/XL

#1784 fix:(login) remove the tailing slash in the cloudbees application URL
  pkg/jx/cmd/login.go
Labels: size/XS

#1778 feat(jenkins) allow jenkins build detection if plugins.txt exists
  pkg/jx/cmd/import.go
Labels: size/XS

#1785 fix:(cloudbees addon) use the create flag to disalbe the sso instead of disable flag
  pkg/jx/cmd/create_addon_cloudbees.go
Labels: approved, size/XS

#1740 feat:(upgrade ingress) add an opitons to upgrade the ingress only for a list of given kubernetes servies
  pkg/jx/cmd/common.go
  pkg/jx/cmd/upgrade_ingress.go
  pkg/kube/services.go
Labels: approved, size/M

#1780 Migrated installChart() calls to installChartOptions()
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_cert_manager.go
  pkg/jx/cmd/create_devpod.go
Labels: approved, needs-ok-to-test, size/S

#1790 fix:(cloudbees) set the chart flags for basic auth before installing the chart
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/login.go
Labels: size/M

#1792 fix:(sso) return an error if the user is not member of any GitHub organization
  pkg/jx/cmd/create_addon_sso.go
Labels: approved, size/XS

#1791 `jx create cluster eks` should respect region resolving logic
  pkg/cloud/amazon/common.go
  pkg/cloud/amazon/common_test.go
  pkg/jx/cmd/create_cluster_eks.go
Labels: needs-ok-to-test, size/S

#1794 Fixes to adding pipeline user as collaborator
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_cloud_test.go
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
  pkg/gits/gerrit.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/gitlab_test.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/provider_fake.go
  pkg/jx/cmd/import.go
Labels: approved, needs-ok-to-test, size/M

#1781 Region for ELB service should be resolved from env
  pkg/jx/cmd/delete_aws.go
Labels: approved, needs-ok-to-test, size/XS

#1788 Fix #1750 - Add more parameters to jx create cluster aks
  pkg/jx/cmd/create_cluster_aks.go
Labels: approved, size/M

#1786 Use AWS region in kops s3 bucket creation
  pkg/jx/cmd/create_cluster_aws.go
Labels: approved, size/XS

#1758 Upgraded AWS SDK
  Gopkg.lock
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/query/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/query/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/restxml/restxml.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: needs-ok-to-test, size/XXL

#1777 Fix: typo in pre build
  pkg/jx/cmd/step_pre_build.go
Labels: approved, size/XS

#1800 feat(cwp) added build detection for custom war packager
  pkg/jx/cmd/import.go
Labels: approved

#1768 Added generic support for extracting version from binaries
  pkg/binaries/binaries.go
  pkg/binaries/binaries_test.go
  pkg/jx/cmd/common_install.go
Labels: approved, needs-ok-to-test, size/L

#1783 Added `jx get eks` command
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_eks.go
Labels: needs-ok-to-test, size/M

#1793 fix:(sso) prompt only the organisations which have the user as member
  pkg/gits/github.go
  pkg/gits/interface.go
  pkg/gits/mocks/organisation_checker.go
  pkg/jx/cmd/create_addon_sso.go
Labels: approved, size/L

#1807 fix(prow) adding in dummy repos when tide config is created
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, size/M

#1799 fix(devpod): Resolve error creating devpods with the sync flag.
  pkg/jx/cmd/create_devpod.go
Labels: approved, needs-ok-to-test, size/M

#1810 fix: git user auth options should be respected in all operations in i…
  pkg/jx/cmd/install.go
Labels: size/XS

#1804 Upgraded eksctl version
  pkg/binaries/binaries.go
  pkg/jx/cmd/common_install.go
Labels: needs-ok-to-test, size/XS

#1816 fix prow and no tiller
  .updatebot.yml
  Jenkinsfile
  charts/jx/templates/cronjob.yaml
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/delete.go
  pkg/jx/cmd/delete_branch.go
  pkg/jx/cmd/delete_repo.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/mocks/factory.go
  pkg/prow/prow.go
Labels: approved, size/L

#1820 AWS commands should respect --region and --profile flags
  pkg/cloud/amazon/ecr.go
  pkg/cloud/amazon/s3.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/get_aws_info.go
  pkg/jx/cmd/get_eks.go
Labels: approved, needs-ok-to-test, size/S

#1823 polish team controller further
  Jenkinsfile
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/install.go
  pkg/kube/version.go
Labels: size/M

#1795 External Jenkins URL
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_import.go
  pkg/jx/cmd/import.go
Labels: approved, size/M

#1809 `upgrade platform` should use platform version from cloud-env
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, size/XS

#1819 fix:(step service link) handle errors and reset the cluster IP
  pkg/jx/cmd/step_link_services.go
Labels: approved, size/S

#1826 chore: put back helper function that got removed in a refactor
  pkg/cloud/amazon/common.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/get_eks.go
  pkg/jx/cmd/step_link_services.go
  pkg/kube/config.go
  pkg/kube/crds.go
  pkg/kube/git_services_test.go
Labels: approved, size/M

#1821 [WIP] Store defaults in team settings
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/auth/config.go
  pkg/auth/config_service.go
  pkg/auth/types.go
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/edit.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/install.go
  pkg/tests/helpers.go
Labels: do-not-merge/work-in-progress, needs-ok-to-test, size/L
