Repository jenkins-x/jx, pull requests merged in 2018-11, with the labels that each got.

#2139 chore(github): add a template for pull request
  .github/pull_request_template.md
Labels: approved, size/S

#2141 fix: need to decode the script file
  pkg/jx/cmd/upgrade_extensions_repository.go
Labels: approved, size/XS

#2144 Fix: remove unused option
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/XS

#2143 chore: add more tests
  pkg/builds/build_info_test.go
  pkg/builds/test_data/pod1.yml
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/get_build_pods.go
Labels: approved, size/L

#2140 fix: better logging for `jx upgrade extensions`
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/M

#2142 fix: hack around the very broken git auth stuff
  pkg/jx/cmd/controller_commitstatus.go
Labels: approved, size/M

#2089 changing case of helm statements for clarity
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/gc_helm.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_helm_version.go
  pkg/jx/cmd/step_split_monorepo.go
  pkg/jx/cmd/upgrade_addons.go
Labels: approved, size/S

#2146 feat(vault): encode to HCL the vault path rule and add some tests
  go.mod
  go.sum
  pkg/jx/cmd/create_vault.go
  pkg/kube/vault.go
  pkg/kube/vault_test.go
  pkg/vault/rule.go
  pkg/vault/rule_test.go
Labels: approved, size/L

#2151 Revert "test(git provider): add tests for git providers creation from URL"
  pkg/auth/server.go
  pkg/gits/provider.go
  pkg/gits/provider_test.go
  pkg/util/environ.go
  pkg/util/environ_test.go
  pkg/util/maps.go
Labels: approved, size/XL

#2093 Alignment of columns when printing multi byte characters
  pkg/table/table.go
  pkg/util/padding.go
Labels: approved, size/S

#2148 Use domain for minikube cluster if set
  pkg/jx/cmd/create_cluster_minikube.go
Labels: approved, size/S

#2161 fix: fix the commitstatus controller
  pkg/jx/cmd/controller_commitstatus.go
Labels: approved, size/M

#2159 fix: complete the role controller
  pkg/builds/build_info_test.go
  pkg/jx/cmd/controller_role.go
  pkg/jx/cmd/controller_role_test.go
Labels: approved, size/XL

#2163 Use domain if specified
  pkg/jx/cmd/install.go
Labels: approved, size/S

#2090 Remove old resources
  pkg/jx/cmd/step_helm_apply.go
Labels: approved, size/S

#2169 fix: correct url for chart museum
  pkg/jx/cmd/init.go
Labels: approved, size/XS

#2170 fix: Use HA URL for chartmuseum
  pkg/jx/cmd/init.go
Labels: approved, size/XS

#2171 fix: improve message
  pkg/jx/cmd/controller_commitstatus.go
Labels: approved, size/XS

#2173 fix: removed references to depreacted chartmuseum instance
  charts/controller-backup/Makefile
  charts/controller-build/Makefile
  charts/controller-compliance/Makefile
  charts/controller-role/Makefile
  charts/controller-team/Makefile
  charts/controller-workflow/Makefile
  charts/gc-previews/Makefile
  charts/gc-releases/Makefile
  charts/jx/Makefile
  charts/service-linker/Makefile
  pkg/helm/helm_cli_test.go
  pkg/jx/cmd/test_data/install_cloud_environments_repo/Makefile
  pkg/kube/test_data/env_modify_namespace/Makefile
Labels: approved, size/M

#2126 `jx promote` coverage increase
  pkg/gits/provider_fake.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/get_workflow_integration_test.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/promote_test.go
  pkg/jx/cmd/test_helpers.go
Labels: approved, lgtm, size/XXL

#2177 chore: make the results of `jx create pr` easier to reuse from BDD tests
  pkg/jx/cmd/create_pullrequest.go
Labels: approved, size/S

#2175 fix:(preview) Try getting CHANGE_URL env variable for PRs, fixes #2174
  pkg/gits/git_cli.go
  pkg/jx/cmd/preview.go
Labels: approved, size/M

#2178 feat(preview): Default to batch mode when running in pipeline.
  pkg/jx/cmd/common.go
  pkg/jx/cmd/preview.go
Labels: approved, size/M

#2182 fix: fix the marshal name for field
  pkg/apis/jenkins.io/v1/types_pipeline.go
Labels: approved, size/XS

#2181 feat(knative adddon) switch to Jenkins X helm chart and improve addon CLI comamnds for knative build
  pkg/jx/cmd/create_addon_knative_build.go
  pkg/jx/cmd/delete_addon.go
  pkg/jx/cmd/delete_addon_knative_build.go
  pkg/kube/constants.go
Labels: approved, size/L

#2155 Update OWNERS file
  OWNERS
Labels: approved, size/S

#2179 fix: adding '--skip-login' to default commands for codeship
  pkg/jx/cmd/create_codeship.go
Labels: approved, size/XS

#2186 fix: ensure releases CRD is registered
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, size/S

#2187 Commitstatus8
  pkg/extensions/commitstatuses.go
  pkg/jx/cmd/controller_commitstatus.go
Labels: approved, size/M

#2185 fix: using gke as the provider when generating the context name
  pkg/jx/cmd/create_terraform.go
Labels: approved, size/XS

#2188 refactor: s/IsInCDPIpeline/IsInCDPipeline/g
  pkg/jx/cmd/common_auth.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/preview.go
Labels: approved, size/M

#2190 feat: add `jx delete extension`
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/delete.go
  pkg/jx/cmd/delete_extension.go
Labels: approved, size/L

#2130 fix: jx upgrade cli not working on windows
  pkg/jx/cmd/common_install.go
  pkg/util/dirs.go
  pkg/util/dirs_test.go
  pkg/util/downloads.go
  pkg/util/test_data/2_files.zip
  pkg/util/unzip.go
  pkg/util/unzip_test.go
Labels: approved, size/L

#2198 feat(helm) added DecryptSecrets method to helm to allow installation of jx-infra
  pkg/helm/helm_cli.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/install.go
Labels: approved, size/M

#2202 fix(bitbucket): Issue creation now returns HTML URL for Issue, fixes …
  pkg/gits/bitbucket_cloud.go
Labels: approved, size/XS

#2199 fix(git): Cleanup git URL parsing logic.
  pkg/gits/git_url.go
Labels: approved, lgtm, size/S

#2197 feat: recursively delete extension children
  pkg/extensions/management.go
  pkg/jx/cmd/delete_extension.go
Labels: approved, size/M

#2167 feat(vault): Vault CLI integration
  pkg/jx/cmd/cloudbees.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common/interfaces.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/common_jenkins.go
  pkg/jx/cmd/create_addon_anchore.go
  pkg/jx/cmd/create_addon_pipeline_events.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/create_etc_hosts.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete_addon.go
  pkg/jx/cmd/delete_vault.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_applications.go
  pkg/jx/cmd/get_secret.go
  pkg/jx/cmd/get_url.go
  pkg/jx/cmd/get_vault.go
  pkg/jx/cmd/get_vault_config.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_post_build.go
  pkg/jx/cmd/test_helpers.go
  pkg/jx/cmd/uninstall_test.go
  pkg/jx/cmd/upgrade_ingress.go
  pkg/jx/cmd/upgrade_ingress_test.go
  pkg/kube/serviceaccount/serviceaccounts.go
  pkg/kube/services/services.go
  pkg/kube/vault_test.go
  pkg/util/pickers.go
  pkg/vault/commonhelpers_test.go
  pkg/vault/interfaces.go
  pkg/vault/jxvaulter.go
  pkg/vault/vault.go
  pkg/vault/vaultfactory.go
  pkg/vault/vaultfactory_test.go
  pkg/vault/vaultselector.go
  pkg/vault/vaultselector_test.go
Labels: approved, lgtm, size/XL

#2208 Picker
  pkg/auth/config.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_archetype.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/create_issue.go
  pkg/jx/cmd/create_jhipster.go
  pkg/jx/cmd/create_lile.go
  pkg/jx/cmd/create_micro.go
  pkg/jx/cmd/create_pullrequest.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/delete_branch.go
  pkg/jx/cmd/delete_context.go
  pkg/jx/cmd/delete_devpod.go
  pkg/jx/cmd/delete_extension.go
  pkg/jx/cmd/delete_preview.go
  pkg/jx/cmd/delete_quickstart_location.go
  pkg/jx/cmd/delete_team.go
  pkg/jx/cmd/delete_user.go
  pkg/jx/cmd/edit_addon.go
  pkg/jx/cmd/edit_buildpack.go
  pkg/jx/cmd/edit_config.go
  pkg/jx/cmd/edit_extensionsrepository.go
  pkg/jx/cmd/edit_userrole.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/logs.go
  pkg/jx/cmd/metrics.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/rsh.go
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/stop_pipeline.go
  pkg/jx/cmd/team.go
  pkg/jx/cmd/uninstall.go
  pkg/jx/cmd/upgrade_ingress.go
  pkg/quickstarts/model.go
  pkg/util/pickers.go
  pkg/vault/vaultselector.go
Labels: approved, size/L

#2212 feat: make prow logging return status code 1 if build fails.
  pkg/jx/cmd/logs.go
Labels: approved, size/S

#2192 lets add a `jx step bdd` step to run BDD tests
  Jenkinsfile
  pkg/auth/config.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/create_git_server.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_bdd.go
  pkg/kube/crds.go
  pkg/kube/git_services.go
Labels: approved, size/XL

#2203 feat(secrets) added secret decryption to upgrade platform
  pkg/helm/helm_cli.go
  pkg/helm/helm_template.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, size/L

#2204 feat(builds) support `jx start pipeline` for knative builds
  pkg/jx/cmd/common.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/start_pipeline.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, size/L

#2215 Automatically source <(jx completion bash) from jx shell
  pkg/jx/cmd/shell.go
Labels: approved, size/XS

#2219 chore: fmt
  go.mod
  go.sum
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/controller_role_test.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/create_git_server.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/mocks/matchers/auth_authconfigservice.go
  pkg/jx/cmd/mocks/matchers/clientset0_interface.go
  pkg/jx/cmd/mocks/matchers/cmd_factory.go
  pkg/jx/cmd/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/mocks/matchers/io_writer.go
  pkg/jx/cmd/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_dynamic_apihelper.go
  pkg/jx/cmd/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/mocks/matchers/table_table.go
  pkg/jx/cmd/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/promote_test.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/test_helpers.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/kube/git_services.go
  pkg/util/dirs.go
  pkg/util/dirs_test.go
  pkg/util/unzip.go
  pkg/util/unzip_test.go
Labels: approved, size/L

#2216 fix up knative build addon
  pkg/config/helm_values.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_knative_build.go
  pkg/jx/cmd/delete_addon_knative_build.go
  pkg/jx/cmd/install.go
Labels: approved, size/M

#2221 Revert "fix up knative build addon"
  pkg/config/helm_values.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_knative_build.go
  pkg/jx/cmd/delete_addon_knative_build.go
  pkg/jx/cmd/install.go
Labels: size/S

#2223 fix up knative build addon
  pkg/config/helm_values.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_knative_build.go
  pkg/jx/cmd/delete_addon_knative_build.go
  pkg/jx/cmd/install.go
Labels: approved, size/S

#2211 fix unit test on OS-X
  pkg/util/dirs_test.go
Labels: approved, size/XS

#2207 Nil map
  pkg/extensions/config.go
  pkg/jx/cmd/edit_extensionsrepository.go
Labels: approved, size/XS

#2201 feat(aws): add tags flag to tag AWS resource
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_cluster_eks.go
Labels: approved, size/S

#2220 feat: load jx-install-config from encrypted secrets stored in git
  pkg/config/admin_secrets.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, size/L

#2166 Refactor Helmer creation from CommonOptions to Factory.
  pkg/gits/interface.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_commands.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/preview.go
  pkg/kube/activity_test.go
  pkg/util/process.go
Labels: approved, size/L

#2213 refactor(auth config): create the building blocks for refactoring the current auth config (updated data model, readers and writers)
  pkg/auth/auth_config.go
  pkg/auth/auth_config_test.go
  pkg/auth/config.go
  pkg/auth/config_test.go
  pkg/auth/server.go
  pkg/auth/user_auth.go
  pkg/auth/user_auth_test.go
  pkg/gits/provider.go
  pkg/gits/provider_test.go
  pkg/io/config_readers.go
  pkg/io/config_readers_test.go
  pkg/io/config_writers.go
  pkg/io/config_writers_test.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/create_chat_token.go
  pkg/jx/cmd/create_token_addon.go
  pkg/jx/cmd/create_tracker_token.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/gc_previews.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/step_split_monorepo.go
  pkg/kube/constants.go
  pkg/kube/metadata.go
  pkg/util/environ.go
  pkg/util/environ_test.go
  pkg/util/maps.go
  pkg/util/urls.go
Labels: approved, size/XXL

#2232 fix(preview): switch to create git provider in oder to fix the preview update into the PR
  pkg/jx/cmd/factory.go
Labels: approved, size/XS

#2234 Fix: Avoiding unnecessary initialization just to get struct members
  pkg/jx/cmd/common_team_settings.go
Labels: approved, size/XS

#2236 feat: attempting to validate terraform version before install
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/import_placehoders_test.go
  pkg/terraform/terraform.go
  pkg/terraform/terraform_test.go
Labels: approved, size/L

#2237 Use default-environment-prefix if provided
  pkg/jx/cmd/common_gke.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_gke_terraform.go
Labels: approved, lgtm, size/M

#2240 feat: export kube.RegisterCRD
  pkg/kube/crds.go
Labels: approved, size/M

#2239 fix:(bitbucket) Handle some more idiosyncratic Bitbucket Server URLs
  pkg/gits/git_url.go
  pkg/gits/git_url_test.go
Labels: approved, size/XS

#2087 Allow promote for other than cluster admins
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/kube/crds.go
Labels: approved, size/M

#2242 feat: handling error response from spring quickstart
  pkg/jx/cmd/create_cluster_gke_terraform.go
  pkg/jx/cmd/import_placehoders_test.go
  pkg/spring/model.go
  pkg/terraform/terraform.go
  pkg/util/dirs_test.go
Labels: approved, size/M

#2228 improvement: Add convenient way to get HTTP Client with sensible timeouts
  pkg/jx/cmd/common_install.go
  pkg/util/downloads.go
  pkg/util/http_utils.go
  pkg/util/http_utils_test.go
Labels: approved, size/L

#2235 first spike of the GitOps mode for jx install
  Makefile
  pkg/gits/constants.go
  pkg/gits/git_fake.go
  pkg/gits/git_provider_fake.go
  pkg/gits/git_url.go
  pkg/gits/provider.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
  pkg/helm/helm_template.go
  pkg/helm/mocks/helmer_fake.go
  pkg/jenkins/fake/fake_jenkins.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_environments.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/common_import.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/create_quickstart_location.go
  pkg/jx/cmd/delete_quickstart_location.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_env.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_post.go
  pkg/jx/cmd/step_post_install.go
  pkg/jx/cmd/step_post_install_integration_test.go
  pkg/kube/configmap.go
  pkg/kube/env.go
  pkg/kube/namespaces.go
  pkg/kube/secrets.go
  pkg/testkube/secrets.go
  pkg/util/maps.go
Labels: approved, size/XXL

#2246 Fix: Allow non admin to execute various jx commands
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/create_quickstart.go
  pkg/jx/cmd/get_activity.go
  pkg/jx/cmd/get_env.go
  pkg/jx/cmd/get_issue.go
  pkg/jx/cmd/get_preview.go
  pkg/jx/cmd/get_release.go
  pkg/jx/cmd/get_user.go
  pkg/jx/cmd/get_workflow.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/step_post_install.go
Labels: approved, size/M

#2247 feat: allow registering CRDs for other groups
  pkg/kube/crds.go
Labels: approved, size/S

#2248 fix: ensure RegisterAllCRDs works well with gitops mode
  .gitignore
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/create_pullrequest.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/auth_authconfigservice.go
  pkg/jx/cmd/mocks/matchers/clientset_interface.go
  pkg/jx/cmd/mocks/matchers/cmd_factory.go
  pkg/jx/cmd/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/mocks/matchers/io_writer.go
  pkg/jx/cmd/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset0_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_dynamic_apihelper.go
  pkg/jx/cmd/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/mocks/matchers/table_table.go
  pkg/jx/cmd/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/uninstall.go
Labels: approved, size/L

#2249 `create vault` prompts the user for a vault name if in interactive mode
  pkg/jx/cmd/create_vault.go
Labels: approved, size/S

#2251 feat: added support for --gitops flag in codeship build
  pkg/jx/cmd/create_codeship.go
Labels: approved, lgtm, size/XS

#2250 fix for lazy create namespace if using gitops
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_post_install.go
  pkg/util/downloads.go
Labels: approved, size/S

#2254 s/amy/any/
  pkg/jx/cmd/install.go
Labels: approved, size/XS

#2255 Copy editing on help
  pkg/jx/cmd/step_post_install.go
Labels: approved, size/XS

#2257 Fail the build if there are uncommitted modifications
  Jenkinsfile
Labels: approved, size/XS

#2260 fix: updated log message when checking terraform version
  pkg/terraform/terraform.go
Labels: approved, size/XS

#2262 fix: typo "Examples: jx create pullRequest" at "jx create pullrequest…
  pkg/jx/cmd/create_pullrequest.go
Labels: approved, size/S

#2252 Vault install
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/M

#2268 add support for a post install job for gitop dev mode
  charts/jx/templates/job.yaml
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/step_tag.go
  pkg/kube/env.go
  pkg/kube/namespaces.go
  pkg/kube/namespaces_test.go
Labels: approved, size/M

#2264 feat(serve-buildnumbers): Add new cmd to serve build numbers over HTTP interface.
  pkg/buildnum/build_num_gen.go
  pkg/buildnum/http_build_num.go
  pkg/buildnum/http_build_num_test.go
  pkg/buildnum/interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/buildnum/mocks/matchers/kube_pipelineid.go
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/serve_buildnumbers.go
  pkg/jx/cmd/step_next_buildnumber.go
  pkg/kube/activity.go
  pkg/kube/activity_test.go
Labels: approved, size/XL

#2272 feat(upgrade) prompt user if kubeProvider is not set
  pkg/buildnum/mocks/matchers/kube_pipelineid.go
  pkg/gits/constants.go
  pkg/gits/git_fake.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/common_team_settings.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/mocks/matchers/auth_authconfigservice.go
  pkg/jx/cmd/mocks/matchers/clientset_interface.go
  pkg/jx/cmd/mocks/matchers/cmd_factory.go
  pkg/jx/cmd/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/mocks/matchers/io_writer.go
  pkg/jx/cmd/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/mocks/matchers/ptr_to_clientset0_clientset.go
  pkg/jx/cmd/mocks/matchers/ptr_to_dynamic_apihelper.go
  pkg/jx/cmd/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/mocks/matchers/table_table.go
  pkg/jx/cmd/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_env.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/kube/configmap.go
  pkg/kube/secrets.go
  pkg/testkube/secrets.go
  pkg/util/http_utils.go
  pkg/util/maps.go
Labels: approved, size/L

#2271 fix for devpods
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/delete.go
  pkg/jx/cmd/delete_namespace.go
  pkg/jx/cmd/delete_team.go
  pkg/jx/cmd/uninstall.go
  pkg/util/downloads.go
  pkg/util/http_utils.go
  pkg/util/http_utils_test.go
Labels: approved, size/L

#2275 Fix err != err
  pkg/jx/cmd/init.go
  pkg/jx/cmd/start_pipeline.go
  pkg/kube/env.go
Labels: approved, size/S

#2280 chore: Update OWNERS
  OWNERS
Labels: size/XS

#2269 A few methods for Gerrit support
  go.mod
  go.sum
  pkg/gits/gerrit.go
  pkg/gits/gerrit_test.go
  pkg/gits/test_data/gerrit/create-project.json
  pkg/gits/test_data/gerrit/list-projects.json
  pkg/util/test.go
Labels: approved, size/L

#2273 fix(controller): Move build number controller under 'jx controllers'
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/controller.go
  pkg/jx/cmd/serve_buildnumbers.go
Labels: approved, size/S

#2274 chore add missing entries from go.sum
  go.sum
Labels: approved, size/XS

#2278 chore: added some debug logging to upgrade platform
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, size/XS

#2281 chore remove internal call to docker system prune for releases.
  Makefile
Labels: approved, size/XS

#2283 feat: `jx add app`
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/gits/provider.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/helm/mocks/helmer_fake.go
  pkg/jx/cmd/add.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/common_environments.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_ambassador.go
  pkg/jx/cmd/create_addon_anchore.go
  pkg/jx/cmd/create_addon_gitea.go
  pkg/jx/cmd/create_addon_istio.go
  pkg/jx/cmd/create_addon_kubeless.go
  pkg/jx/cmd/create_addon_pipeline_events.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_helm_install.go
  pkg/jx/cmd/test_helpers.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/kube/env.go
Labels: approved, size/XL

#2287 fix: improved format of log messages on upgrade
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, size/XS

#2284 typo
  pkg/tests/helpers.go
Labels: approved, size/XS

#2290 feat(buildlogs): Displays which build it is printing logs for
  pkg/jx/cmd/get_build_logs.go
Labels: approved, size/XS

#2295 A new test case and a make target for debugging git tests
  Makefile
  pkg/gits/bitbucket_cloud_test.go
Labels: approved, size/L

#2292 feat: `jx upgrade apps`
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/common_app.go
  pkg/jx/cmd/common_environments.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/upgrade.go
  pkg/jx/cmd/upgrade_apps.go
  pkg/jx/cmd/upgrade_apps_test.go
Labels: approved, size/XL

#2293 add support for Cloud Native Build Packs
  pkg/jenkinsfile/buildpack.go
  pkg/jenkinsfile/jenkinsfile_writer.go
  pkg/jenkinsfile/jenkinsfile_writer_test.go
  pkg/jenkinsfile/modules.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/step_create_jenkinfiles_integration_test.go
  pkg/jx/cmd/step_create_jenkinfiles_test.go
  pkg/jx/cmd/step_create_jenkinsfile.go
  pkg/jx/cmd/step_post_install.go
  pkg/jx/cmd/step_tag.go
  pkg/jx/cmd/test_data/step_create_jenkinsfile/import_inheritence/Jenkinsfile
  pkg/jx/cmd/test_data/step_create_jenkinsfile/import_inheritence/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_create_jenkinsfile/import_inheritence/README.md
  pkg/jx/cmd/test_data/step_create_jenkinsfile/import_inheritence/import_dir/classic/maven/README.md
  pkg/jx/cmd/test_data/step_create_jenkinsfile/import_inheritence/import_dir/classic/maven/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_jenkinsfile/import_inheritence/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence/Jenkinsfile
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence/README.md
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence/base-pipeline.yaml
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence2/Jenkinsfile
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence2/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence2/README.md
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence2/base-pipeline.yaml
  pkg/jx/cmd/test_data/step_create_jenkinsfile/inheritence2/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_jenkinsfile/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_jenkinsfile/simple/Jenkinsfile
  pkg/jx/cmd/test_data/step_create_jenkinsfile/simple/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_create_jenkinsfile/simple/pipeline.yaml
  pkg/kube/env.go
  pkg/util/files.go
  pkg/util/strings.go
Labels: approved, size/XXL

#2297 improvements for cloud native jenkins build packs
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_buildpack_apply.go
  pkg/jx/cmd/step_buildpack_apply_integration_test.go
  pkg/jx/cmd/step_buildpack_apply_test.go
  pkg/jx/cmd/test_data/step_buildpack_apply/classic/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/classic/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/classic/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/import_inheritence/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/import_inheritence/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/import_inheritence/README.md
  pkg/jx/cmd/test_data/step_buildpack_apply/import_inheritence/import_dir/classic/maven/README.md
  pkg/jx/cmd/test_data/step_buildpack_apply/import_inheritence/import_dir/classic/maven/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/import_inheritence/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence/README.md
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence/base-pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence2/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence2/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence2/README.md
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence2/base-pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/inheritence2/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/prow/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/prow/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/prow/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/simple/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/simple/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/simple/pipeline.yaml
  pkg/util/strings.go
Labels: approved, size/L

#2129 fix: broken tls in jx preview
  pkg/config/helm_values.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
Labels: approved, size/L

#2291 feat(jx) add the OS details to `jx version` output
  Makefile
  pkg/jx/cmd/version.go
  pkg/util/system/version_darwin.go
  pkg/util/system/version_linux.go
  pkg/util/system/version_test.go
  pkg/util/system/version_unknown.go
  pkg/util/system/version_windows.go
Labels: approved, lgtm, size/L

#2298 chore(tests): Refactored go-expect tests to support better error reporting
  go.mod
  go.sum
  pkg/gits/provider_test.go
  pkg/jx/cmd/common_commands_test.go
  pkg/jx/cmd/common_import_test.go
  pkg/jx/cmd/create_env_test.go
  pkg/jx/cmd/uninstall.go
  pkg/jx/cmd/uninstall_test.go
  pkg/kube/env_test.go
  pkg/tests/console_wrapper.go
  pkg/tests/helpers.go
  pkg/vault/vaultselector_test.go
Labels: approved, lgtm, size/L

#2315 feat: ++ to updatebot to upgrade jenkins-x-charts/prow repo.
  .updatebot.yml
  Makefile
Labels: approved, lgtm, size/XS

#2317 fix: ensure gcloud is installed before login
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/S

#2282 bug(controller buildnumbers): Encode PipelineActivity names to avoid collisions
  pkg/kube/activity.go
  pkg/kube/activity_test.go
  pkg/util/k8s.go
  pkg/util/k8s_test.go
Labels: approved, lgtm, size/L

#2321 fix: use prow if enabled in the Jenkinfile generation
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/test_data/step_buildpack_apply/prow/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/prow/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/prow/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/simple/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/simple/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/simple/pipeline.yaml
Labels: approved, lgtm, size/M

#2323 Changes to work with the latest prow
  go.mod
  go.sum
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_knative_build.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_helm_build.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: size/M

#2325 fixes for prow and the new cloud native build packs
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/step_buildpack_apply_test.go
  pkg/jx/cmd/test_data/step_buildpack_apply/go_inherit/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/go_inherit/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/go_inherit/base-pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/go_inherit/pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/prow_go_inherit/Jenkinsfile
  pkg/jx/cmd/test_data/step_buildpack_apply/prow_go_inherit/Jenkinsfile.tmpl
  pkg/jx/cmd/test_data/step_buildpack_apply/prow_go_inherit/base-pipeline.yaml
  pkg/jx/cmd/test_data/step_buildpack_apply/prow_go_inherit/pipeline.yaml
Labels: approved, lgtm, size/L

#2326 fix: lets use a more explicit label for the default workloads
  pkg/builds/buildpacks.go
Labels: approved, lgtm, size/XS

#2289 feat(vault): Create vault resources in GCP that are unique to the cluster
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/gcloud_test.go
  pkg/cloud/gke/vault/naming.go
  pkg/cloud/gke/vault/vault_backend.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete_vault.go
  pkg/vault/commonhelpers_test.go
  pkg/vault/vault.go
Labels: approved, lgtm, size/L

#2332 Fix: Create API token on promote if needed
  pkg/gits/provider.go
Labels: approved, lgtm, size/S

#2337 Fix username is not set correctly for Openshift provider
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/install.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/M

#2319 Add a basic unit test for PreviewOptions
  pkg/gits/mocks/matchers/auth_userauth.go
  pkg/gits/mocks/matchers/gits_gitprovider.go
  pkg/gits/mocks/matchers/io_writer.go
  pkg/gits/mocks/matchers/ptr_to_auth_authserver.go
  pkg/gits/mocks/matchers/ptr_to_auth_userauth.go
  pkg/gits/mocks/matchers/ptr_to_config_config.go
  pkg/gits/mocks/matchers/ptr_to_github_response.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitissue.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitpullrequest.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitpullrequestarguments.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitrelease.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitrepository.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitrepositoryinfo.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitrepostatus.go
  pkg/gits/mocks/matchers/ptr_to_gits_gituser.go
  pkg/gits/mocks/matchers/ptr_to_gits_gitwebhookarguments.go
  pkg/gits/mocks/matchers/slice_of_gits_gitlabel.go
  pkg/gits/mocks/matchers/slice_of_gits_gitorganisation.go
  pkg/gits/mocks/matchers/slice_of_ptr_to_github_repositoryinvitation.go
  pkg/gits/mocks/matchers/slice_of_ptr_to_gits_gitcommit.go
  pkg/gits/mocks/matchers/slice_of_ptr_to_gits_gitissue.go
  pkg/gits/mocks/matchers/slice_of_ptr_to_gits_gitrelease.go
  pkg/gits/mocks/matchers/slice_of_ptr_to_gits_gitrepository.go
  pkg/gits/mocks/matchers/slice_of_ptr_to_gits_gitrepostatus.go
  pkg/gits/mocks/matchers/slice_of_string.go
  pkg/gits/mocks/matchers/time_time.go
  pkg/jx/cmd/mocks/matchers/helm_helmer.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/step_pr_comment.go
Labels: approved, lgtm, size/XL

#2314 Fix: Making a few more commands possible to run w/o being cluster admin
  pkg/jx/cmd/create_quickstart_location.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/delete_quickstart_location.go
  pkg/jx/cmd/environment.go
  pkg/jx/cmd/get_quickstart_locations.go
Labels: approved, lgtm, size/S

#2338 feat(install) added command to install additional dependencies
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_dependencies.go
Labels: approved, lgtm, size/L

#2334 fix: Add domain name validation when configuring ingress to loadbalancer
  pkg/jx/cmd/init.go
  pkg/util/validators.go
  pkg/util/validators_test.go
Labels: approved, lgtm, size/M

#2345 fix(login) let's make sure users that haven't installed or created the cluster have the base set of binaries installed fixes #2300
  pkg/jx/cmd/login.go
Labels: approved, lgtm, size/XS

#2346 fix: add a command to create knative build templates from the pipelines
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_create.go
  pkg/jx/cmd/step_create_build.go
  pkg/jx/cmd/step_create_buildtemplate.go
  pkg/jx/cmd/test_data/step_create_build/add_common_envvars/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_pod_templates/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_previous_step/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/inherit_pod_template_env_volumes/expected-build-release.yml
Labels: approved, lgtm, size/XL

#2304 Feat: Add an app CRD
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/certmanager/certmanager.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/app.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_app.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/v1/app.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/listers/jenkins.io/v1/app.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/expose/exposecontroller.go
  pkg/extensions/hooks.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_app.go
  pkg/jx/cmd/common_cert_manager.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/create_addon_prometheus.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/step_env_apply.go
  pkg/kube/crds.go
Labels: approved, lgtm, size/XXL

#2328 fix(get pipelines): don't ask for an API token
  pkg/jx/cmd/get_pipeline.go
  pkg/jx/cmd/get_pipeline_test.go
Labels: approved, lgtm, size/L

#2350 fix:(gerrit) Remove some unnecessary logging in tests
  pkg/gits/gerrit_test.go
Labels: approved, lgtm, size/XS

#2341 test(gke): do not run in parallel the tests which mocks the same method
  pkg/cloud/gke/gcloud_test.go
Labels: approved, lgtm, size/XS

#2336 Add a parameter to update webhooks for a single repo in an org
  pkg/jx/cmd/update_webhooks.go
Labels: approved, lgtm, size/M

#2354 fix: Import from non dev team namespace
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/import.go
Labels: approved, lgtm, size/S

#1958 Improved import and BitBucket logging
  pkg/jx/cmd/import_integration_test.go
Labels: approved, lgtm, size/XS

#2360 Add a "Reviewed by Hound" badge
  README.md
Labels: approved, lgtm, size/XS

#2359 added Bitbucket Server PR comment support
  go.mod
  go.sum
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
  pkg/gits/test_data/bitbucket_server/pr-comment.json
Labels: approved, lgtm, size/M

#2361 feat(vault): Added more error handling to vault
  pkg/vault/vaultfactory.go
Labels: approved, lgtm, size/S

#2358 refactor(upgrade ingress): add a flag to skip the update of jx related resources
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, size/M

#2366 Avoid panic on failed repo creation
  pkg/kube/env.go
Labels: approved, lgtm, size/S

#2368 Upgraded eksctl version
  pkg/binaries/binaries.go
Labels: approved, lgtm, size/XS

#2369 Fixed Helm installation error handling
  pkg/jx/cmd/common_install.go
Labels: approved, lgtm, size/XS

#2379 test(status): do not run the test in parallel
  pkg/jx/cmd/status_test.go
Labels: approved, lgtm, size/XS

#2335 Make ACR as the default registry for Azure
  pkg/cloud/aks/aks.go
  pkg/cloud/aks/aks_test.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/preview.go
Labels: approved, lgtm, size/L

#2378 fix(vault): ensure that the created vault has a service account and a proper role binding
  go.mod
  go.sum
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete_vault.go
  pkg/jx/cmd/install.go
  pkg/kube/roles.go
  pkg/vault/vault.go
  pkg/vault/vault_test.go
Labels: approved, lgtm, size/L

#2383 chore: expose results from `jx get app` in a better structure
  pkg/jx/cmd/get_applications.go
Labels: approved, lgtm, size/S

#2384 chore(tests): Windows tests fail
  pkg/gits/provider_test.go
Labels: approved, lgtm, size/XS

#2104 feat: add binary plugins
  Makefile
  go.mod
  go.sum
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_plugin.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/plugin.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/plugin.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/client/listers/jenkins.io/v1/plugin.go
  pkg/extensions/plugins.go
  pkg/extensions/plugins_test.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/provider.go
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/common_plugins.go
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_plugins.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/templates/command_groups.go
  pkg/jx/cmd/templates/templater.go
  pkg/kube/crds.go
  pkg/log/log.go
  pkg/util/dirs.go
Labels: approved, lgtm, size/XXL
