Repository jenkins-x/jx, pull requests merged in 2019-02, with the labels that each got.

#2945 fix: bugs in argument processing for jx add app
  pkg/jx/cmd/add_app.go
Labels: approved, lgtm, size/XS

#2957 fix: need to add apidocs to git on release
  Makefile
Labels: approved, lgtm, size/XS

#2956 Binaries/dependencies code refactoring
  pkg/binaries/binaries.go
  pkg/binaries/binaries_test.go
  pkg/jx/cmd/common_install.go
Labels: approved, lgtm, ok-to-test, size/L

#2959 fix(install): get the create dev environment creation working in batch mode
  pkg/kube/env.go
Labels: approved, lgtm, size/M

#2967 add a flag to install knative-build-pipeline instead of knative-build
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_prow.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/upgrade_addon_prow.go
Labels: approved, lgtm, size/M

#2965 Added user friendly message to BitBucket installation
  pkg/jx/cmd/install.go
Labels: approved, lgtm, ok-to-test, size/XS

#2979 Fix: a couple of nasty little bugs in user resolution
  pkg/users/git.go
  pkg/users/git_test.go
  pkg/users/users.go
  pkg/users/users_test.go
Labels: approved, size/L

#2970 Add exposecontrollers urltemplate
  pkg/config/helm_values.go
  pkg/config/helm_values_test.go
  pkg/config/helm_values_test_with_urltemplate.yaml
  pkg/kube/ingress.go
Labels: approved, lgtm, ok-to-test, size/M

#2980 fix: lets default to batch mode in knative pipeline OOTB
  pkg/jx/cmd/common.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_tag.go
Labels: approved, lgtm, size/M

#2958 lets deprecate old exposecontroller flags now that we recommend `jx u…
  pkg/config/helm_values.go
Labels: approved, lgtm, size/XS

#2983 #2982 Add missing X-Region header for IBM k8s API calls
  pkg/cloud/iks/datacenters.go
  pkg/cloud/iks/helper.go
  pkg/jx/cmd/create_cluster_iks.go
Labels: approved, lgtm, ok-to-test, size/M

#2918 fix: fail early if oke options can't be fetched
  pkg/jx/cmd/create_cluster_oke.go
Labels: approved, lgtm, ok-to-test, size/S

#2973 lets lock down the versions of helm charts
  pkg/auth/mocks/auth_interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/expose/exposecontroller.go
  pkg/extensions/hooks.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/mocks/organisation_checker.go
  pkg/gits/mocks/organisation_lister.go
  pkg/helm/helm_helpers.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_app.go
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_test.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/test_data/install_cloud_environments_repo/Makefile
  pkg/jx/cmd/test_data/install_jenkins_x_versions/charts/jenkins-x/jenkins-x-platform.yml
  pkg/kube/mocks/kuber.go
  pkg/kube/resources/mocks/installer.go
  pkg/util/mocks/commander.go
  pkg/vault/mocks/vault_client.go
  pkg/version/test_data/jenkins-x-versions/charts/jenkins-x/jenkins-x-platform.yml
  pkg/version/test_data/jenkins-x-versions/charts/jenkins-x/jx-build-templates.yml
  pkg/version/test_data/jenkins-x-versions/charts/jenkins-x/knative-build-pipeline.yml
  pkg/version/test_data/jenkins-x-versions/charts/jenkins-x/knative-build.yml
  pkg/version/test_data/jenkins-x-versions/charts/jenkins-x/prow.yml
  pkg/version/test_data/jenkins-x-versions/packages/helm.yml
  pkg/version/test_data/jenkins-x-versions/packages/skaffold.yml
  pkg/version/version_data.go
  pkg/version/version_data_test.go
Labels: approved, lgtm, size/XXL

#2986 fix: add a success message!
  pkg/jx/cmd/add_app.go
Labels: approved, lgtm, size/XS

#2989 fix: upgrade platform to use stable version
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/version/version_data.go
Labels: approved, lgtm, size/S

#2992 Support passing --install-dependencies to bdd tests
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, ok-to-test, size/XS

#2993 add pipeline step names and fix broken SourceRepo marshalling
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_create_buildtemplate.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_next_version.go
  pkg/kube/activity.go
Labels: approved, lgtm, size/L

#2998 Add jx step pr labels command
  pkg/jx/cmd/step_pr.go
  pkg/jx/cmd/step_pr_labels.go
Labels: approved, lgtm, ok-to-test, size/L

#3001 fix(import): Honour the --environment-git-owner flag doing create terraform
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/XS

#3000 fix: various issues around SourceRepository
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/kube/activity.go
  pkg/kube/activity_test.go
  pkg/kube/sourcerepository_impl.go
Labels: approved, lgtm, size/L

#2994 chore(create): InstallOptions already had GitRepositoryOptions embedded
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/S

#3010 feat: detect if adminSecrets.yaml is invalid and attempt to repair
  pkg/config/admin_secrets.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/M

#3009 feat(terraform): Added --cluster-name and --cloud-provider
  pkg/jx/cmd/create_cluster.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/create_terraform_test.go
Labels: approved, lgtm, size/M

#3013 feat: attempt to fix the jx-install-config secret in the cluster
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/S

#3016 fixes for build pods and knative pipeline
  pkg/jx/cmd/common_buildpacks.go
Labels: approved, lgtm, size/S

#3017 feat: Add support for defining Build Pipeline pipeline in jenkins-x.yml
  go.mod
  go.sum
  pkg/builds/build_info.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/step_create_build.go
  pkg/jx/cmd/step_create_task.go
  pkg/kpipelines/constants.go
  pkg/kpipelines/pipelines.go
  pkg/kpipelines/syntax/constants.go
  pkg/kpipelines/syntax/pipeline.go
  pkg/kpipelines/syntax/pipeline_test.go
  pkg/kpipelines/syntax/test_data/custom_workspaces/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/environment_at_top_and_in_stage/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/inherited_custom_workspaces/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/mangled_task_names/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/multiple_stages/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/nested_stages/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/parallel_and_nested_stages/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/parallel_stages/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/post/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/simple_jenkinsfile/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/stage_and_step_agent/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/stage_timeout/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/syntactic_sugar_step_and_a_command/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/top_level_and_stage_options/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/top_level_timeout/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/validation_failures/agent_with_both_image_and_label.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/bad_apiVersion.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/blank_stage_name.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/empty_agent.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/no_parent_or_stage_agent.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/no_stages.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/no_steps_stages_or_parallel.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/stage_retry_with_invalid_count.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/stage_timeout_with_invalid_time.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/stage_timeout_with_invalid_unit.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/stage_timeout_without_time.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/stages_and_parallel.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/stash_without_files.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/stash_without_name.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/step_with_both_command_and_step.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/step_with_command_and_options.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/step_with_step_and_arguments.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/step_without_command_or_step.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/steps_and_parallel.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/steps_and_stages.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/top_level_retry_with_invalid_count.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/top_level_timeout_with_invalid_time.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/top_level_timeout_with_invalid_unit.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/top_level_timeout_without_time.yaml
  pkg/kpipelines/syntax/test_data/validation_failures/unstash_without_name.yaml
Labels: approved, lgtm, ok-to-test, size/XXL

#3003 Skip bdd repo clone
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, ok-to-test, size/M

#3011 chore(bdd): don't use shorthands in tests
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#3014 fix(bdd): don't log sensitive information to the logs
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#3019 Adding Node Volume Size to EKS command
  pkg/jx/cmd/create_cluster_eks.go
Labels: approved, lgtm, ok-to-test, size/XS

#3015 chore(crate cluster): remove duplicated line in help message
  pkg/jx/cmd/create_cluster.go
Labels: approved, lgtm, size/XS

#3018 fix typo in vault arg
  pkg/jx/cmd/step_helm_apply.go
Labels: ok-to-test, size/XS

#3020 add support for generating version PRs
  pkg/jx/cmd/step_create.go
  pkg/jx/cmd/step_create_version_pr.go
  pkg/version/version_data.go
  pkg/version/version_data_test.go
Labels: approved, lgtm, size/L

#3021 fix(sso): use the locked version instead of hard-coding for cert-manager, sso-operator, dex and vault-operator
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/common_cert_manager.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/kube/constants.go
  pkg/kube/namespaces.go
  pkg/kube/namespaces_test.go
  pkg/kube/pki/cert-manager.go
Labels: approved, lgtm, size/L

#3024 fix for the BDD tests with GitOps
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/step_bdd.go
  pkg/version/version_data.go
Labels: approved, lgtm, size/M

#3026 feat: Validate Stage names for duplicates
  pkg/kpipelines/syntax/pipeline.go
  pkg/kpipelines/syntax/pipeline_internal_test.go
  pkg/kpipelines/syntax/pipeline_test.go
  pkg/kpipelines/syntax/test_data/stage_name_validation/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_duplicates.yaml
  pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_duplicates_with_multiple_sub_stages.yaml
  pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_duplicates_with_sub_stages.yaml
  pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_ok.yaml
  pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_ok_with_sub_stages.yaml
  pkg/kpipelines/syntax/test_data/stage_name_validation/stages_names_with_sub_stages.yaml
Labels: approved, lgtm, ok-to-test, size/L

#3027 feat(vault): prefix the system vault and all the related resources with the short cluster name
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/gcloud_test.go
  pkg/cloud/gke/vault/naming.go
  pkg/cloud/gke/vault/vault_backend.go
  pkg/jx/cmd/common_bucket.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete_vault.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/install.go
  pkg/kube/cluster/cluster.go
  pkg/kube/cluster/cluster_test.go
  pkg/kube/vault/vault.go
  pkg/vault/constants.go
Labels: approved, lgtm, size/L

#2941 (feat) Add `jx step verify pod` to output status of all kubernetes pods
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_verify.go
  pkg/jx/cmd/step_verify_pod.go
  pkg/jx/cmd/step_verify_pod_test.go
Labels: approved, lgtm, size/L

#3028 fix: add more labels to clusters
  pkg/jx/cmd/bdd/bdd_clusters.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/L

#3032 Fix: Delete app command is disabled
  pkg/jx/cmd/delete.go
Labels: approved, lgtm, ok-to-test, size/XS

#3033 fix: allow pure docker and/or helm build packs
  Makefile
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_integration_test.go
  pkg/jx/cmd/test_data/import_projects/docker-helm/Dockerfile
  pkg/jx/cmd/test_data/import_projects/docker-helm/charts/REPLACE_ME_APP_NAME/Chart.yaml
  pkg/jx/cmd/test_data/import_projects/docker/Dockerfile
  pkg/jx/cmd/test_data/import_projects/helm/charts/REPLACE_ME_APP_NAME/Chart.yaml
  pkg/tests/files.go
Labels: approved, lgtm, size/L

#3040 fix: lets bring back the `--view` option for `jx step creete task`
  Makefile
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/ptr_to_versioned0_clientset.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/L

#3041 Truncate generated Pipeline names to avoid length issues
  pkg/kpipelines/pipelines.go
  pkg/kube/names.go
  pkg/kube/names_valid_test.go
Labels: approved, lgtm, size/M

#3042 feat(kpipelines): Add loop-over-values to repeat step
  pkg/kpipelines/syntax/pipeline.go
  pkg/kpipelines/syntax/pipeline_test.go
  pkg/kpipelines/syntax/test_data/loop_step/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/loop_with_syntactic_sugar_step/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/validation_failures/loop_without_steps/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/validation_failures/loop_without_values/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/validation_failures/loop_without_variable/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/validation_failures/step_with_both_command_and_loop/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/validation_failures/step_with_loop_and_arguments/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/validation_failures/step_with_loop_and_options/jenkins-x.yml
  pkg/kpipelines/syntax/test_data/validation_failures/step_without_command_step_or_loop/jenkins-x.yml
Labels: approved, lgtm, size/XL

#3039 fix: check if jenkins-x-versions repository is already up to date, if not fetch the latest version
  pkg/jx/cmd/common_helm.go
Labels: approved, lgtm, size/M

#3035 chore: set the version of the docker iamge for vault-operator and bank-vaults to 0.4.7
  pkg/kube/vault/vault.go
Labels: approved, lgtm, size/XS

#3046 fix: Add webhook triggers for PR events in bitbucket
  pkg/gits/bitbucket_cloud.go
Labels: approved, lgtm, ok-to-test, size/XS

#3034 bug: update activities to complete on PR merge.
  pkg/jx/cmd/controller_workflow.go
Labels: approved, lgtm, ok-to-test, size/M

#2938 Only delete apps from Permanent envs
  pkg/jx/cmd/delete_application.go
Labels: approved, lgtm, size/XS

#3048 Minor doc change
  README.md
Labels: needs-ok-to-test, size/XS

#3051 fix: minor spelling mistake in error message
  pkg/jx/cmd/common_helm.go
Labels: approved, lgtm, size/XS

#3053 chore: remove extraneous (but benign) debug.
  pkg/jx/cmd/controller_workflow.go
Labels: approved, lgtm, size/XS

#3056 refactor: move kubernetes providers names into cloud package
  pkg/cloud/cloud.go
  pkg/jx/cmd/common_domain.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_cluster.go
  pkg/jx/cmd/create_cluster_aks.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_gke_terraform.go
  pkg/jx/cmd/create_cluster_iks.go
  pkg/jx/cmd/create_cluster_minikube.go
  pkg/jx/cmd/create_cluster_minishift.go
  pkg/jx/cmd/create_cluster_oke.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/update_cluster_gke.go
  pkg/jx/cmd/update_cluster_gke_terraform.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/L

#3067 fix(upgrade platform): read the chart version from deployment label for no-tiller
  pkg/helm/helm_template.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/M

#3045 chore: fix delete application so that it tries to intelligently figure what org the associated repo belongs to
  pkg/jx/cmd/delete_application.go
Labels: approved, lgtm, size/M

#3072 fix: Error: running postinstall hooks during jx add app
  pkg/jx/cmd/common_app.go
Labels: approved, lgtm

#3071 chore: add David Conde to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3082 chore: add some badges in the README
  README.md
Labels: approved, lgtm, size/XS

#3084 refactor: move into helm package all helper methods for tiller
  .gitignore
  pkg/helm/tiller.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/L

#3086 refactor: move the common pipeline methods in a separate file
  pkg/jx/cmd/common_pipelines.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/step_post_run.go
  pkg/jx/cmd/step_pre_extend.go
Labels: approved, lgtm, size/L

#3061 fix: corrected logging, removed temp file
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install.go.orig
Labels: approved, lgtm, size/XXL

#3064 fix(kpipelines): Override workspace from podtemplate, fix args generation
  go.mod
  go.sum
  pkg/kpipelines/syntax/pipeline.go
  pkg/kpipelines/syntax/pipeline_test.go
Labels: approved, lgtm, size/L

#3065 Check userAuth is not nil
  pkg/jx/cmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#3063 fix: try to make the failing console test pass
  pkg/jx/cmd/add_app_test.go
Labels: approved, lgtm, size/XS

#3074 fix(import): use the org from a github repo when importing
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_test.go
Labels: approved, lgtm, size/M

#3077 fix two typos with --no-gitops-env-setup
  pkg/jx/cmd/install.go
Labels: approved, lgtm, ok-to-test, size/XS

#3085 refactor: remove duplicated const for file default write permissions
  pkg/auth/file_config_saver.go
  pkg/auth/types.go
  pkg/io/config_writers.go
  pkg/jx/cmd/common_environments.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_docs.go
  pkg/jx/cmd/create_jhipster.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/delete_branch.go
  pkg/jx/cmd/helpers.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/step_blog.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/step_create_build.go
  pkg/jx/cmd/step_git_credentials.go
  pkg/jx/cmd/step_gpg_credentials.go
  pkg/jx/cmd/step_split_monorepo.go
  pkg/jx/cmd/step_tag.go
  pkg/jx/cmd/sync.go
Labels: approved, lgtm, size/M

#3036 fix: more flagger configuration
  pkg/jx/cmd/create_addon_flagger.go
  pkg/jx/cmd/delete_addon.go
  pkg/jx/cmd/delete_addon_flagger.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/L

#3088 refactor: use proper command options and move jenkinsfile related consts to jenkinsifle package
  pkg/jenkins/constants.go
  pkg/jenkinsfile/jenkinsfile.go
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/edit_env.go
  pkg/jx/cmd/get_activity.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_integration_test.go
  pkg/jx/cmd/step_buildpack_apply.go
  pkg/jx/cmd/step_buildpack_apply_integration_test.go
  pkg/jx/cmd/step_post_install.go
Labels: approved, lgtm, size/M

#3078 chore: wrap errors instead of returning them directly
  pkg/jx/cmd/delete_application.go
Labels: approved, lgtm, size/XS

#3089 refactor: move the vault opitons into the vault package
  pkg/jx/cmd/common/interfaces.go
  pkg/kube/vault/vault_factory.go
  pkg/kube/vault/vault_selector.go
Labels: approved, lgtm, size/M

#3087 refactor: move some common methods for logs and pods in separate files
  pkg/jenkins/utils.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_logs.go
  pkg/jx/cmd/common_pod.go
  pkg/jx/cmd/completion.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/logs.go
  pkg/jx/cmd/metrics.go
  pkg/jx/cmd/start_pipeline.go
Labels: approved, lgtm, size/L

#3092 refactor: move helm initialization in common and refactor it to avoid dependency cycles with cmd package
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/step_helm_release.go
Labels: approved, lgtm, size/L

#3103 Pegomock1
  Makefile
  go.mod
  go.sum
  pkg/auth/mocks/auth_interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/mocks/organisation_checker.go
  pkg/gits/mocks/organisation_lister.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/kube/mocks/kuber.go
  pkg/kube/resources/mocks/installer.go
  pkg/util/mocks/commander.go
  pkg/vault/mocks/vault_client.go
Labels: approved, lgtm, size/XL

#3097 Respect --no-env flag for jx delete application
  pkg/jx/cmd/delete_application.go
Labels: approved, lgtm, ok-to-test, size/XS

#3101 fix: jx step next-version update the package.json
  pkg/jx/cmd/step_next_version.go
Labels: approved, lgtm, size/XS

#3107 fix: allow a context to be used to run a different pipeline YAML file
  pkg/config/project_config.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/M

#3105 Jx step git merge1
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/ptr_to_versioned4_clientset.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_git.go
  pkg/jx/cmd/step_git_merge.go
  pkg/prow/env_vars.go
  pkg/prow/env_vars_test.go
Labels: approved, lgtm, size/XL

#3102 fix (import) : Defaults from team settings for create quickstart and spring
  pkg/jx/cmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#3066 Extract fact crd
  pkg/apis/jenkins.io/v1/types_fact.go
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fact.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_fact.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/v1/fact.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/client/listers/jenkins.io/v1/fact.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/kube/crds.go
Labels: approved, lgtm, size/XL

#3116 fix: move app test helpers to new pkg
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/delete_app_test.go
  pkg/jx/cmd/upgrade_apps_test.go
Labels: approved, lgtm, size/L

#3121 fix: fork logic was trying to pass an organisation name to a user fork
  pkg/jx/cmd/step_create_version_pr.go
Labels: approved, lgtm, size/XS

#3118 feature: add new command 'get quickstarts' that returns a list of available quickstarts
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_quickstarts.go
Labels: approved, lgtm, size/L

#3100 Fix: refactor common_environments
  pkg/environments/gitops.go
  pkg/gits/provider_fake.go
  pkg/helm/mocks/mock_helpers.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/common_environments.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/promote_test.go
  pkg/jx/cmd/test_helpers.go
  pkg/jx/cmd/upgrade_apps.go
Labels: approved, lgtm, size/XXL

#3130 fixes for pipelinerunner to work with new prow pipeline controller
  Dockerfile
  Makefile
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/M

#3119 chore: improve the message of skip-ingress option and add a warning message
  pkg/jx/cmd/init.go
Labels: approved, lgtm, size/M

#3131 add Devin and Andrew as approvers
  OWNERS
Labels: approved, lgtm, size/XS

#3123 bug: fix directory deletion, add test.
  pkg/util/files.go
  pkg/util/files_test.go
Labels: approved, lgtm, size/M

#3142 fix: Fix pod detection with newer Build Pipeline changes
  go.mod
  go.sum
  pkg/builds/build_number.go
  pkg/builds/constants.go
  pkg/builds/helpers.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_commitstatus.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/S

#3129 feat(kpipelines): Add PipelineStructure CRD
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types_pipelinestructure.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_pipelinestructure.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelinestructure.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/pipelinestructure.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/client/listers/jenkins.io/v1/pipelinestructure.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/step_create_task.go
  pkg/kpipelines/syntax/pipeline.go
  pkg/kpipelines/syntax/pipeline_test.go
  pkg/kube/crds.go
  pkg/kube/crds_test.go
Labels: approved, lgtm, size/XXL

#3138 chore: major refactor of apps structure
  pkg/apps/gitops.go
  pkg/apps/helmops.go
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/extensions/hooks.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/common_app.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/upgrade_apps.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/acceptExisting.test.schema.json
  pkg/surveyutils/test_data/askExisting.test.schema.json
  pkg/surveyutils/test_data/autoAcceptDefaultValues.test.schema.json
  pkg/surveyutils/test_data/errorMissingValues.test.schema.json
  pkg/surveyutils/test_data/ignoreMissingValues.test.schema.json
  pkg/surveyutils/test_data/ingoreMissingValues.test.schema.json
  pkg/surveyutils/test_data/noAskAndAutoAcceptDefaultsWithExisting.test.schema.json
  pkg/util/types.go
Labels: approved, lgtm, size/XXL

#3141 fix: corrected enable apis command
  pkg/cloud/gke/gcloud.go
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, lgtm, size/XS

#3136 Refactor clone JX Versions Repo
  pkg/jx/cmd/common_helm.go
Labels: approved, lgtm, size/L

#3144 Fix Bitbucket Cloud merge bug
  go.mod
  go.sum
  pkg/gits/bitbucket_cloud.go
Labels: approved, lgtm, size/S

#3153 fix(kipelines): PipelineStructure Name should be unique for each build
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_pipelinestructure.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/M

#3149 support knative build pipeline imports and prow config
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/config/project_config.go
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_integration_test.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/start_protection.go
  pkg/jx/cmd/start_protection_test.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
  pkg/util/files.go
Labels: approved, lgtm, size/XL

#3152 fix(upgrade): add missing error check
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, ok-to-test, size/XS

#3151 feat(upgrade): new 'upgrade crd' cmd to upgrade all jenkinsx CRDs
  pkg/jx/cmd/upgrade.go
  pkg/jx/cmd/upgrade_crd.go
Labels: approved, lgtm, ok-to-test, size/M

#3128 Make Ambassador add on does respect the -f flag
  pkg/jx/cmd/create_addon_ambassador.go
Labels: approved, lgtm, ok-to-test, size/XS

#3176 chore: fix broken upstream dependency
  go.mod
  go.sum
  pkg/kpipelines/pipelines.go
Labels: approved, lgtm, size/S

#3172 fix: first spike at getting prow to work with dev gitops
  pkg/environments/gitops.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_prow.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_addon_prow.go
  pkg/util/maps.go
Labels: approved, lgtm, size/L

#3146 fix: spaces in labels, PR- prefix in BRANCH_NAME
  pkg/jx/cmd/step_pr_labels.go
Labels: approved, lgtm, ok-to-test, size/XS

#3187 refactor CLI for tekton
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/controller_team.go
  pkg/jx/cmd/create_addon_prow.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/upgrade_addon_prow.go
  pkg/kube/constants.go
  pkg/prow/prow.go
Labels: approved, lgtm, size/L

#3188 feat: Create a jx step that returns a list of version updates
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/step_get.go
  pkg/jx/cmd/step_get_version_changeset.go
  pkg/version/version_data.go
Labels: approved, lgtm, size/L

#3173 Feat: Only ask new questions on upgrade of apps
  pkg/apps/gitops.go
  pkg/apps/helmops.go
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/environments/gitops.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/delete_app_test.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/upgrade_apps.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/surveyutils/jsonschema.go
Labels: approved, lgtm, size/XXL

#3180 feat: Implement jx get app / apps
  pkg/apps/helmops.go
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/helm/helm_template.go
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_applications.go
  pkg/jx/cmd/get_apps.go
  pkg/jx/cmd/get_apps_test.go
  pkg/util/urls.go
Labels: approved, lgtm, size/L

#3191 fix: Don't discard secrets in non-gitops helm chart install
  pkg/jx/cmd/common_helm.go
Labels: approved, lgtm, size/XS

#3170 feat: create Istio gateway for canaries
  pkg/jx/cmd/create_addon_flagger.go
  pkg/jx/cmd/create_addon_istio.go
Labels: approved, lgtm, size/L

#3148 build pipeline and build use different helm value keys so lets set th…
  pkg/jx/cmd/common_install.go
Labels: approved, lgtm, size/S

#3184 fix: ensure the CommonOptions is set on setp next version and helm version
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_next_version.go
Labels: approved, lgtm, size/S

#3194 (chore): use tekon bot service account instead of build bot
  pkg/jx/cmd/controller_pipelinerunner.go
Labels: approved, lgtm, size/XS

#3193 Register Fact CRD in the client
  pkg/apis/jenkins.io/v1/register.go
Labels: approved, lgtm, size/XS

#3113 Ignore flagger canary auxiliary deployments from get apps
  pkg/flagger/flagger.go
  pkg/jx/cmd/get_applications.go
Labels: approved, lgtm, size/S

#3197 set the versions repo to use custom fork as init step always clones t…
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/S

#3182 fix(devpod): 'delete devpod' was not using the right pod name
  pkg/jx/cmd/delete_devpod.go
Labels: approved, lgtm, ok-to-test, size/XS

#3201 fix: support working with custom Jenkins server Apps
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/clients/interface.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/common_jenkins.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/delete_jenkins.go
  pkg/jx/cmd/delete_jenkins_token.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/get_pipeline.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/stop_pipeline.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/XL

#3185 refactor: remove the headless flag and replace its usage with batch flag
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/create_git_api_token.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/S

#3200 chore: test creation of PipelineRunInfo from resources
  pkg/tekton/pipeline_info.go
  pkg/tekton/pipeline_info_test.go
  pkg/tekton/test_data/pipeline_info/from-build-pack/activity.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/pipeline.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/pods.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/tasks.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/activity.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipeline.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pods.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/structure.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/tasks.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/activity.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pipeline.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pods.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/structure.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/tasks.yml
Labels: approved, lgtm, size/XXL

#3208 fix: add a command to trigger pipelines in custom jenkins apps
  pkg/jenkins/jobs.go
  pkg/jx/cmd/common_import.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_custom_pipeline.go
Labels: approved, lgtm, size/L

#3210 fix: properly use PULL_REFS
  pkg/jx/cmd/step_git_merge.go
  pkg/prow/env_vars.go
  pkg/prow/env_vars_test.go
Labels: approved, lgtm, size/M

#3145 Improve Bitbucket server webhook support
  go.mod
  go.sum
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
  pkg/gits/test_data/bitbucket_server/webhooks.json
  pkg/jx/cmd/update_webhooks.go
Labels: approved, lgtm, ok-to-test, size/L

#3217 fixes for pipelinerunner to work with new prow pipeline controller
  Makefile
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/L

#3179 feat: added verbose flag and extra output to 'jx status'
  pkg/jx/cmd/status.go
  pkg/kube/cluster_status.go
Labels: approved, lgtm, size/L

#3216 include flag to enable passing the release name to cli.
  pkg/jx/cmd/step_env_apply.go
Labels: approved, lgtm, ok-to-test, size/XS

#3222 fix: need to unshallow the fetch
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned0_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_git_merge.go
  pkg/kube/cluster_status.go
Labels: approved, lgtm, size/L

#3226 fix: add support for tagging git before we trigger tekton releases
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/L

#3241 fix: lets add a helper method to lazily create the factory or set it
  pkg/jx/cmd/common.go
Labels: size/S

#3236 fix: use the locked version of the exposecontroller chart
  pkg/expose/exposecontroller.go
Labels: approved, lgtm, size/XS

#3234 fix: work around older git in images
  pkg/gits/helpers.go
Labels: approved, lgtm, size/M

#3238 chore: Different message for no Tekton pipelines logs found
  pkg/jx/cmd/get_build_logs.go
Labels: approved, lgtm, size/XS

#3231 fix for Task.spec.inputs.params when using NGP
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/step_create_task.go
  pkg/kube/cluster/cluster.go
  pkg/kube/cluster/cluster_test.go
  pkg/kube/constants.go
  pkg/kube/vault/vault.go
  pkg/tekton/pipelines.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, size/L

#3240 fix: Don't keep trying to get pods for completed PipelineRuns
  pkg/jx/cmd/get_build_logs.go
  pkg/tekton/pipeline_info.go
  pkg/tekton/pipeline_info_test.go
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/activity.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/pipeline.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/taskruns.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/tasks.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/activity.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipeline.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/structure.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/taskruns.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/tasks.yml
Labels: approved, lgtm, size/XXL

#3242 fix: passing parameters into tekton pipelines
  pkg/builds/build_number.go
  pkg/builds/build_number_test.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_create_task.go
  pkg/kube/crds.go
Labels: approved, lgtm, size/L

#3247 tekton fixes
  pkg/apps/install.go
  pkg/config/project_config.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/M

#3248 chore: Populate PipelineStructure for build pack-generated runs
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/step_create_task.go
  pkg/tekton/pipeline_info.go
  pkg/tekton/pipeline_info_test.go
  pkg/tekton/syntax/constants.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/pipeline.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/structure.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/taskruns.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/tasks.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipeline.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/taskruns.yml
  pkg/tekton/test_data/pipeline_info/completed-from-yaml/tasks.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/pipeline.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/pods.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/structure.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/tasks.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipeline.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pods.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/tasks.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pipeline.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pods.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/tasks.yml
Labels: approved, lgtm, size/L

#3249 fix: pipelinerunner needs to run jx step git credentials
  pkg/jx/cmd/controller_pipelinerunner.go
Labels: approved, lgtm, size/S

#3246 fix: add Pipeline parameters to YAML-generated CRDs
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/XS

#3235 feat: Add apps metadata during gitops install
  go.mod
  go.sum
  pkg/apps/gitops.go
  pkg/apps/values.go
  pkg/environments/gitops.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/delete_app_test.go
  pkg/jx/cmd/get_apps.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/surveyutils/jsonschema_test.go
Labels: approved, lgtm, size/L

#3202 fix: (init.go) enable both ports for EKS NLB
  pkg/jx/cmd/init.go
Labels: approved, lgtm, ok-to-test, size/S
