Repository jenkins-x/jx, pull requests merged in 2019-06, with the labels that each got.

#4080 Chore: enable bdd coverage
  .codecov.yml
  Makefile
  cmd/jx/jx_test.go
  jenkins-x-bdd.yml
  jx/scripts/ci.sh
Labels: approved, lgtm, size/M

#4151 Chore: try different targets
  .codecov.yml
  jx/scripts/ci.sh
Labels: do-not-merge/hold, size/XS

#4152 Chore: add lint for .codecov.yml
  Makefile
  hack/codecov-validate.sh
  hack/run-all-checks.sh
Labels: approved, lgtm, size/S

#4156 feat: switch to a self uploading covered binary
  Makefile
  cmd/jx/codecov/info.go
  cmd/jx/jx_test.go
  go.mod
  go.sum
  jenkins-x-bdd.yml
  jx/scripts/ci.sh
  myvalues.yaml.template
  pkg/util/commands.go
Labels: approved, lgtm, size/L

#4155 chore: use a build tag to prevent building covered binary at other times
  Makefile
  cmd/jx/jx_test.go
  jenkins-x-bdd.yml
Labels: approved, lgtm, size/XS

#4157 chore: stash the results from the e2e tests
  jenkins-x-bdd.yml
  jenkins-x-integration.yml
  jx/scripts/ci.sh
Labels: approved, lgtm, size/S

#4159 chore: don’t include e2e tests in contexts
  .codecov.yml
Labels: approved, lgtm, size/XS

#4161 fix: fixes for terraform with vault installation
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/M

#4163 Fix cluster name for install and credentials
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, lgtm, size/XS

#4093 Equaled the PR and Batch CRDs expiration times so they get garbage collected together
  pkg/jx/cmd/gc_activities.go
  pkg/jx/cmd/gc_activities_test.go
Labels: approved, lgtm, size/L

#4167 Extend use of jx create cluster advanced flag
  pkg/auth/auth_config.go
  pkg/gits/provider_test.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: approved, lgtm, size/L

#4170 feat: allow 'jx step create pr' to update the terraform builder images
  pkg/jx/cmd/step/create/step_create_version_pr.go
Labels: approved, lgtm, size/XS

#4174 s/http://chartmuseum.jenkins-x.io/https://storage.googleapis.com/char…
  charts/jx/Makefile
  pkg/helm/helm_cli_test.go
  pkg/jx/cmd/add/add_app_test.go
  pkg/jx/cmd/test_data/get_apps/get_apps_table_json.json
  pkg/jx/cmd/test_data/get_apps/get_apps_table_yaml.yaml
  pkg/kube/constants.go
  pkg/kube/test_data/env_modify_namespace/Makefile
Labels: approved, lgtm, size/M

#4176 fix: gc activities if no tekton
  pkg/jx/cmd/gc_activities.go
Labels: approved, lgtm, size/S

#4179 fix: improve devpod
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/opts/common_test.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/XL

#4177 chore: add a prefix to the versions used for covered images
  jenkins-x-bdd.yml
  jenkins-x-images.yml
  jx/scripts/ci.sh
Labels: approved, lgtm, size/M

#4182 fix: move the output stripper to the bdd test runner
  cmd/jx/jx_test.go
  jx/scripts/ci.sh
Labels: approved, lgtm, size/M

#4171 Hide ingress installation behind advanced flag
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/S

#4186 chore: remove the set -x - was in there for debugging
  jx/scripts/ci.sh
Labels: approved, lgtm, size/XS

#4181 feat: improved install flags validation
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_test.go
Labels: approved, lgtm, size/L

#4162 chore: enabled error checking in linter
  cmd/codegen/codegen.go
  hack/linter.sh
  pkg/client/clientset/versioned/typed/jenkins.io/v1/testutil.go
  pkg/gits/commits.go
  pkg/tekton/syntax/pipeline.go
  pkg/util/json/patch.go
Labels: approved, lgtm, size/M

#4188 chore: run bdd tests during build in order to produce coverage baseline
  jenkins-x.yml
Labels: approved, lgtm, size/M

#3411 jx get lang command
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_lang.go
Labels: approved, lgtm, ok-to-test, size/M

#4180 fix for error during `jx create addon gloo` #4178
  pkg/jx/cmd/opts/install.go
Labels: approved, lgtm, ok-to-test, size/XS

#3979 feat: Automate dns managed zone creation for tenant cluster
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/gcloud_test.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_gke_test.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/install.go
  pkg/tenant/tenant.go
  pkg/tenant/tenant_test.go
Labels: approved, lgtm, size/XL

#4190 fix: add support for VS Code to DevPods
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/step/create/step_create.go
  pkg/jx/cmd/step/create/step_create_devpod_workspace.go
Labels: approved, lgtm, size/L

#4193 feat: Moved tenant cluster delegation to install phase
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_gke_test.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_test.go
Labels: approved, lgtm, size/L

#4198 Default to pull latest versions repo during install
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/opts/helm.go
Labels: approved, lgtm, size/M

#4204 Default recreate cloud environments repo
  pkg/gits/git_cli.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/S

#4197 fix: increase the expect timeout for some tests
  pkg/gits/provider_test.go
  pkg/jx/cmd/add/add_app_integration_test.go
  pkg/jx/cmd/add/add_app_test.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/opts/commands_test.go
  pkg/jx/cmd/uninstall_test.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/kube/env_test.go
  pkg/kube/vault/vault_selector_test.go
  pkg/surveyutils/jsonschema_test.go
  pkg/tests/helpers.go
Labels: approved, lgtm, size/M

#4202 Buildalerts
  pkg/jx/cmd/controller_build.go
Labels: approved, lgtm, size/M

#4192 Fix create pr
  jx/scripts/update-clients.sh
  pkg/gits/helpers.go
  pkg/gits/provider.go
  pkg/jx/cmd/create_pullrequest.go
Labels: approved, lgtm, size/S

#4154 fix: pass helm values files to tekton chart installation
  pkg/jx/cmd/opts/install.go
Labels: approved, lgtm, size/XS

#4203 Retrieve Project ID from gcloud
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#4140 fix: removing attributes unknown (not supported) by kubernetes deployment
  charts/jx/templates/deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#4209 fix: support multi-namespaces in charts with tillerless
  pkg/helm/helm_template.go
  pkg/helm/helm_template_test.go
  pkg/helm/test_data/multi_objects/objects_separator_namespace.yaml
Labels: approved, lgtm, size/L

#4207 fix(tekton): Populate activity with correct step order
  pkg/jx/cmd/controller_build_test.go
  pkg/jx/cmd/test_data/controller_build/update_stage_info/pod.yml
  pkg/kube/pod.go
  pkg/tekton/pipelines.go
  pkg/tekton/tekton_helpers_test/test_helpers.go
Labels: approved, lgtm, size/XL

#4212 fix: the logic for determining tag history
  Makefile
  pkg/gits/git_cli.go
  pkg/gits/github.go
  pkg/jx/cmd/step/step_changelog.go
Labels: approved, lgtm, size/M

#4201 first spike at an interpret mode for 'jx step create task'
  pkg/helm/helm_template.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/step/create/step_create_task.go
  pkg/jx/cmd/step/helm/step_helm.go
  pkg/tekton/crds.go
Labels: approved, lgtm, size/L

#4213 fix: the changelog runs after the new tag, so try going back a bit fu…
  pkg/gits/git_cli.go
Labels: approved, lgtm, size/XS

#4211 chore: upgrade the builder to fix the client update script
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#4214 fix: allow helm lint to be given the values/secrets to validate against
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/step/helm/step_helm.go
  pkg/jx/cmd/step/helm/step_helm_apply.go
  pkg/jx/cmd/step/helm/step_helm_build.go
  pkg/jx/cmd/step/helm/step_helm_release.go
Labels: approved, lgtm, size/M

#4200 feat: added vault & kaniko flags into terraform vars
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/create_terraform_integration_test.go
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/M

#4158 jx get preview --current should print the url
  pkg/jx/cmd/get_preview.go
Labels: approved, lgtm, ok-to-test, size/XS

#4215 Chore: retry tests that use expect as they are flaky
  pkg/jx/cmd/add/add_app_integration_test.go
  pkg/jx/cmd/add/add_app_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/surveyutils/jsonschema_test.go
  pkg/tests/console_wrapper.go
  pkg/tests/helpers.go
  pkg/tests/retry.go
  pkg/tests/retry_test.go
Labels: approved, lgtm, size/XXL

#4216 fix: don’t include the parent commit!
  pkg/jx/cmd/step/step_changelog.go
Labels: approved, lgtm, size/XS

#4218 feat: refactored to use error writer pattern
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/L

#4223 Defaulting workload type
  pkg/jx/cmd/edit_buildpack.go
Labels: approved, lgtm, size/S

#4225 Formatting default answers in advanced mode
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/edit_buildpack.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/helm.go
  pkg/util/color.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: approved, lgtm, size/M

#4222 fix: making sure go modules is enabled for test rules
  Makefile
Labels: approved, lgtm, size/XS

#4224 chore: Ensuring external-dns chart repo is added to helm repo
  pkg/jx/cmd/opts/install.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/XS

#4220 feat: removed o.Debugf helper, using logger directly
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/controller/controller_workflow.go
  pkg/jx/cmd/controller_backup.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_commitstatus.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/create_archetype.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/create_cluster_gke_terraform.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/create_mlquickstart.go
  pkg/jx/cmd/create_quickstart.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/delete_aws.go
  pkg/jx/cmd/delete_context.go
  pkg/jx/cmd/delete_extension.go
  pkg/jx/cmd/gc_activities.go
  pkg/jx/cmd/gc_helm.go
  pkg/jx/cmd/gc_previews.go
  pkg/jx/cmd/gc_releases.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/get_quickstarts.go
  pkg/jx/cmd/import_integration_test.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_dependencies.go
  pkg/jx/cmd/opts/commands.go
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/opts/environments.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/opts/plugins.go
  pkg/jx/cmd/promote/promote.go
  pkg/jx/cmd/rsh.go
  pkg/jx/cmd/step/create/step_create_task.go
  pkg/jx/cmd/step/create/step_create_version_pr.go
  pkg/jx/cmd/step/post/step_post_run.go
  pkg/jx/cmd/step/step_changelog.go
  pkg/jx/cmd/step/step_next_version.go
  pkg/jx/cmd/step/step_split_monorepo.go
  pkg/jx/cmd/step/step_tag.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_extensions_repository.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/XL

#4232 feat: Improve how extenral-dns prompts user for domain
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/M

#4227 Restrict cluster name length
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_gke_test.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/M

#4233 Unique Loop Name
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/loop_step_with_name/jenkins-x.yml
Labels: approved, lgtm, size/M

#4219 feat: added some basic validation to the terraform clustername
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/create_terraform_test.go
Labels: approved, lgtm, size/M

#4231 fix: added a few verify steps
  pkg/jx/cmd/opts/install.go
  pkg/jx/cmd/step/verify/step_verify.go
  pkg/jx/cmd/step/verify/step_verify_git.go
  pkg/jx/cmd/step/verify/step_verify_install.go
  pkg/jx/cmd/step/verify/step_verify_pod_count.go
Labels: approved, lgtm, size/L

#4137 fix: Add search filter for Gitlab repos to resolve issue with Gitlab …
  pkg/gits/gitlab.go
Labels: approved, lgtm, ok-to-test, size/S

#4240 chore: converted fmt.Print* to log.Logger()
  pkg/cloud/iks/registry.go
  pkg/cloud/oke/helper.go
  pkg/collector/git_collector.go
  pkg/gits/github.go
  pkg/jx/cmd/create_cluster_iks.go
  pkg/jx/cmd/create_cluster_oke.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/delete_eks.go
  pkg/jx/cmd/get_eks.go
  pkg/jx/cmd/get_preview.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/step/git/step_git_fork_and_clone.go
  pkg/jx/cmd/step/verify/step_verify_pod_ready.go
  pkg/kube/activity.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, size/M

#4226 fix: too many open files installing istio addon
  pkg/util/downloads.go
Labels: approved, lgtm, size/M

#4243 Template for naming service accounts
  pkg/cloud/gke/externaldns/external_dns.go
  pkg/cloud/gke/helper.go
  pkg/cloud/gke/naming.go
  pkg/cloud/gke/vault/vault_backend.go
  pkg/cmd/create/install.go
  pkg/cmd/deletecmd/delete_vault.go
Labels: approved, lgtm, size/M

#4237 feat: create the managed zone when using external-dns
  pkg/cmd/create/install.go
  pkg/cmd/opts/common.go
  pkg/cmd/opts/install.go
Labels: approved, size/M

#4275 fix: improved logic around upgrades and brew
  pkg/cmd/opts/install.go
  pkg/cmd/upgrade_cli.go
  pkg/cmd/upgrade_cli_test.go
  pkg/cmd/version.go
  pkg/cmd/version_test.go
Labels: approved, lgtm, size/L

#4277 Move advanced flag to init flags
  pkg/cmd/initcmd/init.go
  pkg/cmd/opts/common.go
Labels: approved, lgtm, size/XS

#4279 Make some logging Debugf
  pkg/helm/helm_template.go
Labels: approved, lgtm, size/S

#4285 chore: Set resource request and limit for lint context
  jenkins-x-lint.yml
Labels: approved, lgtm, size/XS

#4135 chore(tekton): Move build pack translation to jenkinsfile pkg
  pkg/cmd/importcmd/import.go
  pkg/cmd/opts/constants.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/cmd/step/syntax/step_syntax.go
  pkg/cmd/step/syntax/step_syntax_effective.go
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/jenkinsfile/pipeline.go
  pkg/tekton/syntax/constants.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
  pkg/util/constants.go
Labels: approved, lgtm, size/XXL

#4274 refactor: moving upgrade and update commands in sub-packages
  pkg/cmd/cmd.go
  pkg/cmd/create/create_addon_sso.go
  pkg/cmd/create/create_vault.go
  pkg/cmd/opts/upgrade/upgrade_ingress.go
  pkg/cmd/update/update.go
  pkg/cmd/update/update_cluster.go
  pkg/cmd/update/update_cluster_gke.go
  pkg/cmd/update/update_cluster_gke_terraform.go
  pkg/cmd/upgrade/upgrade.go
  pkg/cmd/upgrade/upgrade_addon_prow.go
  pkg/cmd/upgrade/upgrade_addons.go
  pkg/cmd/upgrade/upgrade_apps.go
  pkg/cmd/upgrade/upgrade_apps_test.go
  pkg/cmd/upgrade/upgrade_binaries.go
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/cmd/upgrade/upgrade_cli_test.go
  pkg/cmd/upgrade/upgrade_cluster.go
  pkg/cmd/upgrade/upgrade_crd.go
  pkg/cmd/upgrade/upgrade_extensions.go
  pkg/cmd/upgrade/upgrade_extensions_repository.go
  pkg/cmd/upgrade/upgrade_ingress.go
  pkg/cmd/upgrade/upgrade_ingress_test.go
  pkg/cmd/upgrade/upgrade_platform.go
  pkg/cmd/version.go
Labels: approved, lgtm, size/XXL

#4288 Refactor clone jx-versions repo
  pkg/cmd/opts/helm.go
Labels: approved, lgtm, size/M

#4217 feat: use project configured build pack url if present
  pkg/cmd/importcmd/import.go
  pkg/cmd/initcmd/init.go
  pkg/cmd/opts/buildpacks.go
Labels: approved, lgtm, size/S

#4290 Refactor install logging
  pkg/cmd/clients/factory.go
  pkg/cmd/create/install.go
  pkg/cmd/initcmd/init.go
  pkg/cmd/opts/domain.go
  pkg/cmd/opts/helm.go
  pkg/cmd/opts/install.go
  pkg/config/admin_secrets.go
  pkg/gits/git_repo.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/kube/env.go
  pkg/kube/secrets.go
  pkg/version/version_data.go
Labels: approved, lgtm, size/M

#4298 chore: improved logging statements
  pkg/cmd/create/create_cluster_oke.go
  pkg/cmd/create/install.go
  pkg/cmd/gc/gc_previews.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/opts/buildpacks.go
  pkg/cmd/opts/cert_manager.go
  pkg/cmd/preview/preview.go
  pkg/cmd/status.go
  pkg/cmd/step/pr/step_pr_labels.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/github.go
  pkg/helm/helm_template.go
  pkg/users/user_details.go
Labels: approved, lgtm, size/M

#4300 Default long term log storage
  pkg/cmd/create/install.go
Labels: approved, lgtm, size/S

#4297 Add user label to lts bucket
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/storage/long_term_storage.go
Labels: approved, lgtm, size/M

#4307 fix(tekton): Pass the updated pipelineConfig, not the stale one
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/S

#4295 fix: add deprecation warning for knative build
  pkg/cmd/create/install.go
  pkg/cmd/step/verify/step_verify_git.go
Labels: approved, lgtm, size/XS

#4306 fix(tekton): Don't wait for pods for stages after a failure
  pkg/cmd/get/get_build_logs.go
Labels: approved, lgtm, size/S

#4309 fix: fix service URL discovery so it can work without exposecontroller
  pkg/cmd/clients/factory.go
  pkg/cmd/opts/install.go
  pkg/kube/services/services.go
Labels: approved, lgtm, size/S

#3793 fix: adding local app fails to build dependencies
  pkg/apps/install.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
Labels: approved, lgtm, size/M

#4132 use Jenkins X image for git merges now that it has been released fixe…
  pkg/cmd/step/create/test_data/step_create_task/add-env-to-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/command-as-multiline-script/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/containeroptions-on-pipelineconfig/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/correct-pipeline-stage-is-removed/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/from_yaml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/loop-in-buildpack-syntax/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override_block_step/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/per_step_container_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/pipeline-timeout/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/remove-stage-from-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/remove-stage/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/M

#4318 fix getting secrets from vault when deploying to preview environments
  pkg/cmd/opts/helm.go
  pkg/cmd/opts/install.go
  pkg/cmd/preview/preview.go
Labels: approved, lgtm, size/S

#4319 fix: add step to auto-default GitOps install values
  pkg/cmd/initcmd/init.go
  pkg/cmd/opts/constants.go
  pkg/cmd/step/create/step_create.go
  pkg/cmd/step/create/step_create_install_values.go
  pkg/cmd/step/create/step_create_install_values_test.go
  pkg/cmd/step/create/test_data/step_create_install_values/init-values.yaml
  pkg/cmd/step/verify/step_verify_git.go
  pkg/util/maps.go
Labels: approved, lgtm, size/L

#4325 fix: make it easier to capture the preview URL from scripts/shell
  pkg/cmd/get/get_preview.go
Labels: approved, lgtm, size/XS

#4327 chore: minor rename of terraform service account
  pkg/cmd/create/create_terraform.go
Labels: approved, lgtm, size/XS

#4130 feat: Updated release process to use goreleaser
  .gitignore
  .goreleaser.yml
  Makefile
Labels: approved, lgtm, size/M

#4312 chore: Remove some unused code in pipeline_config
  pkg/config/project_config.go
  pkg/config/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#4332 chore(tekton): Switch env to be corev1.EnvVar
  Makefile.codegen
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
  pkg/tekton/syntax/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#4335 Revert "feat: Updated release process to use goreleaser"
  .gitignore
  .goreleaser.yml
  Makefile
Labels: approved, lgtm, size/M

#4336 fix: making sure the right Run function is called for step git merge
  go.mod
  pkg/cmd/opts/step.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/git/step_git_merge.go
  pkg/cmd/step/git/step_git_merge_test.go
  pkg/gits/testhelpers.go
Labels: approved, lgtm, size/L

#4346 fix: removed the hack to set the verbose flag
  pkg/cmd/create/install.go
Labels: approved, lgtm, size/XS

#4343 feat: add jx step create values
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/cmd/add/add_app.go
  pkg/cmd/add/add_app_test.go
  pkg/cmd/step/create/step_create.go
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/create/step_create_values_test.go
  pkg/cmd/step/create/test_data/step_create_values/install/values.schema.json
  pkg/cmd/step/create/test_data/step_create_values/install/values.yaml.golden
  pkg/cmd/upgrade/upgrade_apps.go
  pkg/secreturl/helpers.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/AllOfIf.test.schema.json
  pkg/surveyutils/test_data/ifThenElse.test.schema.json
  pkg/surveyutils/test_data/ifThenElseNested.test.schema.json
Labels: approved, lgtm, size/XL

#4338 fix: updating git merge image used in Tekton pipeline
  pkg/cmd/step/create/test_data/step_create_task/add-env-to-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/command-as-multiline-script/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/containeroptions-on-pipelineconfig/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/correct-pipeline-stage-is-removed/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/from_yaml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/loop-in-buildpack-syntax/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override_block_step/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/per_step_container_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/pipeline-timeout/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/remove-stage-from-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/remove-stage/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/M

#4342 fix: defaulting LTS to false if provide not GKE as not supported by other providers
  pkg/cmd/create/install.go
Labels: approved, lgtm, ok-to-test, size/XS

#4302 fix: Added missing timestamps
  pkg/cmd/create/create_addon_owasp.go
  pkg/cmd/create/create_post_preview_job.go
Labels: approved, lgtm, ok-to-test, size/S

#4351 fix: remove the secret abstraction in jsonschema
  pkg/apps/values.go
  pkg/cmd/add/add_app_test.go
  pkg/cmd/step/create/test_data/step_create_values/install/values.schema.json
  pkg/cmd/step/create/test_data/step_create_values/install/values.yaml.golden
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/vault/fake/client.go
Labels: approved, lgtm, size/L

#4347 feat: support for generated secrets in schemas
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/generatedToken.test.schema.json
  pkg/util/secrets/secrets.go
  pkg/vault/helpers_test.go
Labels: approved, lgtm, size/L

#4363 fix(tekton): Preserve overridden step name and fix override test
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-steps/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/S

#4350 fix: lets let `jx step create values` work with vault + local files
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/cmd/add/add_app_test.go
  pkg/cmd/opts/helm.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/create/test_data/step_create_values/install/values.schema.json
  pkg/cmd/step/create/test_data/step_create_values/install/values.yaml.golden
  pkg/kube/constants.go
  pkg/secreturl/client.go
  pkg/secreturl/localvault/client.go
  pkg/secreturl/mocks/secreturl_client.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/util/dirs.go
  pkg/vault/fake/client.go
Labels: approved, lgtm, size/L

#4360 feat: support looking for existing secrets in vault
  pkg/cmd/step/create/step_create_values_test.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/ingoreMissingValues.test.schema.json
  pkg/vault/fake/client.go
Labels: approved, lgtm, size/XXL

#4371 chore: reduced install logging further
  pkg/cloud/gke/gcloud.go
  pkg/cmd/create/create_cluster_gke.go
  pkg/cmd/create/create_terraform.go
  pkg/cmd/opts/common.go
Labels: approved, lgtm, size/S

#4372 feat: checking for a min terraform version of 0.12.0
  pkg/cmd/clients/factory.go
  pkg/cmd/create/create_terraform.go
  pkg/terraform/terraform.go
Labels: approved, lgtm, size/S

#4368 fix: correctly setting docker registry on GKE
  pkg/cmd/create/create_cluster_gke.go
  pkg/cmd/create/install.go
  pkg/cmd/create/install_test.go
Labels: approved, lgtm, size/L

#4384 fix: default to use a temporary directory for applying helm charts
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/spring/model.go
Labels: approved, lgtm, size/M

#4381 fix: first spike at a canonical jx requirements configuration file
  go.mod
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/verify/step_verify_git.go
  pkg/cmd/step/verify/step_verify_install.go
  pkg/cmd/upgrade/upgrade_apps_test.go
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
  pkg/config/zz_generated.deepcopy.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
Labels: approved, lgtm, size/L

#4387 fix: disabling kaniko by default on EKS
  pkg/cmd/create/install.go
  pkg/cmd/create/install_test.go
Labels: approved, lgtm, size/M

#4378 fix: 'jx create terraform' working again with increased priv
  pkg/cloud/gke/gcloud.go
  pkg/cmd/create/create_terraform.go
  pkg/cmd/opts/auth.go
Labels: approved, lgtm, size/M

#4382 fix: if the user is fully numeric, prepend an X
  pkg/cmd/create/create_user.go
  pkg/cmd/create/create_user_integration_test.go
  pkg/kube/names.go
Labels: approved, lgtm, size/M

#4397 fix: add a 'jx step verify preinstall' step
  pkg/cmd/create/create_cluster_aws.go
  pkg/cmd/create/create_cluster_eks.go
  pkg/cmd/create/create_cluster_gke.go
  pkg/cmd/create/create_terraform.go
  pkg/cmd/create/install.go
  pkg/cmd/opts/common.go
  pkg/cmd/step/env/step_env_apply.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/verify/common.go
  pkg/cmd/step/verify/step_verify.go
  pkg/cmd/step/verify/step_verify_install.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_test.go
  pkg/cmd/step/verify/test_data/preinstall/no_kaniko_or_terraform/jx-requirements.yml
  pkg/cmd/step/verify/test_data/preinstall/terraform_kaniko/jx-requirements.yml
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/L

#4400 fix: 'jx step helm apply' with temporary dir
  pkg/cmd/opts/helm.go
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/M

#4406 fix: add a 'jx boot' command
  pkg/cmd/boot/boot.go
  pkg/cmd/boot/boot_test.go
  pkg/cmd/boot/test_data/jenkins-x.yml
  pkg/cmd/boot/test_data/jx-requirements.yml
  pkg/cmd/cmd.go
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/L

#4408 chore: improve formatting of `step bdd` status report
  pkg/cmd/step_bdd.go
  pkg/util/commands.go
Labels: approved, lgtm, size/S

#4389 fix(tekton): Pick up build pack top-level containerOptions properly
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/pipeline.yml
  pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/pipelineresources.yml
  pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/pipelinerun.yml
  pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/structure.yml
  pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/packs/maven-with-resource-limit/pipeline.yaml
  pkg/jenkinsfile/pipeline.go
Labels: approved, lgtm, size/XL

#4348 feat: Updated release to use goreleaser
  .gitignore
  .goreleaser.yml
  Makefile
  jenkins-x.yml
Labels: approved, lgtm, size/M

#4396 feat: implement updatebot in jx
  pkg/cmd/create/create_pullrequest.go
  pkg/cmd/opts/step.go
  pkg/cmd/promote/promote.go
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/create/pr/step_create_pr_docker.go
  pkg/cmd/step/create/pr/step_create_pr_versions.go
  pkg/cmd/step/create/step_create.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/create/step_create_values_test.go
  pkg/cmd/step/create/test_data/step_create_values/install/values.schema.json
  pkg/cmd/step/step_blog.go
  pkg/cmd/step/step_changelog.go
  pkg/docker/dockerfile.go
  pkg/docker/dockerfile_test.go
  pkg/docker/test_data/dotname.golden/Dockerfile.builder-base
  pkg/docker/test_data/dotname/Dockerfile.builder-base
  pkg/docker/test_data/nested.golden/foo/bar/Dockerfile
  pkg/docker/test_data/nested/foo/bar/Dockerfile
  pkg/docker/test_data/simple.golden/Dockerfile
  pkg/docker/test_data/simple/Dockerfile
  pkg/environments/gitops.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/provider_fake.go
  pkg/gits/releases.go
  pkg/gits/releases/releases.go
  pkg/gits/releases/releases_test.go
  pkg/tests/files.go
  templates/release.yaml
  values.yaml
Labels: approved, lgtm, size/XXL

#4418 Specifying the builders version for the release step
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#4419 Corrected version number
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#4420 Sanitize bucket labels
  pkg/cloud/gke/gcloud.go
  pkg/cmd/create/create_cluster_gke.go
  pkg/cmd/create/create_cluster_gke_terraform.go
  pkg/cmd/create/create_cluster_gke_test.go
  pkg/cmd/create/create_terraform.go
  pkg/cmd/create/install.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: approved, lgtm, size/M

#4358 chore: set a valid version for bank-vaults
  go.mod
Labels: approved, lgtm, size/XS

#4320 feat(tekton): adding command to create and apply metapipeline
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/apps/constants.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/cmd/controller/controller_pipelinerunner.go
  pkg/cmd/step/create/step_create.go
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/cmd/step/create/step_create_meta_pipeline_test.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/step_next_version_test.go
  pkg/cmd/step/step_tag.go
  pkg/config/project_config.go
  pkg/config/project_config_test.go
  pkg/kube/pod_templates.go
  pkg/prow/env_vars.go
  pkg/prow/env_vars_test.go
  pkg/tekton/crds.go
  pkg/tekton/metapipeline/metapipeline.go
  pkg/tekton/metapipeline/metapipeline_test.go
  pkg/tekton/pipelines.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/util/strings.go
  pkg/util/strings_test.go
  pkg/util/structs.go
Labels: approved, lgtm, size/XXL

#4427 fix: Resolving lack of tags in repo during release
  .goreleaser.yml
  Makefile
Labels: approved, lgtm, size/L

#4428 Try and implement a separate build for each binary
  .goreleaser.yml
Labels: approved, lgtm, size/L

#4435 Chore: Added retry around some tests which appear to be flaky
  pkg/cmd/step/verify/step_verify_preinstall_test.go
  pkg/prow/env_vars_test.go
Labels: approved, lgtm, size/S

#4426 fix: add vault support to 'jx boot'
  pkg/cmd/boot/boot.go
  pkg/cmd/clients/fake/fake_factory.go
  pkg/cmd/create/create_vault.go
  pkg/cmd/create/install.go
  pkg/cmd/namespace/namespace.go
  pkg/cmd/opts/common.go
  pkg/cmd/opts/helm.go
  pkg/cmd/step.go
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/create/step_create_values_test.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/helm/step_helm_apply_test.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_test.go
  pkg/cmd/testhelpers/app_test_helpers.go
  pkg/cmd/testhelpers/cmd_test_helpers.go
  pkg/config/install_requirements.go
  pkg/helm/helm_helpers.go
  pkg/helm/test_data/tree_of_values_yaml_templates/prow/values.tmpl.yaml
  pkg/helm/test_data/tree_of_values_yaml_templates/tekton/values.tmpl.yaml
  pkg/helm/test_data/tree_of_values_yaml_templates/values.tmpl.yaml
  pkg/helm/values_tree.go
  pkg/secreturl/fakevault/client.go
Labels: approved, lgtm, size/XL

#4446 Fix path to linux binary when calling changelog
  Makefile
Labels: approved, lgtm, size/XS

#4430 fix(tekton): Metapipeline should pass env/labels to generated pipeline
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/tekton/metapipeline/metapipeline.go
  pkg/tekton/metapipeline/metapipeline_test.go
  pkg/tekton/pipeline_info.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/L

#4453 Allow changelog step to update the release
  Makefile
Labels: approved, lgtm, size/XS

#4434 feat: add support for regex and chart based version updates
  go.mod
  go.sum
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/create/pr/step_create_pr_chart.go
  pkg/cmd/step/create/pr/step_create_pr_docker.go
  pkg/cmd/step/create/pr/step_create_pr_regex.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/helm/helm_helpers.go
  pkg/util/regex.go
  pkg/util/regex_test.go
Labels: approved, lgtm, size/XL

#4457 fix: lets default to jenkins x pipelines if there's a missing importmode
  pkg/apis/jenkins.io/v1/types_environment.go
Labels: approved, lgtm, size/XS

#4450 chore: Fix scheduler docs
  pkg/cmd/step/scheduler/step_scheduler_config_apply.go
  pkg/cmd/step/scheduler/step_scheduler_config_migrate.go
Labels: approved, lgtm, size/S

#4459 fix: Try uploading the release note with the release
  Makefile
Labels: approved, lgtm, size/XS

#4447 fix: environment controller not finding git token if GIT_KIND
  pkg/cmd/controller/controller_enviornmentcontroller.go
Labels: approved, lgtm, size/S

#4454 feat: generate a table showing dependency updates
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_release.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/cmd/opts/releases.go
  pkg/cmd/opts/releases_test.go
  pkg/cmd/step/step_changelog.go
  pkg/gits/commits.go
  pkg/gits/commits_integration_test.go
  pkg/gits/commits_test.go
  pkg/gits/releases/releases.go
  pkg/gits/releases/releases_test.go
Labels: approved, lgtm, size/XL

#4462 Fix AddLabel
  pkg/cmd/create/create_cluster_gke.go
  pkg/cmd/create/create_cluster_gke_test.go
Labels: approved, lgtm, size/XS

#4461 fix(tekton): Make sure parsed.Options is initted.
  pkg/cmd/step/syntax/step_syntax_effective.go
Labels: approved, lgtm, size/XS

#4469 fix: Ignoring temporary edits when releasing
  .gitignore
  Makefile
Labels: approved, lgtm, size/XS

#4473 chore: configure semantics-commits bot
  semantic.yml
Labels: approved, lgtm, size/XS

#4479 fix(tekton): Clone before getting GitInfo in step create task
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/M

#4472 feat: do not redownload istio tarball
  pkg/cmd/create/create_addon_istio.go
Labels: approved, lgtm, size/S

#4449 chore: better document how the test targets works
  Makefile
Labels: approved, lgtm, size/XS

#4484 fix: Don't update release when generating changelog
  Makefile
Labels: approved, lgtm, size/XS

#4488 fix: place all ldflag parameters onto one line
  .goreleaser.yml
  Makefile
Labels: approved, lgtm, size/S

#4489 fix: Assign boolean to update-release explicitly
  Makefile
Labels: approved, lgtm, size/XS

#4433 fix(tekton): Git org and repo should be replaced consistently
  pkg/apps/install.go
  pkg/cmd/controller/controller_commitstatus.go
  pkg/cmd/create/create_chat_token.go
  pkg/cmd/create/create_devpod.go
  pkg/cmd/create/create_token_addon.go
  pkg/cmd/create/create_tracker_token.go
  pkg/cmd/create/install.go
  pkg/cmd/deletecmd/delete_application.go
  pkg/cmd/deletecmd/delete_devpod.go
  pkg/cmd/get/get_preview.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/initcmd/init.go
  pkg/cmd/opts/git.go
  pkg/cmd/opts/team_settings.go
  pkg/cmd/preview/preview.go
  pkg/cmd/promote/promote.go
  pkg/cmd/step/post/step_post_run.go
  pkg/cmd/step/pre/step_pre_extend.go
  pkg/cmd/step/step_changelog.go
  pkg/cmd/step/step_stash.go
  pkg/cmd/step/step_tag.go
  pkg/cmd/step/verify/step_verify_pod_count.go
  pkg/cmd/step_bdd.go
  pkg/io/config_writers.go
  pkg/jenkinsfile/pipeline.go
  pkg/kube/activity.go
  pkg/kube/activity_test.go
  pkg/kube/cluster/cluster.go
  pkg/kube/git_services.go
  pkg/kube/namespaces.go
  pkg/kube/naming/names.go
  pkg/kube/naming/names_valid_test.go
  pkg/kube/sourcerepositories.go
  pkg/kube/teams.go
  pkg/kube/vault/vault.go
  pkg/pipelinescheduler/generator.go
  pkg/tekton/pipelines.go
  pkg/testkube/secrets.go
  pkg/users/git.go
  pkg/users/user_details.go
  pkg/users/users.go
  pkg/workflow/workflows.go
Labels: approved, lgtm, size/L

#4494 fix: Remove pre goreleaser call
  Makefile
Labels: size/XS

#4487 fix: Environment prefix defaulting to generated name
  pkg/cmd/create/install.go
Labels: approved, lgtm, size/S

#4500 fix: allow environment variables to be used in batch mode for defaults
  pkg/surveyutils/jsonschema.go
Labels: approved, lgtm, size/S

#4497 fix: Update jenkins-x[-context].yml builder images
  jenkins-x-bdd.yml
  jenkins-x-integration.yml
  jenkins-x-tekton.yml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#4464 fix: added .exe to minikube download url for windows
  pkg/cmd/opts/install.go
Labels: approved, lgtm, ok-to-test, size/XS
