Repository jenkins-x/jx, pull requests merged in 2019-04, with the labels that each got.

#3488 Added '--urlTemplate' argument to 'jx upgrade ingress'
  go.mod
  go.sum
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, size/S

#3489 fix: support lazy creation of the SourceRepository resource
  cmd/codegen/generator/open_api.go
  jx/scripts/update-website.sh
  pkg/gits/git_url_test.go
  pkg/gits/provider.go
  pkg/jx/cmd/install.go
  pkg/kube/sourcerepository_impl.go
  pkg/tekton/pipelines.go
Labels: size/M

#3493 Added publish-service arg to ingress-controller
  pkg/jx/cmd/init.go
Labels: approved, lgtm, size/XS

#3491 fix: return correct SourceRepository
  jx/scripts/update-website.sh
  pkg/gits/git_url_test.go
  pkg/gits/helpers.go
  pkg/gits/provider.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/step_create_task.go
  pkg/kube/activity.go
  pkg/kube/sourcerepositories.go
  pkg/kube/sourcerepository_interface.go
  pkg/tekton/pipelines.go
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/L

#3495 fix: build number generation for tekton
  pkg/jx/cmd/step_create_task.go
  pkg/kube/sourcerepositories.go
Labels: approved, lgtm, size/S

#3509 fix(userrole) lookup users from the correct namespace
  pkg/jx/cmd/common.go
  pkg/jx/cmd/edit_userrole.go
  pkg/jx/cmd/get_user.go
  pkg/kube/roles.go
Labels: approved, lgtm, size/M

#3504 fix: use a different version of prow for knative build
  jx/scripts/update-website.sh
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/L

#3519 fix: lets discover app URLs if using knative serve
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  go.mod
  go.sum
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/builds/jenkinsfiles.go
  pkg/builds/jenkinsfiles_test.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/config/project_config.go
  pkg/config/project_config_test.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/matchers/ptr_to_gits_listcommitsarguments.go
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/clients/interface.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned5_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/edit.go
  pkg/jx/cmd/edit_deploy.go
  pkg/jx/cmd/get_applications.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_create.go
  pkg/jx/cmd/step_create_build.go
  pkg/jx/cmd/step_create_build_test.go
  pkg/jx/cmd/step_create_buildtemplate.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/test_helpers.go
  pkg/kserving/constants.go
  pkg/kserving/kservices.go
  pkg/kube/version.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/XXL

#3507 fix: propagate error from PatchUpdate
  pkg/client/clientset/versioned/typed/jenkins.io/v1/app_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/app_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/buildpack_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/buildpack_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/commitstatus_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/commitstatus_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environment_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environment_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environmentrolebinding_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environmentrolebinding_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/extension_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/extension_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fact_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fact_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/gitservice_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/gitservice_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelinestructure_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelinestructure_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/plugin_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/plugin_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/release_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/release_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/sourcerepository_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/sourcerepository_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/team_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/team_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/testutil.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/user_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/user_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/workflow_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/workflow_expansion_test.go
Labels: approved, lgtm, size/XXL

#3520 fix: using pushd/popd to navigate dirs when building website
  jx/scripts/update-website.sh
Labels: approved, lgtm, size/S

#3521 Added cagiti and warrenbailey to owners list
  OWNERS
Labels: approved, lgtm, size/XS

#3525 fix: corrected jx dir when generating website
  jx/scripts/update-website.sh
Labels: approved, size/XS

#3526 fix: add support for knative serve
  jenkins-x-bdd.yml
  pkg/builds/jenkinsfiles.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_template.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/edit_deploy.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_integration_test.go
Labels: approved, lgtm, size/L

#3531 more old workspace entries
  Jenkinsfile
  jenkins-x-integration.yml
  jenkins-x-lint.yml
  jenkins-x.yml
Labels: approved, lgtm, size/L

#3532 fixes for devpods, pipelinecontroller and gitops apps folder
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/collector/git_collector.go
  pkg/environments/gitops.go
  pkg/helm/values_tree.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_create_task.go
Labels: size/L

#3496 feature: added a way to show the status of the app and provided funti…
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/clients/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/get_apps.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/test_data/get_apps/get_app_status.json
  pkg/jx/cmd/test_data/get_apps/get_apps_table_json.json
  pkg/jx/cmd/test_data/get_apps/get_apps_table_yaml.yaml
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, size/XL

#3533 fix for prow bdd tests
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion_test.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/create_git_server.go
  pkg/jx/cmd/install.go
  pkg/kube/git_services.go
Labels: approved, lgtm, size/M

#3535 Fix/no app exit code
  pkg/jx/cmd/get_apps.go
  pkg/jx/cmd/get_apps_test.go
Labels: approved, lgtm, size/XS

#3499 Added domain argument to 'jx upgrade ingress'
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, size/XS

#3516 fix(userrole) removing multiple roles was not correct
  pkg/jx/cmd/get_apps_test.go
  pkg/kube/roles.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: approved, lgtm, size/M

#3508 NotExecuted is not a failure
  pkg/jx/cmd/controller_build.go
  pkg/kube/activity.go
Labels: approved, lgtm, size/S

#3523 feature: hiearchical config for prow.
  pkg/pipelinescheduler/builder.go
  pkg/pipelinescheduler/builder_test.go
  pkg/pipelinescheduler/config.go
  pkg/pipelinescheduler/prow/config_builder.go
  pkg/pipelinescheduler/prow/config_builder_test.go
  pkg/pipelinescheduler/prow/test_data/repo/config.yaml
  pkg/pipelinescheduler/prow/test_data/repo/plugins.yaml
  pkg/pipelinescheduler/prow/test_data/repo/repo.yaml
  pkg/pipelinescheduler/prow/test_data/with_parent/config.yaml
  pkg/pipelinescheduler/prow/test_data/with_parent/parent.yaml
  pkg/pipelinescheduler/prow/test_data/with_parent/plugins.yaml
  pkg/pipelinescheduler/prow/test_data/with_parent/repo.yaml
  pkg/pipelinescheduler/prow_config.go
  pkg/pipelinescheduler/testhelpers/helpers.go
  pkg/surveyutils/jsonschema.go
Labels: approved, lgtm, size/XXL

#3541 feat: enabling cloudkms api when --vault is used
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#3512 fix: Use /workspace/workspace everywhere for non-build-packs
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/L

#3548 fixes for pipelinerunner
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/S

#3546 fix: various issues to get the --ng option working in the install
  pkg/cloud/gke/vault/vault_backend.go
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_auth.go
  pkg/jx/cmd/common_bucket.go
  pkg/jx/cmd/common_gke.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/install.go
  pkg/kube/vault/vault.go
Labels: approved, lgtm, size/L

#3549 fix(git-info): complete tekton based PAs with git information
  pkg/jx/cmd/controller_build.go
Labels: approved, lgtm, size/XS

#3551 add support for docker images for version streams
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/common_version.go
  pkg/jx/cmd/common_versions_test.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/step_tag.go
  pkg/jx/cmd/test_data/common_versions/docker/gcr.io/cheese.yml
  pkg/jx/cmd/test_data/common_versions/docker/maven.yml
  pkg/jx/cmd/test_data/step_create_build/README.md
  pkg/jx/cmd/test_data/step_create_build/add_common_envvars/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/add_common_envvars/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_pod_templates/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_pod_templates/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_previous_step/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/default_image_from_previous_step/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_build/inherit_pod_template_env_volumes/expected-build-release.yml
  pkg/jx/cmd/test_data/step_create_build/inherit_pod_template_env_volumes/jenkins-x.yml
  pkg/kube/names.go
  pkg/version/version_data.go
Labels: approved, lgtm, size/L

#3540 fix: Use per-step build pack images, inherit from agent.container
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/packs/apps/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/podTemplates.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/XL

#3550 fix: minor spelling & lint fixes
  docs/apidocs/openapi-spec/openapiv2.json
  pkg/client/openapi/all/openapi_generated.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/install.go
  pkg/pipelinescheduler/builder.go
  pkg/pipelinescheduler/testhelpers/helpers.go
Labels: approved, lgtm, size/M

#3557 fix: improve selection of regional/zonal clusters
  pkg/jx/cmd/common_gke.go
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, lgtm, size/M

#3556 fix: support generating PRs for docker builder images
  go.mod
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_gloo.go
  pkg/jx/cmd/get.go
  pkg/jx/cmd/get_stream.go
  pkg/jx/cmd/step_create_version_pr.go
  pkg/kube/activity.go
  pkg/version/version_data.go
Labels: approved, size/L

#3560 fix: /bin/sh -c should always take a single string
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/M

#3558 fix: use the dev namespace when fetching the secret location
  pkg/jx/cmd/clients/factory.go
Labels: approved, lgtm, size/XS

#3562 fix promote if a repo is not a fork
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion_test.go
  pkg/client/openapi/all/openapi_generated.go
  pkg/environments/gitops.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned5_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/create_addon_gloo.go
  pkg/jx/cmd/edit_deploy.go
  pkg/jx/cmd/step_create_task.go
Labels: size/L

#3576 fix: order of arguments passed to function
  pkg/gits/gitlab.go
Labels: approved, lgtm, ok-to-test

#3586 feat: store helm repo creds in Vault
  pkg/apps/helmops.go
  pkg/apps/install.go
  pkg/expose/exposecontroller.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/upgrade_apps.go
Labels: approved, lgtm, size/L

#3578 fix: minor fixes to upgrade app
  pkg/apps/install.go
  pkg/jx/cmd/upgrade_apps.go
Labels: approved, lgtm, size/S

#3579 Fix: release name needs to include namespace
  pkg/apps/install.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
Labels: approved, lgtm, size/S

#3597 Fix: don’t error if vault is not available
  pkg/jx/cmd/opts/helm.go
Labels: approved, lgtm, size/XS

#3545 Issue #3502 Improve pegomock integration
  Makefile
  Makefile.codegen
  go.mod
  go.sum
  pkg/auth/mocks/auth_interface.go
  pkg/buildnum/interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/mocks/organisation_checker.go
  pkg/gits/mocks/organisation_lister.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/clients/interface.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/auth_configservice.go
  pkg/jx/cmd/clients/mocks/matchers/clients_factory.go
  pkg/jx/cmd/clients/mocks/matchers/clientset_interface.go
  pkg/jx/cmd/clients/mocks/matchers/gits_gitprovider.go
  pkg/jx/cmd/clients/mocks/matchers/gits_gitter.go
  pkg/jx/cmd/clients/mocks/matchers/golang_jenkins_jenkinsclient.go
  pkg/jx/cmd/clients/mocks/matchers/helm_helmer.go
  pkg/jx/cmd/clients/mocks/matchers/io_writer.go
  pkg/jx/cmd/clients/mocks/matchers/kubernetes_interface.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_auth_authconfig.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_client_sonobuoyclient.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_dynamic_apihelper.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_rest_config.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_v1_secretlist.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned0_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned1_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned2_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned3_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned4_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/secrets_secretslocationkind.go
  pkg/jx/cmd/clients/mocks/matchers/table_table.go
  pkg/jx/cmd/clients/mocks/matchers/terminal_filereader.go
  pkg/jx/cmd/clients/mocks/matchers/terminal_filewriter.go
  pkg/jx/cmd/clients/mocks/matchers/vault_client.go
  pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned5_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/create_env_test.go
  pkg/jx/cmd/import_common_test.go
  pkg/jx/cmd/preview_test.go
  pkg/kube/mocks/kuber.go
  pkg/kube/mocks/sourcerepoer.go
  pkg/kube/resources/mocks/installer.go
  pkg/util/mocks/commander.go
  pkg/vault/mocks/vault_client.go
  pkg/vault/vault_client.go
Labels: approved, lgtm, size/XXL

#3581 fix(tag): trim the content of the VERSION file
  pkg/jx/cmd/step_tag.go
Labels: approved, lgtm, ok-to-test, size/XS

#3583 feat(tag): set the chart's appVersion when tagging
  pkg/jx/cmd/step_tag.go
  pkg/jx/cmd/step_tag_test.go
  pkg/jx/cmd/test_data/step_tag_project/charts/mydemo/Chart.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#3610 fix: update jenkins-x-lint to verify no generated resources got missed
  hack/check-docs.sh
  hack/check-openapi.sh
  hack/run-all-checks.sh
  jenkins-x-lint.yml
  pkg/jx/cmd/opts/jenkins.go
  pkg/jx/cmd/opts/team_settings.go
Labels: approved, lgtm, size/M

#3590 fixes for jenkins ConfigMap size + environment controller
  pkg/gits/github.go
  pkg/helm/helm_template.go
  pkg/jx/cmd/controller.go
  pkg/jx/cmd/controller_enviornmentcontroller.go
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_environment_controller.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/step_create.go
  pkg/jx/cmd/step_create_jenkins_config.go
  pkg/jx/cmd/step_create_jenkins_config_integration_test.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/test_data/step_create_jenkins_config/gradle.yaml
  pkg/jx/cmd/test_data/step_create_jenkins_config/jenkins.yml
  pkg/jx/cmd/test_data/step_create_jenkins_config/maven.yaml
  pkg/kube/constants.go
  pkg/kube/load_pod_templates_integration_test.go
  pkg/kube/pod_templates.go
  pkg/kube/services/services.go
  pkg/kube/test_data/load_pod_templates/gradle.yml
  pkg/kube/test_data/load_pod_templates/maven.yml
Labels: approved, lgtm, size/XXL

#3611 fix: Use pipelineConfig.Env again, don't merge for later stages
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/L

#3612 feat: replace vault: references with secrets
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
  pkg/helm/interface.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_ambassador.go
  pkg/jx/cmd/create_addon_anchore.go
  pkg/jx/cmd/create_addon_environment_controller.go
  pkg/jx/cmd/create_addon_flagger.go
  pkg/jx/cmd/create_addon_gitea.go
  pkg/jx/cmd/create_addon_kubeless.go
  pkg/jx/cmd/create_addon_pipeline_events.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_helm_install.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/vault/helpers.go
Labels: approved, lgtm, size/XL

#3622 fix: rework the helm credentials
  pkg/apps/install.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
  pkg/helm/helm_template.go
  pkg/jx/cmd/opts/helm.go
Labels: approved, lgtm, size/L

#3623 Add a test and linting
  pkg/vault/helpers.go
  pkg/vault/helpers_test.go
Labels: approved, lgtm, size/L

#3624 switch Jenkins X log package to use logrus
  go.mod
  go.sum
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/buildnum/http_build_num.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/compliance_results.go
  pkg/jx/cmd/compliance_status.go
  pkg/jx/cmd/controller_enviornmentcontroller.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/create_git_api_token.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/create_jhipster.go
  pkg/jx/cmd/create_lile.go
  pkg/jx/cmd/create_micro.go
  pkg/jx/cmd/delete_addon_knative_build.go
  pkg/jx/cmd/delete_aws.go
  pkg/jx/cmd/gc_helm.go
  pkg/jx/cmd/get_config.go
  pkg/jx/cmd/get_plugins.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/opts/git.go
  pkg/jx/cmd/opts/install.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/step_git_merge.go
  pkg/jx/cmd/upgrade_cli.go
  pkg/jx/cmd/upgrade_ingress.go
  pkg/kube/pki/certificate.go
  pkg/log/log.go
  pkg/util/dirs.go
Labels: approved, lgtm, size/XL

#3626 fix: rework the helm credentials
  pkg/apps/install.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/opts/helm.go
Labels: approved, lgtm, size/M

#3616 fix: lets return the error if a git command fails
  pkg/gits/git_cli.go
Labels: approved, lgtm, size/XS

#3594 Issue #3205 - Add ability to determine whether a given flag was explicitly set
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/opts/common_test.go
  pkg/jx/cmd/test_helpers.go
Labels: approved, lgtm, size/L

#3584 Stop copying workspace as output for final tasks
  go.mod
  go.sum
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, ok-to-test, size/L

#3633 Fix: use the hostname without the port
  pkg/helm/helm_helpers.go
Labels: approved, lgtm, size/XS

#3638 fix: use a shallow clone in create task
  go.mod
  go.sum
  pkg/client/openapi/all/openapi_generated.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/L

#3639 fix: revert regression of moving to logrus everywhere
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/create_addon_environment_controller.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/prompt.go
  pkg/jx/cmd/step_credential.go
Labels: approved, lgtm, size/M

#3643 fix: if a webhook has an old secret lets replace it
  pkg/gits/github.go
Labels: approved, lgtm, size/XS

#3644 fix: lets add a retry to get the preview URL
  pkg/jx/cmd/opts/team_settings.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_create_task.go
  pkg/kube/pod_templates.go
  pkg/users/git.go
Labels: approved, lgtm, size/M

#3648 fix: only perform a git checkout if we have a custom version ref
  Dockerfile.builder-go
  Dockerfile.builder-maven
  Dockerfile.builder-nodejs
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/get_stream.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/expose.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/opts/install.go
  pkg/jx/cmd/opts/version.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_get_version_changeset.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/L

#3653 chore: add help messages in the makefiles which display the most important make goals with a description
  Makefile
  Makefile.codegen
  Makefile.docker
Labels: approved, lgtm, size/M

#3651 fix: Use temp JX_HOME and KUBECONFIG for integration tests
  go.sum
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/create_quickstart_integration_test.go
  pkg/jx/cmd/create_terraform_integration_test.go
  pkg/jx/cmd/get_workflow_integration_test.go
  pkg/jx/cmd/import_integration_test.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/prompt.go
  pkg/jx/cmd/step_buildpack_apply_integration_test.go
  pkg/jx/cmd/step_create_jenkins_config_integration_test.go
  pkg/jx/cmd/step_next_version_integration_test.go
  pkg/jx/cmd/step_post_install_integration_test.go
  pkg/jx/cmd/step_stash_integration_test.go
  pkg/jx/cmd/test_helpers.go
  pkg/jx/cmd/uninstall_test.go
  pkg/kube/env_modify_namespace_integration_test.go
  pkg/kube/load_pod_templates_integration_test.go
  pkg/util/dirs.go
Labels: approved, lgtm, size/L

#3654 fix: fix the merge logic
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/L

#3650 Fix to the get, upgrade and delete app commands after the side effects of the add apps changes
  pkg/apps/helmops.go
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/delete_app_test.go
  pkg/jx/cmd/get_apps.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/test_data/get_apps/get_apps_table_json.json
  pkg/jx/cmd/test_data/get_apps/get_apps_table_yaml.yaml
Labels: approved, lgtm, size/L

#3661 chore: added dgozalo to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3662 fix: add new command 'jx create var'
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/controller_enviornmentcontroller.go
  pkg/jx/cmd/create.go
  pkg/jx/cmd/create_addon_environment_controller.go
  pkg/jx/cmd/create_step.go
  pkg/jx/cmd/create_variable.go
  pkg/jx/cmd/delete_addon.go
  pkg/jx/cmd/delete_addon_environment_controller.go
  pkg/jx/cmd/edit_config.go
  pkg/jx/cmd/opts/auth.go
  pkg/jx/cmd/opts/buildpacks.go
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/opts/team_settings.go
  pkg/jx/cmd/repository.go
  pkg/jx/cmd/step_create_task.go
  pkg/kube/envvar.go
Labels: approved, lgtm, size/L

#3663 fix: lets setup the team settings before installing prow
  pkg/jx/cmd/controller_enviornmentcontroller.go
  pkg/jx/cmd/create_addon_environment_controller.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/docker.go
  pkg/jx/cmd/opts/install.go
  pkg/jx/cmd/opts/team_settings.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_tag.go
  pkg/kube/crds.go
Labels: approved, lgtm, size/L

#3665 fix: jx add app . does not create a valid chart directory
  pkg/apps/install.go
Labels: approved, lgtm, size/XS

#3669 fix(vault): provision a single vault instance
  pkg/kube/vault/vault.go
Labels: approved, lgtm, size/XS

#3668 fix parsing vault placeholders
  pkg/jx/cmd/upgrade_platform.go
  pkg/vault/helpers.go
  pkg/vault/helpers_test.go
Labels: approved, lgtm, size/M

#3680 feat: Initial framework for installing ExternalDNS
  pkg/cloud/gke/externaldns/external_dns.go
  pkg/cloud/gke/helper.go
  pkg/cloud/gke/naming.go
  pkg/cloud/gke/vault/naming.go
  pkg/cloud/gke/vault/vault_backend.go
  pkg/jx/cmd/create_addon_prow.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete_vault.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/opts/install.go
  pkg/jx/cmd/upgrade_addon_prow.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/L

#3667 envctl improvements
  pkg/jx/cmd/controller_enviornmentcontroller.go
  pkg/jx/cmd/create_addon_environment_controller.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/kube/crds.go
Labels: approved, lgtm, size/L

#3671 chore: remove logs messages because they are not quite informative
  pkg/jx/cmd/opts/helm.go
Labels: approved, lgtm, size/XS

#3672 chore: udpate the issue template with the current installation types
  .github/issue_template.md
Labels: approved, lgtm, size/XS

#3678 fix: allow default ns
  pkg/jx/cmd/delete_app.go
Labels: approved, lgtm, size/XS

#3679 fix: Simplify merging and fix override of top level env vars
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/test_data/step_create_task/from_yaml/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/L

#3660 feat: Support conditional questions when configuring an App
  pkg/jx/cmd/add_app_test.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/AllOfIf.test.schema.json
  pkg/surveyutils/test_data/ifThenElse.test.schema.json
  pkg/surveyutils/test_data/ifThenElseNested.test.schema.json
Labels: approved, lgtm, size/XL

#3642 Solved helm namespace issue for IBM block storage
  pkg/jx/cmd/install.go
Labels: approved, lgtm, ok-to-test, size/XS

#3686 fix: upgrade survey library
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#3706 fix: avoid tiller less failing with empty templates
  charts/jx/.helmignore
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/helm/helm_template.go
Labels: approved, lgtm, size/M

#3670 feat: prompt for repo username/password if needed
  pkg/apps/install.go
  pkg/apps/utils.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_release.go
  pkg/jx/cmd/upgrade_apps_test.go
Labels: approved, lgtm, size/L

#3698 Make sure the command `jx upgrade app` finds the correct latest version when not providing one
  pkg/apps/gitops.go
Labels: approved, lgtm, size/XS

#3675 fix: jenkins-x.yml agent.container was getting cleared for buildpacks
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/packs/no-default-agent/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/packs/override-default-agent/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
Labels: approved, lgtm, size/XL

#3712 fix: logging
  charts/jx/values.yaml
  pkg/jx/cmd/gc_activities.go
  pkg/jx/cmd/get_build_pods.go
  pkg/log/log.go
Labels: approved, lgtm, size/L

#3711 Avoid having a null reference as a list element in the requirements.yaml file when deleting an app in GitOps mode
  pkg/apps/gitops.go
  pkg/jx/cmd/delete_app_test.go
Labels: approved, lgtm, size/XS

#3645 Feat: support values.schema.json preprocessing
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/app_expansion_test.go
  pkg/environments/gitops.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_integration_test.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/opts/logs.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/kube/logs.go
  pkg/kube/pod.go
  pkg/util/json/patch_test.go
Labels: approved, lgtm, size/XL

#3685 fix: Step name needs to be mangled to rfc1035
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/simple_jenkinsfile/jenkins-x.yml
Labels: approved, lgtm, size/S

#3589 fix(gke): GetCurrentProject can be multi-line causing error(s)
  pkg/cloud/gke/helper.go
Labels: approved, lgtm, size/XS

#3692 chore: add the developer certificate of origin (DCO)
  .github/dco.yml
  DCO
Labels: approved, lgtm, size/M

#3709 Fixes the upgrade app command so it doesn't ask for already answered configuration questions
  pkg/apps/gitops.go
  pkg/environments/gitops.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/promote.go
Labels: approved, lgtm, size/M

#3716 Update logrus to fix picking up wrong format on windows.
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#3659 fix: centralise shallow clone logic in gitter
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/L

#3718 Get lifecycle
  .stignore
  pkg/jenkinsfile/pipeline.go
  pkg/jenkinsfile/pipeline_test.go
  pkg/jx/cmd/create_step.go
  templates/.syncthing.cronjob.yaml.tmp
  templates/.syncthing.daemonset.yaml.tmp
  templates/.syncthing.deployment.yaml.tmp
  templates/.syncthing.job.yaml.tmp
Labels: approved, lgtm, size/L

#3736 lets build a second set of binaries using a feature flag token
  Makefile
  jenkins-x.yml
Labels: approved, lgtm, size/M

#3732 Istio addon fails to install when using --no-tiller
  pkg/helm/helm_template.go
  pkg/jx/cmd/create_addon_istio.go
Labels: approved, lgtm, size/S

#3727 Chore: disable noisy test
  pkg/jx/cmd/add_app_integration_test.go
Labels: approved, lgtm, size/XS

#3746 fix: flagger installation fails with no tiller
  pkg/jx/cmd/create_addon_flagger.go
  pkg/jx/cmd/delete_addon_flagger.go
Labels: approved, lgtm, size/S

#3646 feat: enable shortnames e.g. jx add app athens
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/apps/install.go
  pkg/apps/values.go
  pkg/helm/helm.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/delete_app_test.go
  pkg/jx/cmd/get_addon.go
  pkg/jx/cmd/get_apps.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/step_helm_list.go
  pkg/jx/cmd/step_validate.go
  pkg/jx/cmd/test_data/get_apps/get_apps_table_json.json
  pkg/jx/cmd/test_data/get_apps/get_apps_table_yaml.yaml
  pkg/jx/cmd/upgrade_addon_prow.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/jx/cmd/version.go
Labels: approved, lgtm, size/XXL

#3744 fix: improvements for Environment Controller
  go.mod
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/console.go
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_environment_controller.go
  pkg/jx/cmd/create_addon_ingress.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/edit_env.go
  pkg/jx/cmd/get_url.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/environments.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/opts/pullrequest.go
  pkg/jx/cmd/step_create_version_pr.go
  pkg/kube/constants.go
  pkg/kube/env.go
  pkg/kube/env_modify_namespace_integration_test.go
  pkg/kube/env_test.go
  pkg/kube/services/services.go
  pkg/log/log.go
  pkg/prow/config/branch_protection.go
  pkg/prow/config/tide.go
  pkg/prow/config/types.go
  pkg/prow/prow.go
  pkg/util/urls.go
  pkg/version/version_data.go
Labels: approved, lgtm, size/XL

#3751 Fix: ensure repositories are added
  pkg/apps/install.go
Labels: approved, lgtm, size/S

#3750 CloudBees Jenkins X Distribution
  Makefile
  cmd/jx/app/jx.go
  go.mod
  go.sum
  pkg/features/features.go
  pkg/features/features_test.go
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/create_cluster_aks.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_iks.go
  pkg/jx/cmd/create_cluster_minikube.go
  pkg/jx/cmd/create_cluster_minishift.go
  pkg/jx/cmd/create_cluster_oke.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/L

#3763 Update build order
  jenkins-x.yml
Labels: approved, lgtm, size/S

#3764 fix regressions on build controller
  charts/jx/values.yaml
  pkg/auth/server.go
  pkg/collector/git_collector.go
  pkg/gits/interface.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/opts/pullrequest.go
  pkg/jx/cmd/step_create_version_pr.go
Labels: approved, lgtm, size/S

#3769 fix: don’t barf when templating doesn’t work
  pkg/environments/gitops.go
Labels: approved, lgtm, size/S

#3766 lets only set the features build flag when running the distro target
  Makefile
  go.mod
Labels: approved, lgtm, size/S

#3774 fix releasing with feature flags
  Makefile
  jenkins-x.yml
Labels: approved, lgtm, size/S

#3777 fix(tekton): targetPath for stages after first needs to be specified.
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/L

#3765 fix: try disabling parallel for this test
  pkg/jx/cmd/upgrade_apps_test.go
Labels: approved, lgtm, size/XS

#3768 chore: report errors for --ng better
  charts/jx/values.yaml
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/install.go
Labels: size/XS

#3770 chore: cleanup dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#3745 fix: delete the Istio addon in the correct namespace
  pkg/jx/cmd/delete_addon.go
  pkg/jx/cmd/delete_addon_istio.go
Labels: approved, area/istio, lgtm, size/M

#3772 Feat: add jx step values schema template
  pkg/jx/cmd/opts/commands.go
  pkg/jx/cmd/step_values_schema_template.go
  pkg/jx/cmd/step_values_schema_template_test.go
Labels: approved, lgtm, size/L

#3778 fix: upgrade addons fixes
  pkg/jx/cmd/upgrade_addons.go
Labels: approved, lgtm, size/M

#3782 better fix for build controller
  charts/jx/values.yaml
  pkg/jx/cmd/clients/factory.go
Labels: approved, lgtm, size/XS

#3791 fix for controller build
  pkg/config/helm_values.go
  pkg/gits/github.go
  pkg/jx/cmd/get_env.go
  pkg/jx/cmd/get_preview.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/M

#3792 fix: lets default commitish to master if not specified
  pkg/gits/git_cli.go
Labels: approved, lgtm, size/XS

#3797 fix: support conditions other than true in questions
  pkg/environments/gitops.go
  pkg/surveyutils/jsonschema.go
  pkg/util/types.go
Labels: approved, lgtm, size/M

#3802 revert: shallow clone logic
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/M

#3805 fix: clone an actual revision
  pkg/jx/cmd/opts/helm.go
Labels: approved, lgtm, size/S

#3806 Workaround for failing pipelinerunner and fix for `jx upgrade app`
  pkg/apps/gitops.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/upgrade_apps_test.go
Labels: approved, lgtm, size/S

#3814 fix: add missing step values schema template
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_values_schema_template.go
Labels: approved, lgtm, size/XS
