Repository jenkins-x/jx, pull requests merged in 2019-11, with the labels that each got.

#6002 fix: use the template file when config file is not specified
  pkg/cmd/step/create/step_create_templated_config.go
Labels: approved, lgtm, size/XS

#6003 chore: remove people from OWNERS file who don't anymore contribute to jx
  OWNERS
Labels: approved, lgtm, size/S

#6008 fix(logs): Log metapipeline when generated pipeline is not yet running
  pkg/cmd/controller/controller_build.go
  pkg/cmd/get/get_build_logs.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
  pkg/logs/test_data/metapipeline_and_pending_generated/pipelineruns.yml
  pkg/logs/test_data/metapipeline_and_pending_generated/pods.yml
  pkg/logs/test_data/metapipeline_and_pending_generated/structures.yml
  pkg/logs/test_data/pod_with_failure/pipelineruns.yml
Labels: approved, lgtm, size/XL

#6013 fix: Set `.Requirements.repository` by default to "nexus"
  pkg/cmd/step/verify/step_verify_preinstall_test.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/M

#6012 feat: if we are using staging certs from letsencrypt lets skip the S…
  .secrets.baseline
  pkg/cmd/clients/factory.go
  pkg/cmd/clients/fake/fake_factory.go
  pkg/kube/vault/vault_factory.go
  pkg/kube/vault/vault_factory_test.go
Labels: approved, lgtm, size/M

#6015 fix: do not `brew tap caskroom/cask` when installing `gcloud` on macOS.
  pkg/cmd/opts/install.go
Labels: approved, lgtm, ok-to-test, size/XS

#5722 fix: Removing duplicate jx chart
  Chart.yaml
  templates/NOTES.txt
  templates/_helpers.tpl
  templates/release.yaml
  templates/service.yaml
  values.yaml
Labels: approved, lgtm, ok-to-test, size/M

#5994 feat: allow boot to correctly launch from a sha
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/M

#6028 fix: downstream boot config repo builds as teh GitHubApp.Enablede fie…
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/XS

#5988 chore: refactor `cmd` ginkgo tests
  pkg/cmd/get/get_activity_test.go
  pkg/cmd/get/get_preview_test.go
  pkg/cmd/testhelpers/cmd_test_helpers.go
Labels: approved, lgtm, size/M

#6030 fix(boot): Only update to version stream boot config if current is ancestor
  jx/bdd/boot-vault/ci.sh
  pkg/cmd/boot/boot.go
  pkg/cmd/boot/boot_integration_test.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
Labels: approved, lgtm, size/L

#6034 refactor: rename all auth config savers to auth config handlers to better reflect their purpose to load and save auth config from/into different sources
  pkg/auth/auth_config_service.go
  pkg/auth/configmap_vault_config_handler.go
  pkg/auth/configmap_vault_config_handler_test.go
  pkg/auth/file_config_handler.go
  pkg/auth/interfaces.go
  pkg/auth/memory_config_handler.go
  pkg/auth/memory_config_saver.go
  pkg/auth/mocks/auth_interface.go
  pkg/auth/types.go
  pkg/auth/vault_config_handler.go
  pkg/cmd/step/verify/test_data/preinstall/no_kaniko_or_terraform/jx-requirements.yml
  pkg/cmd/step/verify/test_data/preinstall/no_tls/jx-requirements.yml
  pkg/cmd/step/verify/test_data/preinstall/terraform_kaniko/jx-requirements.yml
  pkg/tests/helpers.go
Labels: approved, lgtm, size/L

#5720 fix: Adding clarity to git access error message
  pkg/gits/github.go
Labels: approved, lgtm, ok-to-test, size/XS

#5892 chore: Switch distro-specific strings to overrideable vars, not constants
  Makefile
  pkg/cmd/boot/boot.go
  pkg/cmd/opts/install.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/config/install_requirements.go
  pkg/util/downloads.go
  pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go
Labels: approved, lgtm, size/L

#5943 fix: Correct command name in output
  pkg/versionstream/resolver.go
  pkg/versionstream/version_data.go
Labels: approved, lgtm, ok-to-test, size/XS

#6027 fix: only use the base file path when loading the auth config from vault
  pkg/auth/vault_config_handler.go
Labels: approved, lgtm, size/XS

#6043 fix: remove typo
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/XS

#5857 feat: add the capability to configure exposer
  pkg/config/install_requirements.go
Labels: approved, lgtm, ok-to-test, size/XS

#5962 fix: Output language of git
  pkg/gits/git_cli.go
Labels: approved, lgtm, ok-to-test, size/XS

#5987 feat: use a yaml template to create resources for Vault through CloudFormation and use a provided user
  jx/bdd/boot-vault/ci.sh
  pkg/cloud/amazon/vault/vault_resources.go
  pkg/cmd/create/create_vault.go
  pkg/cmd/create/install.go
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/config/install_requirements.go
  pkg/config/zz_generated.deepcopy.go
  pkg/kube/vault/vault.go
Labels: approved, lgtm, size/L

#5991 chore(docs): fixing punctuation in README
  README.md
Labels: approved, lgtm, ok-to-test, size/M

#6053 fix: Don't use config.DefaultVersionsURL outside of version stream cloning logic
  pkg/cmd/create/create_addon_environment_controller.go
  pkg/cmd/create/create_vault.go
  pkg/cmd/get/get_stream.go
  pkg/cmd/scan_cluster.go
  pkg/cmd/step/get/step_get_version_changeset.go
Labels: approved, lgtm, size/M

#6054 fix: More consistent use of `gitRef` rather than `o.GitRef` in boot
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/S

#6047 fix: extract author info from commit
  pkg/gits/github.go
  pkg/gits/github_test.go
Labels: approved, lgtm, size/L

#6057 chore: Add builder-go-nodejs, switch BDD tests to use that image
  Dockerfile.builder-go-nodejs
  jenkins-x-boot-vault.yml
  jenkins-x-tekton.yml
  pkg/cmd/step/create/pr/step_create_pr_versions.go
Labels: approved, lgtm, size/S

#6063 feat: implement a generic mechanism to deprecate commands and marked a few commands as deprecated
  pkg/cmd/cmd.go
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/M

#6065 docs: fix a few links
  README.md
Labels: approved, lgtm, size/XS

#6078 fix: allow passing in of a git repo or PR URL for `jx get build log/pod`
  pkg/builds/build_info.go
  pkg/builds/build_info_test.go
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/get/get_build_pods.go
Labels: approved, lgtm, size/M

#6081 fix(build logs): allow to filter by `build_id`
  pkg/builds/build_info.go
Labels: approved, lgtm, size/XS

#6084 chore: Add --short option to jx step get dependency-version
  pkg/cmd/step/get/step_get_dependency_version.go
Labels: approved, lgtm, size/S

#6092 chore: Add resource request/limit to metapipeline
  pkg/tekton/metapipeline/metapipeline.go
Labels: approved, lgtm, size/S

#6093 fix(boot): Exclude all pipeline pods from pod ready check
  pkg/cmd/step/verify/step_verify_pod_ready.go
  pkg/cmd/step/verify/step_verify_pod_ready_test.go
Labels: approved, lgtm, size/L

#6087 chore: jx step report junit can handle both []<testsuite> and <testsuites> junit kind of reports
  pkg/cmd/step/report/step_report_junit.go
  pkg/cmd/step/report/step_report_junit_test.go
  pkg/cmd/step/report/test_data/junit/multiple_reports/ui_smoke.junit.xml
  pkg/cmd/step/report/test_data/junit/testsuites_report/ui_smoke.junit.xml
Labels: approved, lgtm, size/M

#6095 feat: allow to install on PKS
  pkg/cmd/add/add_app.go
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/create/step_create_values_test.go
  pkg/cmd/step/create/test_data/step_create_values/local_secrets_install/jx-requirements.yml
  pkg/cmd/step/create/test_data/step_create_values/local_secrets_install/parameters.tmpl.schema.json
  pkg/cmd/step/create/test_data/step_create_values/local_secrets_install/parameters.yaml.golden
  pkg/secreturl/localvault/client.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/ifThenElseTrueBoolean.test.schema.json
Labels: approved, lgtm, size/XL

#6062 fix: Don't include pipeline runs that failed/were retried by Prow in logs
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
  pkg/logs/test_data/active_single_run/pipelineruns.yml
  pkg/logs/test_data/failed_and_rerun/pipelineruns.yml
  pkg/logs/test_data/only_waiting_step/pipelineruns.yml
Labels: approved, lgtm, size/XL

#6069 fix: filter environments from delete application
  pkg/cmd/deletecmd/delete_application.go
  pkg/cmd/deletecmd/delete_application_test.go
Labels: approved, lgtm, size/M

#6118 fix: check also the commands which have children for deprecation
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/XS

#6119 docs: create Security Policy for Jenkins-X project
  SECURITY.md
Labels: approved, lgtm, size/S

#6125 fix: corrected regexp for pull-requests
  pkg/gits/git_url.go
Labels: approved, lgtm, size/XS

#6129 fix: support github app tokens better
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/M

#6130 fix: wrap Exposecontroller UrlTemplate config in quotes
  pkg/expose/exposecontroller.go
Labels: approved, lgtm, size/S

#6135 fix: add a helper method
  pkg/cmd/clients/factory.go
Labels: approved, lgtm, size/XS

#6104 fix: Add build number when displaying pipelines to stop
  pkg/cmd/stop/stop_pipeline.go
Labels: approved, lgtm, size/XS

#6134 fix: Support checking for updates in a gcloud bucket
  pkg/cmd/opts/install.go
Labels: approved, lgtm, size/S

#6139 feat: output GitHub app installation url
  pkg/cmd/create/create_quickstart.go
  pkg/cmd/importcmd/import.go
  pkg/github/github_app.go
Labels: approved, lgtm, size/L

#6144 fix: Return an error if upgrade boot gets a nil userAuth
  pkg/cmd/upgrade/upgrade_boot.go
Labels: approved, lgtm, size/XS

#6148 feat: checkout to the ref instead of FETCH_HEAD if ref is a branch
  pkg/gits/helpers.go
  pkg/versionstream/versionstreamrepo/gitrepo.go
Labels: approved, lgtm, size/M

#6150 fix: avoid possible exception
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/XS

#6149 fix: can't install an app with version containing letters like *SNAPSHOT*
  pkg/cmd/add/add_app_test.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
Labels: approved, lgtm, size/M

#6145 feat: implement cluster.interface for EKS
  pkg/cloud/amazon/aws_cli.go
  pkg/cloud/amazon/eks.go
  pkg/cluster/eks/clusterclient.go
  pkg/cluster/eks/clusterclient_test.go
  pkg/cluster/factory/factory.go
  pkg/cmd/create/create_cluster_eks.go
Labels: approved, lgtm, size/L

#6155 chore: Add ability to skip auto merging during `step create pr`
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/gits/operations/pull_request_op.go
Labels: approved, lgtm, size/M

#6156 fix: jx upgrade boot should use set-in-binary version stream ref as default
  pkg/cmd/upgrade/upgrade_boot.go
Labels: approved, lgtm, size/XS

#5926 feat: Completion for namespace and environment
  go.mod
  go.sum
  pkg/cmd/completion.go
  pkg/cmd/get/get_env.go
Labels: approved, lgtm, ok-to-test, size/M

#6166 docs: Fix typo. Remove '-' too much on --bucket-url
  pkg/cmd/step/step_stash.go
Labels: approved, lgtm, ok-to-test, size/XS

#6171 docs: Version Stream documentation links
  pkg/cmd/get/get_stream.go
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/versionstream/resolver.go
  pkg/versionstream/version_data.go
Labels: approved, lgtm, ok-to-test, size/S

#6175 chore: add some commands which were announced to be deprecated in the deprecation list
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/L

#6178 feat: added override for velero serviceaccount
  .secrets.baseline
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/L

#6177 fix: Add missing space between words
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, ok-to-test, size/XS

#6190 fix: corrected out of date TLS doc URL
  pkg/config/install_requirements.go
Labels: approved, lgtm, ok-to-test, size/XS

#6189 feat: add option to customise preview timeout
  pkg/cmd/preview/preview.go
Labels: approved, lgtm, ok-to-test, size/S

#6204 fix: Use debug image and /busybox/sh for /kaniko/executor
  boot-vault.prow.yaml.template
  myvalues.yaml.tekton.template
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/M

#6208 fix: update urls for contributor guidelines
  .github/pull_request_template.md
  docs/contributing/hacking.md
Labels: approved, lgtm, ok-to-test, size/XS

#6187 fix: only commit requirement upgrade files if changed
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
Labels: approved, lgtm, size/M

#6221 fix: add better error handling for missing git auth
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, size/S

#6220 fix: Correct use of AWS credentials for vault
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/cmd/step/helm/step_helm_apply.go
Labels: approved, lgtm, ok-to-test, size/XS

#6229 fix: make sure the cluster zone is stored in jx-install-config
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, do-not-merge/hold, lgtm, size/XS

#6222 chore: disable the initial build trigger if github app enabled as the…
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, size/S

#6216 chore: bring velero gcp serviceaccount suffix inline with others
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/XS

#6234 feat: when overriding TLS requirements lets update any specific envir…
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/XS

#6151 fix: do not force external dns on GKE cluster with custom domain
  pkg/cmd/step/create/step_create_install_values.go
Labels: approved, lgtm, ok-to-test, size/M

#6231 chore: add git file change tests
  pkg/gits/git_cli_test.go
Labels: approved, lgtm, size/M

#6227 chore: add some clarification on help messages from app commands to reduce confusion
  pkg/cmd/add/add_app.go
  pkg/cmd/deletecmd/delete_app.go
  pkg/cmd/get/get_apps.go
  pkg/cmd/upgrade/upgrade_apps.go
Labels: approved, lgtm, size/S

#6244 fix: create promote PR with labels
  pkg/environments/gitops.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
Labels: approved, lgtm, size/S

#6252 chore: Add more debug logging around log collection in build controller
  pkg/cloud/gke/gcloud.go
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, size/XS
