Repository jenkins-x/jx, pull requests merged in 2019-10, with the labels that each got.

#5653 fix: Stop updating jenkins-x-platform and prow charts from jx directly
  jx/scripts/update-bot.sh
Labels: approved, lgtm, size/XS

#5677 feat: adding Jenkins-x[bot] user
  pkg/cmd/step/verify/step_verify_git.go
  pkg/gits/github.go
Labels: approved, lgtm, size/XS

#5676 fix: increase linter deadline to 15 minutes
  hack/linter.sh
Labels: approved, lgtm, size/XS

#5678 docs: add CII Best Practicies badge
  README.md
Labels: approved, lgtm, size/XS

#5689 feat: passing user email temporarily on the subdomain call
  pkg/tenant/tenant.go
Labels: approved, lgtm, size/S

#5691 fix: Update existing PR before pushing in `jx step create pr`
  pkg/gits/helpers.go
Labels: approved, lgtm, size/S

#5688 fix: create PR on all jenkins-x.yml files
  pkg/cmd/step/create/pr/step_create_pr_versions.go
Labels: approved, lgtm, size/XS

#5693 feat: passing cluster with subdomain call
  pkg/cmd/create/install.go
  pkg/cmd/step/get/step_get_subdomain.go
  pkg/tenant/tenant.go
  pkg/tenant/tenant_test.go
Labels: approved, lgtm, size/S

#5694 fix: Use builder from version stream in release
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#5696 fix: allow bucket check to retry
  pkg/cloud/gke/gcloud.go
Labels: approved, lgtm, size/XS

#5692 fix: add better defaulting of the container registry
  pkg/cmd/step/create/step_create_values.go
Labels: approved, lgtm, size/L

#5697 fix: Set not-yet-really-running steps to Pending in PipelineActivity
  pkg/cmd/controller/controller_build.go
  pkg/cmd/controller/controller_build_test.go
  pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/activity.yml
  pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/pipelineruns.yml
  pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/pipelines.yml
  pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/pods.yml
  pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/structures.yml
  pkg/cmd/controller/test_data/controller_build/running_generated/expected/activity.yml
Labels: approved, lgtm, size/XXL

#5700 feat: allow control of jx diagnose output
  pkg/cmd/diagnose.go
Labels: approved, lgtm, size/M

#5709 chore: remove cloudbees addon which is now replaced by jx ui app
  pkg/cmd/create/create_addon.go
  pkg/cmd/create/create_addon_cloudbees.go
  pkg/cmd/deletecmd/delete_addon.go
  pkg/cmd/deletecmd/delete_addon_cloudbees.go
Labels: approved, lgtm, size/L

#5708 chore: remove sso addon which is replaced by jx-app-sso
  pkg/cmd/create/create_addon.go
  pkg/cmd/create/create_addon_sso.go
  pkg/cmd/deletecmd/delete_addon.go
  pkg/cmd/deletecmd/delete_addon_sso.go
Labels: approved, lgtm, size/L

#4443 fix: import GitLab repos with subgroups
  pkg/gits/git_url.go
  pkg/gits/git_url_test.go
Labels: approved, lgtm, ok-to-test, size/S

#5674 feat: allow annotations on ServiceAccount
  charts/jx/templates/serviceaccount.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#5710 fix: use non-boolean value to represent enabled
  pkg/cmd/step/step_override_requirements.go
Labels: approved, lgtm, size/XS

#5728 fix: 'jx step cluster label' now supports the --gke-project flag
  pkg/cmd/opts/clusters.go
Labels: approved, lgtm, size/S

#5733 fix: get promote working on bitbucket cloud
  pkg/gits/bitbucket_cloud.go
Labels: approved, lgtm, size/S

#5734 fix: Clean up "-dn" service accounts in e2e GC as well
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/XS

#5712 feat: add the JX build status badge
  README.md
Labels: approved, lgtm, size/XS

#5736 chore: Remove @dwnusbaum from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#5704 feat: enable IRSA when booting and create the defined policies and ServiceAccounts
  pkg/cloud/amazon/permissions.go
  pkg/cmd/opts/domain.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/L

#5741 fix: specify version stream for vault operator
  pkg/cmd/step/boot/step_boot_vault.go
Labels: approved, lgtm, size/XS

#5742 docs: add the Scheduler CRD
  docs/apidocs/config.yaml
Labels: approved, lgtm, size/XS

#5745 fix: prevent updates to bootConfigURL from being lost
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#5748 fix: Add "Signed-off-by:" to `jx step create pr` commit messages
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/create/pr/step_create_pr_quickstarts.go
  pkg/cmd/step/create/pr/step_create_pr_versions.go
  pkg/gits/operations/pull_request_op.go
  pkg/gits/operations/pull_request_op_test.go
Labels: approved, lgtm, size/M

#5750 chore: refactored update script into pipeline
  jenkins-x.yml
  jx/scripts/update-bot.sh
  jx/scripts/update-clients.sh
  jx/scripts/update-website.sh
Labels: approved, lgtm, size/L

#5747 feat: Move requirements record to TeamSettings
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_test.go
  pkg/config/install_requirements.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/L

#5752 fix: use the builder-go for the jxui-backend update
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#5740 feat: make step boot vault use the version stream defined in jx-requirements.yaml
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_test.go
Labels: approved, lgtm, size/M

#5758 fix: kuberhealthy err response
  pkg/health/health.go
Labels: approved, lgtm, size/XS

#5762 fix: upgrade pipeline uses new builder
  pkg/cmd/step/boot/step_boot.go
  pkg/cmd/step/boot/step_boot_upgrade.go
  pkg/cmd/upgrade/test_data/upgrade_boot_builders/jenkins-x-boot-config/jenkins-x.yml
  pkg/cmd/upgrade/test_data/upgrade_boot_builders/jenkins-x-versions/docker/gcr.io/jenkinsxio/builder-go.yml
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_test.go
Labels: approved, lgtm, size/L

#5765 fix: kuberhealthy protocol and authed redirect
  pkg/health/health.go
Labels: approved, lgtm, size/S

#5770 fix: Mark steps after a failed step as not executed in PipelineActivity
  pkg/cmd/controller/controller_build.go
  pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/pipelineruns.yml
  pkg/cmd/controller/test_data/controller_build/failed_metapipeline/cluster_state/pods.yml
  pkg/cmd/controller/test_data/controller_build/failed_metapipeline/expected/activity.yml
Labels: approved, lgtm, size/M

#5769 fix: log error if we can't find the git info in the current dir
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#5771 feat: gitPublic can be configured from jx-requirements
  .secrets.baseline
  pkg/cmd/step/step_override_requirements.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#5774 fix: change git command to determine lastest dev version
  Makefile
Labels: approved, lgtm, size/XS

#5643 fix: UI App BDD tests
  jx/bdd/boot-vault/ci.sh
  jx/bdd/tekton/ci.sh
Labels: approved, lgtm, size/XS

#5788 feat: set helm values for environment charts so that we can generate …
  pkg/cmd/create/install.go
  pkg/cmd/opts/upgrade/upgrade_ingress.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/config/helm_values.go
  pkg/config/helm_values_test.go
Labels: approved, lgtm, size/M

#5791 fix: missing organisation from SourceRepositries when importing repos…
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, size/XS

#5793 chore: existing boot clone should include requirements
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/M

#5808 fix(pipeline): Use version stream for default pipeline image
  pkg/tekton/metapipeline/metapipeline_test.go
  pkg/tekton/metapipeline/test_data/stable_versions/docker/gcr.io/jenkinsxio/builder-maven.yml
  pkg/tekton/syntax/constants.go
Labels: approved, lgtm, size/XS

#5809 chore: Remove golang-http quickstart from Tekton context
  jx/bdd/tekton/ci.sh
Labels: approved, lgtm, size/XS

#5795 fix: lookup boot config ref unless it's specified
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/M

#5803 feat: get the current region and cluster name differently so we avoid wrong regions due to misconfiguration
  pkg/cloud/amazon/common.go
  pkg/cloud/amazon/ecr.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/S

#5780 fix(activity): Properly handle unrun stages after a failure
  OWNERS
  pkg/cmd/controller/controller_build.go
  pkg/cmd/controller/controller_build_test.go
  pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/activity.yml
  pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/pipelineruns.yml
  pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/pipelines.yml
  pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/pods.yml
  pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/structures.yml
  pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/expected/activity.yml
Labels: approved, lgtm, size/XXL

#5783 fix(activity): Set activity status for manual promotions with Tekton
  pkg/cmd/controller/controller_workflow.go
  pkg/cmd/promote/promote.go
  pkg/kube/activity.go
  pkg/kube/activity_test.go
Labels: approved, lgtm, size/M

#5801 fix: make sure that the DNS API is enabled when running create domain gke command
  pkg/cmd/create/create_domain_gke.go
Labels: approved, lgtm, size/XS

#5792 fix: Fix create project typo in create_project.go
  pkg/cmd/create/create_project.go
Labels: approved, lgtm, ok-to-test, size/XS

#5799 fix: install latest micro in go module syntax
  pkg/cmd/create/create_micro.go
Labels: approved, lgtm, ok-to-test, size/XS

#5814 fix(activity): Don't panic for batch builds with PRs without activities
  pkg/kube/activity.go
  pkg/kube/activity_test.go
Labels: approved, lgtm, size/L

#5684 feat: Enable new stackdriver k8s monitoring
  pkg/cmd/create/create_cluster_gke.go
Labels: approved, lgtm, size/M

#5818 fix: fail-with-pod works with tekton logging
  pkg/cmd/get/get_build_logs.go
  pkg/logs/tekton_logging.go
Labels: approved, lgtm, size/L

#5825 fix: Stop creating jenkins-x-serverless PRs
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#5831 fix(logs): For completed builds, only check for pods that ran
  pkg/apis/jenkins.io/v1/types_pipelinestructure.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
  pkg/logs/test_data/metapipeline_failure/pipelineruns.yml
  pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/activity.yml
  pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/pipelineruns.yml
  pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/pipelines.yml
  pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/pods.yml
  pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/structures.yml
  pkg/logs/test_data/pipelineruns.yml
Labels: approved, lgtm, size/XXL

#5835 fix: add a better api docs generation
  Makefile.codegen
  docs/refdocs/config.json
  docs/refdocs/templates/.gitignore
Labels: approved, lgtm, size/M

#5823 fix: only create/update dev environment repo when within `jx boot`
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
Labels: approved, lgtm, size/M

#5832 feat: added step for tenant token
  .secrets.baseline
  pkg/cmd/step/get/step_get_tenant_token.go
  pkg/config/install_requirements.go
  pkg/tenant/tenant.go
  pkg/tenant/tenant_test.go
Labels: approved, lgtm, size/L

#5840 fix: initial commit message of duplicate git repo
  pkg/gits/helpers.go
Labels: approved, lgtm, size/XS

#5828 fix: Separate creation of pull request and adding labels
  pkg/cmd/create/create_pullrequest.go
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/environments/gitops.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/operations/pull_request_op.go
Labels: approved, lgtm, size/M

#5834 fix(logs): Get correct location For completed builds in GHE
  pkg/collector/git_collector.go
Labels: approved, lgtm, ok-to-test, size/S

#5859 fix: missing gitref when overriding default boot-config
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#5866 feat: add an option to boot command to override the default requirements file from repository
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/M

#5875 fix: default gitRef to master if not in default/specified version stream
  pkg/cmd/boot/boot.go
  pkg/cmd/boot/boot_test.go
  pkg/cmd/boot/test_data/jenkins-x-versions/git/github.com/jenkins-x/jenkins-x-boot-config.yml
  pkg/cmd/boot/test_data/requirements/jx-requirements.yml
Labels: approved, lgtm, size/L

#5870 fix: Revert PR 5110
  pkg/boot/constants.go
  pkg/cmd/boot/boot.go
  pkg/cmd/create/install.go
  pkg/cmd/opts/expose.go
  pkg/cmd/opts/helm.go
  pkg/cmd/opts/team_settings.go
  pkg/cmd/opts/upgrade/upgrade_ingress.go
  pkg/cmd/opts/version.go
  pkg/cmd/step/get/step_get_version_changeset.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/step/verify/step_verify_environments_test.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_integration_test.go
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_platform.go
  pkg/gits/git_cli.go
  pkg/gits/git_cli_test.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/versionstream/versionstreamrepo/gitrepo.go
  pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go
Labels: approved, lgtm, size/XXL

#5876 chore: functionalise cb profile setup
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/S

#5884 chore: remove github app command
  pkg/cmd/step.go
  pkg/cmd/step/github/step_github.go
  pkg/cmd/step/github/step_github_app.go
  pkg/cmd/step/github/step_github_app_token.go
  pkg/github/github_app.go
Labels: approved, lgtm, size/L

#5886 chore: support making the version stream upgrade ref configurable
  pkg/cmd/upgrade/upgrade_boot.go
Labels: approved, lgtm, size/S

#5864 chore: added a timer to display the time taken to verify the endpoint
  pkg/cmd/step/verify/step_verify_url.go
Labels: approved, lgtm, size/XS

#5895 chore: fix comment typo
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/XS

#5891 fix(pipeline): Use standard version stream cloning logic in metapipeline
  pkg/cmd/controller/pipeline/pipelinerunner_cmd.go
  pkg/cmd/start/start_pipeline.go
  pkg/tekton/metapipeline/clientfactory.go
  pkg/tekton/metapipeline/clientfactory_test.go
  pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go
Labels: approved, lgtm, size/L

#5904 feat: lets add a specific wait-for-chart step so that pipelines can w…
  pkg/cmd/step.go
  pkg/cmd/step/step_wait_for_chart.go
  pkg/cmd/step/step_wait_for_chart_test.go
Labels: approved, lgtm, size/L

#5849 feat: upgrade template builder images
  pkg/cmd/upgrade/test_data/upgrade_boot_builders/jenkins-x-boot-config/values.tmpl.yaml
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_test.go
  pkg/gits/git_cli.go
Labels: approved, lgtm, size/L

#5912 feat: added mergo to handle the differences between versions of jx-requirements.yml when upgrading a cluster
  go.mod
  go.sum
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_test.go
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
Labels: approved, lgtm, size/L

#5916 fix(pipeline): Add GIT_* env vars to non-pod template images
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/add-env-to-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/command-as-multiline-script/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/correct-pipeline-stage-is-removed/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/from_yaml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/pipeline-timeout/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/remove-stage-from-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/git/step_git_merge.go
  pkg/cmd/step/git/step_git_validate.go
  pkg/cmd/step/report/step_report_image_version.go
  pkg/cmd/step/step_release.go
  pkg/gits/helpers.go
  pkg/util/constants.go
Labels: approved, lgtm, size/L

#5824 test: adds get preview test
  pkg/cmd/get/get_preview_test.go
Labels: approved, lgtm, size/L

#5910 feat(pipeline): Allow activity for next build number and branch as revision
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/pipelineresources.yml
  pkg/tekton/metapipeline/client.go
  pkg/tekton/metapipeline/clientfactory.go
  pkg/tekton/metapipeline/metapipeline.go
  pkg/tekton/pipelines.go
  pkg/tekton/pipelines_test.go
  pkg/tekton/test_data/next_build_number/no_activities/activities.yml
  pkg/tekton/test_data/next_build_number/unparseable_build_number/activities.yml
  pkg/tekton/test_data/next_build_number/valid/activities.yml
Labels: approved, lgtm, size/XL

#5933 fix: git remote add fix
  pkg/gits/git_cli.go
Labels: approved, lgtm, size/XS

#5928 fix: Don't patch unnecessarily
  pkg/client/clientset/versioned/typed/jenkins.io/v1/app_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/buildpack_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/buildpack_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/commitstatus_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/commitstatus_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environment_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environment_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environmentrolebinding_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environmentrolebinding_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/extension_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/extension_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fact_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fact_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/gitservice_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/gitservice_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelinestructure_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelinestructure_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/plugin_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/plugin_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/release_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/release_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/sourcerepository_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/sourcerepository_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/team_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/team_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/user_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/user_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/workflow_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/workflow_expansion_test.go
Labels: approved, lgtm, ok-to-test, size/L

#5930 fix: Reducing and structuring the log output of `jx boot`
  pkg/cmd/boot/boot.go
  pkg/cmd/create/install.go
  pkg/cmd/opts/domain.go
  pkg/cmd/opts/helm.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/helm/step_helm.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/helm/step_helm_version.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/step/verify/step_verify_git.go
  pkg/cmd/step/verify/step_verify_install.go
  pkg/cmd/step/verify/step_verify_packages.go
  pkg/cmd/step/verify/step_verify_pod_ready.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_requirements.go
  pkg/kube/secrets.go
  pkg/log/log.go
  pkg/versionstream/versionstreamrepo/gitrepo.go
Labels: approved, lgtm, size/L

#5941 chore: reverting PR #5891 to return to custom version stream cloning
  pkg/cmd/controller/pipeline/pipelinerunner_cmd.go
  pkg/cmd/start/start_pipeline.go
  pkg/tekton/metapipeline/clientfactory.go
  pkg/tekton/metapipeline/clientfactory_test.go
Labels: approved, lgtm, size/L

#5946 fix: Delete and reclone version stream in case of non-fast-forward
  pkg/versionstream/versionstreamrepo/gitrepo.go
  pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go
Labels: approved, lgtm, size/L

#5954 feat: if using self signed certs from letsencrypt (typically during C…
  .secrets.baseline
  pkg/cmd/controller/controller_enviornmentcontroller.go
  pkg/cmd/opts/common.go
  pkg/cmd/opts/import.go
  pkg/cmd/opts/install.go
  pkg/cmd/update/update_webhooks.go
  pkg/gits/github.go
  pkg/gits/provider.go
  pkg/kube/certmanager.go
  pkg/kube/certmanager_test.go
Labels: approved, lgtm, size/L

#5787 feat: enable S3 as a LongTermStorage target and refactor code to work with two providers
  pkg/cloud/amazon/permissions.go
  pkg/cloud/amazon/storage/bucket_provider.go
  pkg/cloud/amazon/storage/bucket_provider_test.go
  pkg/cloud/buckets/default_provider.go
  pkg/cloud/buckets/interface.go
  pkg/cloud/buckets/mocks/buckets_interface.go
  pkg/cloud/factory/factory.go
  pkg/cloud/factory/factory_test.go
  pkg/cloud/factory/test_data/jx-requirements.yml
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/storage/bucket_provider.go
  pkg/cmd/controller/controller_build.go
  pkg/cmd/step/step_stash.go
  pkg/collector/bucket_collector.go
  pkg/collector/bucket_collector_test.go
  pkg/collector/helpers.go
  pkg/collector/test_data/collect_files/example.txt
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/XXL

#5944 fix: added function to generate projectNumber for gke in requirements
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/interface.go
  pkg/cloud/gke/mocks/gclouder.go
  pkg/cmd/step/step_override_requirements.go
Labels: approved, lgtm, size/M

#5961 fix: Don't lazily create SourceRepository for PipelineActivity
  pkg/kube/activity.go
  pkg/kube/activity_test.go
Labels: approved, lgtm, size/M

#5963 fix: Ignore tide context for last commit status on PRs
  pkg/gits/github.go
Labels: approved, lgtm, size/XS

#5970 test: update pegomock to version v2.7.0
  Makefile.codegen
  go.mod
  go.sum
  pkg/auth/mocks/auth_interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/cloud/buckets/mocks/buckets_interface.go
  pkg/cloud/gke/mocks/gclouder.go
  pkg/cmd/clients/mocks/factory.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/mocks/organisation_checker.go
  pkg/helm/mocks/helmer.go
  pkg/jxfactory/mocks/factory.go
  pkg/kube/mocks/kuber.go
  pkg/kube/resources/mocks/installer.go
  pkg/reportingtools/mocks/xunitclient.go
  pkg/secreturl/mocks/secreturl_client.go
  pkg/util/mocks/commander.go
  pkg/vault/mocks/vault_client.go
Labels: approved, lgtm, size/XXL

#5949 fix(boot): Try to update local boot clone to config ref from versions
  pkg/cmd/boot/boot.go
  pkg/cmd/boot/boot_integration_test.go
  pkg/gits/helpers.go
Labels: approved, lgtm, size/L

#5973 fix: Don't crash build controller for errors in labeling legacy resources
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, size/XS

#5959 feat: sort activities output
  pkg/cmd/get/get_activity.go
  pkg/cmd/get/get_activity_test.go
  pkg/cmd/testhelpers/cmd_test_helpers.go
  pkg/kube/activity_test.go
  pkg/kube/env.go
Labels: approved, lgtm, size/L

#5977 fix(boot): 'jx upgrade boot' needs to fetch upgrade boot config SHA before cherrypicking
  Makefile
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_integration_test.go
Labels: approved, lgtm, size/L

#5924 fix: Remove defunct CloudBees addon
  pkg/cmd/cmd.go
  pkg/cmd/login.go
  pkg/cmd/login_test.go
  pkg/cmd/ui/ui.go
  pkg/cmd/ui/ui_test.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/L

#5989 test: Use boot config release from version stream in boot-vault test
  jx/bdd/boot-vault/ci.sh
Labels: approved, lgtm, size/XS

#5995 fix: it can be hard to override booleans with terraform, we have used…
  pkg/cmd/step/step_override_requirements.go
Labels: approved, lgtm, size/XS
