Repository jenkins-x/jx, pull requests merged in 2019-01, with the labels that each got.

#2593 fix(login) : do not hard code the temp directory.
  go.sum
  pkg/jx/cmd/login.go
Labels: approved, lgtm, size/XS

#2590 Better error message
  pkg/jx/cmd/promote.go
Labels: approved, lgtm, ok-to-test, size/XS

#2594 Simpler check for local file modifications
  Jenkinsfile
Labels: approved, lgtm, size/XS

#2589 fix(compliance): print a user friendly message instead of a generic error message
  pkg/jx/cmd/compliance_results.go
Labels: approved, lgtm, size/XS

#2575 fix(gitops): get the gitops mode working in install command with vault and no-tiller
  go.sum
  pkg/auth/vault_config_saver.go
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/helper.go
  pkg/io/config_store.go
  pkg/jx/cmd/common_gke.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/upgrade_ingress.go
  pkg/kube/secrets.go
  pkg/vault/constants.go
  pkg/vault/vault_client.go
  pkg/vault/vault_path.go
Labels: approved, lgtm, size/L

#2602 fix: fixes the generation of Ingress with exposecontroller in staging
  pkg/config/helm_values.go
  pkg/jx/cmd/get_build_logs.go
  pkg/kube/pod.go
Labels: approved, lgtm, size/M

#2601 fix(ingress): Don't use empty strings in possible organisations
  pkg/gits/provider.go
Labels: approved, lgtm, size/XS

#2607 fix: jx step link service
  pkg/jx/cmd/step_link_services.go
Labels: approved, lgtm, size/M

#2605 fix(ingress): github webhooks weren't being updated on `jx upgrade ingress`
  pkg/gits/github.go
  pkg/gits/provider.go
  pkg/jx/cmd/update_webhooks.go
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, size/S

#2609 fix(install): use http redirects to get latest github releases
  pkg/util/downloads.go
  pkg/util/downloads_test.go
Labels: approved, lgtm, size/L

#2611 feat(upgrade) add a command to upgrade prow which handles if knative build is not on 0.2.x
  go.mod
  go.sum
  pkg/jx/cmd/create_addon_knative_build.go
  pkg/jx/cmd/delete_addon_knative_build.go
  pkg/jx/cmd/upgrade_addon_prow.go
  pkg/jx/cmd/upgrade_addons.go
Labels: approved, lgtm, size/L

#2613 allow new knative chart version to be passed as a flag
  pkg/jx/cmd/upgrade_addon_prow.go
Labels: approved, lgtm, size/M

#2619 fix: add a helper step for exposing secret values as env vars/files
  Jenkinsfile
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_credential.go
  pkg/kube/env.go
  pkg/util/suggestions.go
Labels: approved, lgtm, size/L

#2596 Slow startup
  cmd/jx/app/jx.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd.go
  pkg/jx/cmd/cmd_test.go
  pkg/jx/cmd/create_docs.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/templates/templater.go
  pkg/jx/cmd/upgrade_apps.go
  pkg/tests/console_wrapper.go
Labels: approved, lgtm, size/L

#2615 Pass kube client in ProwOptions
  pkg/jx/cmd/start_pipeline.go
Labels: approved, lgtm, size/XS

#2629 fix(gc) lets clean up stale pull request activities too
  pkg/jx/cmd/create_addon_knative_build.go
  pkg/jx/cmd/create_addon_prow.go
  pkg/jx/cmd/gc_activities.go
Labels: approved, lgtm, size/S

#2621 chore: Correct updatebot regex for prow charts repo.
  Makefile
Labels: approved, lgtm, size/XS

#2623 bug(create environment): Create new environments in GitHub org.
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/auth/auth_config.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/kube/env.go
Labels: approved, lgtm, size/M

#2645 [fix] Typo: jenkinx-x
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#2618 fix(helm): Passwords for helm repos were logged in plaintext to the command line
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/helm/mocks/helmer_fake.go
  pkg/jx/cmd/common_helm.go
  pkg/jx/cmd/create_addon_ambassador.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/edit_extensionsrepository.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/util/commands.go
Labels: approved, lgtm, size/L

#2625 Correct aligment in jx get applications
  pkg/jx/cmd/get_applications.go
Labels: approved, ok-to-test, size/L

#2649 feat: ask questions based on JSON schema
  go.mod
  go.sum
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/init.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/validators.go
  pkg/surveyutils/validators_test.go
  pkg/util/types.go
  pkg/util/validators.go
Labels: approved, lgtm, size/XXL

#2654 fix: use correct repo/org for step collect
  pkg/jx/cmd/step_collect.go
Labels: approved, lgtm, size/M

#2635 feat(ingress): add option to wait for TLS certificates until are issued by cert-manager
  go.mod
  go.sum
  pkg/expose/exposecontroller.go
  pkg/helm/helm_template.go
  pkg/helm/helm_template_test.go
  pkg/helm/test_data/multi_objects/objects.yaml
  pkg/helm/test_data/multi_objects/objects_separator.yaml
  pkg/helm/test_data/multi_objects/single_object.yaml
  pkg/helm/test_data/multi_objects/single_object_separator.yaml
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/get_secret.go
  pkg/jx/cmd/get_vault_config.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/upgrade_ingress.go
  pkg/jx/cmd/upgrade_ingress_test.go
  pkg/kube/env.go
  pkg/kube/pki/certificate.go
  pkg/kube/pki/certificate_test.go
  pkg/kube/services/services.go
  pkg/kube/vault/vault_factory.go
Labels: approved, lgtm, size/XXL

#2639 Custom marshaler
  pkg/apis/jenkins.io/v1/types_users.go
Labels: approved, lgtm, size/M

#2631 fixed typo in common_helm.go - renamed chat to chart
  pkg/jx/cmd/common_helm.go
Labels: approved, lgtm, ok-to-test, size/XS

#2630 fix ChartMuseum casing
  pkg/config/admin_secrets.go
  pkg/jx/cmd/install.go
  pkg/kube/constants.go
  pkg/vault/constants.go
Labels: approved, lgtm, ok-to-test, size/S

#2659 [feat] Jenkins API token redux
  pkg/jenkins/utils.go
  pkg/jx/cmd/create_jenkins_token.go
Labels: approved, lgtm, size/L

#2646 fix: add caching into the build number generator
  pkg/buildnum/build_num_gen.go
  pkg/jx/cmd/serve_buildnumbers.go
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_next_buildnumber.go
  pkg/kube/activity.go
  pkg/kube/activity_test.go
  pkg/kube/pipeline_cache.go
  pkg/util/strings.go
Labels: approved, lgtm, size/L

#2665 feat(cli): add --no-comment flag to `jx preview` cmd
  pkg/jx/cmd/preview.go
Labels: approved, lgtm, ok-to-test, size/XS

#2666 fix: add better error reporting
  pkg/jx/cmd/step_helm_release.go
Labels: approved, lgtm, size/XS

#2667 chore: fix wrong command argument description
  pkg/jx/cmd/import.go
Labels: approved, lgtm, size/XS

#2642 chore: Add a CRD for storing application('project') metadata
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_sourcerepository.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/sourcerepository.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/sourcerepository.go
  pkg/client/listers/jenkins.io/v1/Readme.md
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/client/listers/jenkins.io/v1/sourcerepository.go
  pkg/jx/cmd/get_applications.go
  pkg/jx/cmd/import.go
  pkg/kube/crds.go
  pkg/prow/config/branch_protection.go
  pkg/prow/config/types.go
  pkg/prow/prow_test.go
  pkg/util/git.go
  pkg/util/git_test.go
Labels: approved, lgtm, size/XL

#2670 fix(buildnum): Services fails on repos with underscores
  pkg/kube/activity.go
Labels: approved, lgtm, size/XS

#2672 chore(tests) : do not hardcode the temp directory
  pkg/helm/helm_cli_test.go
Labels: approved, lgtm, size/XS

#2673 bug: fix typo in sourcerepositories CRD name which causes registration to fail
  pkg/kube/crds.go
Labels: approved, lgtm, size/XS

#2676 fix: improve proxy configuration
  pkg/util/http_utils.go
Labels: approved, lgtm, size/XS

#2678 plugins do not work on windows - so for now ignore the test.
  pkg/extensions/plugins_test.go
Labels: approved, lgtm, size/XS

#2671 feat: unalias `jx delete app`
  pkg/jx/cmd/delete_application.go
Labels: approved, lgtm, size/S

#2658 feat(applications): Use the new `applications` CRD to store metadata about applications.
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/import.go
  pkg/sourcerepository/interface.go
  pkg/sourcerepository/mocks/matchers/ptr_to_v1_sourcerepository.go
  pkg/sourcerepository/mocks/sourcerepository.go
  pkg/sourcerepository/sourcerepository.go
Labels: approved, size/L

#2679 chore(build) add missing go.sum entries
  go.sum
Labels: approved, lgtm, size/XS

#2680 Delete1
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/delete_app_test.go
  pkg/util/suggestions.go
Labels: approved, lgtm, size/L

#2693 feat(devpod): added --username flag to get/delete devpod
  pkg/jx/cmd/common_devpod.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/delete_devpod.go
  pkg/jx/cmd/get_devpod.go
  pkg/jx/cmd/start_pipeline.go
  pkg/kube/pod.go
Labels: approved, lgtm, size/M

#2700 [WIP] Add flag to auto detect repo and owner from current dir
  pkg/jx/cmd/get_build_logs.go
Labels: approved, lgtm, ok-to-test, size/S

#2698 Fix import crash
  pkg/jx/cmd/import.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, ok-to-test, size/S

#2702 Chore: add some docs
  cmd/jx/jx.go
Labels: approved, lgtm, size/XS

#2690 feat: extract a generic user resolver
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/step_changelog.go
  pkg/users/git.go
  pkg/users/users.go
Labels: approved, lgtm, size/L

#2709 Upgraded eksctl version
  pkg/binaries/binaries.go
Labels: approved, lgtm, ok-to-test, size/XS

#2692 feat(teams) store the admin namespace in the team
  pkg/jx/cmd/controller_team.go
  pkg/kube/teams.go
  pkg/kube/teams_test.go
Labels: approved, lgtm, size/L

#2708 feat(pipelineactivities): label pipeline activities with repo, owner and branch
  go.mod
  go.sum
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/kube/activity.go
Labels: approved, lgtm, size/M

#2713 general housekeeping, removing old code
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_report.go
  pkg/jx/cmd/step_report_activities.go
  pkg/jx/cmd/step_report_releases.go
Labels: approved, lgtm, size/L

#2710 feat: refactor to allow entire template to be modified
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/common_environments.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/test_helpers.go
  pkg/jx/cmd/upgrade_apps.go
  pkg/util/files.go
Labels: approved, lgtm, size/L

#2668 fix(preview): when deleting the preview, also purge the helm release
  charts/jx/templates/clusterrolebinding.yaml
  charts/jx/templates/cronjob.yaml
  charts/jx/templates/deployment.yaml
  charts/jx/templates/rolebinding.yaml
  charts/jx/templates/serviceaccount.yaml
  charts/jx/values.yaml
  pkg/jx/cmd/common.go
  pkg/jx/cmd/delete_preview.go
  pkg/jx/cmd/gc_previews.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
  pkg/kube/constants.go
  pkg/kube/env.go
  pkg/kube/env_test.go
Labels: approved, lgtm, ok-to-test, size/L

#2717 Made delete_eks lint-friendly. Added extra comments.
  pkg/jx/cmd/delete.go
  pkg/jx/cmd/delete_eks.go
Labels: approved, lgtm, ok-to-test, size/S

#2718 fix: re-add support for `jx start protection`
  pkg/jx/cmd/start_protection.go
  pkg/jx/cmd/start_protection_test.go
  pkg/prow/config/branch_protection.go
Labels: approved, lgtm, size/M

#2719 fix: add support for `jx step unstash` to fetch files from storage
  pkg/cloud/buckets/buckets.go
  pkg/cloud/buckets/buckets_test.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/edit_storage.go
  pkg/jx/cmd/get_storage.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_stash.go
  pkg/jx/cmd/step_stash_integration_test.go
  pkg/jx/cmd/step_unstash.go
  pkg/tests/files.go
Labels: approved, lgtm, size/L

#2720 feat(updatebot) expose a flag to enable to DisableMaven functionality in import
  pkg/jx/cmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#2722 Allow to checkout a different branch while running bdd tests
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, ok-to-test, size/M

#2731 fix: attempt at fixing getting user by git signature
  pkg/jx/cmd/step_changelog.go
  pkg/users/git.go
  pkg/users/git_test.go
  pkg/users/users.go
Labels: approved, lgtm, size/L

#2735 using the recently built binary when generating changelog
  Makefile
Labels: size/XS

#2727 fix(install): make sure that a domain is configured even when the skip-ingress option is active
  pkg/jx/cmd/common_domain.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/step_buildpack_apply_integration_test.go
  pkg/jx/cmd/step_stash_integration_test.go
Labels: approved, lgtm, size/XL

#2733 feat: generate `values.yaml` from a directory tree
  pkg/helm/values_tree.go
  pkg/helm/values_tree_test.go
  pkg/util/types.go
Labels: approved, lgtm, size/L

#2738 fix (import) : Select Git Repository first
  go.mod
  pkg/jx/cmd/create_spring.go
  pkg/jx/cmd/import.go
Labels: approved, lgtm, size/M

#2737 fix(upgrade ingress): apply the cert-manager annotation after clearing the annotations
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, size/S

#2716 chore: implement lazy creation of sourcerepository objects
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/promote_test.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/step_post_run.go
  pkg/jx/cmd/step_pre_extend.go
  pkg/jx/cmd/step_stash.go
  pkg/jx/cmd/test_helpers.go
  pkg/kube/activity.go
  pkg/kube/activity_test.go
  pkg/sourcerepository/sourcerepository.go
Labels: approved, lgtm, size/L

#2707 AWS region should be remembered in ConfigMap and read on import
  pkg/cloud/amazon/ecr.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/step_pre_build.go
  pkg/kube/constants.go
  pkg/kube/jx_install_config.go
Labels: approved, lgtm, ok-to-test, size/L

#2742 fix: don’t create a new JXClient, use the existing one
  pkg/users/git_test.go
Labels: approved, lgtm, size/XS

#2744 fix: never create a new kube client or jx client
  pkg/jx/cmd/common_plugins.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/delete_extension.go
  pkg/jx/cmd/gc_previews.go
  pkg/jx/cmd/get_activity.go
  pkg/jx/cmd/get_applications.go
  pkg/jx/cmd/get_issue.go
  pkg/jx/cmd/serve_buildnumbers.go
  pkg/jx/cmd/step_changelog.go
  pkg/jx/cmd/step_next_buildnumber.go
  pkg/jx/cmd/step_post_run.go
  pkg/jx/cmd/step_stash.go
  pkg/jx/cmd/upgrade_extensions.go
Labels: approved, lgtm, size/M

#2746 EKS resources should be tagged as created by jx by default
  pkg/jx/cmd/create_cluster_eks.go
Labels: approved, lgtm, ok-to-test, size/XS

#2747 Fixed lint errors for eks
  pkg/cloud/amazon/eks.go
Labels: approved, lgtm, ok-to-test, size/S

#2753 fix: lets not fail if there is no `.gitignore` when importing a project
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/create_spring.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_bdd.go
Labels: approved, size/M

#2757 fix: allow ReadURL to work with private repositories with git based URLs
  Dockerfile.builder-maven
  pkg/cloud/buckets/buckets.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_unstash.go
Labels: approved, lgtm, size/M

#2758 feat: add `GitLocal` for tests
  pkg/gits/git_local.go
Labels: approved, lgtm, size/L

#2755 Please merge fix
  pkg/jenkinsfile/pipeline.go
Labels: approved, lgtm, ok-to-test, size/XS

#2762 fix: mark some tests as parallelizable
  pkg/helm/values_tree_test.go
  pkg/users/git_test.go
Labels: approved, lgtm, size/XS

#2772 fix: use the :latest image for docker builds
  Dockerfile.builder-maven
  Dockerfile.jenkins-maven
Labels: approved, lgtm, size/XS

#2767 improve install config capture + refactor bucket create code
  pkg/jx/cmd/common_bucket.go
  pkg/jx/cmd/create_cluster_aws.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/edit_storage.go
  pkg/jx/cmd/install.go
  pkg/kube/constants.go
  pkg/kube/jx_install_config.go
Labels: approved, lgtm, size/L

#2775 fix: improve the glob behaviour of Collector
  pkg/collector/bucket_collector.go
  pkg/collector/git_collector.go
  pkg/util/files.go
  pkg/util/files_test.go
  pkg/util/test_data/glob_test/artifacts/goodbye.txt
  pkg/util/test_data/glob_test/hello.txt
Labels: approved, lgtm, size/L

#2773 fix(upgrade ingress): get the upgrade ingress command working in batch mode with and without TLS
  pkg/jx/cmd/common_cert_manager.go
  pkg/jx/cmd/upgrade_ingress.go
  pkg/kube/pki/certificate.go
  pkg/kube/services/services.go
Labels: approved, lgtm, size/L

#2776 chore: start to write tests for jsonschema
  pkg/jx/cmd/add_app.go
  pkg/surveyutils/basicTypes.test.schema.json
  pkg/surveyutils/constValues.test.schema.json
  pkg/surveyutils/defaultValues.test.schema.json
  pkg/surveyutils/descriptionAndTitle.test.schema.json
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/objectType.test.schema.json
  pkg/surveyutils/validators.go
Labels: approved, lgtm, size/L

#2778 feat(gke) added options to use premptible VMs in the node-pool
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/M

#2780 chore: tests for lots of validators for jsonschema
  pkg/surveyutils/exclusiveMaximum.test.schema.json
  pkg/surveyutils/exclusiveMinimum.test.schema.json
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/maxLength.test.schema.json
  pkg/surveyutils/maximum.test.schema.json
  pkg/surveyutils/minLength.test.schema.json
  pkg/surveyutils/minProperties.test.schema.json
  pkg/surveyutils/minimum.test.schema.json
  pkg/surveyutils/multipleOf.test.schema.json
  pkg/surveyutils/pattern.test.schema.json
  pkg/surveyutils/required.test.schema.json
  pkg/surveyutils/validators.go
Labels: approved, lgtm, size/L

#2789 feat: make it easy to add enhanced scopes to GKE clusters
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/M

#2795 fix(sso): update the default namespace and wait for dex certificate to be issued
  pkg/jx/cmd/create_addon_sso.go
Labels: approved, lgtm, size/S

#2801 fix(sourcerepositories): added missing list type
  pkg/apis/jenkins.io/v1/register.go
Labels: approved, lgtm, size/XS

#2803 fix: improve the jx step bdd so it can create clusters
  pkg/jx/cmd/bdd/bdd_clusters.go
  pkg/jx/cmd/create_git_user.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete_preview.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/L

#2794 Initialize jxclient
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/step_post_run.go
Labels: approved, lgtm, size/S

#2790 chore: update the GitHub issue template with Jenkins installation type
  .github/issue_template.md
Labels: approved, lgtm, size/S

#2797 feat(ingress): define a new flag in the upgrade ingress command which allows to specify the namespace where the ingress config is stored
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, size/S

#2805 chore: add more tests for jsonschema
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/basicTypes.test.schema.json
  pkg/surveyutils/test_data/basicTypesValidation.test.schema.json
  pkg/surveyutils/test_data/constValues.test.schema.json
  pkg/surveyutils/test_data/date.test.schema.json
  pkg/surveyutils/test_data/dateTime.test.schema.json
  pkg/surveyutils/test_data/defaultValues.test.schema.json
  pkg/surveyutils/test_data/descriptionAndTitle.test.schema.json
  pkg/surveyutils/test_data/email.test.schema.json
  pkg/surveyutils/test_data/exclusiveMaximum.test.schema.json
  pkg/surveyutils/test_data/exclusiveMinimum.test.schema.json
  pkg/surveyutils/test_data/hostname.test.schema.json
  pkg/surveyutils/test_data/idnemail.test.schema.json
  pkg/surveyutils/test_data/idnhostname.test.schema.json
  pkg/surveyutils/test_data/ipv4.test.schema.json
  pkg/surveyutils/test_data/ipv6.test.schema.json
  pkg/surveyutils/test_data/jsonPointer.test.schema.json
  pkg/surveyutils/test_data/maxLength.test.schema.json
  pkg/surveyutils/test_data/maxProperties.test.schema.json
  pkg/surveyutils/test_data/maximum.test.schema.json
  pkg/surveyutils/test_data/minLength.test.schema.json
  pkg/surveyutils/test_data/minProperties.test.schema.json
  pkg/surveyutils/test_data/minimum.test.schema.json
  pkg/surveyutils/test_data/multipleOf.test.schema.json
  pkg/surveyutils/test_data/objectType.test.schema.json
  pkg/surveyutils/test_data/pattern.test.schema.json
  pkg/surveyutils/test_data/required.test.schema.json
  pkg/surveyutils/test_data/time.test.schema.json
  pkg/surveyutils/test_data/uri.test.schema.json
  pkg/surveyutils/test_data/uriReference.test.schema.json
  pkg/surveyutils/validators.go
  pkg/tests/helpers.go
Labels: approved, lgtm, size/XL

#2808 fix: broken git file location for Collector
  pkg/collector/git_collector.go
Labels: approved, lgtm, size/S

#2809 Chore: add some test for apps when not using gitops
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/helm/mocks/helmer_fake.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/app_test_helpers.go
  pkg/jx/cmd/delete_app_test.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_helm_install.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_apps.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/L

#2812 chore: extract CreateAddRequirementFn
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/common_environments.go
Labels: approved, lgtm, size/XL

#2796 fix: prompting for Serverless/Static before generating helm values
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/S

#2813 feat: generate values.yaml from tree during `jx step helm apply`
  pkg/jx/cmd/step_helm_apply.go
Labels: approved, lgtm, size/S

#2821 fix: avoid failing create project if no GitService
  pkg/helm/helm_template.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_install.go
  pkg/kube/git_services.go
Labels: approved, lgtm, size/S

#2823 Upgraded eksctl version
  pkg/binaries/binaries.go
Labels: approved, lgtm, ok-to-test, size/XS

#2822 fix: oops, bad refactor on 20df278c909a9fc1a5c1abd41f027f30d3c998a5
  pkg/jx/cmd/common_git.go
Labels: approved, lgtm, size/XS

#2824 fix: allow `jx get build logs jobName` to be used with prow
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/promote.go
Labels: approved, lgtm, size/M

#2831 fix: adding authentication for mirror repository
  pkg/config/admin_secrets.go
  pkg/config/admin_secrets_test.yaml
Labels: approved, lgtm, size/M

#2825 Various fixes to improve the way we do serverless builds
  Jenkinsfile
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/step_changelog.go
Labels: approved, lgtm, size/L

#2836 fix: unbreak the pipeline CRD
  pkg/apis/jenkins.io/v1/types_pipeline.go
Labels: approved, lgtm, size/S

#2840 fix: add test case and fix for failure in BDD create cluster tests
  pkg/kube/git_services.go
  pkg/kube/git_services_test.go
Labels: approved, lgtm, size/M

#2842 fix: defaulting to disable legacy auth, to be consistent with jx create cluster gke
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/XS

#2771 fix (import) : Select Git Repository first
  pkg/jx/cmd/create_quickstart.go
  pkg/jx/cmd/create_spring.go
  pkg/jx/cmd/import.go
  pkg/quickstarts/model.go
Labels: approved, lgtm, size/M

#2850 fix: wait for each init container to start in `jx get build log`
  pkg/jx/cmd/get_build_logs.go
  pkg/kube/pod.go
Labels: approved, lgtm, size/M

#2841 feat(upgrade platform) upgrade platform is more consistent in how it deals with secrets
  pkg/config/admin_secrets.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/M

#2859 fixes for the new BDD test suite
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/step_bdd.go
  pkg/util/strings.go
Labels: approved, lgtm, size/L

#2854 fix: updated order of upgrade platform
  pkg/config/admin_secrets.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/M

#2826 fix(install): wait for vault to be initialized and unsealed before retrieving the auth token
  pkg/kube/vault/vault_factory.go
Labels: approved, lgtm, size/M

#2848 fix(upgrade ingress): pass the whitelisted services to the expose controller
  pkg/jx/cmd/common.go
Labels: approved, lgtm, size/S

#2804 feat(create user): add new flag to User CRD to enable serviceaccount.
  pkg/apis/jenkins.io/v1/types_users.go
  pkg/jx/cmd/create_user.go
Labels: approved, lgtm, size/S

#2880 chore: try add a CI script for easy invocation in knative build/pipeline
  jx/scripts/ci.sh
Labels: size/M

#2745 Make bdd reports optional
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#2885 chore: fix ci.sh script
  jx/scripts/ci.sh
Labels: size/XS

#2726 `delete aws` command should wait for gateway address unmapping
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_retry_test.go
  pkg/jx/cmd/delete_aws.go
Labels: approved, lgtm, size/L

#2886 use the correct env var for the build id
  jx/scripts/ci.sh
Labels: approved, lgtm, size/S

#2892 feat: add liveness & readiness probe endpoints to build number service.
  pkg/buildnum/build_num_gen.go
  pkg/buildnum/http_build_num.go
  pkg/buildnum/interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/kube/pipeline_cache.go
Labels: approved, lgtm, size/M

#2893 fix(issuer): do not regenerate issuers if it is not needed
  pkg/kube/pki/cert-manager.go
Labels: approved, lgtm, size/M

#2883 bug: validate webhook url when setting up GitHub webhooks.
  pkg/gits/github.go
Labels: approved, lgtm

#2896 fix(vault): search the system vault in the dev namespace when creating the client
  pkg/jx/cmd/factory.go
Labels: approved, lgtm, size/XS

#2887 chore(bitbucket): Update client lib and refactor to accomodate breaki…
  go.mod
  go.sum
  pkg/gits/bitbucket_cloud.go
Labels: approved, size/S

#2902 Mention `jx shell` during installation
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#2905 fix: need to set job type
  pkg/jx/cmd/start_pipeline.go
Labels: approved, lgtm, size/XS

#2904 Refactor/simplify build number controller to reduce chance of deadlocks
  Makefile
  pkg/buildnum/build_num_gen.go
  pkg/buildnum/http_build_num_soak_test.go
  pkg/kube/pipeline_cache.go
Labels: approved, lgtm, size/L

#2903 fix(install): some fixes to get the install working on a fresh cluster in batch mode with gitops and vault
  pkg/auth/mocks/auth_interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/mocks/organisation_checker.go
  pkg/gits/mocks/organisation_lister.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/get_secret.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/kube/jx_install_config.go
  pkg/kube/jx_install_config_test.go
  pkg/kube/mocks/kuber.go
  pkg/kube/mocks/matchers/ptr_to_v1_sourcerepository.go
  pkg/kube/mocks/matchers/ptr_to_v1_sourcerepositorylist.go
  pkg/kube/mocks/sourcerepoer.go
  pkg/kube/resources/mocks/installer.go
  pkg/kube/sourcerepository_interface.go
  pkg/util/mocks/commander.go
Labels: approved, lgtm, size/XL

#2901 Use chyle upstream
  go.mod
  go.sum
  pkg/jx/cmd/step_changelog.go
Labels: approved, lgtm, size/S

#2882 Fixed lint errors / added documentation
  pkg/util/cache.go
Labels: approved, lgtm, ok-to-test, size/XS

#2881 Added Java11 POM detection
  pkg/jx/cmd/common_buildpacks.go
  pkg/util/pom_flavour.go
  pkg/util/pom_flavour_test.go
Labels: approved, lgtm, ok-to-test, size/M

#2899 fix(certs): always wait for certs
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, size/XS

#2895 jx should control kubectl version it is using
  pkg/binaries/binaries.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/upgrade_binaries.go
Labels: approved, lgtm, ok-to-test, size/L

#2878 feat: create Flagger addon for canary deployments
  pkg/jx/cmd/create_addon.go
  pkg/jx/cmd/create_addon_flagger.go
  pkg/kube/constants.go
Labels: approved, lgtm, ok-to-test, size/L

#2897 feat(certs): wait for certificate issuer on create addon cb
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/delete_addon_cloudbees.go
  pkg/kube/pki/certificate.go
Labels: approved, lgtm, size/M

#2930 refactor: added category 'all' to CRDs
  pkg/jx/cmd/step_changelog.go
  pkg/kube/crds.go
Labels: approved, lgtm, ok-to-test, size/S

#2915 Add all extensions
  pkg/jx/cmd/step_pre_extend.go
Labels: approved, lgtm, size/XS

#2913 Tests for `jx add app` with vault
  pkg/apis/jenkins.io/v1/register.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/password.test.schema.json
  pkg/surveyutils/test_data/token.test.schema.json
  pkg/vault/mocks/matchers/map_of_string_to_interface.go
  pkg/vault/mocks/matchers/slice_of_string.go
  pkg/vault/mocks/matchers/url_url.go
  pkg/vault/mocks/vault_client.go
  pkg/vault/vault_client.go
Labels: approved, lgtm, size/XL

#2929 fix: use the version of pegomock from `go.mod`
  Makefile
  pkg/auth/mocks/auth_interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/mocks/organisation_checker.go
  pkg/gits/mocks/organisation_lister.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/mocks/matchers/versioned_interface.go
  pkg/kube/mocks/kuber.go
  pkg/kube/mocks/sourcerepoer.go
  pkg/kube/resources/mocks/installer.go
  pkg/util/mocks/commander.go
  pkg/vault/mocks/vault_client.go
Labels: approved, lgtm, size/XL

#2932 fix: use the newly built jx to generate docs
  Makefile
Labels: approved, lgtm, size/XS

#2924 initial spike at jx step create task that works
  pkg/auth/mocks/auth_interface.go
  pkg/buildnum/mocks/build_num.go
  pkg/builds/build_info.go
  pkg/builds/build_number.go
  pkg/builds/build_number_test.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/mocks/organisation_checker.go
  pkg/gits/mocks/organisation_lister.go
  pkg/helm/mocks/helmer.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/factory.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/interface.go
  pkg/jx/cmd/mocks/factory.go
  pkg/jx/cmd/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_buildpack_apply_test.go
  pkg/jx/cmd/step_create_buildtemplate.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_get.go
  pkg/jx/cmd/step_get_buildnumber.go
  pkg/jx/cmd/step_helm_release.go
  pkg/kpipelines/constants.go
  pkg/kpipelines/pipelines.go
  pkg/kube/configmap.go
  pkg/kube/containers.go
  pkg/kube/envvar.go
  pkg/kube/mocks/kuber.go
  pkg/kube/mocks/sourcerepoer.go
  pkg/kube/resources/mocks/installer.go
  pkg/kube/volumes.go
  pkg/util/commands.go
  pkg/util/maps.go
  pkg/util/mocks/commander.go
  pkg/vault/mocks/vault_client.go
Labels: approved, lgtm, size/XXL

#2922 Removed Ian Wood
  OWNERS
Labels: approved, lgtm, size/XS

#2891 Issue and PR comments for Bitbucket Cloud
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_cloud_test.go
  pkg/gits/test_data/bitbucket_cloud/issue-comments.issue-1.json
  pkg/gits/test_data/bitbucket_cloud/pullrequests.test-comment.json
Labels: approved, lgtm, size/L

#2944 Mem2
  Makefile
Labels: approved, lgtm, size/XS

#2940 Fix: switch to using AST to add import
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/client/openapi/core/openapi_generated.go
  pkg/client/openapi/k8s_io_apimachinery_intstr_unversioned/openapi_generated.go
  pkg/jx/cmd/create_client_openapi.go
  pkg/kube/client_generator.go
Labels: approved, lgtm, size/L

#2947 add pipelinerun controller for Prow + knative pipeline
  pkg/builds/build_info.go
  pkg/builds/build_number.go
  pkg/jx/cmd/controller.go
  pkg/jx/cmd/controller_buildnumbers.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/step_create_task.go
  pkg/kube/constants.go
  pkg/kube/metadata.go
Labels: approved, lgtm, size/L

#2935 chore: pin the version of sso-operator and dex
  pkg/jx/cmd/create_addon_sso.go
Labels: approved, lgtm, size/XS

#2950 Update Makefile
  Makefile
Labels: approved, lgtm, size/XS
