Repository jenkins-x/jx, pull requests merged in 2019-03, with the labels that each got.

#3250 fix: add support for loading secrets for custom jenkins servers
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/clients/interface.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned3_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_jenkins.go
Labels: size/L

#3252 fix: bug in detection of build number + branch from downward api
  pkg/builds/build_number.go
  pkg/builds/build_number_test.go
Labels: size/M

#3254 fix: correctly use the branch name on BDD tests
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#3258 fixes for tekton build packs + BDD tests
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/delete_jenkins_token.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_create_task.go
  pkg/kube/env.go
Labels: approved, lgtm, size/M

#3257 feat: Add PipelineConfig.Env for global environment variables
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/S

#3263 fixes for tekton
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/step_create_task.go
  pkg/kube/constants.go
  pkg/kube/env.go
Labels: size/L

#3264 fix: update git credentials in shared workspace
  pkg/jx/cmd/step_create_task.go
Labels: size/XS

#3265 fix: run 'jx step git credentials' on each pipeline trigger
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_pipelinerunner.go
Labels: size/M

#3262 fix(tekton): make step_create_task.go unittestable
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/test_data/step_create_task/from_yaml/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/structure.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/packs/import_dir/classic/javascript/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/packs/import_dir/classic/maven/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/packs/import_dir/classic/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/packs/javascript/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/packs/maven/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/podTemplates.yml
  pkg/tekton/pipeline_info_test.go
  pkg/tekton/pipelines.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/tekton_helpers_test/test_helpers.go
Labels: approved, lgtm, size/XXL

#3271 chore: update expected task lists
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
Labels: approved, lgtm, size/M

#3272 revert: lets keep the Jenkinsfile for PRs on our old prod cluster
  Jenkinsfile
Labels: size/M

#3256 fix: retry with an exponential backend to authenticate with the kubernetes auth backend
  pkg/jx/cmd/install.go
  pkg/kube/vault/vault_factory.go
Labels: approved, lgtm, size/S

#3276 Issue 3251: Cluster name validation for jx create cluster gke
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_gke_test.go
Labels: approved, area/UX, area/cli, lgtm, size/M

#3259 chore: Add coverage for version changeset step
  pkg/jx/cmd/step_get_version_changeset.go
  pkg/jx/cmd/step_get_version_changeset_test.go
Labels: approved, lgtm, size/L

#3274 fix: support forking on environment repos if user different to owner
  Makefile
  pkg/environments/gitops.go
  pkg/gits/provider_fake.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/controller_workflow_integration_test.go
  pkg/jx/cmd/promote_test.go
Labels: approved, lgtm, size/L

#3275 chore: Use Tekton runAfter rather than hack for stage ordering
  go.mod
  go.sum
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/L

#3278 fix(tekton): Logs and activity should work with upper-case stage names
  pkg/tekton/pipeline_info.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_internal_test.go
  pkg/tekton/test_data/pipeline_info/from-build-pack/pods.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/tasks.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/pods.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-yaml-nested-stages/tasks.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/pods.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/taskruns.yml
  pkg/tekton/test_data/pipeline_info/from-yaml/tasks.yml
Labels: approved, lgtm, size/M

#3283 fix: Issue 3282 improve error message
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, area/UX, area/cli, lgtm, size/XS

#3284 add kaniko support for tekton build packs
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/step_tag.go
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/packs/javascript/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/packs/maven/pipeline.yaml
  pkg/tekton/syntax/constants.go
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/structure.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/taskruns.yml
  pkg/tekton/test_data/pipeline_info/completed-from-build-pack/tasks.yml
  pkg/tekton/test_data/pipeline_info/from-build-pack/structure.yml
Labels: approved, lgtm, size/L

#3289 fix(tekton): Improve error handling when PipelineConfig is nil
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/test_data/step_create_task/no_pipeline_config/jenkins-x.yml
Labels: approved, lgtm, size/M

#3288 fix: Properly mangle/to-lower-case build pack stage name
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml
  pkg/tekton/syntax/constants.go
  pkg/tekton/test_data/pipeline_info/from-build-pack-init-containers/structure.yml
Labels: approved, lgtm, size/S

#3286 fix for create env on prow and add filtering to jx get build log on tekton
  pkg/jenkins/health.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_create_task.go
  pkg/tekton/pipeline_info.go
Labels: approved, lgtm, size/M

#3294 allow forking for PRs to be disabled for bitbucket and gitlab for now
  charts/controller-backup/Chart.yaml
  charts/controller-backup/Makefile
  charts/controller-backup/requirements.yaml
  charts/controller-backup/values.yaml
  charts/controller-build/Chart.yaml
  charts/controller-build/Makefile
  charts/controller-build/requirements.yaml
  charts/controller-build/templates/.gitignore
  charts/controller-build/values.yaml
  charts/controller-compliance/Chart.yaml
  charts/controller-compliance/Makefile
  charts/controller-compliance/requirements.yaml
  charts/controller-compliance/values.yaml
  charts/controller-role/Chart.yaml
  charts/controller-role/Makefile
  charts/controller-role/requirements.yaml
  charts/controller-role/values.yaml
  charts/controller-team/Chart.yaml
  charts/controller-team/Makefile
  charts/controller-team/requirements.yaml
  charts/controller-team/values.yaml
  charts/controller-workflow/Chart.yaml
  charts/controller-workflow/Makefile
  charts/controller-workflow/requirements.yaml
  charts/controller-workflow/values.yaml
  charts/gc-activities/Chart.yaml
  charts/gc-activities/Makefile
  charts/gc-activities/requirements.yaml
  charts/gc-activities/values.yaml
  charts/gc-previews/Chart.yaml
  charts/gc-previews/Makefile
  charts/gc-previews/requirements.yaml
  charts/gc-previews/values.yaml
  charts/gc-releases/Chart.yaml
  charts/gc-releases/Makefile
  charts/gc-releases/requirements.yaml
  charts/gc-releases/values.yaml
  charts/jx/templates/job.yaml
  charts/service-linker/Chart.yaml
  charts/service-linker/Makefile
  charts/service-linker/requirements.yaml
  charts/service-linker/values.yaml
  pkg/environments/gitops.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/provider_fake.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/common_app.go
Labels: size/XL

#3295 fix: lets not fail a `jx get build log` if we find a pod thats invalid
  charts/jx/templates/job.yaml
  pkg/jx/cmd/create_quickstart_integration_test.go
  pkg/jx/cmd/get_build_logs.go
Labels: approved, lgtm, size/S

#3303 fix: drop lowercase alias
  pkg/jx/cmd/get_apps.go
Labels: approved, lgtm, size/XS

#3300 feat: correctly set the tide url to the deck app
  pkg/config/admin_secrets_test.go
  pkg/jx/cmd/scan_cluster.go
  pkg/jx/cmd/start_protection_test.go
  pkg/prow/config/tide.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
  pkg/surveyutils/jsonschema.go
Labels: approved, lgtm, size/L

#3304 improvements for no-tiller and jenkins API token creation
  pkg/helm/helm_template.go
  pkg/jx/cmd/create_jenkins_token.go
  pkg/kube/job.go
Labels: approved, lgtm, size/M

#3206 Added arg 'use-default-git' to select default git account and avoid prompting user
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_integration_test.go
Labels: approved, lgtm, ok-to-test, size/S

#3199 Fact measurements must be mandatory, while statements and original are optional
  pkg/apis/jenkins.io/v1/types_fact.go
Labels: approved, lgtm, size/S

#3305 fix: handle no-tiller with cluster wide resources better
  pkg/helm/helm_template.go
  pkg/helm/helm_template_test.go
  pkg/helm/test_data/set_labels/clusterrole.yaml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml
  pkg/tekton/syntax/constants.go
  pkg/tekton/test_data/pipeline_info/from-build-pack-init-containers/structure.yml
Labels: approved, size/L

#3322 fix: handle long pipeline resource names
  pkg/jx/cmd/step_create_task.go
Labels: approved, size/XS

#3319 fix: Drastically decrease API calls for PipelineRunInfo creation
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/get_build_logs.go
  pkg/tekton/pipeline_info.go
  pkg/tekton/pipeline_info_test.go
Labels: approved, lgtm, size/L

#3323 fix for bitbucket promote regression
  pkg/environments/gitops.go
  pkg/jx/cmd/common_buildpacks.go
  pkg/jx/cmd/import_integration_test.go
  pkg/jx/cmd/test_data/import_projects/custom_jenkins/Jenkinsfile
Labels: approved, size/L

#3327 jx step split monorepo does not remove files.
  pkg/jx/cmd/step_split_monorepo.go
  pkg/util/files.go
  pkg/util/files_test.go
Labels: approved, lgtm, ok-to-test, size/M

#3325 style(comment): correct the method comment
  pkg/jx/cmd/create_docker_auth.go
Labels: approved, lgtm, ok-to-test, size/XS

#3336 tektonify jx CI and add next gen pipeline
  Jenkinsfile
  Makefile
  pkg/jx/cmd/step_create_task.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/S

#3351 Add --default-admin-username flag on jx-install
  pkg/config/admin_secrets.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, ok-to-test, size/XS

#3352 fix: typo backupJeninsfile to backupJenkinsfile
  pkg/jx/cmd/common_buildpacks.go
Labels: approved, lgtm, ok-to-test, size/XS

#3273 Added external versions support to packages
  pkg/binaries/binaries.go
  pkg/jx/cmd/common_install.go
Labels: approved, lgtm, ok-to-test, size/S

#3280 fix(upgrade): save updated secretes to k8s
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, ok-to-test, size/S

#3354 fix: don't fork a private github repo
  pkg/gits/github.go
  pkg/gits/provider.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/S

#3296 fix: Add cleanup for GKE addresses
  pkg/jx/cmd/gc_gke.go
Labels: approved, lgtm, size/M

#3359 move release pipeline to tekton
  Makefile
  jenkins-x-bdd.yml
  jenkins-x-integration.yml
  jenkins-x.yml
  jx/scripts/update-downstream.sh
Labels: approved, lgtm, size/L

#3365 docs(applications): fix get applications examples
  pkg/jx/cmd/get_applications.go
Labels: approved, lgtm, ok-to-test, size/S

#3361 Go.UUID
  go.mod
  go.sum
  pkg/environments/gitops.go
  pkg/gits/helpers_test.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/step_get_version_changeset_test.go
  pkg/kube/client_generator.go
  pkg/prow/pjutil.go
  pkg/users/git_test.go
Labels: approved, lgtm, size/L

#3364 chore: Switch to using tektoncd/pipeline repo/imports
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  go.mod
  go.sum
  pkg/client/openapi/core/openapi_generated.go
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/clients/interface.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/step_create_version_pr.go
  pkg/tekton/pipeline_info.go
  pkg/tekton/pipeline_info_test.go
  pkg/tekton/pipelines.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/tekton_helpers_test/test_helpers.go
Labels: approved, lgtm, size/M

#3400 Add fact CRD to openapi docs
  docs/apidocs/config.yaml
  pkg/client/openapi/all/openapi_generated.go
Labels: approved, lgtm, size/M

#3394 NotExecuted is not a failure
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/jx/cmd/controller_build.go
Labels: approved, lgtm, size/XS

#3380 chore: Switch to sigs.k8s.io/yaml
  go.mod
  pkg/addon/config.go
  pkg/auth/config.go
  pkg/auth/file_config_saver.go
  pkg/auth/types.go
  pkg/binaries/binaries.go
  pkg/cloud/gke/gcloud.go
  pkg/config/project_config.go
  pkg/config/project_config_test.go
  pkg/io/config_readers.go
  pkg/io/config_writers.go
  pkg/jenkinsfile/gitresolver/resolvers.go
  pkg/jenkinsfile/modules.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/bdd/bdd_clusters.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/create_addon_prometheus.go
  pkg/jx/cmd/get_eks.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/import_test.go
  pkg/jx/cmd/scan_cluster.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/prow/config.go
  pkg/reports/project_history.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/test_data/loop_step/jenkins-x.yml
  pkg/version/version_data.go
Labels: approved, lgtm, size/L

#3279 Upgraded AWS SDK
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#3372 fix: Don't accidentally reuse PipelineStructures
  pkg/jx/cmd/get_build_logs.go
  pkg/tekton/pipeline_info.go
Labels: approved, lgtm, size/S

#3386 Added dev-env repo to updatebot config
  .updatebot.yml
Labels: approved, lgtm, size/XS

#3395 Eksctl version should not be hardcoded
  pkg/binaries/binaries.go
  pkg/jx/cmd/common_install.go
Labels: approved, lgtm, ok-to-test, size/S

#3371 fix(windows) make ansi escape sequences render correctly
  Makefile
  cmd/jx/app/jx-win.go
  cmd/jx/app/jx.go
Labels: approved, lgtm, size/M

#3403 fix for jx console
  pkg/builds/build_info.go
  pkg/jx/cmd/console.go
  pkg/jx/cmd/get_build_logs.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/S

#3407 fix a dog test so it works on windows too
  pkg/util/files_test.go
Labels: approved, lgtm, size/XS

#3408 fix: allow the docker registry org to be specified at a team level
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/step_tag.go
Labels: size/M

#3393 feat: add utility to generate a JSON patch.
  pkg/kube/patch.go
Labels: approved, lgtm, size/M

#3410 fix: lets reset the fork before trying to create a PR
  cmd/jx/app/jx-win.go
  pkg/builds/build_info.go
  pkg/client/openapi/all/openapi_generated.go
  pkg/environments/gitops.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned1_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/common_auth.go
  pkg/jx/cmd/common_git.go
  pkg/jx/cmd/common_import.go
  pkg/jx/cmd/common_import_test.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_prow.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/create_env_test.go
  pkg/jx/cmd/create_git_api_token.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/get_build_pods.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_post_install.go
  pkg/jx/cmd/upgrade_addon_prow.go
  pkg/tekton/pipeline_info.go
  pkg/tests/helpers.go
Labels: approved, lgtm, size/L

#3417 fix: the storage of logs with tekton
  go.mod
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/controller_build.go
Labels: approved, lgtm, size/L

#3277 Support creating vault on AWS
  pkg/cloud/amazon/vault/naming.go
  pkg/cloud/amazon/vault/vault_backend.go
  pkg/cloud/gke/vault/naming.go
  pkg/cloud/gke/vault/vault_backend.go
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete_vault.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/kube/vault/vault.go
  pkg/kube/vault/vault_test.go
Labels: approved, lgtm, size/XL

#3416 feat: Add urltemplate option to install and upgrade ingress
  pkg/config/helm_values.go
  pkg/expose/exposecontroller.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, ok-to-test, size/M

#3406 fix(addon) upgrades ignored previous values
  pkg/buildnum/mocks/matchers/kube_pipelineid.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/M

#3415 test: refactor some flaky unit tests to get them passing with Go 1.12
  Makefile
  pkg/jx/cmd/version.go
  pkg/jx/cmd/version_test.go
  pkg/log/log.go
  pkg/surveyutils/jsonschema_test.go
Labels: approved, lgtm, size/L

#3418 feat: adding a script to fail the build on gofmt errors
  Makefile
  hack/gofmt.sh
  jenkins-x-integration.yml
  pkg/auth/config_test.go
  pkg/client/openapi/all/openapi_generated.go
  pkg/cloud/amazon/routes.go
  pkg/cloud/iks/registry.go
  pkg/extensions/plugins_test.go
  pkg/gits/bitbucket_cloud_test.go
  pkg/gits/provider_fake.go
  pkg/io/config_readers_test.go
  pkg/io/config_writers_test.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/create_addon_owasp.go
  pkg/jx/cmd/create_client_docs.go
  pkg/jx/cmd/create_devpod.go
  pkg/jx/cmd/create_post_preview_job.go
  pkg/jx/cmd/delete_context.go
  pkg/jx/cmd/environment.go
  pkg/jx/cmd/gc_helm.go
  pkg/jx/cmd/get_issue.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/start_pipeline.go
  pkg/jx/cmd/step_blog.go
  pkg/jx/cmd/step_post.go
  pkg/jx/cmd/stop_pipeline.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/kube/namespaces_test.go
  pkg/kube/pki/certificate_test.go
  pkg/kube/pod_test.go
  pkg/kube/roles.go
  pkg/maven/archetype.go
  pkg/prow/prow.go
  pkg/users/git_test.go
  pkg/util/color.go
  pkg/util/strings.go
  pkg/version/info_test.go
  test.sh
Labels: approved, lgtm, size/L

#3426 expose the defaultRole option in the Cloudbees addon
  pkg/jx/cmd/create_addon_cloudbees.go
Labels: approved, lgtm, size/S

#3423 fix: lets default to recreate the vault bucket
  pkg/buildnum/mocks/matchers/kube_pipelineid.go
  pkg/cloud/amazon/vault/vault_backend.go
  pkg/cloud/gke/vault/vault_backend.go
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/clients/interface.go
  pkg/jx/cmd/clients/mocks/factory.go
  pkg/jx/cmd/clients/mocks/matchers/ptr_to_versioned2_clientset.go
  pkg/jx/cmd/clients/mocks/matchers/versioned0_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned2_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned3_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned4_interface.go
  pkg/jx/cmd/clients/mocks/matchers/versioned_interface.go
  pkg/jx/cmd/common.go
  pkg/jx/cmd/common_auth.go
  pkg/jx/cmd/common_chat.go
  pkg/jx/cmd/common_issues.go
  pkg/jx/cmd/create_env_test.go
  pkg/jx/cmd/create_vault.go
  pkg/jx/cmd/delete_vault.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/preview_test.go
  pkg/kube/vault/vault.go
  pkg/kube/vault/vault_test.go
Labels: approved, lgtm, size/L

#3396 Fix go report card link
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#3405 Refactored "binaries" => "packages"
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/create_addon_istio.go
  pkg/packages/packages.go
  pkg/packages/packages_test.go
Labels: approved, lgtm, ok-to-test, size/M

#3431 fix: set modules to on always
  pkg/util/go.go
Labels: approved, lgtm, size/XS

#3321 chore: fix the location of thrift
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#3428 Update PipelineActivity for preview env in dev namespace
  pkg/jx/cmd/preview.go
Labels: approved, lgtm, size/XS

#3434 fix: lets use the `git-owner` for the environment owner too
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#3306 Delete go.mod when running create client docs
  pkg/kube/client_generator.go
Labels: approved, lgtm, size/XS

#3437 fix: lets empty buckets first before removing them
  pkg/cloud/gke/vault/vault_backend.go
Labels: size/XS

#3442 chore: improve reporting if a failure occurs creating a PR
  pkg/gits/github.go
  pkg/jx/cmd/create_pullrequest.go
Labels: approved, lgtm, size/S

#3445 Additional output on jx step tag
  pkg/jx/cmd/step_tag.go
Labels: approved, lgtm, size/XS

#3425 fix: don’t try to overwrite user id
  pkg/users/git.go
  pkg/users/git_test.go
  pkg/users/users_test.go
Labels: approved, lgtm, size/L

#3444 chore: improved linter checks
  Makefile
  hack/gofmt.sh
  hack/linter.sh
  jenkins-x-bdd.yml
  jenkins-x-integration.yml
  jenkins-x-lint.yml
  jenkins-x.yml
  pkg/client/openapi/all/openapi_generated.go
  pkg/cloud/oke/helper.go
  pkg/config/admin_secrets.go
  pkg/config/project_config.go
  pkg/gits/bitbucket_cloud_test.go
  pkg/jenkinsfile/jenkinsfile_writer.go
  pkg/util/downloads.go
  pkg/util/http_utils.go
Labels: approved, lgtm, size/L

#3443 fix: lets default the vault name from the installation details
  pkg/jx/cmd/clients/factory.go
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/M

#3453 fix: allow the jenkins-x-versions BDD test images to be updated
  pkg/client/openapi/all/openapi_generated.go
  pkg/cloud/aks/aks.go
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/helper.go
  pkg/cloud/gke/images.go
  pkg/cloud/gke/images_test.go
  pkg/config/admin_secrets.go
  pkg/environments/gitops.go
  pkg/gits/bitbucket_cloud_test.go
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
  pkg/helm/helm_template.go
  pkg/jenkins/health.go
  pkg/jx/cmd/common_gke.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/create_cluster.go
  pkg/jx/cmd/create_git_api_token.go
  pkg/jx/cmd/gc_gke.go
  pkg/jx/cmd/get_helmbin.go
  pkg/jx/cmd/helpers.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/logs.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/shell.go
  pkg/jx/cmd/status_test.go
  pkg/jx/cmd/step_create_version_pr.go
  pkg/jx/cmd/step_credential.go
  pkg/jx/cmd/step_gpg_credentials.go
  pkg/jx/cmd/step_next_buildnumber.go
  pkg/jx/cmd/step_next_version.go
  pkg/jx/cmd/step_split_monorepo.go
  pkg/jx/cmd/step_validate.go
  pkg/jx/cmd/templates/templater.go
  pkg/jx/cmd/test_helpers.go
  pkg/jx/cmd/upgrade_cluster.go
  pkg/jx/cmd/upgrade_extensions.go
  pkg/jx/cmd/upgrade_platform.go
  pkg/jx/cmd/version.go
  pkg/kube/client_generator.go
  pkg/kube/crds.go
  pkg/kube/deployments_test.go
  pkg/kube/kops.go
  pkg/kube/log_masker.go
  pkg/kube/log_masker_test.go
  pkg/kube/namespaces_test.go
  pkg/kube/vault/vault.go
  pkg/maven/archetype.go
  pkg/surveyutils/validators.go
  pkg/tekton/pipeline_info.go
  pkg/tekton/syntax/pipeline.go
  pkg/users/git.go
  pkg/util/downloads.go
  pkg/util/http_utils_test.go
  pkg/util/padding.go
Labels: approved, lgtm, size/XL

#3255 Get last message from mono repo and put it in the commit message
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/provider.go
  pkg/gits/provider_fake.go
  pkg/jx/cmd/step_split_monorepo.go
  pkg/jx/cmd/step_split_monorepo_test.go
Labels: approved, lgtm, ok-to-test, size/L

#3455 fix: register the dev env for GitOps
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/promote.go
  pkg/kube/env.go
Labels: approved, lgtm, size/M

#3456 chore: remove unused dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#3383 jx promote fails outside of a git working copy
  pkg/kube/activity.go
Labels: approved, lgtm, size/XS

#3439 The urltemplate can be empty
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, ok-to-test, size/XS

#3219 Feat: add app from local path
  pkg/apps/helmops.go
  pkg/apps/install.go
  pkg/apps/utils.go
  pkg/apps/values.go
  pkg/client/openapi/all/openapi_generated.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/add_app_test.go
Labels: approved, lgtm, size/L

#3447 partial revert of #3406 / #3399
  pkg/jx/cmd/upgrade_addons.go
Labels: approved, lgtm, size/XS

#3465 fix: Add JSON struct tags to auth types.
  pkg/auth/types.go
Labels: approved, lgtm, size/S

#3458 fix: lets ensure we register prow configs in `--ng` installs
  pkg/config/helm_values.go
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/common_install.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/kube/log_masker.go
Labels: approved, lgtm, size/L

#3462 feat(windows) Make `jx shell` work on vanilla windows
  pkg/jx/cmd/shell.go
Labels: approved, lgtm, size/M

#3448 Fuller revert of 3406
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/upgrade_addons.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/M

#3476 chore(users) fix incorrect warning message
  pkg/jx/cmd/delete_user.go
Labels: approved, lgtm, size/XS

#3469 chore: Unify build pack and YAML syntax Tekton CRD generation
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/XL

#3473 fix: use GitOps with jx upgrade platform
  pkg/environments/gitops.go
  pkg/helm/helm_template.go
  pkg/jx/cmd/common_pullrequest.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/step_create_version_pr.go
  pkg/jx/cmd/step_env_apply.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/upgrade_platform.go
Labels: approved, lgtm, size/L

#3478 Fix: remove '*' from possible characters for secrets because Jenkins …
  pkg/config/admin_secrets.go
Labels: approved, lgtm, ok-to-test, size/XS

#3479 Chore: fix rendering of table in generated readme
  pkg/helm/helm_helpers.go
  pkg/jx/cmd/add_app_test.go
Labels: approved, lgtm, size/XS

#3480 fix: removed duplicate maven server settings
  pkg/config/admin_secrets.go
  pkg/config/admin_secrets_test.yaml
Labels: approved, lgtm, size/S

#3481 fix: add a new command: `jx create step`
  pkg/config/project_config.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/create.go
  pkg/jx/cmd/create_step.go
Labels: approved, lgtm, size/L

#3468 chore: fix typo in pipelineRunMethods func name
  pkg/jx/cmd/controller_pipelinerunner.go
Labels: approved, lgtm, size/XS

#3477 feat: enabled kaniko/enhanced scopes & apis as part of next gen install
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_terraform.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/S

#3432 fix: Use login not CRD name / Remove roles from deleted user
  pkg/jx/cmd/delete_user.go
  pkg/jx/cmd/get_user.go
  pkg/users/users.go
Labels: approved, lgtm, ok-to-test, size/M

#3435 fix(tekton) make pipelines and tasks unique per-build
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/structure.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/structure.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/tekton/constants.go
  pkg/tekton/pipelines.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/XL

#3090 Add support for Spotinst
  pkg/jx/cmd/create_cluster_aws.go
Labels: approved, lgtm, ok-to-test, size/S

#3483 Gke
  pkg/cloud/gke/helper.go
  pkg/jx/cmd/common_gke.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/step_validate.go
Labels: approved, lgtm, size/L

#3484 fix: release pipeline for creating the docs
  jx/scripts/update-website.sh
Labels: size/XS

#3485 Revert "chore: clean up Makefile"
  Makefile
Labels: size/M
