Repository jenkins-x/jx, pull requests merged in 2019-12, with the labels that each got.

#6265 fix: avoid using hardcoded jenkins x [bot] github username
  pkg/cmd/step/verify/step_verify_git.go
  pkg/gits/github.go
Labels: approved, lgtm, size/XS

#6257 fix: Add kaniko secrets to all steps running `/kaniko/executor`
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipeline.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipelinerun.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/structure.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
Labels: approved, lgtm, size/M

#6182 feat: add '--merge' option when deleting branch
  pkg/cmd/deletecmd/delete_branch.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
Labels: approved, lgtm, size/L

#6268 feat: reduced the default NS and SOA record ttl
  .secrets.baseline
  pkg/cloud/gke/gcloud.go
Labels: approved, lgtm, size/L

#6273 fix: boot upgrade of tagged version stream
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_integration_test.go
Labels: approved, lgtm, size/M

#6241 fix: check helm compatibility to avoid using helm v3
  pkg/cmd/clients/factory.go
  pkg/helm/helm_cli.go
Labels: approved, lgtm, size/M

#6188 feat: allow selection of chart in next-version
  pkg/cmd/step/step_next_version.go
  pkg/cmd/step/step_next_version_integration_test.go
  pkg/cmd/step/test_data/next_version/charts/charts/bar/Chart.yaml
  pkg/cmd/step/test_data/next_version/charts/charts/bar/expected_Chart.yaml
  pkg/cmd/step/test_data/next_version/charts/charts/foo/Chart.yaml
  pkg/cmd/step/test_data/next_version/charts/charts/foo/expected_Chart.yaml
Labels: approved, lgtm, ok-to-test, size/M

#6211 fix: Apply labels as part of pull req creation, not just after
  pkg/gits/operations/pull_request_op.go
  pkg/gits/operations/pull_request_op_test.go
Labels: approved, lgtm, size/M

#6279 fix: only prompt once if github app is enabled but not installed
  pkg/cmd/create/create.go
  pkg/cmd/create/create_quickstart.go
  pkg/cmd/importcmd/import.go
  pkg/github/github_app.go
Labels: approved, lgtm, size/M

#6282 fix: avoid adding invalid labels to PipelineActivity
  pkg/kube/activity.go
  pkg/kube/naming/names.go
  pkg/kube/naming/names_valid_test.go
Labels: approved, lgtm, size/M

#6281 fix: The documentation url is changed.
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, ok-to-test, size/XS

#6284 chore: Deprecate create codeship command
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/XS

#6260 fix: boot upgrade cloning using GitHub apps
  .secrets.baseline
  pkg/cmd/controller/controller_build.go
  pkg/cmd/create/create_addon_prow.go
  pkg/cmd/create/install.go
  pkg/cmd/opts/git.go
  pkg/cmd/upgrade/upgrade_addon_prow.go
  pkg/cmd/upgrade/upgrade_boot.go
Labels: approved, lgtm, size/L

#6289 fix: Correct link to import documentation
  pkg/cmd/create/create_branch_pattern.go
  pkg/cmd/get/get_branchpattern.go
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#6294 chore: add PR labels as part of PR creation
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/operations/pull_request_op.go
Labels: approved, lgtm, size/M

#6288 fix: `jx step helm build --recursive`
  pkg/cmd/opts/helm.go
  pkg/cmd/opts/helm_test.go
  pkg/cmd/opts/test_data/recursive/chart1/Chart.yaml
  pkg/cmd/opts/test_data/recursive/chart1/requirements.yaml
  pkg/cmd/opts/test_data/recursive/chart1/templates/template.yaml
  pkg/cmd/opts/test_data/recursive/chart1/values.yaml
  pkg/cmd/opts/test_data/recursive/chart2/Chart.yaml
  pkg/cmd/opts/test_data/recursive/chart2/requirements.yaml
  pkg/cmd/opts/test_data/recursive/chart2/templates/template.yaml
  pkg/cmd/opts/test_data/recursive/chart2/values.yaml
  pkg/cmd/opts/test_data/recursive/chart3/Chart.yaml
  pkg/cmd/opts/test_data/recursive/chart3/templates/template.yaml
  pkg/cmd/opts/test_data/recursive/chart3/values.yaml
  pkg/util/downloads.go
  pkg/util/downloads_test.go
  pkg/util/test_data/nested-no-dir.tgz
Labels: approved, lgtm, ok-to-test, size/L

#6295 feat: display the github app name during quickstarts
  pkg/github/github_app.go
Labels: approved, lgtm, size/M

#6307 fix: do not display undeployed applications
  pkg/cmd/get/get_applications.go
Labels: approved, lgtm, size/M

#6297 fix: Update go-gitlab to latest version to resolve project creation
  go.mod
  go.sum
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/gits/gitlab.go
Labels: approved, lgtm, ok-to-test, size/S

#6304 fix: Don't require --version for step create pr repositories
  pkg/cmd/step/create/pr/step_create_pr_repositories.go
Labels: approved, lgtm, ok-to-test, size/XS

#6329 fix: avoid creating invalid pipelines
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/S

#6328 feat: format the imports when executing the fmt goal
  Makefile
Labels: approved, do-not-merge/hold, lgtm, size/XS

#6332 fix: upgrades using branch ref
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_integration_test.go
Labels: approved, lgtm, size/S

#6336 fix: avoid creating invalid pipelines
  pkg/tekton/syntax/pipeline.go
Labels: size/XS

#6207 feat: perform GC on EKS BDD clusters too and refactor to AWS code to make abstractions easier to test
  pkg/cloud/amazon/awscli/aws_cli.go
  pkg/cloud/amazon/awscli/interface.go
  pkg/cloud/amazon/awscli/mocks/awsclimock.go
  pkg/cloud/amazon/common_test.go
  pkg/cloud/amazon/ec2/ec2.go
  pkg/cloud/amazon/ec2/ec2_test.go
  pkg/cloud/amazon/ec2/interface.go
  pkg/cloud/amazon/ec2/mocks/ec2erMock.go
  pkg/cloud/amazon/ecr.go
  pkg/cloud/amazon/ecr_test.go
  pkg/cloud/amazon/eks/eks.go
  pkg/cloud/amazon/eks/interface.go
  pkg/cloud/amazon/eks/mocks/ekserMock.go
  pkg/cloud/amazon/eksctl/eksctl_cli.go
  pkg/cloud/amazon/eksctl/interface.go
  pkg/cloud/amazon/eksctl/mocks/eksctl.go
  pkg/cloud/amazon/permissions.go
  pkg/cloud/amazon/provider.go
  pkg/cloud/amazon/routes.go
  pkg/cloud/amazon/s3.go
  pkg/cloud/amazon/session/common.go
  pkg/cloud/amazon/session/common_test.go
  pkg/cloud/amazon/storage/bucket_provider.go
  pkg/cloud/amazon/testutils/mockprovider.go
  pkg/cloud/amazon/testutils/session_test_utils.go
  pkg/cloud/amazon/zones.go
  pkg/cluster/eks/clusterclient.go
  pkg/cluster/eks/clusterclient_test.go
  pkg/cluster/fake/fake.go
  pkg/cluster/gke/gke.go
  pkg/cluster/interface.go
  pkg/cmd/create/create_cluster_aws.go
  pkg/cmd/create/create_cluster_eks.go
  pkg/cmd/deletecmd/delete_aws.go
  pkg/cmd/deletecmd/delete_eks.go
  pkg/cmd/get/get_eks.go
  pkg/cmd/step/e2e/step_e2e_gc.go
  pkg/cmd/step/e2e/step_e2e_gc_test.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/vault/create/create.go
Labels: approved, lgtm, size/XXL

#6109 fix: don’t create default factory in tekton logging code
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/step/step_unstash.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/M

#6339 chore: allow escaping for code comments on PRs
  pkg/cmd/step/pr/step_pr_comment.go
Labels: approved, lgtm, size/XS

#6347 chore: correctly clean down bdd iam bindings with deleted members
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/XS

#6346 feat: ensure that we have goimports for import formatting
  Makefile
Labels: approved, lgtm, size/XS

#6351 chore: update golang image version to 1.12.4
  jenkins-x-bdd.yml
  jenkins-x-boot-vault.yml
  jenkins-x-images.yml
  jenkins-x-tekton.yml
Labels: approved, lgtm, size/S

#6354 feat: configurable velero backups from requirements
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/XS

#6355 feat: use envconfig for velero requirement overrides
  .secrets.baseline
  go.mod
  go.sum
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/M

#6357 feat: podAnnotations on jx pod
  charts/jx/templates/cronjob.yaml
  charts/jx/templates/daemonset.yaml
  charts/jx/templates/deployment.yaml
  charts/jx/templates/job.yaml
  charts/jx/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#6363 feat: Bump helm versions using version stream
  pkg/cmd/opts/install.go
Labels: approved, lgtm, size/S

#6364 chore: test for envconfig usage in OverrideRequirementsFromEnvironment
  pkg/config/install_requirements_test.go
  pkg/config/test_data/jx-requirements.yml
Labels: approved, lgtm, size/M

#6366 fix: making sure naming.ToValidName is called before creating a new CRD
  pkg/users/git.go
  pkg/users/git_test.go
Labels: approved, lgtm, size/M

#6368 feat: Update deprecation dates format to address confusion
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/M

#6371 fix: return info when using --latest for velero restore
  pkg/cmd/step/restore/step_restore_from_backup.go
Labels: approved, lgtm, size/XS
