Repository jenkins-x/jx, pull requests merged in 2019-05, with the labels that each got.

#3825 fix: make it easy to use `jenkins-x.yml` to override the registry
  pkg/config/project_config.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/get_applications.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/opts/docker.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/preview_test.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_tag.go
  pkg/jx/cmd/step_tag_test.go
  pkg/jx/cmd/test_data/step_tag_project/charts/mydemo/values.yaml
  pkg/jx/cmd/test_data/step_tag_project/jenkins-x.yml
  pkg/prow/prow.go
Labels: approved, lgtm, size/L

#3833 Buildpackurl
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/S

#3824 Values preprocessor
  pkg/apps/install.go
  pkg/environments/gitops.go
Labels: approved, lgtm, size/M

#3842 feat(tekton): Add support for per-step environment variables
  pkg/jx/cmd/test_data/step_create_task/from_yaml/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/jenkins-x.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/environment_at_top_and_in_stage/jenkins-x.yml
Labels: approved, lgtm, size/M

#3779 Issue #3738 - pinning versions of all code generators
  Makefile.codegen
  VERSION
  cmd/codegen/app/generate_clientset.go
  cmd/codegen/app/generate_docs.go
  cmd/codegen/app/generate_openapi.go
  cmd/codegen/app/generate_options.go
  cmd/codegen/app/root.go
  cmd/codegen/generator/client_set.go
  cmd/codegen/generator/common.go
  cmd/codegen/generator/docs.go
  cmd/codegen/generator/open_api.go
  cmd/codegen/util/cli.go
  cmd/codegen/util/commands.go
  cmd/codegen/util/files.go
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  go.mod
  go.sum
  hack/run-all-checks.sh
  jenkins-x-lint.yml
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/client/openapi/k8s_io_api_core_v1/openapi_generated.go
  pkg/client/openapi/k8s_io_api_rbac_v1/openapi_generated.go
  pkg/client/openapi/k8s_io_apimachinery_meta_v1/openapi_generated.go
  pkg/client/openapi/k8s_io_apimachinery_resource_unversioned/openapi_generated.go
Labels: approved, lgtm, size/XXL

#3844 fix: remove VERSION file
  VERSION
Labels: approved, size/XS

#3811 user commonoptions username field instead
  pkg/gits/github.go
  pkg/jx/cmd/update_webhooks.go
  pkg/jx/cmd/update_webhooks_test.go
  pkg/jx/cmd/upgrade_ingress.go
Labels: approved, lgtm, ok-to-test, size/M

#3730 fix(webhook): create a webhook when running update webhook command if the repository does not have any webhooks
  pkg/gits/github.go
  pkg/jx/cmd/update_webhooks.go
Labels: approved, lgtm, size/M

#3848 fix: lets add a FakeFactory for easier testing
  pkg/jx/cmd/clients/fake/fake_factory.go
  pkg/jx/cmd/clients/fake/fake_factory_test.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/L

#3847 feat: adding ability to create namespace via 'jx ns --create <name>
  pkg/jx/cmd/namespace.go
  pkg/jx/cmd/namespace_test.go
  pkg/jx/cmd/opts/common.go
  pkg/kube/config.go
Labels: approved, lgtm, size/L

#3855 feat: support for optional creds
  pkg/jx/cmd/step_credential.go
Labels: approved, lgtm, size/S

#3856 fix: fake factory should cache the fake clients
  pkg/jx/cmd/clients/fake/fake_factory.go
Labels: approved, lgtm, size/M

#3837 (fix) git version for jx step bdd versions repository
  pkg/jx/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#3819 Update README.md to add codescene reporting
  README.md
Labels: approved, lgtm, size/S

#3852 docs: improve log statement
  pkg/jx/cmd/create_vault.go
Labels: approved, lgtm, size/XS

#3862 fix: add more labels to SourceRepository and PipelineActivity
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/kube/activity.go
  pkg/kube/crds.go
  pkg/kube/sourcerepositories.go
Labels: approved, lgtm, size/M

#3863 chore: typo
  pkg/apis/jenkins.io/v1/types_pipeline.go
Labels: approved, lgtm, size/XS

#3864 fix: ng install after prow config refactoring
  pkg/jx/cmd/opts/common.go
  pkg/jx/cmd/opts/install.go
  pkg/prow/prow.go
Labels: approved, lgtm, size/L

#3865 fix: store the dev environment in the jx config folder instead of the current directory
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#3867 fix: lets default to using a newer image type
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, lgtm, size/XS

#3868 fix nil pointer exceptions and add better GKE defaults
  pkg/cloud/gke/gcloud.go
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/preview.go
  pkg/jx/cmd/step_changelog.go
  pkg/users/git.go
Labels: approved, lgtm, size/M

#3757 fix: add JSON schema validation for pipeline.yaml and jenkins-x.yml
  go.mod
  go.sum
  jenkins-x-bdd-tekton.yml
  jenkins-x-bdd.yml
  jenkins-x-integration.yml
  pkg/config/project_config.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/step.go
  pkg/jx/cmd/step_syntax.go
  pkg/jx/cmd/step_syntax_schema.go
  pkg/jx/cmd/step_syntax_validate.go
  pkg/jx/cmd/step_syntax_validate_buildpacks.go
  pkg/jx/cmd/step_syntax_validate_pipeline.go
  pkg/jx/cmd/test_data/step_buildpack_apply/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/packs/no-default-agent/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/packs/override-default-agent/pipeline.yaml
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/validation_failures/stages_and_parallel/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/steps_and_parallel/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/steps_and_stages/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/unknown_field/jenkins-x.yml
  pkg/util/validation.go
Labels: approved, lgtm, size/XL

#3798 chore: Update to Tekton Pipelines v0.3.1
  go.mod
  go.sum
  pkg/tekton/pipeline_info.go
Labels: approved, lgtm, size/XS

#3850 feat: Allow overriding/removing steps from build pack by name
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/test_data/step_create_task/override-steps/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/structure.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/structure.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/packs/apps/pipeline.yaml
Labels: approved, lgtm, size/XXL

#3841 chore: Initial work on unification of build pack and jenkins-x.yml syntax
  pkg/builds/jenkinsfiles.go
  pkg/builds/jenkinsfiles_test.go
  pkg/config/project_config_test.go
  pkg/jenkinsfile/pipeline.go
  pkg/jx/cmd/create_step.go
  pkg/jx/cmd/create_variable.go
  pkg/jx/cmd/step_buildpack_apply_test.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/test_data/step_create_task/from_yaml/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/packs/apps/pipeline.yaml
  pkg/jx/cmd/test_data/step_create_task/packs/maven/pipeline.yaml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/container_options_env_merge/jenkins-x.yml
  pkg/tekton/syntax/test_data/environment_at_top_and_in_stage/jenkins-x.yml
  pkg/tekton/syntax/test_data/loop_step/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/agent_container_field/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/agent_dir_field/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/comment_field/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/container_field/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/groovy_field/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/legacy_steps_field/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/sh_field/jenkins-x.yml
  pkg/tekton/syntax/test_data/validation_failures/when_field/jenkins-x.yml
  pkg/util/jenkinsfile_writer.go
  pkg/util/jenkinsfile_writer_test.go
Labels: approved, lgtm, size/XL

#3876 fix: lets only default to containerd image on GKE for tekton
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, lgtm, size/XS

#3881 fix: lets use the containerd image by default on ng
  pkg/jx/cmd/create_cluster_gke.go
Labels: size/S

#3883 chore: revert using a default image type on GKE for tekton
  jx/scripts/update-website.sh
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/step_syntax_schema.go
Labels: approved, lgtm, size/M

#3890 fix(tekton): Reject duplicate step names within a stage
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/validation_failures/duplicate_step_names/jenkins-x.yml
Labels: approved, lgtm, size/M

#3878 Fix the lazily created ecr docker registry organisation
  pkg/jx/cmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#3879 Skip ECR docker repository creation if a project doesn't need a docker image/file
  pkg/jx/cmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#3886 fix: add the expect ***
  pkg/jx/cmd/add_app_test.go
Labels: approved, lgtm, size/XS

#3758 fix: Handle shortening cluster names for clusters named by their FQDN.
  pkg/kube/cluster/cluster.go
  pkg/kube/cluster/cluster_test.go
  pkg/kube/vault/vault.go
Labels: approved, lgtm, ok-to-test, size/M

#3895 Clients1
  .gitignore
  jx/scripts/update-clients.sh
  pkg/apps/gitops.go
  pkg/apps/install.go
  pkg/environments/gitops.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/controller_workflow.go
  pkg/jx/cmd/create_pullrequest.go
  pkg/jx/cmd/delete_app.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/promote_test.go
  pkg/jx/cmd/step_git.go
  pkg/jx/cmd/step_git_fork_and_clone.go
  pkg/jx/cmd/upgrade_apps.go
Labels: approved, lgtm, size/XL

#3892 feat: create Kaniko service account with a distiguishable name
  pkg/cloud/gke/gcloud.go
Labels: approved, lgtm, size/XS

#3872 (feat) Install prow with myvalues.yml
  pkg/jx/cmd/create_addon_prow.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/install.go
  pkg/jx/cmd/upgrade_addon_prow.go
Labels: approved, lgtm, size/S

#3893 fix: wait for a 200 before saying the app is ready
  pkg/jx/cmd/preview.go
Labels: approved, lgtm, size/S

#3737 feat: install Istio using the version passed in the cmd line
  pkg/jx/cmd/create_addon_istio.go
Labels: approved, area/istio, lgtm, size/S

#3909 chore: improve codegen integration and add dep tidy rule
  Makefile
  Makefile.codegen
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#3904 chore: Don't say "installing knative" when it's tekton
  pkg/jx/cmd/opts/install.go
Labels: approved, lgtm, size/XS

#3907 fix: attempt to avoid the storage location being wiped
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/collector/helpers.go
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/get_storage.go
  pkg/jx/cmd/step_stash.go
Labels: approved, lgtm, size/M

#3900 Fix: don’t do a pull, it doesn’t reliably work
  pkg/gits/helpers.go
Labels: approved, lgtm, size/S

#3923 fix: lets retry trying to assign roles to the SA
  pkg/cloud/gke/gcloud.go
Labels: size/XS

#3926 fix: handle > 1 values files with gitops
  pkg/environments/gitops.go
Labels: size/M

#3813 Tekton BDD
  jenkins-x-bdd-tekton.yml
  jenkins-x-tekton.yml
  jx/bdd/tekton/README.md
  jx/bdd/tekton/ci.sh
  jx/bdd/tekton/cluster.yaml
  jx/scripts/ci-tekton.sh
  myvalues.yaml.tekton.template
Labels: approved, lgtm, size/L

#3910 chore: enable update-clients
  jenkins-x-integration.yml
  jenkins-x.yml
  jx/scripts/update-clients.sh
Labels: size/S

#3902 feat(vault): update vault to latest version (v1.1.2), enable auto-unseal, and switch to KV engine V2
  Makefile.codegen
  go.mod
  go.sum
  jenkins-x-lint.yml
  pkg/auth/vault_config_saver.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/kube/vault/vault.go
  pkg/kube/vault/vault_factory.go
  pkg/log/log.go
  pkg/vault/rule.go
  pkg/vault/rule_test.go
  pkg/vault/vault_client.go
  pkg/vault/vault_path.go
Labels: approved, lgtm, size/XL

#3918 fix: the generated apps weren't getting the real app.yml file from it…
  go.mod
  pkg/environments/gitops.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/step_helm_apply.go
Labels: approved, lgtm, size/M

#3877 Enable gcs buckets as default storage for Jenkins X when using GCP
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/storage/long_term_storage.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
Labels: approved, lgtm, size/L

#3937 fixes for envctl and pipeline labels
  pkg/jx/cmd/controller_build.go
  pkg/jx/cmd/controller_enviornmentcontroller.go
Labels: approved, lgtm, size/L

#3940 chore: added joseblas to OWNERS
  OWNERS
Labels: approved, lgtm, ok-to-test, size/XS

#3891 feat: 'jx step create task' should create a PipelineActivity early
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
Labels: approved, lgtm, ok-to-test, size/L

#3859 fix(install): Force Kanoko with Tekton on GKE when interactive
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/M

#3924 feat: allow passing the grafana version to flagger addon
  pkg/jx/cmd/create_addon_flagger.go
Labels: approved, lgtm, size/XS

#3935 Enabled Get Apps in GitOps mode and other changes to Apps GitOps
  go.sum
  pkg/apps/gitops.go
  pkg/apps/helmops.go
  pkg/apps/install.go
  pkg/gits/helpers.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/delete_app_test.go
  pkg/jx/cmd/get_apps.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/step_helm_apply.go
  pkg/jx/cmd/step_helm_apply_test.go
  pkg/jx/cmd/test_data/apply_env/jx-app-dummy-0.0.3.tgz
  pkg/jx/cmd/upgrade_apps_test.go
Labels: approved, lgtm, size/XL

#3830 feat: Add Machine Learning Quickstarts
  pkg/jx/cmd/create.go
  pkg/jx/cmd/create_mlquickstart.go
  pkg/jx/cmd/create_mlquickstart_integration_test.go
Labels: approved, lgtm, ok-to-test, size/L

#3946 feat(vault): get the versions of docker images used by vault from versions repository
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/create_vault.go
  pkg/kube/vault/vault.go
  pkg/kube/vault/vault_test.go
Labels: approved, lgtm, size/L

#3949 feat(tekton): Allow specifying default working dir on pipeline and stage
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/dir_on_pipeline_and_stage/jenkins-x.yml
Labels: approved, lgtm, size/L

#3953 fix(cmd): application environment was always the last environment
  pkg/jx/cmd/get_applications.go
Labels: approved, lgtm, ok-to-test, size/XS

#3945 fix(tekton): Non-schema-errors weren't showing up in validation
  pkg/jx/cmd/step_syntax_validate_pipeline.go
Labels: approved, lgtm, size/XS

#3955 fix: improve the GC of PipelineActivity and PipelineRun
  pkg/jx/cmd/gc_activities.go
Labels: approved, lgtm, size/L

#3956 Amended environment to return cluster name
  pkg/jx/cmd/environment.go
  pkg/kube/config.go
Labels: approved, lgtm, size/S

#3951 feat: initial support for Alibaba Container Service installation
  pkg/cloud/cloud.go
  pkg/jx/cmd/init.go
Labels: approved, lgtm, size/S

#3957 Fixed the status for listed installed apps when not in gitops mode
  pkg/jx/cmd/get_apps.go
  pkg/jx/cmd/get_apps_test.go
Labels: approved, lgtm, size/S

#3930 chore: enable update-clients
  jenkins-x.yml
  jx/scripts/update-clients.sh
Labels: approved, lgtm, size/S

#3968 Set URLTemplate when external-dns flag is set
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#3908 fix: 'jx step create task --no-apply' gets an error: "Failed to outpu…
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, ok-to-test, size/S

#3912 fix(tekton): Include init containers for things like cred init in logs
  pkg/kube/pod.go
  pkg/tekton/pipeline_info_test.go
Labels: approved, lgtm, size/M

#3965 fix: sanitise go package names
  cmd/codegen/generator/open_api.go
Labels: approved, lgtm, size/S

#3969 chore(tekton): Bump Tekton to May 8 rev
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#3970 fix: correct path to gen-apidocs
  cmd/codegen/generator/docs.go
Labels: approved, lgtm, size/XS

#3938 fix: get the login command working with latest chrome version
  pkg/jx/cmd/login.go
Labels: approved, lgtm, size/XS

#3981 chore: update the version of jx image used by the pipelines to 2.0.128
  jenkins-x-integration.yml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#3980 Fixing bug with parsing helm releases.
  pkg/helm/helm_cli.go
Labels: approved, lgtm, ok-to-test, size/XS

#3922 fix(controller_team): copy team settings for git
  pkg/jx/cmd/controller_team.go
Labels: approved, lgtm, ok-to-test, size/XS

#3973 Two typos in environment controller related commands are fixed
  pkg/jx/cmd/controller_enviornmentcontroller.go
  pkg/jx/cmd/create_addon_environment_controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#3985 fix: Don't barf on pods without container statuses
  pkg/kube/pod.go
Labels: approved, lgtm, size/XS

#3992 fix: make sure log level specified via --log-level gets applied
  pkg/jx/cmd/cmd.go
  pkg/log/log.go
  pkg/log/log_test.go
Labels: approved, lgtm, size/M

#3958 chore(tekton): Make Pipeline/Tasks owned by PipelineActivity
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/M

#3959 chore(tekton): Demonstrate that command can be used for multiline script
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/jenkins-x.yml
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/structure.yml
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/tasks.yml
Labels: approved, lgtm, size/L

#3162 feat(install): added flag to pass ingress-class to exposecontroller
  pkg/config/helm_values.go
  pkg/config/helm_values_test.go
  pkg/config/helm_values_test_with_ingress_class.yaml
Labels: approved, lgtm, ok-to-test, size/M

#3982 chore: enable update-clients
  jenkins-x.yml
  jx/scripts/update-clients.sh
Labels: approved, lgtm, size/XS

#3977 Fix: isolated path for go in codegen
  Makefile.codegen
  cmd/codegen/app/generate_clientset.go
  cmd/codegen/app/generate_docs.go
  cmd/codegen/app/generate_openapi.go
  cmd/codegen/app/generate_options.go
  cmd/codegen/generator/client_set.go
  cmd/codegen/generator/common.go
  cmd/codegen/generator/docs.go
  cmd/codegen/generator/open_api.go
  cmd/codegen/util/go.go
  cmd/codegen/util/go_test.go
Labels: approved, lgtm, size/XL

#4003 Fix: disable parallel testing with pegomock, it doesn’t work
  pkg/jx/cmd/cmd_test_helpers/app_test_helpers.go
  pkg/jx/cmd/delete_app_test.go
  pkg/jx/cmd/step_helm_apply_test.go
  pkg/jx/cmd/upgrade_apps_test.go
Labels: approved, lgtm, size/M

#4002 chore: more resources for the release build
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#3999 Default to configured zone/region on GKE interactive install
  pkg/jx/cmd/opts/gcp.go
Labels: approved, lgtm, size/S

#3888 Get jx upgrade apps working with private helm repos and automerge using gitops
  pkg/apps/gitops.go
  pkg/apps/install.go
  pkg/environments/gitops.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/provider.go
  pkg/gits/provider_fake.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
  pkg/jx/cmd/add_app.go
  pkg/jx/cmd/create_addon_ambassador.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/jx/cmd/create_addon_flagger.go
  pkg/jx/cmd/create_addon_sso.go
  pkg/jx/cmd/create_addon_vault.go
  pkg/jx/cmd/create_pullrequest.go
  pkg/jx/cmd/delete_application.go
  pkg/jx/cmd/edit_extensionsrepository.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/promote.go
  pkg/jx/cmd/upgrade_apps.go
  pkg/pipelinescheduler/generator.go
Labels: approved, lgtm, size/L

#3932 fix: 'jx step create task --no-apply' shouldn't bump version
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/step_tag.go
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/command-as-multiline-script/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/containeroptions-on-pipelineconfig/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/containeroptions-on-pipelineconfig/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/containeroptions-on-pipelineconfig/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/containeroptions-on-pipelineconfig/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/from_yaml/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/kaniko_entrypoint/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/loop-in-buildpack-syntax/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/loop-in-buildpack-syntax/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/loop-in-buildpack-syntax/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/loop-in-buildpack-syntax/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/override-steps/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/override_block_step/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/per_step_container_build_pack/tasks.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipeline.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipelineresources.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/pipelinerun.yml
  pkg/jx/cmd/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
Labels: approved, lgtm, ok-to-test, size/XXL

#4000 Deep copy the source repository so nested info is not lost
  pkg/kube/sourcerepositories.go
Labels: approved, lgtm, size/XS

#3990 fix(cmd): GetJenkinsURL ignores the ns argument
  pkg/jx/cmd/clients/factory.go
Labels: approved, lgtm, ok-to-test, size/XS

#3986 chore: add a codecov target
  Makefile
  README.md
  codecov.yml
  jenkins-x-integration.yml
  jenkins-x.yml
Labels: approved, lgtm, size/M

#3995 fix: Get fork status from repo
  pkg/gits/helpers.go
  pkg/jx/cmd/create_mlquickstart.go
Labels: approved, lgtm, ok-to-test, size/S

#4011 fix: api doc generation
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  hack/run-all-checks.sh
  pkg/apis/jenkins.io/v1/types_pipeline_scheduler.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/openapi/core/openapi_generated.go
Labels: approved, lgtm, size/S

#4005 test: changing path for golint to avoid test failures
  cmd/codegen/util/go_test.go
Labels: approved, lgtm, size/XS

#4009 Print correctly environment name
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/XS

#4014 chore: try to set JAVA_OPTS too
  jenkins-x.yml
Labels: approved, lgtm, size/S

#3993 chore(tekton): Add --context filter option for get build logs and pods
  pkg/builds/build_info.go
  pkg/jx/cmd/get_build_logs.go
  pkg/jx/cmd/get_build_pods.go
  pkg/tekton/pipeline_info.go
Labels: approved, lgtm, size/S

#4017 fix: migrate to the new JXUI addon from CloudBeees
  pkg/jx/cmd/cloudbees.go
  pkg/jx/cmd/create_addon_cloudbees.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/M

#4008 Do not try to create the environments if they already exist
  go.sum
  pkg/jx/cmd/create_env.go
  pkg/jx/cmd/edit_env.go
  pkg/jx/cmd/install.go
  pkg/kube/env.go
  pkg/kube/env_test.go
Labels: approved, lgtm, size/M

#4021 Update .updatebot.yml - updated the dev-env repo to dev-env-base
  .updatebot.yml
Labels: approved, lgtm, size/XS

#4023 Chore: try to enable the client update script
  jenkins-x.yml
  jx/scripts/update-clients.sh
Labels: approved, lgtm, size/S

#4026 chore: do the integration tests during release
  Makefile
Labels: approved, lgtm, size/XS

#4024 fix: improve the upload reporter
  .codecov.yml
  Makefile
  jenkins-x-integration.yml
Labels: approved, lgtm, size/M

#4029 Chore: refactor usage of fork when creating a pull request
  pkg/apps/gitops.go
  pkg/environments/gitops.go
  pkg/gits/helpers.go
  pkg/jx/cmd/create_pullrequest.go
  pkg/jx/cmd/step_git_fork_and_clone.go
Labels: approved, lgtm, size/M

#4025 chore: don’t run the unit tests twice!
  jenkins-x-integration.yml
Labels: approved, lgtm, size/XS

#4028 fix: need to use .462 as .461 was a build failure
  jenkins-x.yml
Labels: approved, lgtm, size/S

#4004 refactor: extracting more functionality into pipelines.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/test_data/step_create_task/PodTemplates.yml
  pkg/tekton/crds.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/XL

#4035 Fix: There was an incompatibility problem between gcloud and go-cloud so we are going to create buckets with gsutil
  pkg/cloud/gke/storage/long_term_storage.go
  pkg/jx/cmd/install.go
Labels: approved, lgtm, size/M

#4015 feat: supporting the new helm3 alpha1
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/jx/cmd/init.go
  pkg/jx/cmd/install.go
  pkg/jx/cmd/opts/helm.go
  pkg/jx/cmd/opts/install.go
Labels: approved, lgtm, size/L

#3997 Type assertion on nil value will fail.
  pkg/vault/vault_client.go
Labels: approved, lgtm, ok-to-test, size/S

#4041 chore: fetch & rebase before doing commit
  jx/scripts/update-website.sh
Labels: approved, lgtm, size/XS

#4042 fix: VERSION is an env var in the `Makefile`
  jx/scripts/update-clients.sh
Labels: approved, lgtm, size/XS

#4043 fix: add the CODECOV_TOKEN
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#4047 Fix: make `jx step changelog` less verbose
  pkg/jx/cmd/step_changelog.go
  pkg/users/git.go
Labels: approved, lgtm, size/M

#4048 fix: rebase needs to be after commit
  jx/scripts/update-website.sh
Labels: approved, lgtm, size/XS

#4054 fix: chart is not fetched if a dir in current directory exists
  pkg/helm/helm_template.go
Labels: approved, lgtm, size/XS

#4057 Chore: move the codecov upload earlier
  .codecov.yml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#4050 fix: remove the 'jx-' prefix from application name
  pkg/kube/version.go
Labels: approved, lgtm, size/XS

#4061 fix: remove the "jx console" command from import message
  pkg/jx/cmd/opts/import.go
Labels: approved, lgtm, size/XS

#4060 fix: print a message instead of an error when vault cannot be listed
  pkg/jx/cmd/get_vault.go
Labels: approved, lgtm, size/XS

#3942 fix: Use Gitlab namespaces API to create repo under the user/org name…
  pkg/gits/gitlab.go
Labels: approved, lgtm, ok-to-test, size/S

#4051 refactor(tekton): restructure of 'step create task'
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/step_create_task.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/step_git_merge.go
  pkg/log/log.go
  pkg/tekton/crds.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/XXL

#4068 fix: oops, not var syntax
  Makefile
Labels: approved, lgtm, size/XS

#4062 Fix a couple of small bugs
  cmd/codegen/generator/open_api.go
  pkg/jx/cmd/shell.go
Labels: approved, lgtm, size/S

#4044 fix: don’t error on force-push
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/M

#4069 chore: use coverage flags more appropriate for integration tests
  Makefile
Labels: approved, lgtm, size/S

#4072 fix: changed a variable that was needed to do a shallow clone on step…
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/XS

#4075 Adding macox to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#4065 fix: improved help message to make it more obvious that only GKE is supported
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/XS

#4067 feat: support for a jx binary that will report coverage
  Makefile
  cmd/jx/app/jx-win.go
  cmd/jx/app/jx.go
  cmd/jx/jx.go
  cmd/jx/jx_test.go
  pkg/jx/cmd/cmd.go
Labels: approved, lgtm, size/L

#4056 fix: attempt to cleanup expect usage
  pkg/gits/provider_test.go
  pkg/jx/cmd/add_app_integration_test.go
  pkg/jx/cmd/add_app_test.go
  pkg/jx/cmd/get_apps_test.go
  pkg/jx/cmd/opts/commands_test.go
  pkg/jx/cmd/step_create_task_test.go
  pkg/jx/cmd/uninstall_test.go
  pkg/jx/cmd/upgrade_apps_test.go
  pkg/kube/env_test.go
  pkg/kube/vault/vault_selector_test.go
  pkg/surveyutils/jsonschema_test.go
  pkg/tests/console_wrapper.go
Labels: approved, lgtm, size/L

#4078 fix(tekton): make sure the repo clone url is properly set
  pkg/jx/cmd/step_create_task.go
Labels: approved, lgtm, size/M

#4064 fix(tekton): Use a working and useful versions directory
  pkg/jx/cmd/step/create/step_create_task_test.go
  pkg/jx/cmd/step/create/test_data/step_create_task/stable_versions/docker/gcr.io/jenkinsxio/builder-go.yml
  pkg/jx/cmd/step/create/test_data/step_create_task/stable_versions/docker/gcr.io/jenkinsxio/builder-maven.yml
  pkg/jx/cmd/step/create/test_data/step_create_task/stable_versions/docker/gcr.io/jenkinsxio/builder-nodejs.yml
Labels: approved, lgtm, size/XS

#4020 Add BatchPipelineActivity information to batch builds and PR builds to get linked in the UI
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/jx/cmd/controller_pipelinerunner.go
  pkg/jx/cmd/step/create/step_create_task.go
  pkg/jx/cmd/step/create/step_create_task_test.go
  pkg/kube/activity.go
  pkg/kube/activity_test.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/XL

#4059 fix: store the dev environment next to other environments in the .jx folder
  pkg/jx/cmd/install.go
  pkg/jx/cmd/install_gitops_integration_test.go
Labels: approved, lgtm, size/M

#4086 fix(cmd): on macOS use 'brew info' to determine latest jx version
  pkg/jx/cmd/upgrade_cli.go
  pkg/jx/cmd/upgrade_cli_test.go
Labels: approved, lgtm, size/L

#4105 check returned error when creating CRDs and extra logging to help fix…
  pkg/jx/cmd/install.go
  pkg/kube/crds.go
Labels: approved, lgtm, size/XS

#4108 Revert args parsing
  cmd/jx/app/jx.go
  pkg/jx/cmd/cmd.go
Labels: approved, lgtm, size/XS

#4111 fix: try another way to set args for covered binary
  cmd/jx/app/jx-win.go
  cmd/jx/app/jx.go
  cmd/jx/jx.go
  cmd/jx/jx_test.go
Labels: approved, lgtm, size/S

#4037 EKS BDD Fixes
  pkg/cloud/amazon/routes.go
  pkg/jx/cmd/create_cluster_eks.go
  pkg/jx/cmd/delete_eks.go
  pkg/jx/cmd/get_eks.go
  pkg/jx/cmd/import.go
  pkg/jx/cmd/install_dependencies.go
  pkg/jx/cmd/opts/domain.go
  pkg/jx/cmd/opts/install.go
  pkg/jx/cmd/step_bdd.go
  pkg/jx/cmd/upgrade_binaries.go
  pkg/kube/services/services.go
  pkg/packages/packages.go
Labels: approved, lgtm, size/M

#4112 chore: removed unused downstream updatebot repo
  .updatebot.yml
Labels: approved, lgtm, size/XS

#4113 Prompt for GKE cluster name
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/create_cluster_gke_terraform.go
Labels: approved, lgtm, size/M

#4121 feat: terraform fixes for v0.12
  pkg/jx/cmd/create_terraform.go
Labels: approved, lgtm, size/XS

#4122 Simplify CLI UX of 'jx create cluster'
  pkg/jx/cmd/create_cluster_gke.go
  pkg/jx/cmd/install.go
  pkg/util/color.go
Labels: approved, lgtm, size/L

#4123 chore: report branch correctly
  Makefile
Labels: approved, lgtm, size/S

#4116 feat: adding retries to Stages (tekton based solution)
  pkg/jx/cmd/step/create/test_data/step_create_task/command-as-multiline-script/jenkins-x.yml
  pkg/jx/cmd/step/create/test_data/step_create_task/command-as-multiline-script/pipeline.yml
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, ok-to-test, size/S

#4079 chore: collect test results using junit
  .gitignore
  Makefile
  jenkins-x-integration.yml
Labels: approved, lgtm, size/L

#4128 Parallelism
  Makefile
  jenkins-x-bdd.yml
  jenkins-x-integration.yml
Labels: approved, lgtm, size/S

#4139 chore: bump up ram a bit to try to achieve -p2
  jenkins-x-integration.yml
Labels: approved, lgtm, size/XS

#4141 Fix missing cluster name
  pkg/jx/cmd/create_cluster_gke.go
Labels: approved, lgtm, size/XS
