Repository jenkins-x/jx, pull requests merged in 2019-07, with the labels that each got.

#4507 fix: support legacy prow configuration mode
  pkg/apis/jenkins.io/v1/types_environment.go
Labels: approved, lgtm, size/XS

#4508 fix: ensuring *.json files are excluded from git during 'create terraform'
  pkg/cmd/create/create_terraform.go
Labels: approved, lgtm, size/XS

#4512 chore: replace updatebot with jx step create pr
  jx/scripts/update-bot.sh
Labels: approved, lgtm, size/S

#4493 feat(versions): Add support for semantic releases
  go.mod
  pkg/cmd/step/step_changelog.go
  pkg/cmd/step/step_next_version.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/gitter.go
  pkg/gits/provider_fake.go
  pkg/semrel/semrel.go
Labels: approved, lgtm, size/XL

#4460 chore(tekton): Forgot to add build number to PRI name
  pkg/tekton/pipeline_info.go
Labels: approved, lgtm, size/XS

#4520 fix: get build logs batch mode
  pkg/cmd/get/get_build_logs.go
Labels: approved, lgtm, size/S

#4521 chore: only fetch the current tag
  Makefile
Labels: approved, lgtm, size/XS

#4522 chore: fix the path to the jx binary
  jx/scripts/update-bot.sh
Labels: approved, lgtm, size/S

#4527 fix: add a path to enable semantic releases
  pkg/cmd/controller/controller_pipelinerunner.go
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/S

#4516 fix: Adding brew config for goreleaser
  .goreleaser.yml
  .updatebot.yml
  jx/scripts/update-bot.sh
Labels: approved, lgtm, size/M

#4519 feat: Install type config enabled
  pkg/cmd/create/install.go
Labels: approved, lgtm, size/S

#4524 feat: long term storage config enable
  pkg/cloud/gke/storage/long_term_storage.go
  pkg/cmd/create/create_vault.go
  pkg/cmd/create/install.go
Labels: approved, lgtm, size/S

#4525 fix(tekton): Look for run by labels, not name
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/cmd/step/create/step_create_task.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/S

#4529 chore: set default values for external-dns during jx boot
  pkg/cmd/opts/domain.go
  pkg/cmd/step/create/step_create_install_values.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
  pkg/config/zz_generated.deepcopy.go
  pkg/helm/values_tree.go
Labels: approved, lgtm, size/L

#4560 fix: Use /usr/local/git/bin in path for lint build
  jenkins-x-lint.yml
Labels: approved, lgtm, size/XS

#4552 fix: write the directory to stdout
  jx/scripts/update-clients.sh
  pkg/cmd/step/git/step_git_fork_and_clone.go
Labels: approved, lgtm, size/XS

#4546 fix(install): use YAML import mode for Tekton
  pkg/cmd/create/install.go
Labels: approved, lgtm, ok-to-test, size/XS

#4556 fix: Remove duplicate branches from post submits
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_repogroup_scheduler/config.yaml
  pkg/pipelinescheduler/builder.go
Labels: approved, lgtm, size/S

#4558 feat: Enable skip install config
  pkg/cmd/create/create_cluster.go
Labels: approved, lgtm, size/S

#4562 chore: minor logging improvements to git helper
  pkg/cmd/step/git/step_git_merge.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
Labels: approved, lgtm, size/M

#4357 Created a step to handle JsonPatch syntax queries into Configmaps and a way to apply them into second level embedded resources
  go.mod
  pkg/cmd/cloudbees/cloudbees.go
  pkg/cmd/config/patch_configmap.go
  pkg/cmd/config/patch_configmap_test.go
  pkg/cmd/step.go
  pkg/cmd/test_data/step_config/config_map1.txt
Labels: approved, lgtm, size/L

#4345 fix: "start pipeline PipelineName"
  pkg/cmd/start/start_pipeline.go
Labels: approved, lgtm, ok-to-test, size/M

#4535 fix: test application deletion on static Jenkins
  go.mod
  go.sum
  pkg/cmd/clients/mocks/jenkins_client.go
  pkg/cmd/deletecmd/delete_application.go
  pkg/cmd/deletecmd/delete_application_test.go
Labels: approved, lgtm, size/XXL

#4584 fix(test): making sure original namespace is reset in step verify pre…
  pkg/cmd/step/verify/step_verify_preinstall_integration_test.go
Labels: approved, lgtm, size/M

#4585 feat: extend 'jx gc gke' to clear out service accounts
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/L

#4569 fix(tekton): deriving build related meta information from pull refs
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/cmd/step/create/step_create_meta_pipeline_test.go
  pkg/cmd/step/create/step_create_task.go
  pkg/tekton/metapipeline/metapipeline.go
  pkg/tekton/metapipeline/metapipeline_test.go
Labels: approved, lgtm, size/L

#4589 feat: jx gc gke now removes iam bindings
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/L

#4602 fix(tekton): making sure the right prow job id is passed to meta pipl…
  pkg/cmd/controller/pipelinerunner.go
  pkg/cmd/controller/pipelinerunner_test.go
Labels: approved, lgtm, size/M

#4608 fix(tekton): skiping git merge step if there are no pull refs to merge
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/tekton/metapipeline/metapipeline.go
  pkg/tekton/metapipeline/metapipeline_test.go
Labels: approved, lgtm, size/M

#4607 fix: standardise build images
  jenkins-x-images.yml
  jenkins-x-integration.yml
  jenkins-x-lint.yml
  jenkins-x-tekton.yml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#4597 feat: 'jx gc gke' can select a project
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/M

#4622 chore: updated help text for 'jx boot'
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/S

#4601 feat: support tracking transitive dependencies
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_release.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/cmd/opts/releases.go
  pkg/cmd/opts/releases_test.go
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/step_changelog.go
  pkg/dependencymatrix/matrix.go
  pkg/dependencymatrix/matrix_test.go
  pkg/dependencymatrix/testdata/new_matrix/matrix.golden.yaml
  pkg/dependencymatrix/testdata/one_degree_matrix/matrix.golden.yaml
  pkg/dependencymatrix/testdata/one_degree_matrix/matrix.yaml
  pkg/dependencymatrix/testdata/simple_matrix/matrix.golden.yaml
  pkg/dependencymatrix/testdata/simple_matrix/matrix.yaml
  pkg/dependencymatrix/testdata/two_degree_matrix/matrix.golden.yaml
  pkg/dependencymatrix/testdata/two_degree_matrix/matrix.yaml
  pkg/dependencymatrix/testdata/two_paths_matrix/matrix.golden.yaml
  pkg/dependencymatrix/testdata/two_paths_matrix/matrix.yaml
  pkg/dependencymatrix/updates.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/provider.go
  pkg/gits/provider_fake.go
  pkg/util/types.go
Labels: approved, lgtm, size/XXL

#4611 fix(tests): wrap a flaky test in retry
  pkg/gits/provider_test.go
Labels: approved, lgtm, size/L

#4623 fix: Standardise build images
  jenkins-x-bdd.yml
Labels: approved, lgtm, size/XS

#4582 fix: choose the most recent PR to rebase
  pkg/gits/helpers.go
Labels: approved, lgtm, size/S

#4606 fix: pass the semantic release flag through
  pkg/cmd/controller/pipelinerunner.go
Labels: approved, lgtm, size/XS

#4578 fix: jx create quickstart "--org" and "--name" options doesn't work
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#4600 chore: Delete bdd clusters that have old build numbers
  pkg/cloud/gke/gcloud.go
  pkg/cmd/gc/gc_gke.go
  pkg/cmd/step/e2e/step_e2e_gc.go
  pkg/cmd/step/e2e/step_e2e_gc_test.go
  pkg/cmd/step/e2e/step_e2e_label.go
Labels: approved, lgtm, size/L

#4567 fix: disable brew update by goreleaser
  .goreleaser.yml
Labels: approved, lgtm, size/XS

#4632 chore: expose PULL_BASE_SHA to jx start pipeline
  pkg/cmd/start/start_pipeline.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/provider.go
  pkg/gits/provider_fake.go
  pkg/util/types.go
Labels: approved, lgtm, size/L

#4638 fix: Updating to builder-jx
  jenkins-x-bdd.yml
  jenkins-x-integration.yml
  jenkins-x-tekton.yml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#4605 fix: jx create quickstart --org and --name options
  pkg/cmd/create/create_quickstart.go
  pkg/gits/git_repo.go
Labels: approved, lgtm, size/S

#4628 fix(tekton): making sure no-apply and out-dir can also be set program…
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/M

#4637 feat: add jx step create pr make
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/create/pr/step_create_pr_make.go
  pkg/cmd/step/create/pr/step_create_pr_regex.go
Labels: approved, lgtm, size/L

#4634 fix(tekton): Use pod template name for default image
  pkg/tekton/syntax/constants.go
Labels: approved, lgtm, size/XS

#4572 feat: Brew package version update using new create pullrequest [command]
  jx/scripts/update-bot.sh
Labels: approved, lgtm, size/S

#4644 fix: set the release id when a new release is created
  pkg/gits/github.go
Labels: approved, lgtm, size/XS

#4575 fix: Isolate machine-learning quickstarts from conventional quickstarts
  pkg/cmd/create/create_mlquickstart.go
  pkg/cmd/create/create_quickstart.go
  pkg/cmd/get/get_quickstarts.go
  pkg/quickstarts/model_test.go
  pkg/quickstarts/quickstarts.go
  pkg/quickstarts/types.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: approved, lgtm, ok-to-test, size/L

#4646 fix: removing override of validate options
  pkg/cmd/step/create/pr/step_create_pr_brew.go
Labels: approved, lgtm, size/XS

#4643 fix: If no pods are found for a pipeline, don't loop looking for logs
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/M

#4653 fix: Fixed jx get build logs for old pipeline runs
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
  pkg/logs/test_data/legacy_pipeline_run/pipelinerun.yml
  pkg/logs/test_data/legacy_pipeline_run/pods.yml
Labels: approved, lgtm, size/XXL

#4629 fix: git server url is hardcoded in pipelinerunner #4588
  pkg/cmd/controller/pipelinerunner.go
Labels: approved, lgtm, ok-to-test, size/M

#4655 fix: couple of fixes for new updatebot
  pkg/cmd/step/create/pr/step_create_pr.go
Labels: approved, lgtm, size/XS

#4658 feat: Changed the bucket calls to use gsutil to avoid authentication issues
  pkg/cloud/gke/gcloud.go
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/get/get_build_logs_test.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/M

#4659 fix(tekton): Resolve all step images via the version stream
  pkg/cmd/opts/version.go
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/cmd/step/create/step_create_task.go
  pkg/tekton/metapipeline/metapipeline.go
  pkg/tekton/metapipeline/metapipeline_test.go
  pkg/tekton/metapipeline/test_data/stable_versions/docker/maven.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/stable_versions/docker/gcr.io/jenkinsxio/builder-go.yml
  pkg/tekton/syntax/test_data/stable_versions/docker/gcr.io/jenkinsxio/builder-maven.yml
  pkg/tekton/syntax/test_data/stable_versions/docker/gcr.io/jenkinsxio/builder-nodejs.yml
  pkg/tekton/syntax/test_data/stable_versions/docker/some-image.yml
  pkg/version/version_data.go
Labels: approved, lgtm, size/L

#4647 feat: add jx step verify dependencies
  pkg/cmd/step/verify/step_verify.go
  pkg/cmd/step/verify/step_verify_dependencies.go
  pkg/dependencymatrix/matrix.go
  pkg/dependencymatrix/matrix_test.go
  pkg/dependencymatrix/testdata/one_degree_matrix/dependency-matrix/matrix.yaml
  pkg/dependencymatrix/testdata/simple_matrix/dependency-matrix/matrix.yaml
  pkg/dependencymatrix/testdata/two_degree_matrix/dependency-matrix/matrix.yaml
  pkg/dependencymatrix/testdata/two_paths_matrix/dependency-matrix/matrix.yaml
  pkg/dependencymatrix/testdata/two_paths_matrix_inconsistent/dependency-matrix/matrix.yaml
  pkg/dependencymatrix/testdata/two_versions_two_paths_matrix_inconsistent/dependency-matrix/matrix.yaml
  pkg/dependencymatrix/verify.go
  pkg/dependencymatrix/verify_test.go
  pkg/gits/github.go
Labels: approved, lgtm, size/L

#4677 chore: Enable logging from the GC script so its easier to see failed cleanup
  pkg/cmd/step/e2e/step_e2e_gc.go
Labels: approved, lgtm, size/XS

#4678 feat: support for <generated:hmac> in schema
  pkg/surveyutils/jsonschema.go
  pkg/surveyutils/jsonschema_test.go
  pkg/surveyutils/test_data/generatedHmacToken.test.schema.json
Labels: approved, lgtm, size/M

#4695 fix: various fixes for the fork / rebase logic
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/gits/errors.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/github.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
Labels: approved, lgtm, size/M

#4687 chore: remove deprecated terraform command to avoid confusion
  pkg/cmd/create/create_cluster_gke.go
  pkg/cmd/create/create_cluster_gke_terraform.go
Labels: approved, lgtm, size/L

#4696 feat: some improvements on jx get build logs filters
  pkg/cmd/get/get_build_logs.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/M

#4703 fix: Make Environment Controller work with private repo
  pkg/cmd/create/create_addon_environment_controller.go
Labels: approved, lgtm, ok-to-test, size/XS

#4710 fix: handle spaces properly
  pkg/cmd/step/create/pr/step_create_pr_chart.go
Labels: approved, lgtm, size/S

#4590 chore: Move tekton and bdd baseline coverage into separate pipelines
  jenkins-x.yml
Labels: approved, lgtm, size/L

#4704 fix: correct user for repo
  pkg/gits/github.go
  pkg/gits/helpers.go
  pkg/gits/provider.go
Labels: approved, lgtm, size/XS

#4711 fix: allow the tag name to be specified on the changelog to work with…
  pkg/cmd/step/step_changelog.go
Labels: approved, lgtm, size/S

#4718 fix: don’t retag in step changelog
  pkg/cmd/step/step_changelog.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
Labels: approved, lgtm, size/L

#4702 chore: trim requirement inputs
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/XS

#4724 fix(tekton): making sure GitMergeImage gets resolved via version stream
  pkg/cmd/step/create/test_data/step_create_task/stable_versions/docker/gcr.io/jenkinsxio/builder-jx.yml
  pkg/tekton/metapipeline/test_data/stable_versions/docker/gcr.io/jenkinsxio/builder-jx.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/test_data/stable_versions/docker/gcr.io/jenkinsxio/builder-jx.yml
  pkg/version/test_data/jenkins-x-versions/docker/fubar.yml
  pkg/version/test_data/jenkins-x-versions/docker/gcr.io/jenkinsxio/builder-jx.yml
  pkg/version/test_data/jenkins-x-versions/docker/susfu.yml
  pkg/version/version_data.go
  pkg/version/version_data_test.go
Labels: approved, lgtm, size/L

#4730 fix: set provider to correct value
  pkg/cmd/step/create/step_create_install_values.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/S

#4737 fix: do not try to upgrade CLI if current version is already up to date
  pkg/cmd/version.go
Labels: approved, lgtm, size/M

#4732 fix: select install type before checkFlags
  pkg/cmd/create/install.go
Labels: approved, lgtm, size/S

#4736 feat: Add version stream support in to boot
  pkg/cmd/boot/boot.go
  pkg/cmd/cmd.go
  pkg/cmd/create/create_addon_environment_controller.go
  pkg/cmd/create/create_addon_vault.go
  pkg/cmd/create/create_vault.go
  pkg/cmd/create/install.go
  pkg/cmd/get/get_stream.go
  pkg/cmd/opts/helm.go
  pkg/cmd/opts/install.go
  pkg/cmd/profile/profile.go
  pkg/cmd/step.go
  pkg/cmd/step/boot/step_boot_upgrade.go
  pkg/cmd/step/create/pr/step_create_pr_versions.go
  pkg/cmd/step/get/step_get_version_changeset.go
  pkg/cmd/step_bdd.go
  pkg/config/install_requirements.go
  pkg/config/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#4743 feat: handle different schemes on get build logs
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/M

#4734 fix: Ensure we are tracking a remote branch before attempting a pull …
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/jenkinsfile/gitresolver/buildpack.go
  pkg/jenkinsfile/gitresolver/buildpack_test.go
Labels: approved, lgtm, size/L

#4733 fix: amend PR title
  pkg/gits/helpers.go
Labels: approved, lgtm, size/S

#4745 fix: dedupe and collapse dependency updates
  pkg/cmd/step/step_changelog.go
  pkg/cmd/step/step_changelog_test.go
  pkg/cmd/step/test_data/changelog/platform.golden.yaml
  pkg/cmd/step/test_data/changelog/platform.yaml
  pkg/gits/commits.go
Labels: approved, lgtm, size/XL

#4749 chore: Refactor step boot to contain base command
  pkg/cmd/boot/boot.go
  pkg/cmd/step.go
  pkg/cmd/step/boot/step_boot.go
  pkg/cmd/step/boot/step_boot_upgrade.go
  pkg/cmd/step/boot/step_boot_vault.go
Labels: approved, lgtm, size/M

#4765 fix: don’t add a filter for “”
  pkg/gits/git_cli.go
  pkg/gits/git_cli_test.go
Labels: approved, lgtm, size/M

#4766 fix: Use existing images for release pipeline
  jenkins-x.yml
Labels: approved, lgtm, size/S

#4768 fix: Use a jx image that actually exists.
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#4773 fix: Push jenkinsxio/jx:VERSION to docker.io, not gcr.io
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#4776 fix: create the version resolver from the requirements versions strea…
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#4775 fix: jx step boot upgrade should check all chart locations
  pkg/cloud/gke/gcloud.go
  pkg/cmd/boot/boot.go
  pkg/cmd/opts/install.go
  pkg/cmd/profile/profile.go
  pkg/cmd/step/boot/step_boot_upgrade.go
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/config/install_requirements.go
  pkg/config/zz_generated.deepcopy.go
  pkg/util/downloads.go
Labels: approved, lgtm, size/L

#4777 fix: Allow updating multiple charts in a single `jx step create pr chart`
  pkg/cmd/step/create/pr/step_create_pr_chart.go
Labels: approved, lgtm, size/M

#4759 chore: Suggest currently connected cluster name
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/S

#4791 fix: GC GKE - IAM Policy bindings
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/M

#4798 fix: improve text for long term storage
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/S

#4800 fix: use current cluster in jx boot
  pkg/cloud/gke/helper.go
  pkg/cloud/gke/helper_test.go
  pkg/cmd/create/create_cluster_gke.go
  pkg/cmd/create/create_domain_gke.go
  pkg/cmd/create/create_vault.go
  pkg/cmd/create/install.go
  pkg/cmd/deletecmd/delete_vault.go
  pkg/cmd/gc/gc_gke.go
  pkg/cmd/opts/bucket.go
  pkg/cmd/opts/gcp.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/L

#4796 chore: change http:// links to https:// in README.md
  README.md
Labels: approved, lgtm, size/S

#4811 fix: Make sure helm is setup correctly when using boot
  pkg/cmd/boot/boot.go
  pkg/cmd/create/create_addon_vault.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/S

#4813 fix: log the error
  pkg/cmd/step/helm/step_helm_apply.go
Labels: approved, lgtm, size/XS

#4818 fix: preinstall requirements error messages
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/XS

#4824 fix: Disable manual promotion test in bdd context
  jx/scripts/ci.sh
Labels: approved, lgtm, size/XS

#4826 fix: add optional git server, name and kind
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#4817 feat: Verify boot cluster connection
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/S

#4835 fix(tekton): Look for more pods when running `jx get build logs`
  pkg/apis/jenkins.io/v1/types_pipelinestructure.go
  pkg/builds/helpers.go
  pkg/builds/helpers_test.go
  pkg/builds/test_data/get_pipelinerun_pods/pods.yml
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/get/get_build_logs_test.go
  pkg/cmd/get/test_data/get_build_logs/multiple_stages/activity.yml
  pkg/cmd/get/test_data/get_build_logs/multiple_stages/pipelinerun.yml
  pkg/cmd/get/test_data/get_build_logs/multiple_stages/pods.yml
  pkg/cmd/get/test_data/get_build_logs/multiple_stages/structure.yml
  pkg/cmd/get/test_data/get_build_logs/tekton_build_logs/pod.yml
  pkg/cmd/get/test_data/get_build_logs/tekton_build_logs/structure.yml
  pkg/cmd/get/test_data/get_build_logs/tekton_build_logs_legacy_label/pod.yml
  pkg/cmd/get/test_data/get_build_logs/tekton_build_logs_legacy_label/structure.yml
  pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pipelineruns.yml
  pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pods.yml
  pkg/cmd/get/test_data/get_build_logs/with-metapipeline/structures.yml
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
  pkg/logs/test_data/legacy_pipeline_run/pipelinerun.yml
  pkg/logs/test_data/legacy_pipeline_run/pipelineruns.yml
  pkg/logs/test_data/legacy_pipeline_run/pods.yml
  pkg/logs/test_data/legacy_pipeline_run/structures.yml
  pkg/logs/test_data/multiple_stages/pipelinerun.yml
  pkg/logs/test_data/multiple_stages/pods.yml
  pkg/logs/test_data/multiple_stages/structure.yml
  pkg/logs/test_data/pipelinerun.yml
  pkg/logs/test_data/pipelineruns.yml
  pkg/logs/test_data/pods.yml
  pkg/logs/test_data/structures.yml
Labels: approved, lgtm, size/XXL

#4799 feat: create production environment while running bdd tests
  pkg/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#4841 fix: Just push to jx-docs once in update-website.sh
  jx/scripts/update-website.sh
Labels: approved, lgtm, size/XS

#4842 feat: added a step that takes *.junit.xml files and create an HTML report
  pkg/cmd/step.go
  pkg/cmd/step/report/step_report.go
  pkg/cmd/step/report/step_report_test.go
  pkg/cmd/step/report/test_data/multiple_reports/create_quickstarts.junit.xml
  pkg/cmd/step/report/test_data/multiple_reports/import_applications.junit.xml
  pkg/cmd/step/report/test_data/single_report/import_applications.junit.xml
  pkg/reportingtools/XUnitViewer.go
  pkg/reportingtools/mocks/xunitclient.go
  pkg/reportingtools/xunit_client.go
Labels: approved, lgtm, size/XL

#4845 fix(tekton): Make sure the effective pipeline yml contains release.setVersion
  pkg/cmd/step/syntax/step_syntax_effective.go
  pkg/cmd/step/syntax/step_syntax_effective_test.go
Labels: approved, lgtm, size/M

#4855 chore: Push the go-maven builder during image generation
  Dockerfile.builder-go-maven
  jenkins-x-images.yml
Labels: approved, lgtm, size/XS

#4846 fix: Don't fail the whole GKE GC for a resource that's already deleted
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/XS

#4823 fix: refactor ForkAndPullRepo
  pkg/apps/gitops.go
  pkg/apps/install.go
  pkg/cmd/add/add_app.go
  pkg/cmd/add/add_app_integration_test.go
  pkg/cmd/add/add_app_test.go
  pkg/cmd/controller/controller_workflow.go
  pkg/cmd/controller/controller_workflow_integration_test.go
  pkg/cmd/create/create_pullrequest.go
  pkg/cmd/deletecmd/delete_app.go
  pkg/cmd/deletecmd/delete_app_test.go
  pkg/cmd/deletecmd/delete_application.go
  pkg/cmd/deletecmd/delete_branch.go
  pkg/cmd/get/get_apps.go
  pkg/cmd/get/get_apps_test.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/promote/promote.go
  pkg/cmd/promote/promote_test.go
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/step_create_values_test.go
  pkg/cmd/step/get/step_get_version_changeset_test.go
  pkg/cmd/step/git/step_git_fork_and_clone.go
  pkg/cmd/step/helm/step_helm_apply_test.go
  pkg/cmd/step/scheduler/step_scheduler_config_apply.go
  pkg/cmd/step/scheduler/step_scheduler_config_apply_test.go
  pkg/cmd/step/scheduler/step_scheduler_config_migrate.go
  pkg/cmd/step/scheduler/step_scheduler_config_migrate_test.go
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/cmd/testhelpers/app_test_helpers.go
  pkg/cmd/upgrade/upgrade_apps.go
  pkg/cmd/upgrade/upgrade_apps_test.go
  pkg/environments/gitops.go
  pkg/gits/git_cli.go
  pkg/gits/git_cli_test.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/github.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/gits/provider_fake.go
  pkg/pipelinescheduler/generator.go
  pkg/users/git_test.go
Labels: approved, lgtm, size/XXL

#4742 fix: Added Azure command line flag to allow specifying an Azure subscription id
  pkg/cloud/aks/aks.go
  pkg/cloud/aks/aks_test.go
  pkg/cmd/create/install.go
Labels: approved, lgtm, ok-to-test, size/L

#4832 fix: use the upgrade addon prow command
  pkg/cmd/upgrade/upgrade_addon_prow.go
  pkg/cmd/upgrade/upgrade_addons.go
Labels: approved, lgtm, size/M

#4725 fix: Typo in create var dialog
  pkg/cmd/create/create_variable.go
Labels: approved, lgtm, ok-to-test, size/XS

#4859 feat: create dev repo during pipeline & pr config
  pkg/apps/gitops.go
  pkg/cmd/boot/boot.go
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/git/step_git_fork_and_clone.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/config/install_requirements.go
  pkg/environments/gitops.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/github.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/gits/provider_fake.go
Labels: approved, lgtm, size/XL

#4863 fix: jx boot fails to create storage
  Makefile
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/gcloud_test.go
Labels: approved, lgtm, size/S

#4872 fix: need to duplicate the repo first
  pkg/apps/gitops.go
  pkg/cmd/boot/boot.go
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/git/step_git_fork_and_clone.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/environments/gitops.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
Labels: approved, lgtm, size/L

#4875 fix: handle branch as committing for duplicating git repo
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
Labels: approved, lgtm, size/L

#4857 fix(tekton): Properly handle non-step overrides for packs using jx syntax
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/overrides-with-buildpack-using-jenkins-x-syntax/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/packs/jx-syntax-in-buildpack/pipeline.yaml
  pkg/cmd/step/syntax/step_syntax_effective.go
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/jenkinsfile/pipeline.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/XXL

#4879 feat: rebase existing PR during jx boot
  pkg/boot/constants.go
  pkg/cmd/create/create_pullrequest.go
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/environments/gitops.go
  pkg/gits/helpers.go
Labels: approved, lgtm, size/M

#4890 docs: remove former logo from README.md
  README.md
Labels: approved, lgtm, size/XS

#4753 fix: jx import does not respect --git-username and --git-api-token
  pkg/auth/auth_config.go
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, ok-to-test, size/S

#4874 feat: allowing static-jenkins flag when using terraform
  pkg/cmd/create/create_cluster_gke.go
  pkg/cmd/create/create_terraform.go
  pkg/cmd/create/create_terraform_gke.go
Labels: approved, lgtm, size/S

#4880 fix: don’t set push urls as remotes
  pkg/cmd/importcmd/import.go
  pkg/cmd/opts/pullrequest.go
  pkg/cmd/step/get/step_get_version_changeset_test.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/collector/git_collector.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/kube/env.go
Labels: approved, lgtm, size/L

#4869 feat: add tests to create PR and refactor
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/gits/operations/pull_request_op.go
  pkg/gits/operations/pull_request_op_test.go
Labels: approved, lgtm, size/XL

#4885 fix: lets use the tag not version for version stream in boot
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#4900 fix: run `helm repo update` when installing ingress
  pkg/cmd/initcmd/init.go
Labels: approved, lgtm, size/XS

#4893 fix: Upgrade Prow in GitOps cluster
  pkg/cmd/create/create_addon_prow.go
  pkg/cmd/create/install.go
  pkg/cmd/opts/helm.go
  pkg/cmd/opts/install.go
  pkg/cmd/upgrade/upgrade_addon_prow.go
  pkg/helm/helm_helpers.go
Labels: approved, lgtm, size/L

#4858 chore(tekton): Add BDD test using jenkins-x.yml to Tekton context
  jx/bdd/tekton/ci.sh
Labels: approved, lgtm, size/XS

#4896 fix: refactor create pull request
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/provider_fake.go
Labels: approved, lgtm, size/XL

#4883 fix: Exponential backoff while waiting for DNS to propagate
  pkg/cmd/preview/preview.go
Labels: approved, lgtm, ok-to-test, size/S

#4915 feat: let's ignore the charts that have no file when getting apps instead of forcing them
  pkg/apps/gitops.go
Labels: approved, lgtm, size/S

#4916 fix: bitbucket server should populate Project + Org on GetRepository
  pkg/gits/bitbucket_server.go
Labels: approved, lgtm, size/S

#4919 fix: allow boot config git ref to be overridden
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/M

#4920 feat: check if env var exists before overridding
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/M

#4901 fix: fixed a bug that made boot fail when a generated bucket name ends with '-'
  pkg/cloud/gke/storage/bucket_provider.go
  pkg/cloud/gke/storage/bucket_provider_test.go
  pkg/cloud/gke/storage/long_term_storage.go
  pkg/cloud/gke/storage/long_term_storage_test.go
Labels: approved, lgtm, size/M
