Repository jenkins-x/jx, pull requests merged in 2019-08, with the labels that each got.

#4914 fix(tekton): PipelineResource should be reused for all builds on branch
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipeline.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipelineresources.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/pipelinerun.yml
  pkg/tekton/metapipeline/metapipeline.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/M

#4929 chore: Add jenkins-x-builders-ml to update-bot.sh
  jx/scripts/update-bot.sh
Labels: approved, lgtm, size/XS

#4911 fix: support private repos
  pkg/cmd/step/git/step_git_validate.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/config/install_requirements.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
Labels: approved, lgtm, size/S

#4927 fix: fix the jx changelog for now
  pkg/cmd/step/git/step_git_merge_test.go
  pkg/cmd/step/step_changelog.go
  pkg/cmd/step/step_next_version.go
  pkg/gits/git_cli.go
  pkg/gits/git_cli_test.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/gits/testhelpers/testhelpers.go
  pkg/jenkinsfile/gitresolver/buildpack_test.go
Labels: approved, lgtm, size/XL

#4928 feat: only check for tags on the main repository when creating the environments
  pkg/cmd/boot/boot.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
Labels: approved, lgtm, size/L

#4930 fix: Enable batch mode in delete devpod
  pkg/cmd/deletecmd/delete_devpod.go
Labels: approved, lgtm, size/S

#4934 fix: moved error check to ensure that namespace is verified
  .secrets.baseline
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/S

#4946 fix: updated incorrect requirements environment variable
  .secrets.baseline
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/M

#4939 fix(tekton): Include logs for builds with just init containers running
  pkg/tekton/pipelines.go
  pkg/tekton/pipelines_test.go
Labels: approved, lgtm, size/M

#4947 fix: removed \n from logging statements
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/M

#4941 feat: moved the boot configuration to step helm to be used by helm build too
  pkg/cmd/step/helm/step_helm.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/helm/step_helm_build.go
Labels: approved, lgtm, size/L

#4962 fix: add a CLI command to create a PR for go module updates
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/create/pr/step_create_pr_go.go
  pkg/cmd/step/create/pr/step_create_pr_regex.go
Labels: approved, lgtm, size/L

#4892 feat: add jx step git close
  pkg/cmd/get/get_issues.go
  pkg/cmd/opts/git.go
  pkg/cmd/step/git/step_git.go
  pkg/cmd/step/git/step_git_close.go
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/constants.go
  pkg/gits/errors.go
  pkg/gits/features/disable_features.go
  pkg/gits/features/disable_features_test.go
  pkg/gits/gerrit.go
  pkg/gits/git_url.go
  pkg/gits/git_url_test.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/gitlab.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/operations/pull_request_op.go
  pkg/gits/provider.go
  pkg/gits/provider_fake.go
  pkg/issues/constants.go
Labels: approved, lgtm, size/XXL

#4959 chore: remove codecov
  .codecov.yml
  Makefile
  README.md
  cmd/jx/codecov/info.go
  cmd/jx/jx_test.go
  hack/codecov-validate.sh
  hack/run-all-checks.sh
  jenkins-x-bdd.yml
  jenkins-x-integration.yml
  jenkins-x.yml
Labels: approved, lgtm, size/L

#4977 fix: updated logic to correct scenario
  pkg/cmd/preview/preview.go
Labels: approved, lgtm, size/XS

#4985 fix: making sure verify-generation-complete fails for new untracked f…
  Makefile.codegen
Labels: approved, lgtm, size/XS

#4982 fix: make promote pr title & commit a semantic style message
  pkg/cmd/promote/promote.go
Labels: approved, lgtm, size/XS

#4991 fix(tekton): Metapipeline resource name should be consistent.
  pkg/tekton/metapipeline/metapipeline.go
Labels: approved, lgtm, size/XS

#4975 fix: check boot cluster exists
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#4997 fix: Remove codecov from tekton context
  jenkins-x-bdd.yml
  jenkins-x-tekton.yml
Labels: approved, lgtm, size/M

#4998 chore: fix spelling of healthy
  pkg/jenkins/health.go
Labels: approved, lgtm, ok-to-test, size/XS

#4887 chore: Fix typos and grammar
  pkg/cmd/create/create_jenkins_token.go
Labels: approved, lgtm, size/S

#5013 fix: revert bad change in quoting that seems to cause issues
  charts/jx/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#5014 feat: allow gitconfig to be configured from the environment
  pkg/cmd/step/git/step_git_validate.go
Labels: approved, lgtm, size/S

#5003 feat(tekton): Add flag to distribute parallel stages across nodes
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/pipeline.yml
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/pipelineresources.yml
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/pipelinerun.yml
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/structure.yml
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/tasks.yml
  pkg/tekton/metapipeline/metapipeline.go
  pkg/tekton/pipelines.go
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
  pkg/tekton/syntax/test_data/node_distributed_parallel_stages/jenkins-x.yml
Labels: approved, lgtm, size/XL

#5017 fix: auto clone boot config failing
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#5022 fix: Push an updated PR before updating its title and body
  pkg/gits/helpers.go
Labels: approved, lgtm, size/XS

#5021 fix: Fix gh-pages for log storage in a couple ways
  pkg/collector/git_collector.go
Labels: approved, lgtm, size/XS

#5030 feat: added a way to read logs from HTTP/HTTPS URLs back
  pkg/cmd/get/get_build_logs.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/M

#5032 fix: Update images used in release pipeline for double PR fix
  jenkins-x-bdd.yml
  jenkins-x-images.yml
  jenkins-x-integration.yml
  jenkins-x-tekton.yml
  jenkins-x.yml
Labels: approved, lgtm, size/M

#4986 chore: add debug logging for vault
  pkg/cmd/clients/factory.go
  pkg/kube/services/services.go
  pkg/kube/vault/vault.go
  pkg/kube/vault/vault_factory.go
Labels: approved, lgtm, size/M

#4609 chore: generate html report for tests and upload it
  jenkins-x-bdd.yml
  jenkins-x-tekton.yml
Labels: approved, lgtm, size/M

#5011 fix: polish SourceRepository CRD display
  pkg/kube/crds.go
Labels: approved, lgtm, size/S

#5031 fix: docker registry is the host, owner is the org
  pkg/cmd/opts/docker.go
Labels: approved, lgtm, ok-to-test, size/XS

#4852 fix: separating global flag options and install/create cluster flags
  pkg/cmd/cmd.go
  pkg/cmd/create/create_lile.go
  pkg/cmd/create/create_micro.go
  pkg/cmd/create/install.go
  pkg/cmd/opts/common.go
  pkg/cmd/step/create/step_create_meta_pipeline.go
  pkg/cmd/step/scheduler/step_scheduler_config_apply.go
  pkg/cmd/step/scheduler/step_scheduler_config_migrate.go
  pkg/cmd/step/step_custom_pipeline.go
  pkg/cmd/step/syntax/step_syntax_effective.go
  pkg/cmd/upgrade/upgrade_cli.go
Labels: approved, lgtm, size/M

#4924 fix: print the quickstarts that match
  pkg/quickstarts/model.go
Labels: approved, lgtm, size/XS

#4935 fix: handle existing commits on local branch
  pkg/cmd/boot/boot.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/gits/provider.go
Labels: approved, lgtm, size/L

#5047 fix: do not fail if git config is not available
  pkg/cmd/step/git/step_git_validate.go
Labels: approved, lgtm, size/S

#5054 fix: allow the cloudbees profile to override
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/S

#5060 fix: use the stream specified
  pkg/cmd/boot/boot.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#5062 fix: only skip the commit for the versions pr
  pkg/cmd/step/create/pr/step_create_pr.go
  pkg/cmd/step/create/pr/step_create_pr_versions.go
  pkg/gits/operations/pull_request_op.go
Labels: approved, lgtm, size/XS

#5065 fix: don't force --global check for git name & email
  pkg/gits/git_cli.go
Labels: approved, lgtm, size/XS

#5067 fix: typo `promomote ` to `promote`
  pkg/cmd/promote/promote.go
Labels: approved, lgtm, ok-to-test, size/XS

#5074 fix: don’t collapse unrelated versions
  pkg/cmd/step/step_changelog.go
  pkg/cmd/step/step_changelog_test.go
  pkg/cmd/step/test_data/changelog2/platform.golden.yaml
  pkg/cmd/step/test_data/changelog2/platform.yaml
Labels: approved, lgtm, size/L

#5070 feat: refactor tekton logging and skip steps on failure
  pkg/cmd/controller/controller_build.go
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/get/get_build_logs_test.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/XL

#5079 chore: remove unused config readers and writers
  pkg/auth/config.go
  pkg/auth/config_test.go
  pkg/io/config_readers.go
  pkg/io/config_readers_test.go
  pkg/io/config_writers.go
  pkg/io/config_writers_test.go
Labels: approved, lgtm, size/XXL

#5084 fix: update create-timestamp for terraform clusters
  pkg/cmd/create/create_terraform_gke.go
Labels: approved, lgtm, size/XS

#5086 fix: cleanup for terraform clusters
  pkg/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#5082 fix: Use vault operator version from chart
  pkg/cmd/create/create_addon_vault.go
  pkg/cmd/create/create_vault.go
  pkg/kube/vault/vault.go
Labels: approved, lgtm, size/M

#5089 fix(test): making sure TestStepVerifyPreInstallNoKanikoLazyCreate use…
  pkg/cmd/step/verify/step_verify_preinstall_integration_test.go
Labels: approved, lgtm, size/S

#5151 fix: handle the case when the vault client url is nil in the value tree
  pkg/helm/values_tree.go
Labels: approved, lgtm, size/S

#5152 fix: gc activities shouldn't try to delete running activities
  pkg/cmd/gc/gc_activities.go
  pkg/cmd/gc/gc_activities_test.go
Labels: size/L

#5099 feat(cmd): bind use meta pipeline and custom image option to viper
  hack/curl-pipeline-runner.sh
  pkg/cmd/cmd.go
  pkg/cmd/controller/controller.go
  pkg/cmd/controller/controller_enviornmentcontroller.go
  pkg/cmd/controller/pipeline/pipelinerunner_cmd.go
  pkg/cmd/controller/pipeline/pipelinerunner_controller.go
  pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go
  pkg/cmd/controller/test_helpers.go
Labels: approved, area/fox, lgtm

#5159 fix(tekton): topologyKey needs to be specified in affinity policy
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/pipelinerun.yml
  pkg/tekton/syntax/pipeline.go
Labels: approved, size/XS

#5160 fix(test): use log.CaptureOutput instead os.Pipe() to capture log output
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/M

#5168 chore: wrap flaky test in retry
  pkg/cmd/controller/pipeline/pipelinerunner_controller.go
  pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/M

#5165 fix: exit with a diff in pipeline
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, area/fox, lgtm, size/S

#5177 fix: Don't require ordering of env vars on command in metapipeline test
  pkg/tekton/metapipeline/metapipeline_test.go
Labels: approved, lgtm, size/XS

#5182 fix: Include versions stream URL in BDD requirements
  pkg/cmd/step_bdd.go
Labels: approved, lgtm, size/XS

#5091 feat: added a flag to skip the jx install for terraform clusters
  pkg/cmd/create/create_terraform.go
  pkg/cmd/create/create_terraform_gke.go
Labels: approved, lgtm, size/S

#5189 fix: disable TLS warning for tests
  pkg/boot/constants.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step_bdd.go
Labels: approved, lgtm, size/S

#5192 fix: make excludes not break out the loop
  pkg/cmd/step/create/pr/step_create_pr_versions.go
  pkg/cmd/step/create/pr/step_create_pr_versions_test.go
Labels: approved, lgtm, size/M

#5068 fix: add confirmation to uninstall command
  pkg/cmd/uninstall/uninstall.go
  pkg/cmd/uninstall/uninstall_test.go
Labels: approved, lgtm, size/M

#5196 fix(tekton): allow clientFactory to clone a version stream with a SHA ref
  pkg/tekton/metapipeline/clientfactory.go
  pkg/tekton/metapipeline/clientfactory_test.go
Labels: approved, lgtm, size/M

#5202 fix: Fetch ref in pipelinerunner version stream checkout
  pkg/tekton/metapipeline/clientfactory.go
  pkg/tekton/metapipeline/clientfactory_test.go
Labels: approved, lgtm, size/S

#5199 chore: Increase cpu limit for release builds to 4
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#5096 fix(version): set namespace for jx version command
  pkg/cmd/version.go
Labels: approved, lgtm, ok-to-test, size/S

#5209 fix: Turn off JSON logging for metapipeline-triggered pipelines
  pkg/tekton/metapipeline/metapipeline.go
Labels: approved, lgtm, size/XS

#5228 fix: need to check that we are in cluster as well
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/XS

#5153 fix(init): enable both http and https for NLB ingress
  pkg/cmd/initcmd/init.go
Labels: approved, lgtm, ok-to-test, size/S

#4595 feat: add method code for UpdatePullRequest + tests + correct previously un…
  pkg/gits/gitlab.go
  pkg/gits/gitlab_test.go
  pkg/gits/test_data/gitlab/create-merge-request.json
  pkg/gits/test_data/gitlab/merge-request.json
  pkg/gits/test_data/gitlab/update-merge-request.json
Labels: approved, lgtm, ok-to-test, size/L

#5232 chore: remove misleading warning message
  pkg/cmd/opts/helm.go
Labels: approved, lgtm, size/XS

#5233 fix: hide warning when override is not relevant
  pkg/cmd/step/helm/step_helm_apply.go
Labels: approved, lgtm, size/XS

#5239 fix: e2e gc should check equality of cluster type between clusters
  pkg/cmd/step/e2e/step_e2e_gc.go
Labels: approved, lgtm, size/XS

#5244 fix: Override search name for FindLatestChart
  pkg/gits/operations/pull_request_op.go
Labels: approved, lgtm, size/XS

#5248 fix: wait for vault service to become ready after provisioning
  pkg/cmd/create/create_vault.go
Labels: approved, lgtm, size/S

#5250 docs: typo in command help
  pkg/cmd/create/create_step.go
Labels: approved, lgtm, size/XS

#5255 fix: resort to default version stream ref if not set
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/M

#5249 fix: ensure we always update the git status correctly
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, size/M

#5256 fix: do not log an error when an ingress is not found for a service
  pkg/kube/services/services.go
Labels: approved, lgtm, size/XS

#5262 fix: Use correct gitRef in boot version resolver
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#5271 feat: remove git diff check from environment repo and get vault name differently
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/S

#5270 fix: allow boot to start at a specified step
  pkg/cmd/boot/boot.go
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/M
