Repository jenkins-x/jx, pull requests merged in 2019-09, with the labels that each got.

#5294 fix: Pull request and release age limits in gc activities are flipped
  pkg/cmd/gc/gc_activities.go
Labels: approved, lgtm, size/XS

#5298 chore: added test to verify no postsubmit
  pkg/pipelinescheduler/config_builder_test.go
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/config.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/parent.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/plugins.yaml
  pkg/pipelinescheduler/test_data/no_postsubmits_with_parent/repo.yaml
Labels: approved, lgtm, size/L

#4788 fix: create/delete addon envctl functions to handle namespaces
  pkg/cmd/create/create_addon_environment_controller.go
  pkg/cmd/deletecmd/delete_addon_environment_controller.go
Labels: approved, lgtm, ok-to-test, size/S

#5305 chore: using the 'latest' tagged images in bdd tests
  Dockerfile.builder-base
  Dockerfile.builder-go
  Dockerfile.builder-go-maven
  Dockerfile.builder-gradle
  Dockerfile.builder-jx
  Dockerfile.builder-maven
  Dockerfile.builder-nodejs
  Dockerfile.builder-python
  Dockerfile.builder-python2
  Dockerfile.builder-ruby
  Dockerfile.builder-rust
  Dockerfile.builder-scala
  Dockerfile.builder-swift
  Dockerfile.builder-terraform
Labels: approved, lgtm, size/S

#5291 fix: lets properly handle errors parsing the requirements file in boot
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/M

#5306 chore: push the 'latest' release of the jx image
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#5300 test: make the go get test to not update the dependencies
  cmd/codegen/generator/client_set.go
  cmd/codegen/generator/docs.go
  cmd/codegen/generator/open_api.go
  cmd/codegen/util/go.go
  cmd/codegen/util/go_test.go
Labels: approved, lgtm, size/S

#5299 fix: regenerate prow config from source repositories after delete
  pkg/cmd/create/create_env.go
  pkg/cmd/deletecmd/delete_application.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/opts/import.go
Labels: approved, lgtm, size/M

#5301 fix: don’t include data in error
  pkg/surveyutils/jsonschema.go
Labels: approved, lgtm, size/XS

#5295 fix: use namespace from jx-requirements
  pkg/cmd/boot/boot.go
  pkg/cmd/boot/boot_test.go
  pkg/cmd/boot/test_data/jenkins-x.yml
  pkg/cmd/boot/test_data/jx-requirements.yml
  pkg/cmd/opts/common.go
  pkg/cmd/step/boot/step_boot_upgrade.go
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/cmd/step/create/step_create_install_values.go
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/env/step_env_apply.go
  pkg/cmd/step/expose/step_expose.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/verify/step_verify_install.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/L

#5319 fix: create devpods - check for empty tls value
  pkg/kube/ingress.go
Labels: approved, lgtm, size/XS

#5321 fix: properly verify kubectl/git/helm packages in boot
  pkg/cmd/step/verify/step_verify_packages.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/XS

#5325 fix(gits): correct webhook URL for Bitbucket Server
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#5328 fix: lets avoid failing to promote if we cannot add labels
  pkg/gits/bitbucket_server.go
  pkg/gits/gitlab.go
  pkg/gits/helpers.go
Labels: approved, lgtm, size/M

#5335 fix: Revert "fix: use namespace from jx-requirements"
  pkg/cmd/boot/boot.go
  pkg/cmd/boot/boot_test.go
  pkg/cmd/boot/test_data/jenkins-x.yml
  pkg/cmd/boot/test_data/jx-requirements.yml
  pkg/cmd/opts/common.go
  pkg/cmd/step/boot/step_boot_upgrade.go
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/cmd/step/create/step_create_install_values.go
  pkg/cmd/step/create/step_create_values.go
  pkg/cmd/step/env/step_env_apply.go
  pkg/cmd/step/expose/step_expose.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/verify/step_verify_install.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm

#5333 chore: simplify the domain verification regexp
  pkg/tenant/tenant.go
  pkg/tenant/tenant_test.go
Labels: approved, lgtm, size/S

#5285 fix: Fixed boolean logic around creating dev environment repo
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, ok-to-test, size/XS

#5352 fix: Add context label to PipelineActivity
  pkg/cmd/get/get_build_logs.go
  pkg/kube/activity.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/S

#5229 feat(cloud): create buckets for AWS
  pkg/cloud/amazon/storage/bucket_provider.go
  pkg/cloud/amazon/storage/bucket_provider_test.go
  pkg/cloud/factory/factory.go
Labels: approved, lgtm, ok-to-test, size/L

#5356 fix: detect lastCommitSha in latest tekton pods
  pkg/tekton/pipeline_info.go
  pkg/tekton/pipeline_info_test.go
  pkg/tekton/test_data/pipeline_info/pr-yaml/activity.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/pipeline.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/pipelineresources.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/pipelinerun.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/pods.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/structure.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/taskruns.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/tasks.yml
Labels: approved, lgtm, size/XXL

#5358 feat: can determine tls server from env variable
  .secrets.baseline
  pkg/cmd/step/create/step_create_install_values.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#5348 fix: getEnabledServices api now uses exponential backup
  pkg/cloud/gke/gcloud.go
Labels: approved, lgtm, size/XS

#5369 fix: allow .git to appear in dep update messages
  pkg/cmd/opts/releases_test.go
  pkg/dependencymatrix/commits.go
Labels: approved, lgtm, size/S

#5374 fix: Use builder-go for update-bot due to create pr go
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#5323 fix: Prevent concurrent environment deploys
  pkg/cmd/controller/controller_enviornmentcontroller.go
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, ok-to-test, size/M

#5379 fix: enable TLS only when it is enabled in the environment configuration
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/XS

#5385 feat: step to annotate configmaps or secrets so that the replicator a…
  pkg/cmd/step.go
  pkg/cmd/step/step_replicate.go
  pkg/cmd/step/step_replicate_test.go
  pkg/cmd/step/test_data/step_replicate/secret.yml
  pkg/tekton/tekton_helpers_test/test_helpers.go
Labels: approved, lgtm, size/L

#5397 fix: creation of dev repo in 'jx boot'
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/M

#5399 feat: can use private env repo from env variable
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#5404 fix: `jx step create pr go` should ignore build errors by default
  pkg/cmd/step/create/pr/step_create_pr_go.go
Labels: approved, lgtm, size/XS

#5405 fix: jx step report iv
  pkg/cmd/step/report/step_report_image_version.go
  pkg/util/strings.go
Labels: approved, lgtm, size/L

#5410 feat: add env variable to toggle vault storage type
  .secrets.baseline
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/L

#5414 fix: use JX_INTERPRET_PIPELINE to decided whether to create PR
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/XS

#5424 fix: mount secrets as a volume outside of the dir where repos are clo…
  jenkins-x-bdd.yml
  jenkins-x-tekton.yml
  jx/bdd/tekton/ci.sh
  jx/scripts/ci.sh
Labels: size/M

#5428 fix: BDD tests, use new GCP test project
  jenkins-x-bdd.yml
  jenkins-x-tekton.yml
  jx/bdd/tekton/cluster.yaml
Labels: approved, lgtm, size/M

#5392 fix: allow helm3 to be enabled for boot
  pkg/cmd/boot/boot.go
  pkg/cmd/clients/factory.go
  pkg/cmd/opts/common.go
  pkg/cmd/opts/team_settings.go
  pkg/config/install_requirements.go
  pkg/helm/helm_cli.go
Labels: approved, lgtm, size/M

#5409 feat: avoid passing arguments down the chain with create cluster
  pkg/cmd/create/create_cluster_eks.go
Labels: approved, lgtm, size/XS

#5444 feat: extract requirments overrides into own step
  .secrets.baseline
  pkg/cmd/step.go
  pkg/cmd/step/create/step_create_install_values.go
  pkg/cmd/step/step_override_requirements.go
  pkg/cmd/step/step_replicate.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/L

#5460 feat: allow vault to be configured in cluster
  pkg/cmd/create/create_vault.go
  pkg/cmd/step/boot/step_boot_vault.go
Labels: approved, lgtm, size/S

#5475 fix: handle deprecated vault elements in jx-requirements.yml
  .secrets.baseline
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#5474 chore: handle errors when setting up the vault resources for AWS
  pkg/cmd/create/create_vault.go
Labels: approved, lgtm, size/S

#5478 fix: allow retry when searching for gcloud sa
  pkg/cloud/gke/gcloud.go
Labels: approved, lgtm, size/XS

#5473 chore: make autoupdate flag consistent
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/XS

#5483 feat: pass the requirements vault name to the create vault command
  pkg/cmd/create/create_vault.go
  pkg/cmd/step/boot/step_boot_vault.go
Labels: approved, lgtm, size/XS

#5484 fix: update PR only when files changed
  pkg/gits/helpers.go
Labels: approved, lgtm, size/XS

#5486 chore: minor refactor
  go.mod
  go.sum
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/tekton/metapipeline/clientfactory.go
  pkg/tekton/pipelines.go
  pkg/tekton/pullrefs.go
Labels: approved, lgtm, size/M

#5490 chore: fixes for customising keyring & key within vault config
  .secrets.baseline
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/vault/vault_backend.go
  pkg/cmd/create/create_vault.go
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/cmd/step/step_override_requirements.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/M

#5492 feat: expose the insecureSkipVerify flag to `jx step verify url` so w…
  pkg/cmd/step/verify/step_verify_url.go
Labels: approved, lgtm, size/S

#5494 feat: replicate secrets can create missing namespaces if required
  pkg/cmd/step/step_replicate.go
Labels: approved, lgtm, size/S

#5495 feat: use regexp when updating secrets
  pkg/cmd/step/step_replicate.go
Labels: approved, lgtm, size/M

#5452 fix: avoid failing boot if folks want TLS and are not using GKE
  pkg/cmd/step/create/step_create_install_values.go
Labels: approved, lgtm, size/S

#5485 chore: use the kube-hunter image from version stream
  pkg/cmd/scan_cluster.go
Labels: approved, lgtm, size/S

#5481 fix: use namespace from jx-requirements
  pkg/cmd/boot/boot.go
  pkg/cmd/boot/boot_test.go
  pkg/cmd/boot/test_data/jenkins-x.yml
  pkg/cmd/boot/test_data/jx-requirements.yml
Labels: approved, lgtm, size/L

#5500 feat: get files from GCS by stream transfer instead of file copy
  pkg/cloud/gke/gcloud.go
  pkg/logs/tekton_logging.go
Labels: approved, lgtm, size/M

#5508 fix: Add Helm repo for jetstack/cert-manager
  pkg/cmd/opts/cert_manager.go
  pkg/kube/pki/cert-manager.go
Labels: approved, lgtm, size/S

#5504 fix: allow webhook type to be configurable by env variable
  pkg/cmd/step/step_override_requirements.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/XS

#5453 feat: modify jx cloudbees to open the UI app in local, read-only mode
  pkg/cmd/cloudbees/cloudbees.go
  pkg/cmd/cloudbees/cloudbees_pipeline.go
  pkg/cmd/cloudbees/cloudbees_test.go
Labels: approved, lgtm, size/L

#5511 fix: Revert making all created repos private by default
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/test_data/environment/git_public_false_git_private_nil.json
  pkg/apis/jenkins.io/v1/test_data/environment/git_public_nil_git_private_false.json
  pkg/apis/jenkins.io/v1/test_data/environment/git_public_nil_git_private_true.json
  pkg/apis/jenkins.io/v1/test_data/environment/git_public_true_git_private_nil.json
  pkg/apis/jenkins.io/v1/test_data/environment/git_public_true_git_private_true.json
  pkg/apis/jenkins.io/v1/types_environment.go
  pkg/apis/jenkins.io/v1/types_environment_test.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/cmd/controller/controller_backup.go
  pkg/cmd/controller/controller_team.go
  pkg/cmd/create/create_codeship.go
  pkg/cmd/create/create_mlquickstart.go
  pkg/cmd/create/create_terraform.go
  pkg/cmd/create/create_terraform_gke.go
  pkg/cmd/create/install.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/opts/git.go
  pkg/cmd/step/step_override_requirements.go
  pkg/cmd/step/step_split_monorepo.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step_bdd.go
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
  pkg/config/test_data/git_public_false_git_private_nil.yaml
  pkg/config/test_data/git_public_nil_git_private_false.yaml
  pkg/config/test_data/git_public_nil_git_private_true.yaml
  pkg/config/test_data/git_public_true_git_private_nil.yaml
  pkg/config/test_data/git_public_true_git_private_true.yaml
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/git_repo.go
  pkg/gits/github.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/gits/provider.go
  pkg/kube/env.go
Labels: approved, lgtm, size/XL

#5518 feat: add ability to skip linter
  hack/linter.sh
Labels: approved, lgtm, size/XS

#5525 fix: Revert update to latest cert-manager
  jx/bdd/tekton/ci.sh
  pkg/cmd/opts/cert_manager.go
  pkg/kube/pki/cert-manager.go
Labels: approved, lgtm, size/M

#5524 fix: prevent creation of dev env pr in cluster
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/S

#5480 feat: use vault substitutions in app
  pkg/cmd/opts/helm.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
Labels: approved, lgtm, size/L

#5526 fix: removing sourcerepository label from PipelineActivity
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/cmd/deletecmd/delete_application.go
  pkg/kube/activity.go
  pkg/kube/activity_test.go
Labels: approved, lgtm, size/M

#5497 fix: Add 403 resp code for successful deployment
  pkg/cmd/preview/preview.go
Labels: approved, lgtm, ok-to-test, size/XS

#5528 fix: enable build packs to checkout tags
  pkg/jenkinsfile/gitresolver/buildpack.go
Labels: approved, lgtm, size/M

#5545 feat: update aws-sdk-go to the latest version
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#5509 fix: making the uninstall confirmation clear by displaying context
  pkg/cmd/uninstall/uninstall.go
  pkg/cmd/uninstall/uninstall_test.go
Labels: approved, lgtm, size/L

#5548 fix: use the new website path for docs creation
  jx/scripts/update-website.sh
Labels: approved, lgtm, size/XS

#5550 fix(pipeline): Pass pull refs for metapipeline to PipelineActivity
  pkg/tekton/metapipeline/clientfactory.go
Labels: approved, lgtm, size/XS

#5555 fix: Add test for pull refs ending up on activity key
  pkg/tekton/metapipeline/clientfactory.go
  pkg/tekton/metapipeline/clientfactory_test.go
Labels: approved, lgtm, size/M

#5554 fix: correct and add storage overrides for boot override step
  pkg/cmd/step/step_override_requirements.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/M

#5559 fix: Proper relative path for jx binary in update-website.sh
  jx/scripts/update-website.sh
Labels: approved, lgtm, size/XS

#5557 fix: move activity_integration_test.go into dedicated package
  pkg/kube/test_integration/activity_integration_test.go
  pkg/kube/test_integration/doc.go
Labels: approved, lgtm, size/XS

#5562 fix: lets add a warning if boot is being used without a clusterName
  pkg/cmd/step/helm/step_helm_apply.go
Labels: approved, lgtm, size/S

#5563 fix: default vault client to using internal kubernetes service dns na…
  pkg/cmd/clients/factory.go
  pkg/cmd/clients/interface.go
  pkg/cmd/clients/mocks/factory.go
  pkg/cmd/get/get_vault.go
  pkg/cmd/opts/auth.go
  pkg/cmd/opts/common.go
  pkg/cmd/opts/git.go
  pkg/cmd/opts/team_settings.go
  pkg/kube/cluster/cluster.go
  pkg/kube/vault/commonhelpers_test.go
  pkg/kube/vault/vault.go
  pkg/kube/vault/vault_factory.go
  pkg/kube/vault/vault_factory_test.go
  pkg/kube/vault/vault_selector.go
  pkg/kube/vault/vault_selector_test.go
Labels: approved, lgtm, size/L

#5575 fix: avoid duplicating env vars during verify env
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/M

#5567 feat: correctly gather boot requirements for EKS
  pkg/cloud/amazon/common.go
  pkg/cloud/amazon/common_test.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/L

#5234 feat: perform pre-release of jx prior to version stream release
  .goreleaser.yml
  jenkins-x.yml
  jx/scripts/update-bot.sh
Labels: approved, lgtm, size/S

#5591 chore: boot upgrade tests
  pkg/cmd/upgrade/test_data/upgrade_boot/jx-requirements.yml
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_test.go
  pkg/gits/git_cli.go
Labels: approved, lgtm, size/L

#5590 feat: avoid asking the user to create a custom domain when booting and default to nip.io if a domain is not provided
  pkg/cmd/opts/domain.go
  pkg/cmd/step/create/step_create_install_values.go
Labels: approved, lgtm, size/M

#5604 fix: Revert "fix(pipeline): Don't use `dir` as container `workingDir`"
  pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/containeroptions-on-pipelineconfig/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/loop-in-buildpack-syntax/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override_block_step/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/per_step_container_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/remove-stage/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/tasks.yml
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
Labels: approved, lgtm, size/L

#5572 fix: boot command should not ask for confirmation when provider is not GKE
  pkg/cmd/step/verify/step_verify_preinstall_test.go
Labels: approved, lgtm, ok-to-test, size/L

#5577 fix: always fetch to a new local branch
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
Labels: approved, lgtm, size/XXL

#5612 chore: remove the --file flag from 'jx step credential'
  pkg/cmd/step/step_credential.go
Labels: approved, lgtm, size/M

#5608 feat: update the compliance to use sonobuoy v0.16.0
  go.mod
  go.sum
  pkg/cmd/compliance/compliance.go
  pkg/cmd/compliance/compliance_results.go
  pkg/cmd/compliance/compliance_run.go
  pkg/cmd/compliance/compliance_status.go
Labels: approved, lgtm, size/L

#5618 fix: version stream info correctly written into jx-requirements.yml
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#5621 chore: revert remove the --file flag from 'jx step credential'
  pkg/cmd/step/step_credential.go
Labels: approved, lgtm, size/M

#5624 feat: write/read bootConfigURL from dev env requirements
  pkg/cmd/boot/boot.go
  pkg/cmd/upgrade/test_data/upgrade_boot_alternative/jx-requirements.yml
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_test.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/L

#5629 feat: add the requirements file to a ConfigMap on every pipeline run so it can be obtained in other contexts
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_test.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/L

#5606 feat: remove the nginx-ingress chart when uninstalling
  pkg/cmd/uninstall/uninstall.go
  pkg/cmd/uninstall/uninstall_test.go
Labels: approved, lgtm, size/L

#5649 fix: lookup the vault operator image tag used by boot vault into the version stream
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/kube/vault/vault.go
Labels: approved, lgtm, size/M

#5651 fix: Don't use pointers for getPipelineRunsForActivity return
  pkg/logs/tekton_logging.go
  pkg/logs/test_data/metapipeline_failure/pipelineruns.yml
Labels: approved, lgtm, size/L
