Repository jenkins-x/jx, pull requests merged in 2020-09, with the labels that each got.

#7552 fix: Bring back config refdocs generation
  Makefile.codegen
Labels: approved, lgtm, size/S

#7544 feat: Vault - Added in Azure Key Vault support
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/config/install_requirements.go
  pkg/kube/vault/vault.go
  pkg/vault/create/create.go
Labels: approved, lgtm, ok-to-test, size/L

#7551 fix: upgrade lighthouse
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#7556 fix: add optional pipeline username + email
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#7536 fix: add a flag to keep namespaces when uninstalling jx
  pkg/cmd/uninstall/uninstall.go
  pkg/cmd/uninstall/uninstall_test.go
Labels: approved, lgtm, size/S

#7563 feat: jx preview --single-comment
  pkg/cmd/preview/preview.go
Labels: approved, lgtm, ok-to-test, size/M

#7565 fix: step next-version and helm 3
  pkg/cmd/step/step_next_version.go
  pkg/cmd/step/step_next_version_integration_test.go
  pkg/cmd/step/test_data/next_version/helm3/Chart.yaml
  pkg/cmd/step/test_data/next_version/helm3/expected_Chart.yaml
Labels: approved, lgtm, ok-to-test, size/M

#7569 fix: Workarounds for go modules that fail with Athens proxy
  go.mod
  go.sum
  jenkins-x-codegen.yml
Labels: approved, lgtm, size/S

#7567 chore: migrate code.gitea.io/sdk/gitea to v0.13.0
  go.mod
  go.sum
  pkg/gits/gitea.go
Labels: approved, lgtm, ok-to-test, size/M

#7558 feat: add support to gitlab to the environment controller
  pkg/cmd/controller/controller_enviornmentcontroller.go
Labels: approved, lgtm, ok-to-test, size/L

#7530 fix: hack helm hooks on upgrade helm chart
  pkg/helm/helm_template.go
Labels: approved, lgtm, ok-to-test, size/XS

#7557 fix: split command creates a new repo as public
  pkg/cmd/step/step_split_monorepo.go
Labels: approved, lgtm, ok-to-test, size/XS
