Repository jenkins-x/jx, pull requests merged in 2020-07, with the labels that each got.

#7416 chore: added debugging and default values for 'jx step next-version --semantic-release'
  pkg/cmd/step/step_next_version.go
  pkg/semrel/semrel.go
Labels: approved, lgtm, size/XS

#7419 fix: remove step_create_jenkins_config directory as Jenkins static ma…
  pkg/cmd/step/create/test_data/step_create_jenkins_config/gradle.yaml
  pkg/cmd/step/create/test_data/step_create_jenkins_config/jenkins.yml
  pkg/cmd/step/create/test_data/step_create_jenkins_config/maven.yaml
Labels: approved, lgtm, size/M

#7411 fix: explicitly empty buckets before 'terraform destroy'
  jx/bdd/tf-boot/ci.sh
Labels: approved, lgtm, size/S

#7352 fix: uninstall jenkins-x
  pkg/cmd/uninstall/uninstall.go
Labels: approved, lgtm, size/M

#7429 refactor: improve build log stream
  pkg/cloud/amazon/storage/bucket_provider.go
  pkg/cloud/amazon/storage/bucket_provider_test.go
  pkg/cloud/buckets/buckets.go
  pkg/cloud/buckets/default_provider.go
  pkg/cloud/buckets/interface.go
  pkg/cloud/buckets/mocks/buckets_interface.go
  pkg/cloud/gke/gcloud.go
  pkg/cloud/gke/storage/bucket_provider.go
  pkg/cmd/controller/controller_build.go
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/get/get_build_logs_test.go
  pkg/cmd/step/step_unstash.go
  pkg/collector/bucket_collector.go
  pkg/collector/bucket_collector_test.go
  pkg/collector/git_collector.go
  pkg/collector/interface.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
Labels: approved, lgtm, size/XXL

#7438 fix: default the DOCKER_REGISTRY_ORG env var
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/test_data/step_create_task/add-env-to-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/append-and-prepend-stage-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/command-as-multiline-script/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/containeroptions-on-pipelineconfig/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/correct-pipeline-stage-is-removed/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes-with-labels/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/distribute-parallel-across-nodes/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/from_yaml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/loop-in-buildpack-syntax/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/maven_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-agent-container-with-build-pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-buildpack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-default-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override_block_step/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/per_step_container_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/pipeline-timeout/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/remove-stage-from-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/remove-stage/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps-in-jenkins-x-yml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/replace-stage-steps/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/set-agent-container-with-agentless-build-pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/tolerations/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/volume-in-overrides/tasks.yml
Labels: approved, lgtm, size/XL

#7439 fix: kaniko env vars
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/XS

#7433 chore: Upgrade go-github to v32.0.0
  go.mod
  go.sum
  pkg/gits/bitbucket_cloud.go
  pkg/gits/bitbucket_server.go
  pkg/gits/gerrit.go
  pkg/gits/gitea.go
  pkg/gits/github.go
  pkg/gits/github_test.go
  pkg/gits/gitlab.go
  pkg/gits/interface.go
  pkg/gits/mocks/git_provider.go
  pkg/gits/mocks/matchers/ptr_to_github_response.go
  pkg/gits/mocks/matchers/slice_of_ptr_to_github_repositoryinvitation.go
  pkg/gits/provider_fake.go
  pkg/util/downloads.go
Labels: approved, lgtm, size/M

#7443 fix: Use $() instead of ${} for pipeline parameters
  jenkins-x-bdd.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-vault.yml
  jenkins-x-images.yml
  jenkins-x-tekton.yml
  jenkins-x-tf-boot.yml
  jenkins-x.yml
Labels: approved, lgtm, size/M

#7447 fix: fix changelog errors
  pkg/cmd/step/step_changelog.go
  pkg/users/git.go
Labels: approved, lgtm, size/S

#7457 chore: upgrade helm2 to 2.16.9
  pkg/packages/packages.go
Labels: approved, lgtm, size/XS

#7455 refactor: use google uuid package for generating uuids in the codebase
  .golangci.yml
  cmd/codegen/util/go.go
  cmd/jx/jx_test.go
  go.mod
  pkg/apps/install.go
  pkg/cloud/amazon/storage/bucket_provider.go
  pkg/cloud/amazon/vault/vault_resources.go
  pkg/cloud/gke/storage/bucket_provider.go
  pkg/cloud/gke/storage/long_term_storage.go
  pkg/cloud/openshift/cli.go
  pkg/cluster/helpers.go
  pkg/cmd/add/add_app_test.go
  pkg/cmd/create/create_addon_prometheus.go
  pkg/cmd/deletecmd/delete_app_test.go
  pkg/cmd/deletecmd/delete_application_test.go
  pkg/cmd/get/get_apps_test.go
  pkg/cmd/opts/helm.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/step_create_values_test.go
  pkg/cmd/step/get/step_get_version_changeset_test.go
  pkg/cmd/step/report/step_report_image_version.go
  pkg/cmd/step/scheduler/step_scheduler_config_apply_test.go
  pkg/cmd/step/scheduler/step_scheduler_config_migrate_test.go
  pkg/cmd/step/step_values_schema_template_test.go
  pkg/cmd/step/step_wait_for_chart_test.go
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/cmd/testhelpers/app_test_helpers.go
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/gits/helpers.go
  pkg/gits/helpers_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
  pkg/kube/naming/names.go
  pkg/packages/install.go
  pkg/pipelinescheduler/builder_test.go
  pkg/pipelinescheduler/config_builder_test.go
  pkg/pipelinescheduler/generator.go
  pkg/pipelinescheduler/testhelpers/helpers.go
  pkg/prow/pjutil.go
  pkg/users/git_test.go
  pkg/vault/create/create.go
  pkg/vault/helpers_test.go
Labels: approved, lgtm, size/L

#7460 fix: Set HELM_HOME to /tekton/home/.helm
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#7462 fix: Read the entire reader before writing to bucket
  pkg/cloud/buckets/buckets.go
Labels: approved, lgtm, size/S

#7452 fix: add a few more options
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/M

#7459 fix: fix unreachable code after generating readme
  pkg/environments/gitops.go
  pkg/pipelinescheduler/scheduler_builder.go
Labels: approved, lgtm, size/M

#7441 fix: skip dir when loop Helm templates
  pkg/environments/gitops.go
Labels: approved, lgtm, ok-to-test, size/XS

#7465 chore: add MarckK to Owners
  OWNERS
Labels: approved, lgtm, size/XS

#7436 fix: support add an app from git repository
  pkg/apps/install.go
  pkg/cmd/add/add_app.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_helpers_test.go
Labels: approved, lgtm, ok-to-test, size/L

#7476 fix: remove broken link from command description
  pkg/cmd/create/create_branch_pattern.go
Labels: approved, lgtm, size/S

#7478 fix: terms in test comments
  pkg/cmd/opts/commands_test.go
  pkg/kube/env_test.go
Labels: approved, lgtm, size/XS

#7440 fix: deprecate create addon kubeless
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, ok-to-test, size/XS

#7473 fix: return tekton pipeline runs instead of prow releasejobs
  pkg/cmd/deletecmd/delete_gke.go
  pkg/cmd/get/get.go
  pkg/cmd/get/get_addon.go
  pkg/cmd/get/get_apps.go
  pkg/cmd/get/get_apps_test.go
  pkg/cmd/get/get_branchpattern.go
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/get/get_build_logs_test.go
  pkg/cmd/get/get_build_pods.go
  pkg/cmd/get/get_buildpack.go
  pkg/cmd/get/get_chat.go
  pkg/cmd/get/get_config.go
  pkg/cmd/get/get_cve.go
  pkg/cmd/get/get_devpod.go
  pkg/cmd/get/get_env.go
  pkg/cmd/get/get_git.go
  pkg/cmd/get/get_helmbin.go
  pkg/cmd/get/get_issue.go
  pkg/cmd/get/get_issues.go
  pkg/cmd/get/get_lang.go
  pkg/cmd/get/get_limits.go
  pkg/cmd/get/get_pipeline.go
  pkg/cmd/get/get_pipeline_test.go
  pkg/cmd/get/get_preview.go
  pkg/cmd/get/get_preview_test.go
  pkg/cmd/get/get_quickstart_locations.go
  pkg/cmd/get/get_quickstarts.go
  pkg/cmd/get/get_release.go
  pkg/cmd/get/get_storage.go
  pkg/cmd/get/get_stream.go
  pkg/cmd/get/get_team.go
  pkg/cmd/get/get_teamrole.go
  pkg/cmd/get/get_token.go
  pkg/cmd/get/get_token_addon.go
  pkg/cmd/get/get_tracker.go
  pkg/cmd/get/get_url.go
  pkg/cmd/get/get_user.go
  pkg/cmd/open.go
  pkg/cmd/opts/common.go
  pkg/cmd/step/e2e/step_e2e_gc.go
  pkg/cmd/step/scheduler/step_scheduler_config_apply_test.go
  pkg/cmd/step/verify/step_verify_behavior.go
  pkg/cmd/stop/stop_pipeline.go
  pkg/pipelinescheduler/generator.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, lgtm, size/XL
