Repository jenkins-x/jx, pull requests merged in 2020-02, with the labels that each got.

#6678 fix: helmfile create namespace helm repo
  .secrets.baseline
  pkg/cmd/step/create/helmfile/create_helmfile.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm

#6680 fix: Fetch k8s.io openapi dependencies as modules
  cmd/codegen/app/generate_openapi.go
Labels: approved, lgtm, size/S

#6671 fix(git): parsing of Bitbucket Server URLs
  pkg/gits/git_url.go
  pkg/gits/git_url_test.go
Labels: approved, lgtm, ok-to-test, size/S

#6677 feat(cli): show ConfigMaps on jx diagnose output
  pkg/cmd/diagnose.go
Labels: approved, lgtm, ok-to-test, size/XS

#6682 fix: Turns `globals.jx-*` template variables into valid variable names
  pkg/cmd/promote/promote.go
  pkg/cmd/promote/promote_test.go
  pkg/cmd/step/helm/step_helm.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: approved, lgtm, ok-to-test, size/M

#6550 fix: various problem due to non-conventional github repository name
  pkg/cmd/preview/preview.go
  pkg/cmd/promote/promote.go
  pkg/cmd/step/step_tag.go
  pkg/cmd/step/step_tag_test.go
  pkg/logs/tekton_logging.go
  pkg/logs/tekton_logging_test.go
  pkg/logs/test_data/invalid_name/activity.yml
  pkg/logs/test_data/invalid_name/pipelineruns.yml
Labels: approved, lgtm, ok-to-test, size/L

#6695 feat: add a stackdriver log formatter
  go.mod
  go.sum
  pkg/log/log.go
Labels: approved, lgtm, size/S

#6693 fix: non-conventional github repository names don't appear in `jx get applications`
  pkg/applications/applications.go
Labels: approved, lgtm, ok-to-test, size/XS

#6696 fix(cli): handle errors when doing a jx upgrade boot in non dev namespace
  pkg/cmd/opts/git.go
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/cmd/upgrade/upgrade_boot_test.go
Labels: approved, lgtm, ok-to-test, size/L

#6718 fix: Replace dir placeholders on build pack stages
  pkg/cmd/step/create/test_data/step_create_task/packs/jx-syntax-in-buildpack/pipeline.yaml
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/L

#6715 fix(cli): avoid creating dev environment in arbitrary namespace
  pkg/cmd/get/get_build_logs.go
Labels: approved, lgtm, ok-to-test, size/XS

#6720 feat: always pass the repo owner to the credential helper
  pkg/cmd/step/git/credentials/step_git_credentials.go
  pkg/cmd/step/git/credentials/step_git_credentials_test.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/gits/helpers.go
Labels: approved, lgtm, size/M

#6652 docs: update replicate step example to use the correct flag
  pkg/cmd/step/step_replicate.go
Labels: approved, lgtm, size/XS

#6699 feat: `helm lint` calls pass variables too
  pkg/cmd/opts/helm_test.go
  pkg/cmd/opts/test_data/lint/Chart.yaml
  pkg/cmd/opts/test_data/lint/templates/test.yaml
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
Labels: approved, lgtm, ok-to-test, size/M

#6742 fix: only check the repo owner if gha is enabled
  .secrets.baseline
  pkg/cmd/create/create_devpod.go
  pkg/cmd/step/git/credentials/step_git_credentials.go
  pkg/cmd/step/git/credentials/step_git_credentials_test.go
Labels: approved, lgtm, size/L

#6740 feat: added information on env vars to step helm apply
  pkg/cmd/step/helm/step_helm_apply.go
Labels: approved, lgtm, size/XS

#6751 fix: Don't test update of PipelineActivity in static master context
  jx/bdd/static/ci.sh
Labels: approved, lgtm, size/XS

#6494 feat: Ensure Kustomize
  pkg/cmd/clients/factory.go
  pkg/cmd/clients/fake/fake_factory.go
  pkg/cmd/clients/interface.go
  pkg/cmd/clients/mocks/factory.go
  pkg/cmd/opts/common.go
  pkg/cmd/opts/install.go
  pkg/cmd/opts/kustomize.go
  pkg/cmd/opts/kustomize_integration_test.go
  pkg/cmd/opts/kustomize_test.go
  pkg/cmd/testhelpers/cmd_test_helpers.go
  pkg/kustomize/interface.go
  pkg/kustomize/kustomize_cli.go
Labels: approved, lgtm, ok-to-test, size/L

#6747 fix(boot): fix --dir flag
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, ok-to-test, size/S

#6754 test: Add image tag overrides for all controllers/cronjobs to boot test
  jenkins-x-bdd.yml
  jenkins-x-boot-lh-ghe.yml
  jenkins-x-boot-vault.yml
  jenkins-x-tekton.yml
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-vault.platform.yaml.template
  jx/bdd/boot-vault.prow.yaml.template
  jx/bdd/boot-vault/ci.sh
Labels: approved, lgtm, size/L

#6768 fix: UrlWithoutUser return correct URL when using ssh URL starting with git@
  pkg/gits/git_url.go
Labels: approved, lgtm, ok-to-test, size/XS

#6769 fix: fill organisation and other fields for bitbucketcloud
  pkg/gits/bitbucket_cloud.go
Labels: approved, lgtm, ok-to-test, size/S

#6776 fix: repositoryResouce httpCloneURL should not be an sshURL
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, ok-to-test, size/XS

#6711 fix(prow): postsubmit jobs branches should be regexp
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, lgtm, ok-to-test, size/M

#6778 feat: adding ability to trace GitHub API calls via TRACE_GITHUB_API=1
  pkg/gits/github.go
Labels: approved, lgtm, size/XS

#6785 test: Add test to verify that pipelineConfig env secrets get used
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/pipeline.yml
  pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/pipelineresources.yml
  pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/pipelinerun.yml
  pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/structure.yml
  pkg/cmd/step/create/test_data/step_create_task/secret-in-pipelineconfig-env/tasks.yml
Labels: approved, lgtm, size/XL

#6788 fix: FileExists returns now false for directories
  pkg/cmd/boot/boot.go
  pkg/cmd/controller/controller_backup.go
  pkg/cmd/create/create_addon_istio.go
  pkg/cmd/create/create_codeship.go
  pkg/cmd/create/create_docs.go
  pkg/cmd/create/create_quickstart.go
  pkg/cmd/create/create_terraform.go
  pkg/cmd/create/create_terraform_gke.go
  pkg/cmd/create/create_terraform_integration_test.go
  pkg/cmd/deletecmd/delete_branch.go
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_integration_test.go
  pkg/cmd/opts/buildpacks.go
  pkg/cmd/promote/promote.go
  pkg/cmd/step/helm/step_helm.go
  pkg/cmd/step/post/step_post_build.go
  pkg/cmd/step/step_release.go
  pkg/cmd/step/step_split_monorepo.go
  pkg/cmd/step/step_split_monorepo_test.go
  pkg/cmd/upgrade/upgrade_apps_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/tests/files.go
  pkg/util/files.go
  pkg/util/files_test.go
Labels: approved, lgtm, size/L

#6802 fix: making sure boot repo exists before loading requirements
  pkg/cmd/boot/boot.go
  pkg/cmd/boot/boot_integration_test.go
  pkg/cmd/boot/boot_test.go
Labels: approved, lgtm, size/XL

#6797 fix: jx get applications when helm release == app name
  pkg/kube/version.go
Labels: approved, lgtm, size/S

#6815 fix: jx step helm apply should always use default reqs for non-boot
  pkg/cmd/step/helm/step_helm_apply.go
Labels: approved, lgtm, size/S

#6789 fix: Use kube crd name to look up the docker registry image
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/pipeline.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/pipelineresources.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/pipelinerun.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/structure.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/M

#6823 fix: add a `jx alpha boot` command
  pkg/cmd/alpha/alpha.go
  pkg/cmd/cmd.go
  pkg/extensions/plugins.go
Labels: approved, lgtm, size/L

#6835 fix: Properly set BaseSHA on activities
  pkg/cmd/controller/controller_build.go
  pkg/cmd/controller/test_data/controller_build/completed_generated/expected/activity.yml
  pkg/cmd/controller/test_data/controller_build/completed_metapipeline/expected/activity.yml
  pkg/cmd/controller/test_data/controller_build/failed_metapipeline/expected/activity.yml
  pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/expected/activity.yml
  pkg/cmd/controller/test_data/controller_build/running_generated/expected/activity.yml
  pkg/tekton/pipeline_info.go
  pkg/tekton/test_data/pipeline_info/pr-yaml/pods.yml
Labels: approved, lgtm, size/M

#6833 fix: Change the commit status description when running stage changes
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/cmd/controller/controller_build.go
  pkg/gits/provider.go
Labels: approved, lgtm, size/M

#6829 fix: better validation of helm
  pkg/helm/helm_cli.go
Labels: approved, lgtm, size/XS

#6836 chore: Fix typo of "PipelineActicity" in build controller logs
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, size/XS

#6826 fix: do not run helm init when using helm version > v2
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_template.go
Labels: approved, lgtm, size/L

#6840 chore: Use an annotation to see if running stages have already been reported
  pkg/cmd/controller/controller_build.go
  pkg/kube/constants.go
Labels: approved, lgtm, size/M

#6757 fix: FindKustomize
  pkg/kustomize/interface.go
  pkg/kustomize/kustomize_cli.go
  pkg/kustomize/kustomize_cli_test.go
  pkg/kustomize/test_data/kustomize_dummy/base/charts/kustomization.yaml
  pkg/kustomize/test_data/kustomize_dummy/base/charts/xyz.yaml
  pkg/kustomize/test_data/kustomize_dummy/base/kustomization.yaml
  pkg/kustomize/test_data/kustomize_dummy/base/template/xyz.yaml
  pkg/kustomize/test_data/kustomize_dummy/staging/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/M

#6839 fix: lets just log a warning if the alpha commands can't be found
  pkg/cmd/alpha/alpha.go
  pkg/cmd/cmd.go
Labels: approved, lgtm, size/S
