Repository jenkins-x/jx, pull requests merged in 2020-04, with the labels that each got.

#6994 fix: Don't warn about static master removal in "jx completion ..."
  pkg/cmd/cmd.go
Labels: approved, lgtm, size/XS

#6996 feat: add a command to verify dns resolution of ingress rules
  pkg/cmd/step/verify/step_verify.go
  pkg/cmd/step/verify/step_verify_dns.go
Labels: approved, lgtm, size/L

#7001 fix: enforce vault GCP service account minimum name length
  .secrets.baseline
  pkg/cloud/gke/gcloud.go
  pkg/cmd/deletecmd/delete_vault.go
Labels: approved, lgtm, ok-to-test, size/S

#6953 fix: prevent concurrent build to edit the same namespace
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/kube/build_lock.go
  pkg/kube/build_lock_test.go
Labels: approved, lgtm, size/XXL

#7013 fix: use newer kaniko image
  pkg/builds/test_data/get_pipelinerun_pods/pods.yml
  pkg/cmd/controller/test_data/controller_build/completed_generated/cluster_state/pods.yml
  pkg/cmd/controller/test_data/controller_build/failed_multistage_generated/cluster_state/pods.yml
  pkg/cmd/controller/test_data/controller_build/running_generated/cluster_state/pods.yml
  pkg/cmd/get/test_data/get_build_logs/tekton_build_logs/pod.yml
  pkg/cmd/get/test_data/get_build_logs/tekton_build_logs_legacy_label/pod.yml
  pkg/cmd/get/test_data/get_build_logs/with-metapipeline/pods.yml
  pkg/cmd/get/test_data/get_build_logs/with-metapipeline/tasks.yml
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/kaniko_entrypoint/tasks.yml
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/logs/test_data/legacy_pipeline_run/pods.yml
  pkg/logs/test_data/multiple_stages_failure_activity_done_run_not_done/pods.yml
  pkg/logs/test_data/multiple_stages_with_failure_in_first_stage/pods.yml
  pkg/logs/test_data/pod_with_failure/pods.yml
  pkg/logs/test_data/pods.yml
  pkg/tekton/syntax/constants.go
  pkg/tekton/test_data/pipeline_info/batch-yaml/pods.yml
  pkg/tekton/test_data/pipeline_info/batch-yaml/tasks.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/pods.yml
  pkg/tekton/test_data/pipeline_info/pr-yaml/tasks.yml
Labels: approved, lgtm, ok-to-test, size/M

#7000 feat: add more reporting to ImportReporter
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_reporter.go
Labels: approved, lgtm, size/S

#7030 chore: Disable PR status reporting if new enough Lighthouse present
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, size/S

#7028 fix: catch errors when retrieving logs from gs bucket
  pkg/cloud/gke/gcloud.go
Labels: approved, lgtm, size/S

#7031 fix: go.mod replace for spf13/cobra
  go.mod
Labels: approved, lgtm, size/XS

#7033 fix: Foghorn check logic was wrong
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, size/XS

#7034 fix: set ContentType when uploading files to s3
  pkg/cloud/amazon/storage/bucket_provider.go
Labels: approved, lgtm, ok-to-test, size/XS

#7038 chore: Bump antham/chyle to 1.6.0
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#7043 fix: Actually use a specific version of codegen dependencies
  cmd/codegen/generator/client_set.go
  cmd/codegen/generator/open_api.go
  go.mod
  go.sum
  pkg/jenkinsfile/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#7047 chore: Switch to using org rather than user for boot test repo owner
  jx/bdd/boot-vault/ci.sh
  jx/bdd/boot-vault/jx-requirements.yml
Labels: approved, lgtm, size/XS

#7051 chore: set whitesource image to version 20.3.1
  jenkins-x-whitesource.yml
Labels: size/XS

#7054 fix: GC SAs ending in `-bc`
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/XS

#7057 fix: Do not create a PR against a remote environment
  pkg/kube/env.go
Labels: approved, lgtm, size/XS

#7062 fix: removing GitHub check verifyPrivateRepos during boot
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_test.go
Labels: approved, lgtm, size/L

#7071 fix: Turn off Athens proxy when running "jx step create pr go"
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#7021 fix: Remove static Jenkins masters
  pkg/cmd/create/install.go
  pkg/cmd/create/install_gitops_integration_test.go
  pkg/cmd/create/install_test.go
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/opts/jenkins.go
  pkg/cmd/promote/promote.go
Labels: approved, lgtm, size/L

#7068 feat: list pods instead of namespaces to avoid needing a cluster-wide permission
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#7041 chore: remove deprecated `jx console` cmd
  pkg/cmd/cmd.go
  pkg/cmd/console.go
  pkg/cmd/open.go
Labels: approved, lgtm, size/L

#7085 fix: Do not register a register a webhook on the dev environment
  pkg/cmd/update/update_webhooks.go
  pkg/cmd/update/update_webhooks_test.go
  pkg/kube/sourcerepositories.go
Labels: approved, lgtm, size/L

#7094 chore: remove logWarningForRemovalOfStaticMasters to warn about Stati…
  pkg/cmd/cmd.go
Labels: approved, lgtm, size/M

#7089 feat: don't register the CRDs on controllers the installations take care of that already
  pkg/cmd/controller/controller.go
  pkg/cmd/controller/controller_build.go
  pkg/cmd/controller/controller_role.go
Labels: approved, lgtm, size/S

#7091 fix: Handle Terraform SA display name format in gc_gke
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/S

#7073 feat: create a function to check the current permissions and split the deletion of old resources between cluster and non cluster resources
  pkg/helm/helm_template.go
  pkg/kube/permissions.go
Labels: approved, lgtm, size/M

#7097 feat: make it possible to configure a different exposer from requirements.yml
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/step/verify/step_verify_environments_test.go
  pkg/cmd/step/verify/test_data/verify_ingress/exposer/jx-requirements.yml
Labels: approved, lgtm, size/M

#7096 fix: use sh instead of /bin/sh in Windows
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, ok-to-test, size/XS

#7110 chore: Remove installation type from the issue template
  .github/issue_template.md
Labels: approved, lgtm, size/XS

#7108 feat: add authorAvatarUrl and authorURL to PA
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/apis/jenkins.io/v1/types_pipeline.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/cmd/controller/controller_build.go
  pkg/cmd/controller/controller_build_test.go
  pkg/gits/github.go
Labels: approved, lgtm, size/M

#7120 fix: Add labels to GitLab MRs
  pkg/gits/gitlab.go
Labels: approved, lgtm, size/M

#6919 fix(sync): use commit sha instead of tag for ksync image
  pkg/cmd/sync/sync.go
  pkg/ksync/cli.go
  pkg/ksync/interface.go
  pkg/ksync/ksync_integration_test.go
  pkg/packages/install.go
  pkg/util/downloads.go
  pkg/vault/cli.go
Labels: approved, lgtm, ok-to-test, size/L

#7117 chore: remove unused code
  pkg/builds/jenkinsfiles.go
  pkg/cmd/controller/controller_enviornmentcontroller.go
  pkg/cmd/create/create_cluster_iks.go
  pkg/cmd/get/get_apps.go
  pkg/cmd/get/get_build_logs.go
  pkg/cmd/get/get_issues.go
  pkg/cmd/initcmd/init.go
  pkg/cmd/step/boot/step_boot_vault.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/git/step_git.go
  pkg/cmd/step/helm/step_helm.go
  pkg/cmd/step/report/step_report_image_version.go
  pkg/cmd/step/step_next_version.go
  pkg/cmd/step/verify/common.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/sync/sync.go
  pkg/github/github_app.go
  pkg/gits/git_fake.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_template.go
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/XL

#7125 fix: Various small GitLab fixes
  pkg/gits/gitlab.go
  pkg/gits/gitlab_test.go
  pkg/gits/test_data/gitlab/add-project-member.json
  pkg/gits/test_data/gitlab/list-users.json
Labels: approved, lgtm, size/M

#7124 feat: wrap kuberhealthy check in exponential backoff
  pkg/health/health.go
Labels: approved, lgtm, size/S

#7128 fix: Disable the build lock when running via the env controller
  pkg/cmd/controller/controller_enviornmentcontroller.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/kube/build_lock.go
Labels: approved, lgtm, size/S

#7130 fix: Sleep five seconds after GitHub repo creation
  pkg/gits/github.go
Labels: approved, lgtm, size/XS
