Repository jenkins-x/jx, pull requests merged in 2020-06, with the labels that each got.

#7275 fix: remove the old alpha command
  pkg/cmd/alpha/alpha.go
  pkg/cmd/cmd.go
Labels: approved, lgtm, size/L

#7276 chore: Add Adam to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#7287 fix: Docker auth use prompted secret
  pkg/cmd/create/create_docker_auth.go
Labels: approved, lgtm, ok-to-test, size/XS

#7279 chore: Switch to lighthouse-config library
  go.mod
  go.sum
  pkg/cmd/get/get_pipeline_test.go
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_all/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_default_scheduler/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_repo_scheduler/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_repogroup_scheduler/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_all/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_default_scheduler/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_repo_scheduler/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_repogroup_scheduler/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/gitops_basic/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/nongitops_advanced/config.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_migrate/nongitops_basic/config.yaml
  pkg/pipelinescheduler/config_builder.go
  pkg/pipelinescheduler/generator.go
  pkg/pipelinescheduler/scheduler_builder.go
  pkg/pipelinescheduler/testhelpers/helpers.go
  pkg/prow/config/branch_protection.go
  pkg/prow/config/branch_protection_test.go
  pkg/prow/config/tide.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, lgtm, size/L

#7297 fix: make sure Vault config struct is not created too early in CreateSystemVaultClient
  pkg/cmd/clients/factory.go
  pkg/kube/vault/vault_factory.go
Labels: approved, lgtm, size/S

#7304 docs: remove docs about opening static jenkins console
  README.md
Labels: approved, lgtm, size/XS

#7311 fix: disable edit buildpack cmd for boot clusters
  pkg/cmd/edit/edit_buildpack.go
Labels: approved, lgtm, size/M

#7317 feat: let users define a preview namespace when importing / creating quickstarts
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/import_test.go
  pkg/cmd/importcmd/test_data/application_with_preview/charts/preview/values.yaml
Labels: approved, lgtm, size/L

#7339 fix: install openapigen and clientset depedencies w/o -u option in 'go get'
  cmd/codegen/generator/client_set.go
  cmd/codegen/generator/open_api.go
Labels: approved, lgtm, size/XS

#7334 refactor: minor refactoring of cluster connection function
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/S

#7092 fix: simplify jx version
  .github/issue_template.md
  Makefile
  cmd/jx/app/jx.go
  pkg/cmd/cmd.go
  pkg/cmd/deprecation/deprecated.go
  pkg/cmd/diagnose.go
  pkg/cmd/opts/version.go
  pkg/cmd/step/step_validate.go
  pkg/cmd/version.go
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
  pkg/cmd/version_test.go
  pkg/version/info.go
  pkg/version/info_test.go
Labels: approved, lgtm, size/XL

#7328 fix: update the docs to point to correct URL
  pkg/cmd/edit/edit_buildpack.go
Labels: approved, lgtm, size/XS

#7351 fix: add missing v1 to api directory
  Makefile.codegen
  hack/generate.sh
Labels: approved, lgtm, size/XS

#7348 fix: avoid nil pointer exception when creating sr
  pkg/cmd/create/create_env.go
Labels: approved, lgtm, ok-to-test, size/XS

#7320 feat: add bot as repo collaborator during import
  pkg/cmd/importcmd/import.go
Labels: approved, lgtm, size/M

#7356 fix: Fall back on default SA for PipelineRuns
  pkg/cmd/controller/pipeline/pipelinerunner_cmd.go
  pkg/cmd/create/create_devpod.go
  pkg/cmd/start/start_pipeline.go
  pkg/cmd/step/create/step_create_task.go
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/report/step_report_image_version.go
  pkg/cmd/step/syntax/step_syntax_effective.go
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/cmd/step/verify/step_verify_behavior.go
  pkg/tekton/constants.go
  pkg/tekton/metapipeline/clientfactory_test.go
  pkg/tekton/metapipeline/metapipeline_test.go
  pkg/tekton/pipelines.go
Labels: approved, lgtm, size/M

#7357 feat: jx ui opens Ingress in browser
  pkg/cmd/ui/ui.go
  pkg/cmd/ui/ui_test.go
Labels: approved, lgtm, size/M

#7367 fix: check if installed version is more recent than version specified in version stream
  pkg/cmd/opts/install.go
  pkg/cmd/step/verify/step_verify_packages.go
  pkg/cmd/step/verify/step_verify_packages_test.go
  pkg/cmd/step/verify/test_data/verify_packages/greater/dependency-matrix/matrix.yaml
  pkg/cmd/step/verify/test_data/verify_packages/lesser/dependency-matrix/matrix.yaml
  pkg/cmd/step/verify/test_data/verify_packages/same/dependency-matrix/matrix.yaml
  pkg/versionstream/interface.go
  pkg/versionstream/mocks/streamer.go
  pkg/versionstream/resolver.go
Labels: approved, lgtm, size/XL

#7365 fix(storage): Fixes LegacyBucketProvider() for non-cloud environments
  pkg/cloud/factory/factory.go
Labels: approved, lgtm, ok-to-test, size/S

#7371 fix(import): Fix application reimport
  pkg/cmd/importcmd/import.go
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/Dockerfile
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/Makefile
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/OWNERS
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/OWNERS_ALIASES
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/README.md
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/.helmignore
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/Chart.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/Makefile
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/README.md
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/NOTES.txt
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/_helpers.tpl
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/canary.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/deployment.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/hpa.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/ingress.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/ksvc.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/templates/service.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/jx-quickstartxy/values.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/preview/Chart.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/preview/Makefile
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/preview/requirements.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/charts/preview/values.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/curlloop.sh
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/jenkins-x.yml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/main.go
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/skaffold.yaml
  pkg/cmd/importcmd/test_data/import_projects/jenkins-x-go/watch.sh
  pkg/util/files.go
Labels: approved, lgtm, size/XL

#7373 chore: minor typo in vault comments
  pkg/vault/vault.go
Labels: approved, lgtm, size/XS

#7386 fix: eagerly download binary plugins
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/cmd/upgrade/upgrade_cli_test.go
Labels: approved, lgtm, size/L

#7324 refactor: remove commands past removal date
  .github/issue_template.md
  README.md
  jx/bdd/boot-lh-ghe/ci.sh
  jx/bdd/boot-vault/ci.sh
  jx/bdd/tf-boot/ci.sh
  pkg/cmd/create/create.go
  pkg/cmd/create/create_addon_owasp.go
  pkg/cmd/create/create_post_preview_job.go
  pkg/cmd/create/create_project.go
  pkg/cmd/create/create_spring.go
  pkg/cmd/deletecmd/delete.go
  pkg/cmd/deletecmd/delete_extension.go
  pkg/cmd/deprecation/deprecated.go
  pkg/cmd/edit/edit.go
  pkg/cmd/edit/edit_extensionsrepository.go
  pkg/cmd/get/get.go
  pkg/cmd/get/get_post_preview_job.go
  pkg/cmd/opts/domain.go
  pkg/cmd/opts/upgrade/upgrade_ingress.go
  pkg/cmd/step.go
  pkg/cmd/step/nexus/step_nexus.go
  pkg/cmd/step/nexus/step_nexus_drop.go
  pkg/cmd/step/nexus/step_nexus_release.go
  pkg/cmd/step/step_release.go
  pkg/cmd/step/step_validate.go
  pkg/cmd/upgrade/upgrade.go
  pkg/cmd/upgrade/upgrade_platform.go
  pkg/config/helm_values.go
Labels: approved, lgtm, size/XXL

#7177 fix: support finding a plugin in the plugins dir
  pkg/cmd/cmd.go
  pkg/cmd/cmd_test.go
  pkg/cmd/test_data/binary_plugins_dir/jx-dummy-plugin-1.2.3
Labels: approved, lgtm, size/M

#7400 chore: update kubectl binary to 1.16.5
  pkg/packages/packages.go
Labels: approved, lgtm, size/XS

#7392 chore: Switch to lighthouse-config for Lighthouse plugins too
  go.mod
  go.sum
  pkg/cmd/step/scheduler/step_scheduler_config_apply_test.go
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_all/plugins.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_default_scheduler/plugins.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_repo_scheduler/plugins.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/gitops_repogroup_scheduler/plugins.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_all/plugins.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_default_scheduler/plugins.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_repo_scheduler/plugins.yaml
  pkg/cmd/step/scheduler/test_data/step_scheduler_config_apply/nongitops_repogroup_scheduler/plugins.yaml
  pkg/pipelinescheduler/config_builder.go
  pkg/pipelinescheduler/generator.go
  pkg/pipelinescheduler/scheduler_builder.go
  pkg/pipelinescheduler/testhelpers/helpers.go
  pkg/prow/prow.go
  pkg/prow/prow_test.go
Labels: approved, lgtm, size/M

#7410 chore(deps): bump cobra from 0.0.5 to 1.0.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#7408 fix: making sure envconfig is not initialising nil structs
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
Labels: approved, lgtm, size/L
