Repository jenkins-x/jx, pull requests merged in 2020-05, with the labels that each got.

#7075 feat: split repo label into 4 labels (scheme, host, org and name parts)
  pkg/cmd/create/create_devpod.go
  pkg/kube/naming/names.go
Labels: approved, lgtm, ok-to-test, size/L

#7139 feat: add strict permissions flag
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#7144 chore: Switch `boot-vault` context to Lighthouse
  jx/bdd/boot-vault/jx-requirements.yml
Labels: approved, lgtm, size/XS

#7153 fix: GitLab PR info should include assignees
  pkg/gits/gitlab.go
Labels: approved, lgtm, size/S

#7143 feat: Allow to disable availability check in preview
  pkg/cmd/preview/preview.go
Labels: approved, lgtm, size/XS

#7146 fix: adding JX_LOG_LEVEL documentation to the global verbose flag
  pkg/cmd/opts/common.go
Labels: approved, lgtm, size/XS

#7158 fix: add compatibility sh
  pkg/cmd/step/create/step_create_task.go
  pkg/tekton/syntax/pipeline.go
  pkg/util/shell.go
Labels: approved, lgtm, ok-to-test, size/S

#7160 fix: Handle Lighthouse-specific HMAC secret in update_webhooks
  pkg/cmd/update/update_webhooks.go
  pkg/cmd/update/update_webhooks_test.go
Labels: approved, lgtm, size/M

#7162 fix: Fix hmac token reference in CreateWebhookProw too
  pkg/cmd/opts/install.go
  pkg/cmd/update/update_webhooks.go
  pkg/cmd/update/update_webhooks_test.go
Labels: approved, lgtm, size/M

#7166 fix(eks): wrong cloud constant for eks
  pkg/cmd/create/create_cluster_eks.go
Labels: approved, lgtm, ok-to-test, size/XS

#7170 fix: Upgrade Kaniko to 0.22.0
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/js_build_pack_with_yaml/tasks.yml
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/tekton/syntax/constants.go
Labels: approved, lgtm, size/S

#7175 chore: adding explicit IsVersionControlled to Gitter interface
  pkg/cmd/boot/boot.go
  pkg/gits/git_cli.go
  pkg/gits/git_cli_test.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/helpers.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
  pkg/util/commands.go
Labels: approved, lgtm, size/XXL

#7179 fix: Gitlab (12?) namespace should use path in GitRepository
  pkg/gits/gitlab.go
Labels: approved, lgtm, ok-to-test, size/XS

#7185 fix: Support build log URLs on GitLab and BitBucket Server
  pkg/cmd/controller/controller_build.go
  pkg/cmd/step/step_stash.go
  pkg/collector/git_collector.go
  pkg/collector/helpers.go
Labels: approved, lgtm, size/M

#7191 refactor: remove deprecated delete post command
  pkg/cmd/deletecmd/delete.go
  pkg/cmd/deletecmd/delete_post_preview_job.go
Labels: approved, lgtm, ok-to-test, size/M

#7206 fix: Don't use pr:from_ref_updated webhook on older BitBucket Servers
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
  pkg/gits/test_data/bitbucket_server/app-props.json
Labels: approved, lgtm, size/M

#7211 feat: remove the CRD creation from the changelog step and allow the creation of the controller's role and rolebindings on other namespaces
  charts/jx/templates/role.yaml
  charts/jx/templates/rolebinding.yaml
  pkg/cmd/step/step_changelog.go
Labels: approved, lgtm, size/M

#7214 fix: Don't determine git URL for log storage with bucket storage
  pkg/cmd/controller/controller_build.go
Labels: approved, lgtm, size/XS

#7222 fix: Need to include v2 in compile values
  CONTRIBUTING.MD
  Makefile
  docs/configdocs/config.json
Labels: approved, lgtm, size/S

#7230 feat: Make `jx ui` accept 401 JXUI response.
  pkg/cmd/ui/ui.go
Labels: approved, lgtm, size/XS

#7172 feat: Add buildpack config to requirements file
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
  pkg/config/test_data/build_pack_library.yaml
  pkg/config/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#7236 fix: Lock eksctl version to 0.11.1
  pkg/cloud/amazon/cli.go
  pkg/ksync/cli.go
  pkg/packages/packages.go
Labels: approved, lgtm, size/S

#7252 fix: remove usage of deprecated apiVersions
  pkg/cmd/get/get_applications.go
  pkg/cmd/step/report/step_report_chart.go
  pkg/kube/daemonsets.go
  pkg/kube/deployments.go
Labels: approved, lgtm, ok-to-test, size/S

#7254 fix: update Go supported versions in CONTRIBUTING.MD
  CONTRIBUTING.MD
Labels: approved, lgtm, ok-to-test, size/XS

#7246 chore: migrate code.gitea.io/sdk/gitea to v0.12.0
  go.mod
  go.sum
  pkg/gits/gitea.go
Labels: approved, lgtm, size/L

#7243 chore: removing commands not longer in codebase from deprecation list
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/L

#7255 chore: fixed broken links on main readme
  README.md
Labels: approved, lgtm, size/XS

#7261 refactor: moving pkg/util/error.go to pkg/util/errors/errors.go
  pkg/cloud/factory/factory.go
  pkg/cmd/controller/controller_build.go
  pkg/cmd/controller/controller_role.go
  pkg/cmd/create/install.go
  pkg/cmd/gc/gc_pods.go
  pkg/cmd/step/bdd/step_bdd.go
  pkg/cmd/step/post/step_post_install.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/uninstall/uninstall.go
  pkg/errorutil/errors.go
  pkg/errorutil/errors_test.go
  pkg/gits/helpers.go
  pkg/helm/helm_template.go
  pkg/kube/pod_templates.go
  pkg/logs/tekton_logging.go
  pkg/util/error.go
  pkg/vault/create/create.go
  pkg/versionstream/resolver.go
Labels: approved, lgtm, size/XL
