Repository jenkins-x/jx, pull requests merged in 2020-08, with the labels that each got.

#7500 docs: update docs to use correct Version Stream URL
  pkg/cmd/get/get_stream.go
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/versionstream/resolver.go
  pkg/versionstream/version_data.go
Labels: approved, lgtm, ok-to-test, size/S

#7472 fix: add InstallOnly to InstallChartOptions and add checks before fetchChat
  pkg/apps/helmops.go
  pkg/helm/helm_template.go
Labels: approved, lgtm, ok-to-test, size/S

#7504 fix: correct example of include flag and update terms to GlobalBinary…
  pkg/cmd/step/git/step_git_close.go
  pkg/packages/install.go
  pkg/packages/packages.go
Labels: approved, lgtm, size/XS

#7489 feat(pipelines): add support for Tekton Sidecar containers
  pkg/tekton/syntax/pipeline.go
  pkg/tekton/syntax/pipeline_test.go
  pkg/tekton/syntax/syntax_helpers_test/test_helpers.go
  pkg/tekton/syntax/test_data/sidecars/jenkins-x.yml
Labels: approved, lgtm, ok-to-test, size/L

#7508 fix: lets switch to using a var for the dependency matrix dir
  pkg/dependencymatrix/matrix.go
Labels: approved, lgtm, size/S

#7515 fix: support ingress.ignoreLoadBalancer flag
  pkg/cmd/step/verify/step_verify_ingress.go
Labels: approved, lgtm, size/XS

#7517 docs: refactor issue template and add discourse link to readme
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: approved, lgtm, size/M

#7526 fix: add metadata to fix bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm, size/XS

#7547 fix: Don't error out step create task if no docker registry configmap
  pkg/cmd/step/create/step_create_task.go
Labels: approved, lgtm, size/XS

#7529 fix: update eksctl binary to the latest stable version
  pkg/packages/packages.go
Labels: approved, lgtm, size/XS

#7542 fix: broken link
  README.md
Labels: lgtm, needs-ok-to-test, size/XS

#7418 fix: jx step tag can edit the wrong chart file
  pkg/cmd/step/step_tag.go
  pkg/cmd/step/step_tag_test.go
  pkg/cmd/step/test_data/step_tag_find_chart/aaa/my-project/Chart.yaml
  pkg/cmd/step/test_data/step_tag_find_chart/charts/aaa/Chart.yaml
  pkg/cmd/step/test_data/step_tag_find_chart/charts/my-project/Chart.yaml
Labels: approved, lgtm, size/M
