Repository jenkins-x/jx, pull requests merged in 2020-03, with the labels that each got.

#6844 fix(aks): check for missing azure config when registry is empty
  pkg/cmd/step/create/step_create_values.go
Labels: approved, lgtm, ok-to-test, size/XS

#6853 chore: allow versions-git-ref to be overridden
  .secrets.baseline
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#6849 feat: add a pipeline which scans the Go dependencies with whitesource
  .whitesource.config
  jenkins-x-whitesource.yml
Labels: approved, lgtm, size/L

#6854 chore: temporary file to test that whitesource scanning trigger on merge to master
  .test-whitesource-scanning
Labels: size/XS

#6860 chore: use latest docker image for whitesource agent
  jenkins-x-whitesource.yml
Labels: approved, lgtm, size/XS

#6868 fix(secreturl): Cluster names can have dots in them
  pkg/secreturl/fakevault/client.go
  pkg/secreturl/helpers_test.go
  pkg/secreturl/localvault/client.go
  pkg/vault/fake/client.go
  pkg/vault/vault_client.go
Labels: approved, lgtm, ok-to-test, size/S

#6878 fix: add more service account suffixes
  pkg/cmd/gc/gc_gke.go
Labels: approved, lgtm, size/XS

#6882 chore(config): add .gitignore rules
  .gitignore
Labels: approved, lgtm, ok-to-test, size/XS

#6891 feat: allow labels to be added to boot upgrade PRs
  pkg/cmd/upgrade/upgrade_boot.go
Labels: approved, lgtm, size/S

#6894 fix: wrap dependency asset retrieval with exp backoff strategy
  pkg/gits/operations/pull_request_op.go
Labels: approved, lgtm, size/M

#6884 fix: add env variables specified per step
  pkg/cmd/step/create/test_data/step_create_task/override-steps/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/override-steps/tasks.yml
  pkg/jenkinsfile/pipeline.go
Labels: approved, lgtm, ok-to-test, size/S

#6898 chore: clean up dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#6888 chore: Add warning for upcoming removal of static masters
  pkg/cmd/cmd.go
Labels: approved, lgtm, size/M

#6911 fix: enforce GCP service account minimum name length Closes #6334 fixes #6334
  pkg/cmd/create/install.go
  pkg/kube/naming/names.go
  pkg/kube/naming/names_valid_test.go
Labels: approved, lgtm, ok-to-test, size/M

#6913 fix: remove namespace switch used for helm3 alpha
  pkg/helm/helm_cli.go
Labels: approved, lgtm, ok-to-test, size/M

#6910 feat: add option request memory to devpod
  pkg/cmd/create/create_devpod.go
Labels: approved, lgtm, ok-to-test, size/S

#6921 fix: lets not fail an update if a depedency asset cannot be found
  pkg/gits/operations/pull_request_op.go
Labels: approved, lgtm, size/S

#6938 fix: increase asset retrieval timeout
  pkg/gits/operations/pull_request_op.go
Labels: approved, lgtm, size/XS

#6942 feat: get environment urlTemplate from requirements when running JX Boot for the first time
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/step/verify/step_verify_environments_test.go
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/S

#6939 fix: trim suffix from semver-ish version text to avoid OS dependant errors
  pkg/versionstream/version_data.go
  pkg/versionstream/version_data_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#6943 fix: ignore load jx-requirements.yml validation errors
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
  pkg/config/test_data/jx-requirements-syntax-error/jx-requirements.yml
Labels: approved, lgtm, ok-to-test, size/M

#6950 fix: simplify convertToVersion implementation
  pkg/versionstream/version_data.go
  pkg/versionstream/version_data_test.go
Labels: approved, lgtm, size/M

#6952 fix: Updating github.com/gfleury/go-bitbucket-v1
  go.mod
  go.sum
  pkg/gits/bitbucket_server.go
  pkg/gits/bitbucket_server_test.go
Labels: approved, lgtm, ok-to-test, size/M

#6955 fix: Fresh authentication for each PR status polling check
  pkg/cmd/deletecmd/delete_application.go
  pkg/cmd/promote/promote.go
Labels: approved, lgtm, size/S

#6956 chore: display git status/diff on git stash pop error
  pkg/gits/helpers.go
Labels: approved, lgtm, size/XS

#6958 fix: check helm version instead of binary for timeout
  pkg/helm/helm_cli.go
Labels: approved, lgtm, ok-to-test, size/XS

#6968 fix: jx upgrade boot failure when duplicate commits
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
Labels: approved, lgtm, size/M

#6974 fix: add extract PRETTY_NAME from /etc/os-release to as the current OS
  pkg/util/system/version_linux.go
  pkg/util/system/version_linux_test.go
Labels: approved, lgtm, ok-to-test, size/L

#6977 fix: GHA install check needed an "or", not an "and"
  pkg/util/http_utils.go
Labels: approved, lgtm, size/XS

#6984 fix: Lower-case dir placeholder replacements from build pack
  pkg/cmd/step/syntax/step_syntax_effective_test.go
  pkg/tekton/syntax/pipeline.go
Labels: approved, lgtm, size/S

#6988 feat: correctly determine if a user is an org when creating a repo
  .secrets.baseline
  pkg/gits/github.go
Labels: approved, lgtm, size/S
