Repository jenkins-x/jx, pull requests merged in 2020-01, with the labels that each got.

#6399 chore: update project name in log info printed during installation
  pkg/cmd/create/install.go
Labels: approved, lgtm, size/XS

#6379 refactor: handle the errors when generating the documentation of the commands
  pkg/cmd/create/create_docs.go
Labels: approved, lgtm, size/S

#6393 fix: GC ProwJobs in gc_activities
  pkg/cmd/clients/factory.go
  pkg/cmd/clients/fake/fake_factory.go
  pkg/cmd/clients/interface.go
  pkg/cmd/clients/mocks/factory.go
  pkg/cmd/gc/gc_activities.go
  pkg/cmd/gc/gc_activities_test.go
  pkg/cmd/opts/common.go
Labels: approved, lgtm, size/L

#6402 feat: Updated Helm install URLs
  pkg/cmd/opts/install.go
Labels: approved, lgtm, size/XS

#6409 chore: edit jx create step deprecation warning
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/XS

#6420 fix: Stop lowercasing environmentGitOwner value
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_test.go
Labels: approved, lgtm, size/M

#6422 fix: missing labels when using `jx create pullrequest`
  pkg/cmd/create/create_pullrequest.go
Labels: approved, lgtm, size/XS

#6430 feat: Support passing a service account to jx create cluster gke
  pkg/cmd/create/create_cluster_gke.go
Labels: approved, lgtm, size/XS

#6418 fix: removed edit deploy from the list of deprecated commands
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/XS

#6455 fix: quote log variables and correct message
  pkg/cmd/step/verify/step_verify_behavior.go
Labels: approved, lgtm, size/S

#6427 feat: pass tags and global chart variables when deploying an application
  pkg/cmd/add/add_app_test.go
  pkg/cmd/preview/preview.go
  pkg/cmd/promote/promote.go
  pkg/cmd/promote/promote_test.go
  pkg/cmd/step/helm/step_helm.go
  pkg/cmd/step/helm/step_helm_apply.go
  pkg/cmd/step/helm/step_helm_install.go
  pkg/environments/gitops.go
  pkg/helm/helm_cli.go
  pkg/helm/helm_cli_test.go
  pkg/helm/helm_helpers.go
  pkg/helm/helm_template.go
  pkg/helm/interface.go
  pkg/helm/mocks/helmer.go
Labels: approved, lgtm, ok-to-test, size/L

#6452 feat: changes to make EKS BDD tests work
  pkg/cloud/amazon/eks/eks.go
  pkg/cloud/amazon/vault/vault_resources.go
  pkg/cmd/create/create_cluster_eks.go
  pkg/cmd/step/bdd/step_bdd.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/vault/create/create.go
Labels: approved, lgtm, size/L

#6464 fix: issue with generated tlsSecretName expose config containing dots…
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/XS

#6454 fix: use common options github app mode check as well as the github owner for gitprovider
  .secrets.baseline
  pkg/cmd/opts/auth.go
  pkg/cmd/opts/git.go
  pkg/cmd/step/git/step_git_credentials.go
Labels: approved, lgtm, size/M

#6470 fix: change the boot vault BDD to use the version of boot config from version stream instead of master
  jx/bdd/boot-vault/ci.sh
Labels: approved, lgtm, size/XS

#6461 fix: Optionally write OWNERS file for dev env repo during boot
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/step/verify/step_verify_preinstall_test.go
  pkg/config/install_requirements.go
  pkg/config/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#6487 chore: remove velero config omitempty tags
  pkg/config/install_requirements.go
Labels: approved, lgtm, size/XS

#6497 fix: improve error handling and some log messages in helm template
  pkg/helm/helm_template.go
Labels: approved, lgtm, size/M

#6501 fix: make it easier to pass in a fake tekton/dynamic client
  pkg/cmd/clients/fake/fake_factory.go
  pkg/cmd/testhelpers/cmd_test_helpers.go
Labels: approved, lgtm, size/M

#6505 fix(boot message): Add EKS as supported kubernetes provider
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/XS

#6507 fix: #6483 - boot should not show warning as first impression
  pkg/cmd/boot/boot.go
Labels: approved, area/boot, lgtm, size/XS

#6496 fix: handle correctly ctrl+c on confirmation
  pkg/cloud/gke/vault/vault_backend.go
  pkg/cmd/boot/boot.go
  pkg/cmd/create/install.go
  pkg/cmd/deletecmd/delete_application.go
  pkg/cmd/deletecmd/delete_devpod.go
  pkg/cmd/deletecmd/delete_extension.go
  pkg/cmd/deletecmd/delete_preview.go
  pkg/cmd/edit/edit.go
  pkg/cmd/edit/edit_addon.go
  pkg/cmd/opts/cert_manager.go
  pkg/cmd/opts/domain.go
  pkg/cmd/opts/install.go
  pkg/cmd/opts/upgrade/upgrade_ingress.go
  pkg/cmd/step/report/step_report_image_version.go
  pkg/cmd/step/verify/step_verify_packages.go
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/cmd/stop/stop_pipeline.go
  pkg/cmd/uninstall/uninstall.go
  pkg/cmd/upgrade/upgrade_addon_prow.go
  pkg/cmd/version.go
  pkg/github/github_app.go
  pkg/gits/features/disable_features.go
  pkg/kube/env.go
  pkg/util/pickers.go
Labels: approved, lgtm, ok-to-test, size/L

#6508 docs: Update CONTRIBUTING.MD with supported Golang versions
  CONTRIBUTING.MD
Labels: approved, lgtm, size/XS

#6510 fix: make the step help apply to also load the requirements from the team settings if not requirements file is found locally
  pkg/cmd/step/helm/step_helm_apply.go
Labels: approved, lgtm, size/S

#6506 fix: prevent `jx stop pipeline` from having "failed to cancel pipeline" error
  pkg/cmd/stop/stop_pipeline.go
Labels: approved, lgtm, ok-to-test, size/S

#6530 fix: Use builder-go-maven for make release due to new tests needing maven/java
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#6533 fix: create git provider with auth info
  pkg/cmd/create/create_git_server.go
Labels: approved, lgtm, ok-to-test, size/S

#6544 fix: avoid returning errors for unimplemented capabilities on bitbucket cloud
  pkg/gits/bitbucket_cloud.go
Labels: approved, lgtm, size/XS

#6556 chore: default spring version to 2.2.3 in `jx create spring`
  pkg/cmd/create/create_spring.go
Labels: approved, lgtm, size/XS

#6546 fix: lets make step verify git github app aware
  pkg/cmd/step/verify/step_verify_git.go
Labels: approved, lgtm, size/M

#6558 chore: Revert "chore: default spring version to 2.2.3 in `jx create spring`"
  pkg/cmd/create/create_spring.go
Labels: approved, lgtm, size/XS

#6574 fix: Fall back to not using provider for dev env creation in more cases
  pkg/cmd/step/verify/step_verify_environments.go
Labels: approved, lgtm, size/S

#6569 fix: cmd_test_helpers - CreateTestJxHomeDir()
  pkg/cmd/testhelpers/cmd_test_helpers.go
Labels: approved, lgtm, ok-to-test, size/M

#6575 fix: Look up SourceRepositorys by labels, not just name.
  pkg/cmd/start/start_pipeline.go
  pkg/kube/sourcerepositories.go
  pkg/kube/sourcerepositories_test.go
Labels: approved, lgtm, size/L

#6598 fix: lets always use the dev namespace for applying schedules
  pkg/cmd/step/scheduler/step_scheduler_config_apply.go
Labels: approved, lgtm, size/XS

#6594 feat: add a command to get the custom resource counts in a cluster
  pkg/cmd/clients/factory.go
  pkg/cmd/clients/fake/fake_factory.go
  pkg/cmd/clients/interface.go
  pkg/cmd/clients/mocks/factory.go
  pkg/cmd/get/get.go
  pkg/cmd/get/get_crd_counts.go
  pkg/cmd/get/get_crd_counts_test.go
Labels: approved, lgtm, size/L

#6590 fix: Lookup git service URL kind from jx-auth-config as well
  pkg/cmd/opts/git.go
  pkg/kube/git_services.go
  pkg/kube/git_services_test.go
  pkg/kube/test_data/git_service_kind/configmap_vault_auth.yaml
Labels: approved, lgtm, size/M

#6600 fix: add a CLI argument to disable boot messing with the local git clone
  pkg/cmd/boot/boot.go
Labels: approved, lgtm, size/XS

#6602 fix: validate AWS parameters to prevent panics
  pkg/vault/create/create.go
Labels: approved, lgtm, ok-to-test, size/M

#6502 fix: Resolve OWNERS merge conflicts in boot upgrade with existing version
  pkg/cmd/upgrade/upgrade_boot.go
  pkg/gits/git_cli.go
  pkg/gits/git_fake.go
  pkg/gits/git_local.go
  pkg/gits/interface.go
  pkg/gits/mocks/gitter.go
Labels: approved, lgtm, size/L

#6620 feat: jx create spring accessed via create project. Install deprecation date change.
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/XS

#6624 fix: polish the jx CLI reference generation
  docs/refdocs/templates/pkg.tpl
  pkg/cmd/create/create_docs.go
Labels: approved, lgtm, size/XS

#6626 fix: switched from env var to requirements flag
  pkg/cmd/step/verify/step_verify_preinstall.go
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
  pkg/features/features.go
Labels: approved, lgtm, size/S

#6635 docs: update community info
  README.md
Labels: approved, lgtm, size/M

#6636 feat: add ability to override git_organisation for bdd tests
  pkg/cmd/opts/import.go
  pkg/cmd/step/verify/step_verify_behavior.go
Labels: approved, lgtm, size/S

#6642 fix: allow `jx boot --no-update-git` to not mess with git
  pkg/boot/constants.go
  pkg/cmd/boot/boot.go
  pkg/cmd/opts/team_settings.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/step/verify/step_verify_preinstall.go
Labels: approved, lgtm, size/M

#6641 docs: add link to CONTRIBUTING.MD
  README.md
Labels: approved, lgtm, size/S

#6633 fix: remove deprecation of `jx create step`
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/XS

#6639 docs: delete unnecessary file
  docs/contributing/hacking.md
Labels: approved, lgtm, size/XS

#6645 chore: add a flag to enable the goproxy when running in cluster
  pkg/cmd/step/verify/step_verify_behavior.go
Labels: approved, lgtm, size/XS

#6647 fix: Get structure for rerun PipelineRun properly
  pkg/cmd/controller/controller_build.go
  pkg/logs/tekton_logging.go
  pkg/tekton/pipelines.go
  pkg/tekton/pipelines_test.go
Labels: approved, lgtm, size/L

#6643 fix: Mount Maven settings.xml secret into metapipeline pod
  pkg/tekton/metapipeline/metapipeline.go
Labels: approved, lgtm, size/S

#6649 chore: push the deprecation date for some still used commands to June 1st
  pkg/cmd/deprecation/deprecated.go
Labels: approved, lgtm, size/S

#6663 feat: allow the bdd suite to be configured
  pkg/cmd/step/git/credentials/step_git_credentials.go
  pkg/cmd/step/verify/step_verify_behavior.go
Labels: approved, lgtm, size/S

#6666 chore: check for githubapp mode when verifying environment
  pkg/cmd/opts/auth.go
  pkg/cmd/opts/git.go
  pkg/cmd/step/git/credentials/step_git_credentials.go
  pkg/cmd/step/verify/step_verify_environments.go
  pkg/cmd/step/verify/step_verify_git.go
Labels: approved, lgtm, size/M

#6670 fix: combining rules test1 and test1-pkg into single rule
  Makefile
Labels: approved, lgtm, size/M

#6669 fix: Inherit build pack environment into pipelines
  pkg/cmd/step/create/step_create_task_test.go
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/pipeline.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/pipelineresources.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/pipelinerun.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/structure.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var-extending-build-pack/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/jenkins-x.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/pipeline.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/pipelineresources.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/pipelinerun.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/structure.yml
  pkg/cmd/step/create/test_data/step_create_task/override-pod-template-env-var/tasks.yml
  pkg/cmd/step/create/test_data/step_create_task/packs/maven-with-overridden-env-var/pipeline.yaml
  pkg/jenkinsfile/pipeline.go
Labels: approved, lgtm, size/XXL
