Repository jenkins-x/jx, pull requests merged in 2021-05, with the labels that each got.

#7747 chore: upgrade deps
  go.mod
  go.sum
Labels: approved, size/M

#7748 fix: avoid downloading newer plugin versions
  go.sum
  pkg/cmd/root.go
  pkg/cmd/upgrade/upgrade_plugins.go
  pkg/plugins/versions.go
Labels: approved, size/M

#7754 docs: polish link
  README.md
Labels: approved, size/XS

#7764 fix: Add git-lfs support
  Dockerfile-boot
Labels: approved, lgtm, size/XS

#7786 fix: upgrade octant
  go.mod
  go.sum
  pkg/plugins/versions.go
Labels: approved, size/S
