Repository jenkins-x/jx, pull requests merged in 2021-04, with the labels that each got.

#7595 fix: use conventional commit message for 'jx step tag'
  pkg/cmd/step/step_tag.go
Labels: lifecycle/stale, needs-ok-to-test, size/XS

#7606 fix: Add "all" to list of kinds to clean after deploy in helm template mode
  pkg/helm/helm_template.go
Labels: approved, lgtm, ok-to-test, size/XS

#7578 fix: set a bigger memory limit for the meta-pipeline
  pkg/tekton/metapipeline/metapipeline.go
Labels: approved, ok-to-test, size/XS

#7640 chore: upgrade versions
  pkg/plugins/versions.go
Labels: approved, size/XS

#7684 fix: remove yq and polish readme
  Dockerfile-boot
  Dockerfile-tfo-aws
  Dockerfile-tfo-gcp
  README.md
  go.mod
  go.sum
Labels: approved, size/M

#7713 fix: add a host/port argument
  docs/cmd/jx.md
  docs/cmd/jx_create.md
  docs/cmd/jx_create_project.md
  docs/cmd/jx_create_pullrequest.md
  docs/cmd/jx_create_quickstart.md
  docs/cmd/jx_dashboard.md
  docs/cmd/jx_get.md
  docs/cmd/jx_get_activities.md
  docs/cmd/jx_get_application.md
  docs/cmd/jx_get_build.md
  docs/cmd/jx_get_build_logs.md
  docs/cmd/jx_get_build_pods.md
  docs/cmd/jx_get_pipelines.md
  docs/cmd/jx_get_previews.md
  docs/cmd/jx_import.md
  docs/cmd/jx_namespace.md
  docs/cmd/jx_start.md
  docs/cmd/jx_start_pipeline.md
  docs/cmd/jx_stop.md
  docs/cmd/jx_stop_pipeline.md
  docs/cmd/jx_ui.md
  docs/cmd/jx_upgrade.md
  docs/cmd/jx_upgrade_cli.md
  docs/cmd/jx_upgrade_plugins.md
  docs/cmd/jx_version.md
  docs/man/man1/jx-create.1
  docs/man/man1/jx-ui.1
  docs/man/man1/jx-version.1
  docs/man/man1/jx.1
  go.mod
  go.sum
  pkg/cmd/ui/ui.go
  pkg/plugins/versions.go
Labels: approved, size/L

#7725 docs: fix link to octant in readme
  README.md
Labels: needs-ok-to-test, size/XS
