Repository jenkins-x/jx, pull requests merged in 2022-10, with the labels that each got.

#8406 fix: modify test cases for failing tests
  Dockerfile-go-maven
  pkg/cmd/upgrade/upgrade_cli_test.go
Labels: size/S, approved

#8407 fix: switch back go-maven image to non-alpine
  Dockerfile-go-maven
Labels: size/XS, approved

#8409 feat: use go 1.18.6
  .goreleaser.yml
Labels: size/XS, approved

#8410 revert: remove gobinary version from goreleaser
  .goreleaser.yml
Labels: size/XS, approved

#8412 feat: create multiarch kubectl image for jx
  .github/workflows/jenkins-x-release.yaml
  Dockerfile-kubectl
Labels: approved, size/M

#8434 ci: switch to custom goreleaser image
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/upload-binaries.sh
  Makefile
  go.mod
Labels: size/S, approved

#8435 ci: update go version for images as well
  .github/workflows/jenkins-x-pr.yaml
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/plugins-pr.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile-go
  Dockerfile-go-maven
Labels: size/S, approved

#8436 fix: replace bad digest sha for alpine image
  Dockerfile-go-maven
Labels: size/XS, approved

#8370 GitHub Workflows security hardening
  .github/workflows/jenkins-x-pr.yaml
  .github/workflows/jenkins-x-release.yaml
Labels: size/XS, approved, ok-to-test

#8432 feat: sign goreleaser artifacts with cosign
  .github/workflows/jenkins-x-release.yaml
  .goreleaser.yml
  jx.pub
Labels: size/S, approved

#8437 docs: add instructions to verify archive using cosign
  hack/changelog-header.md
Labels: approved, size/M

#8441 feat: sign pushed images with cosign
  .github/workflows/jenkins-x-release.yaml
Labels: size/S, approved

#8443 fix: change registry org to jx
  .github/workflows/jenkins-x-pr.yaml
  .github/workflows/jenkins-x-release.yaml
  cmd/docs/main.go
  cmd/docs/md_docs.go
  hack/linter.sh
Labels: approved, size/M

#8445 fix: use @ instead of : to fix incorrect image reference
  .github/workflows/jenkins-x-release.yaml
Labels: size/XS, approved

#8448 fix: Correct command in plugin help
  Makefile
  pkg/cmd/root.go
Labels: size/XS, approved

#8447 feat: sign image sbom with syft
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/sbom-container.sh
Labels: approved, size/L

#8449 fix: add version and cosign variables to sbom generation step
  .github/workflows/jenkins-x-release.yaml
Labels: size/XS, approved

#8451 fix: remove sbom.json from cosign sign command
  .github/workflows/jenkins-x-release.yaml
Labels: size/XS, approved
