Repository jenkins-x/jx, pull requests merged in 2022-06, with the labels that each got.

#8203 Use maintainers from jx-community
  OWNERS
  OWNERS_ALIASES
Labels: size/S, approved

#8205 fix: Enable changelog in GitHub release
  .gitignore
Labels: size/XS, approved

#8204 fix: Make command ctx an alias for plugin jx-context
  pkg/cmd/namespace/namespace.go
  pkg/cmd/root.go
Labels: size/XS, approved

#8211 fix: Another attempt to post changelog i release
  .github/workflows/jenkins-x/upload-binaries.sh
Labels: size/XS, approved

#8219 fix: downgrade gitops version to 0.7.8 to fix versionstream tests
  pkg/plugins/versions.go
Labels: size/XS, approved

#8223 fix: Upload release notes
  .github/workflows/jenkins-x/changelog.sh
  .github/workflows/jenkins-x/upload-binaries.sh
Labels: size/XS, approved

#8226 chore: add codecov status badge
  README.md
Labels: size/XS, approved

#8227 test: comment dashboard test to unblock other PRs
  pkg/cmd/dashboard/dashboard_test.go
Labels: approved, size/L

#8228 test: set namespace to fix tests in GH actions
  go.mod
  go.sum
  pkg/cmd/dashboard/dashboard_test.go
Labels: approved, size/L

#8237 chore: switch from jxr to jx3
  .jx/updatebot.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  pkg/cmd/upgrade/upgrade_cli.go
Labels: size/XS, approved

#8253 Revert "chore(deps): upgrade jenkins-x/jx to version 0.7.13"
  pkg/plugins/versions.go
Labels: size/XS, approved

#8256 fix: Mark release as draft when uploading changelog
  .github/workflows/jenkins-x/changelog.sh
  .github/workflows/jenkins-x/upload-binaries.sh
Labels: size/S, approved

#8261 fix: Release issue
  .github/workflows/jenkins-x/upload-binaries.sh
Labels: size/S, approved

#8263 fix: Release
  .github/workflows/jenkins-x/upload-binaries.sh
Labels: size/XS, approved
