Repository jenkins-x/jx, pull requests merged in 2022-03, with the labels that each got.

#8058 refactor: upgrade goreleaser to the latest version
  .github/workflows/jenkins-x-release.yaml
  .goreleaser.yml
Labels: size/XS, approved

#8098 chore: Bump git-ops as robot stuck on merge conflicts
  pkg/plugins/versions.go
Labels: size/XS, approved, lgtm, ok-to-test

#8117 fix: update selfupdate package to address CVEs reported by depandabot
  go.mod
  go.sum
Labels: size/S, approved
