Repository jenkins-x/jx, pull requests merged in 2022-09, with the labels that each got.

#8351 feat: use oras to push sbom to ghcr
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/sbom-container.sh
  .gitignore
Labels: size/S, approved

#8352 fix: update permissions
  .github/workflows/jenkins-x/sbom-container.sh
Labels: size/XS, approved

#8353 fix: install syft
  .github/workflows/jenkins-x/sbom-container.sh
  .github/workflows/jenkins-x/upload-binaries.sh
Labels: size/S, approved

#8359 fix: Aliases for plugins
  docs/cmd/jx.md
  docs/cmd/jx_add.md
  docs/cmd/jx_add_app.md
  docs/cmd/jx_create.md
  docs/cmd/jx_create_project.md
  docs/cmd/jx_create_pullrequest.md
  docs/cmd/jx_create_quickstart.md
  docs/cmd/jx_create_spring.md
  docs/cmd/jx_ctx.md
  docs/cmd/jx_dashboard.md
  docs/cmd/jx_get.md
  docs/cmd/jx_get_activities.md
  docs/cmd/jx_get_application.md
  docs/cmd/jx_get_build.md
  docs/cmd/jx_get_build_logs.md
  docs/cmd/jx_get_build_pods.md
  docs/cmd/jx_get_pipelines.md
  docs/cmd/jx_get_previews.md
  docs/cmd/jx_import.md
  docs/cmd/jx_namespace.md
  docs/cmd/jx_start.md
  docs/cmd/jx_start_pipeline.md
  docs/cmd/jx_stop.md
  docs/cmd/jx_stop_pipeline.md
  docs/cmd/jx_ui.md
  docs/cmd/jx_upgrade.md
  docs/cmd/jx_upgrade_cli.md
  docs/cmd/jx_upgrade_plugins.md
  docs/cmd/jx_version.md
  docs/man/man1/jx-add-app.1
  docs/man/man1/jx-create-pullrequest.1
  docs/man/man1/jx-create-quickstart.1
  docs/man/man1/jx-create-spring.1
  docs/man/man1/jx-ctx.1
  docs/man/man1/jx-get-activities.1
  docs/man/man1/jx-get-application.1
  docs/man/man1/jx-get-build-logs.1
  docs/man/man1/jx-get-build-pods.1
  docs/man/man1/jx-get-pipelines.1
  docs/man/man1/jx-get-previews.1
  docs/man/man1/jx-import.1
  docs/man/man1/jx-start-pipeline.1
  docs/man/man1/jx-stop-pipeline.1
  pkg/cmd/root.go
Labels: approved, size/L

#8299 fix: inherit go version from catalog
  .github/workflows/jenkins-x/upload-binaries.sh
  .github/workflows/plugins-pr.yaml
  Makefile
Labels: size/S, approved, ok-to-test

#8388 refactor: upgrade go version to 1.18.6
  .github/workflows/jenkins-x-pr.yaml
  .github/workflows/plugins-pr.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  Dockerfile-boot
  Dockerfile-go
  Makefile
  go.mod
  go.sum
Labels: approved, size/XL

#8369 fix: Upgrade jx-helpers to show plugins in jx --help
  go.mod
  go.sum
Labels: approved, size/L

#8393 feat: use alpine base image for jx-go
  Dockerfile-go
Labels: size/XS, approved

#8400 fix: add missing curl to jx-go alpine image
  Dockerfile-go
Labels: size/XS, approved

#8403 fix: switch to alpine base image for jx-go-maven
  Dockerfile-go-maven
Labels: size/S, approved

#8405 fix: dont download latest version if on latest version
  pkg/cmd/upgrade/upgrade_cli.go
  pkg/cmd/version/version.go
Labels: size/S, approved
