Repository jenkins-x/jx, pull requests merged in 2022-07, with the labels that each got.

#8282 fix: linting issues after linter upgrade
  pkg/cmd/root.go
  pkg/plugins/helpers.go
  pkg/plugins/versions.go
Labels: size/S, approved

#8291 feat: add build information to jx version
  Makefile
  cloudbuild.yaml
  pkg/cmd/version/version.go
  pkg/cmd/version/version_test.go
Labels: approved, size/L, ok-to-test

#8296 fix: make commit sha from main
  .github/workflows/jenkins-x/changelog.sh
Labels: size/XS, approved, ok-to-test

#8312 feat: add sbom generation
  .github/workflows/jenkins-x-release.yaml
  .goreleaser.yml
Labels: size/XS, approved, ok-to-test

#8317 fix: issues with syft as executable
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/jenkins-x/upload-binaries.sh
Labels: size/XS, approved
