Repository jenkins-x/jx, pull requests merged in 2022-11, with the labels that each got.

#8457 ci: switch to GITHUB_TOKEN for release pipeline
  .github/workflows/jenkins-x-release.yaml
  .github/workflows/plugins-pr.yaml
Labels: size/S, approved

#8458 ci: add package write permission at job level
  .github/workflows/codeql-analysis.yml
  .github/workflows/jenkins-x-release.yaml
Labels: size/XS

#8459 ci: keyless signing for images using cosign
  .github/workflows/jenkins-x-release.yaml
Labels: approved, size/M

#8461 Cosign goreleaser keyless
  .github/workflows/jenkins-x-release.yaml
  .goreleaser.yml
Labels: size/S, approved
