Repository jenkins-x/jx, pull requests merged in 2022-05, with the labels that each got.

#8157 fix: upgrade logging package to fix panics
  go.mod
  go.sum
Labels: size/S, approved

#8159 fix: update alpine linux to 3.15
  Dockerfile-boot
Labels: size/XS, approved

#8166 fix: update json iterator package to fix panics
  go.mod
  go.sum
  pkg/plugins/versions.go
Labels: approved, size/M

#8174 refactor: enable codeql alerts
  .github/workflows/codeql-analysis.yml
Labels: approved, size/M, lgtm, ok-to-test

#8190 chore: update packages
  go.mod
  go.sum
Labels: approved, size/L, ok-to-test
