Repository jenkins-x/jx, pull requests merged in 2023-01, with the labels that each got.

#8465 docs: add instructions to verify archive using cosign with keyless signing
  hack/changelog-header.md
Labels: size/S, approved

#8498 Fix : Function call can be replaced with helper function
  cmd/docs/man_docs.go
  cmd/docs/md_docs.go
  pkg/cmd/root.go
Labels: size/S, approved, ok-to-test

#8495 fix: use changelogs from PRs
  .github/workflows/jenkins-x-release.yaml
Labels: size/S, approved

#8496 feat: add yq to boot image
  Dockerfile-boot
Labels: size/XS, approved

#8507 fix: error checking
  cmd/docs/md_docs.go
  pkg/cmd/root.go
Labels: size/S, approved, ok-to-test
