Repository jenkins-x/jx, pull requests merged in 2025-07, with the labels that each got.

#8846 chore: remove support for octant
  pkg/cmd/root.go
  pkg/cmd/ui/ui.go
  pkg/plugins/helpers.go
  pkg/plugins/helpers_test.go
  pkg/plugins/versions.go
Labels: approved, size/L

#8864 feat: propagate changelog
  .github/workflows/jenkins-x/updatebot.sh
Labels: size/XS, approved

#8865 chore: update GoReleaser configurations
  .goreleaser.yml
Labels: size/XS, approved, lgtm, ok-to-test
